/*--------------------------------------------------------------------------------------+
|
|     $Source: PublicApi/RealityPlatform/RealityPlatformAPI.h $
|
|  $Copyright: (c) 2016 Bentley Systems, Incorporated. All rights reserved. $
|
+--------------------------------------------------------------------------------------*/
#pragma once

#include <Bentley/Bentley.h>
#include <Bentley/BeFileName.h>
#include <Bentley/bvector.h>
#include <Bentley/WString.h>
#include <Bentley/RefCounted.h>
#include <Geom/GeomApi.h>

#if defined (__REALITYPLATFORM_BUILD__)
#   define REALITYDATAPLATFORM_EXPORT EXPORT_ATTRIBUTE
#else
#   define REALITYDATAPLATFORM_EXPORT IMPORT_ATTRIBUTE
#endif

#define BEGIN_BENTLEY_REALITYPLATFORM_NAMESPACE         BEGIN_BENTLEY_NAMESPACE namespace RealityPlatform {
#define END_BENTLEY_REALITYPLATFORM_NAMESPACE           } END_BENTLEY_NAMESPACE
#define USING_NAMESPACE_BENTLEY_REALITYPLATFORM         using namespace BentleyApi::RealityPlatform;


#define REALITYPLATFORM_TYPEDEFS(_name_) \
    BEGIN_BENTLEY_REALITYPLATFORM_NAMESPACE DEFINE_POINTER_SUFFIX_TYPEDEFS(_name_) END_BENTLEY_REALITYPLATFORM_NAMESPACE

#define REALITYPLATFORM_REF_COUNTED_PTR(_sname_) \
    BEGIN_BENTLEY_REALITYPLATFORM_NAMESPACE struct _sname_; DEFINE_REF_COUNTED_PTR(_sname_) END_BENTLEY_REALITYPLATFORM_NAMESPACE

REALITYPLATFORM_TYPEDEFS(RealityData)
REALITYPLATFORM_REF_COUNTED_PTR(RealityData)

REALITYPLATFORM_TYPEDEFS(RasterData)
REALITYPLATFORM_REF_COUNTED_PTR(RasterData)

REALITYPLATFORM_TYPEDEFS(PointCloudData)
REALITYPLATFORM_REF_COUNTED_PTR(PointCloudData)

REALITYPLATFORM_TYPEDEFS(WmsData)
REALITYPLATFORM_REF_COUNTED_PTR(WmsData)

REALITYPLATFORM_TYPEDEFS(RealityDataDownload)
REALITYPLATFORM_REF_COUNTED_PTR(RealityDataDownload)

REALITYPLATFORM_TYPEDEFS(SpatioTemporalDataset)
REALITYPLATFORM_REF_COUNTED_PTR(SpatioTemporalDataset)

REALITYPLATFORM_TYPEDEFS(SpatioTemporalData)
REALITYPLATFORM_REF_COUNTED_PTR(SpatioTemporalData)

REALITYPLATFORM_TYPEDEFS(FtpClient)
REALITYPLATFORM_REF_COUNTED_PTR(FtpClient)

REALITYPLATFORM_TYPEDEFS(WebResourceRequest)
REALITYPLATFORM_REF_COUNTED_PTR(WebResourceRequest)

REALITYPLATFORM_TYPEDEFS(WebResourceResponse)
REALITYPLATFORM_REF_COUNTED_PTR(WebResourceResponse)

REALITYPLATFORM_TYPEDEFS(WebResourceClient)
REALITYPLATFORM_REF_COUNTED_PTR(WebResourceClient)

REALITYPLATFORM_TYPEDEFS(WebResourceData)
REALITYPLATFORM_REF_COUNTED_PTR(WebResourceData)

REALITYPLATFORM_TYPEDEFS(WebResourceThumbnail)
REALITYPLATFORM_REF_COUNTED_PTR(WebResourceThumbnail)

REALITYPLATFORM_TYPEDEFS(WebResourceMetadata)
REALITYPLATFORM_REF_COUNTED_PTR(WebResourceMetadata)

REALITYPLATFORM_TYPEDEFS(WebResourceServer)
REALITYPLATFORM_REF_COUNTED_PTR(WebResourceServer)

REALITYPLATFORM_TYPEDEFS(FtpRequest)
REALITYPLATFORM_REF_COUNTED_PTR(FtpRequest)

REALITYPLATFORM_TYPEDEFS(FtpResponse)
REALITYPLATFORM_REF_COUNTED_PTR(FtpResponse)

REALITYPLATFORM_TYPEDEFS(HttpClient)
REALITYPLATFORM_REF_COUNTED_PTR(HttpClient)

REALITYPLATFORM_TYPEDEFS(HttpRequest)
REALITYPLATFORM_REF_COUNTED_PTR(HttpRequest)

REALITYPLATFORM_TYPEDEFS(HttpResponse)
REALITYPLATFORM_REF_COUNTED_PTR(HttpResponse)