/*--------------------------------------------------------------------------------------+
|
|     $Source: PublicApi/RealityPlatform/RealityPlatformAPI.h $
|
|  $Copyright: (c) 2017 Bentley Systems, Incorporated. All rights reserved. $
|
+--------------------------------------------------------------------------------------*/
#pragma once

#include <Bentley/Bentley.h>
#include <Bentley/BeFileName.h>
#include <Bentley/bvector.h>
#include <Bentley/WString.h>
#include <Bentley/RefCounted.h>
#include <Geom/GeomApi.h>

#if defined (__REALITYPLATFORM_BUILD__)
#   define REALITYDATAPLATFORM_EXPORT EXPORT_ATTRIBUTE
#else
#   define REALITYDATAPLATFORM_EXPORT IMPORT_ATTRIBUTE
#endif

#define BEGIN_BENTLEY_REALITYPLATFORM_NAMESPACE         BEGIN_BENTLEY_NAMESPACE namespace RealityPlatform {
#define END_BENTLEY_REALITYPLATFORM_NAMESPACE           } END_BENTLEY_NAMESPACE
#define USING_NAMESPACE_BENTLEY_REALITYPLATFORM         using namespace BentleyApi::RealityPlatform;


#define REALITYPLATFORM_TYPEDEFS(_name_) \
    BEGIN_BENTLEY_REALITYPLATFORM_NAMESPACE DEFINE_POINTER_SUFFIX_TYPEDEFS(_name_) END_BENTLEY_REALITYPLATFORM_NAMESPACE

#define REALITYPLATFORM_REF_COUNTED_PTR(_sname_) \
    BEGIN_BENTLEY_REALITYPLATFORM_NAMESPACE struct _sname_; DEFINE_REF_COUNTED_PTR(_sname_) END_BENTLEY_REALITYPLATFORM_NAMESPACE

REALITYPLATFORM_TYPEDEFS(RealityDataExtract)
REALITYPLATFORM_REF_COUNTED_PTR(RealityDataExtract)

REALITYPLATFORM_TYPEDEFS(RasterData)
REALITYPLATFORM_REF_COUNTED_PTR(RasterData)

REALITYPLATFORM_TYPEDEFS(PointCloudData)
REALITYPLATFORM_REF_COUNTED_PTR(PointCloudData)

REALITYPLATFORM_TYPEDEFS(WmsData)
REALITYPLATFORM_REF_COUNTED_PTR(WmsData)

REALITYPLATFORM_TYPEDEFS(RealityDataDownload)
REALITYPLATFORM_REF_COUNTED_PTR(RealityDataDownload)

REALITYPLATFORM_TYPEDEFS(SpatialEntityDataset)
REALITYPLATFORM_REF_COUNTED_PTR(SpatialEntityDataset)

REALITYPLATFORM_TYPEDEFS(FtpClient)
REALITYPLATFORM_REF_COUNTED_PTR(FtpClient)

REALITYPLATFORM_TYPEDEFS(SpatialEntityRequest)
REALITYPLATFORM_REF_COUNTED_PTR(SpatialEntityRequest)

REALITYPLATFORM_TYPEDEFS(SpatialEntityResponse)
REALITYPLATFORM_REF_COUNTED_PTR(SpatialEntityResponse)

REALITYPLATFORM_TYPEDEFS(SpatialEntityClient)
REALITYPLATFORM_REF_COUNTED_PTR(SpatialEntityClient)

REALITYPLATFORM_TYPEDEFS(SpatialEntity)
REALITYPLATFORM_REF_COUNTED_PTR(SpatialEntity)

REALITYPLATFORM_TYPEDEFS(SpatialEntityDataSource)
REALITYPLATFORM_REF_COUNTED_PTR(SpatialEntityDataSource)

REALITYPLATFORM_TYPEDEFS(SpatialEntityThumbnail)
REALITYPLATFORM_REF_COUNTED_PTR(SpatialEntityThumbnail)

REALITYPLATFORM_TYPEDEFS(SpatialEntityMetadata)
REALITYPLATFORM_REF_COUNTED_PTR(SpatialEntityMetadata)

REALITYPLATFORM_TYPEDEFS(SpatialEntityServer)
REALITYPLATFORM_REF_COUNTED_PTR(SpatialEntityServer)

REALITYPLATFORM_TYPEDEFS(FtpRequest)
REALITYPLATFORM_REF_COUNTED_PTR(FtpRequest)

REALITYPLATFORM_TYPEDEFS(FtpResponse)
REALITYPLATFORM_REF_COUNTED_PTR(FtpResponse)

REALITYPLATFORM_TYPEDEFS(HttpClient)
REALITYPLATFORM_REF_COUNTED_PTR(HttpClient)

REALITYPLATFORM_TYPEDEFS(HttpRequest)
REALITYPLATFORM_REF_COUNTED_PTR(HttpRequest)

REALITYPLATFORM_TYPEDEFS(HttpResponse)
REALITYPLATFORM_REF_COUNTED_PTR(HttpResponse)

REALITYPLATFORM_TYPEDEFS(RealityDataProjectRelationship)
REALITYPLATFORM_REF_COUNTED_PTR(RealityDataProjectRelationship)

REALITYPLATFORM_TYPEDEFS(RealityDataDocument)
REALITYPLATFORM_REF_COUNTED_PTR(RealityDataDocument)

REALITYPLATFORM_TYPEDEFS(RealityDataFolder)
REALITYPLATFORM_REF_COUNTED_PTR(RealityDataFolder)

REALITYPLATFORM_TYPEDEFS(RealityDataBase)
REALITYPLATFORM_REF_COUNTED_PTR(RealityDataBase)

REALITYPLATFORM_TYPEDEFS(RealityData)
REALITYPLATFORM_REF_COUNTED_PTR(RealityData)
