/*--------------------------------------------------------------------------------------+
|
|  $Source: Domain/GeneratedClassificationInserts.cpp $
|
|  $Copyright: (c) 2018 Bentley Systems, Incorporated. All rights reserved. $
|
+--------------------------------------------------------------------------------------*/
//===========================================================================================
// WARNING: This is an automatically generated code for building classification inserts 
// WARNING: To generate, call "bb -r BuildingShared -f BuildingShared -p CodeGenerators b -c"
//===========================================================================================
void ClassificationSystemsDomain::InsertDefinitionSystems(Dgn::DgnDbR db) const
    {
    ClassificationSystemClassDefinitionGroupPtr group;
    group = InsertGroup(db, "Recreation & Entertainment");
    InsertASHRAE2004(db, group, "Atrium - Each additional floor");
    InsertASHRAE2004(db, group, "Atrium - First 3 floors");
    InsertASHRAE2004(db, group, "Auditorium Seating Area");
    InsertASHRAE2004(db, group, "Bowling Alley Seating Area");
    InsertASHRAE2004(db, group, "Break Room/Locker Room");
    InsertASHRAE2004(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2004(db, group, "Corridor/Transition");
    InsertASHRAE2004(db, group, "Dining Area");
    InsertASHRAE2004(db, group, "Disco/Dance Floor");
    InsertASHRAE2004(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2004(db, group, "Gambling Casinos");
    InsertASHRAE2004(db, group, "Game Arcades");
    InsertASHRAE2004(db, group, "Lecture Classroom");
    InsertASHRAE2004(db, group, "Lobby");
    InsertASHRAE2004(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2004(db, group, "Office - Enclosed");
    InsertASHRAE2004(db, group, "Office - Open Plan");
    InsertASHRAE2004(db, group, "Restrooms");
    InsertASHRAE2004(db, group, "Sales Area");
    InsertASHRAE2004(db, group, "Shipping/Receiving");
    InsertASHRAE2004(db, group, "Storage - Active");
    group = InsertGroup(db, "Public/Civil Services");
    InsertASHRAE2004(db, group, "Atrium - Each additional floor");
    InsertASHRAE2004(db, group, "Atrium - First 3 floors");
    InsertASHRAE2004(db, group, "Auditorium Seating Area");
    InsertASHRAE2004(db, group, "Banks - Banking Activity Area");
    InsertASHRAE2004(db, group, "Banks - Vault/Safe Deposit");
    InsertASHRAE2004(db, group, "Break Room/Locker Room");
    InsertASHRAE2004(db, group, "Computer (not printing)");
    InsertASHRAE2004(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2004(db, group, "Corridor/Transition");
    InsertASHRAE2004(db, group, "Dining Area");
    InsertASHRAE2004(db, group, "Fire Station - Engine Room");
    InsertASHRAE2004(db, group, "Fire Station - Sleeping Quarters");
    InsertASHRAE2004(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2004(db, group, "Lecture Classroom");
    InsertASHRAE2004(db, group, "Legislative Chambers");
    InsertASHRAE2004(db, group, "Lobby");
    InsertASHRAE2004(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2004(db, group, "Office - Enclosed");
    InsertASHRAE2004(db, group, "Office - Open Plan");
    InsertASHRAE2004(db, group, "Post Office - Sorting Area");
    InsertASHRAE2004(db, group, "Restrooms");
    InsertASHRAE2004(db, group, "Sales Area");
    InsertASHRAE2004(db, group, "Shipping/Receiving");
    InsertASHRAE2004(db, group, "Storage - Active");
    group = InsertGroup(db, "Office");
    InsertASHRAE2004(db, group, "Atrium - Each additional floor");
    InsertASHRAE2004(db, group, "Atrium - First 3 floors");
    InsertASHRAE2004(db, group, "Auditorium Seating Area");
    InsertASHRAE2004(db, group, "Break Room/Locker Room");
    InsertASHRAE2004(db, group, "Computer (not printing)");
    InsertASHRAE2004(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2004(db, group, "Corridor/Transition");
    InsertASHRAE2004(db, group, "Lecture Classroom");
    InsertASHRAE2004(db, group, "Lobby");
    InsertASHRAE2004(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2004(db, group, "Office - Enclosed");
    InsertASHRAE2004(db, group, "Office - Open Plan");
    InsertASHRAE2004(db, group, "Reception Area");
    InsertASHRAE2004(db, group, "Restrooms");
    InsertASHRAE2004(db, group, "Sales Area");
    InsertASHRAE2004(db, group, "Shipping/Receiving");
    InsertASHRAE2004(db, group, "Storage - Active");
    InsertASHRAE2004(db, group, "Telephone/Data Entry");
    group = InsertGroup(db, "Manufacturing & Warehouse");
    InsertASHRAE2004(db, group, "Auditorium Seating Area");
    InsertASHRAE2004(db, group, "Break Room/Locker Room");
    InsertASHRAE2004(db, group, "Computer (not printing)");
    InsertASHRAE2004(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2004(db, group, "Control room");
    InsertASHRAE2004(db, group, "Corridor/Transition");
    InsertASHRAE2004(db, group, "Dining Area");
    InsertASHRAE2004(db, group, "Equipment Room");
    InsertASHRAE2004(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2004(db, group, "High Bay  (25 - 50' floor-to-ceiling)");
    InsertASHRAE2004(db, group, "Industrial Laboratory");
    InsertASHRAE2004(db, group, "Lecture Classroom");
    InsertASHRAE2004(db, group, "Lobby");
    InsertASHRAE2004(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2004(db, group, "Low Bay (<25' floor-to-ceiling)");
    InsertASHRAE2004(db, group, "Office - Enclosed");
    InsertASHRAE2004(db, group, "Office - Open Plan");
    InsertASHRAE2004(db, group, "Restrooms");
    InsertASHRAE2004(db, group, "Shipping/Receiving");
    InsertASHRAE2004(db, group, "Sorting, Packing, Light Assembly, Detailed Manufacturing");
    InsertASHRAE2004(db, group, "Storage - Active");
    InsertASHRAE2004(db, group, "Warehouse - Fine Material Storage");
    InsertASHRAE2004(db, group, "Warehouse - General");
    InsertASHRAE2004(db, group, "Warehouse - Medium/Bulky Material Storage");
    group = InsertGroup(db, "Retail & Services");
    InsertASHRAE2004(db, group, "Atrium - Each additional floor");
    InsertASHRAE2004(db, group, "Atrium - First 3 floors");
    InsertASHRAE2004(db, group, "Automotive - Service/Repair");
    InsertASHRAE2004(db, group, "Barber Shop");
    InsertASHRAE2004(db, group, "Beauty and Nail Salons");
    InsertASHRAE2004(db, group, "Break Room/Locker Room");
    InsertASHRAE2004(db, group, "Coin-operated Laundries");
    InsertASHRAE2004(db, group, "Computer (not printing)");
    InsertASHRAE2004(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2004(db, group, "Corridor/Transition");
    InsertASHRAE2004(db, group, "Dining Area");
    InsertASHRAE2004(db, group, "Dressing Room");
    InsertASHRAE2004(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2004(db, group, "Lobby");
    InsertASHRAE2004(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2004(db, group, "Mall Concourse");
    InsertASHRAE2004(db, group, "Office - Enclosed");
    InsertASHRAE2004(db, group, "Office - Open Plan");
    InsertASHRAE2004(db, group, "Pet Shops (animal areas)");
    InsertASHRAE2004(db, group, "Pharmacy (prep area)");
    InsertASHRAE2004(db, group, "Photo Studios");
    InsertASHRAE2004(db, group, "Restrooms");
    InsertASHRAE2004(db, group, "Sales Area");
    InsertASHRAE2004(db, group, "Shipping/Receiving");
    InsertASHRAE2004(db, group, "Storage - Active");
    InsertASHRAE2004(db, group, "Supermarket");
    group = InsertGroup(db, "Hospital");
    InsertASHRAE2004(db, group, "Atrium - Each additional floor");
    InsertASHRAE2004(db, group, "Atrium - First 3 floors");
    InsertASHRAE2004(db, group, "Auditorium Seating Area");
    InsertASHRAE2004(db, group, "Break Room/Locker Room");
    InsertASHRAE2004(db, group, "Computer (not printing)");
    InsertASHRAE2004(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2004(db, group, "Corridor/Transition");
    InsertASHRAE2004(db, group, "Dining Area");
    InsertASHRAE2004(db, group, "Emergency");
    InsertASHRAE2004(db, group, "Exam/Treatment");
    InsertASHRAE2004(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2004(db, group, "Health Care-Clinic");
    InsertASHRAE2004(db, group, "Hospital Storage");
    InsertASHRAE2004(db, group, "Laundry - Washing");
    InsertASHRAE2004(db, group, "Lecture Classroom");
    InsertASHRAE2004(db, group, "Lobby");
    InsertASHRAE2004(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2004(db, group, "Medical Laboratory");
    InsertASHRAE2004(db, group, "Medical Supply");
    InsertASHRAE2004(db, group, "Nurse Station");
    InsertASHRAE2004(db, group, "Nursery");
    InsertASHRAE2004(db, group, "Office - Enclosed");
    InsertASHRAE2004(db, group, "Office - Open Plan");
    InsertASHRAE2004(db, group, "Operating Room");
    InsertASHRAE2004(db, group, "Patient Room");
    InsertASHRAE2004(db, group, "Pharmacy");
    InsertASHRAE2004(db, group, "Physical Therapy");
    InsertASHRAE2004(db, group, "Radiology");
    InsertASHRAE2004(db, group, "Recovery");
    InsertASHRAE2004(db, group, "Restrooms");
    InsertASHRAE2004(db, group, "Sales Area");
    InsertASHRAE2004(db, group, "Shipping/Receiving");
    InsertASHRAE2004(db, group, "Storage - Active");
    group = InsertGroup(db, "Dwelling Unit");
    InsertASHRAE2004(db, group, "Atrium - Each additional floor");
    InsertASHRAE2004(db, group, "Atrium - First 3 floors");
    InsertASHRAE2004(db, group, "Barracks - Sleeping Quarters");
    InsertASHRAE2004(db, group, "Break Room/Locker Room");
    InsertASHRAE2004(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2004(db, group, "Corridor/Transition");
    InsertASHRAE2004(db, group, "Dining Area");
    InsertASHRAE2004(db, group, "Dormitories/Barracks - Living Quarters");
    InsertASHRAE2004(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2004(db, group, "Lobby");
    InsertASHRAE2004(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2004(db, group, "Multi-Family Common Corridors");
    InsertASHRAE2004(db, group, "Multi-Family Dwelling Units");
    InsertASHRAE2004(db, group, "Office - Enclosed");
    InsertASHRAE2004(db, group, "Restrooms");
    InsertASHRAE2004(db, group, "Shipping/Receiving");
    InsertASHRAE2004(db, group, "Storage - Active");
    group = InsertGroup(db, "School/University/Library");
    InsertASHRAE2004(db, group, "Art Classroom");
    InsertASHRAE2004(db, group, "Atrium - Each additional floor");
    InsertASHRAE2004(db, group, "Atrium - First 3 floors");
    InsertASHRAE2004(db, group, "Auditorium Seating Area");
    InsertASHRAE2004(db, group, "Break Room/Locker Room");
    InsertASHRAE2004(db, group, "Classrooms (age 5-8)");
    InsertASHRAE2004(db, group, "Classrooms (age 9+)");
    InsertASHRAE2004(db, group, "Computer (not printing)");
    InsertASHRAE2004(db, group, "Computer Lab/Media Center");
    InsertASHRAE2004(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2004(db, group, "Corridor/Transition");
    InsertASHRAE2004(db, group, "Daycare (through age 4)");
    InsertASHRAE2004(db, group, "Dining Area");
    InsertASHRAE2004(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2004(db, group, "Lecture Classroom");
    InsertASHRAE2004(db, group, "Lecture Hall (fixed seats)");
    InsertASHRAE2004(db, group, "Library - Card File and Cataloging");
    InsertASHRAE2004(db, group, "Library - Reading Area");
    InsertASHRAE2004(db, group, "Library - Stacks");
    InsertASHRAE2004(db, group, "Lobby");
    InsertASHRAE2004(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2004(db, group, "Multi-use Assembly");
    InsertASHRAE2004(db, group, "Music/Theater/Dance");
    InsertASHRAE2004(db, group, "Office - Enclosed");
    InsertASHRAE2004(db, group, "Office - Open Plan");
    InsertASHRAE2004(db, group, "Restrooms");
    InsertASHRAE2004(db, group, "Sales Area");
    InsertASHRAE2004(db, group, "Science/Classroom Laboratory");
    InsertASHRAE2004(db, group, "Shipping/Receiving");
    InsertASHRAE2004(db, group, "Storage - Active");
    InsertASHRAE2004(db, group, "University/College/Research Laboratory");
    group = InsertGroup(db, "Sports & Exercise");
    InsertASHRAE2004(db, group, "Atrium - Each additional floor");
    InsertASHRAE2004(db, group, "Atrium - First 3 floors");
    InsertASHRAE2004(db, group, "Break Room/Locker Room");
    InsertASHRAE2004(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2004(db, group, "Corridor/Transition");
    InsertASHRAE2004(db, group, "Dining Area");
    InsertASHRAE2004(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2004(db, group, "Gym/Exercise/Fitness Center - Playing Area");
    InsertASHRAE2004(db, group, "Gym/Exercise/Fitness Center - Weight Room");
    InsertASHRAE2004(db, group, "Gym/Exercise/Fitness Center- Aerobics Room");
    InsertASHRAE2004(db, group, "Lobby");
    InsertASHRAE2004(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2004(db, group, "Office - Enclosed");
    InsertASHRAE2004(db, group, "Office - Open Plan");
    InsertASHRAE2004(db, group, "Restrooms");
    InsertASHRAE2004(db, group, "Sales Area");
    InsertASHRAE2004(db, group, "Shipping/Receiving");
    InsertASHRAE2004(db, group, "Spectator Area");
    InsertASHRAE2004(db, group, "Sports Arena - Court Sports");
    InsertASHRAE2004(db, group, "Sports Arena - Indoor Playing Field");
    InsertASHRAE2004(db, group, "Sports Arena - Ring Sports");
    InsertASHRAE2004(db, group, "Storage - Active");
    InsertASHRAE2004(db, group, "Swimming (pool & deck)");
    group = InsertGroup(db, "Theater");
    InsertASHRAE2004(db, group, "Atrium - Each additional floor");
    InsertASHRAE2004(db, group, "Atrium - First 3 floors");
    InsertASHRAE2004(db, group, "Break Room/Locker Room");
    InsertASHRAE2004(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2004(db, group, "Corridor/Transition");
    InsertASHRAE2004(db, group, "Dining Area");
    InsertASHRAE2004(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2004(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2004(db, group, "Motion Picture Theater");
    InsertASHRAE2004(db, group, "Motion Picture Theater - Audience/Seating Area");
    InsertASHRAE2004(db, group, "Motion Picture Theater - Lobby");
    InsertASHRAE2004(db, group, "Office - Enclosed");
    InsertASHRAE2004(db, group, "Office - Open Plan");
    InsertASHRAE2004(db, group, "Performing Arts Theater");
    InsertASHRAE2004(db, group, "Performing Arts Theater - Audience/Seating Area");
    InsertASHRAE2004(db, group, "Performing Arts Theater - Dressing/Fitting Room");
    InsertASHRAE2004(db, group, "Performing Arts Theater - Lobby");
    InsertASHRAE2004(db, group, "Restrooms");
    InsertASHRAE2004(db, group, "Sales Area");
    InsertASHRAE2004(db, group, "Shipping/Receiving");
    InsertASHRAE2004(db, group, "Stages, Studios");
    InsertASHRAE2004(db, group, "Storage - Active");
    group = InsertGroup(db, "Transportation");
    InsertASHRAE2004(db, group, "Air/Train/Bus - Baggage Area");
    InsertASHRAE2004(db, group, "Airport - Concourse");
    InsertASHRAE2004(db, group, "Atrium - Each additional floor");
    InsertASHRAE2004(db, group, "Atrium - First 3 floors");
    InsertASHRAE2004(db, group, "Break Room/Locker Room");
    InsertASHRAE2004(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2004(db, group, "Corridor/Transition");
    InsertASHRAE2004(db, group, "Dining Area");
    InsertASHRAE2004(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2004(db, group, "Lobby");
    InsertASHRAE2004(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2004(db, group, "Office - Enclosed");
    InsertASHRAE2004(db, group, "Office - Open Plan");
    InsertASHRAE2004(db, group, "Parking Garage");
    InsertASHRAE2004(db, group, "Restrooms");
    InsertASHRAE2004(db, group, "Sales Area");
    InsertASHRAE2004(db, group, "Seating/Waiting Area");
    InsertASHRAE2004(db, group, "Shipping/Receiving");
    InsertASHRAE2004(db, group, "Storage - Active");
    InsertASHRAE2004(db, group, "Terminal - Ticket Counter");
    group = InsertGroup(db, "Courthouse/Police Station/Penitentiary");
    InsertASHRAE2004(db, group, "Atrium - Each additional floor");
    InsertASHRAE2004(db, group, "Atrium - First 3 floors");
    InsertASHRAE2004(db, group, "Auditorium Seating Area");
    InsertASHRAE2004(db, group, "Break Room/Locker Room");
    InsertASHRAE2004(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2004(db, group, "Confinement Cells");
    InsertASHRAE2004(db, group, "Corridor/Transition");
    InsertASHRAE2004(db, group, "Courtroom");
    InsertASHRAE2004(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2004(db, group, "Judges Chambers");
    InsertASHRAE2004(db, group, "Lobby");
    InsertASHRAE2004(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2004(db, group, "Office - Enclosed");
    InsertASHRAE2004(db, group, "Office - Open Plan");
    InsertASHRAE2004(db, group, "Penitentiary - Booking/Waiting");
    InsertASHRAE2004(db, group, "Penitentiary - Classroom");
    InsertASHRAE2004(db, group, "Penitentiary - Day Room");
    InsertASHRAE2004(db, group, "Penitentiary - Dining Area");
    InsertASHRAE2004(db, group, "Penitentiary - Guard Station");
    InsertASHRAE2004(db, group, "Restrooms");
    InsertASHRAE2004(db, group, "Shipping/Receiving");
    InsertASHRAE2004(db, group, "Storage - Active");
    group = InsertGroup(db, "Public Assembly");
    InsertASHRAE2004(db, group, "Atrium - Each additional floor");
    InsertASHRAE2004(db, group, "Atrium - First 3 floors");
    InsertASHRAE2004(db, group, "Auditorium Seating Area");
    InsertASHRAE2004(db, group, "Break Room/Locker Room");
    InsertASHRAE2004(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2004(db, group, "Convention - Audience Seating");
    InsertASHRAE2004(db, group, "Convention - Exhibit Space");
    InsertASHRAE2004(db, group, "Corridor/Transition");
    InsertASHRAE2004(db, group, "Dining Area");
    InsertASHRAE2004(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2004(db, group, "Lecture Classroom");
    InsertASHRAE2004(db, group, "Lobby");
    InsertASHRAE2004(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2004(db, group, "Museum - Children's");
    InsertASHRAE2004(db, group, "Museum - Exhibition");
    InsertASHRAE2004(db, group, "Museum - Restoration");
    InsertASHRAE2004(db, group, "Museum - Storage");
    InsertASHRAE2004(db, group, "Office - Enclosed");
    InsertASHRAE2004(db, group, "Office - Open Plan");
    InsertASHRAE2004(db, group, "Religious - Fellowship Hall");
    InsertASHRAE2004(db, group, "Religious - Seating");
    InsertASHRAE2004(db, group, "Religious - Worship Pulpit, Choir");
    InsertASHRAE2004(db, group, "Restrooms");
    InsertASHRAE2004(db, group, "Sales Area");
    InsertASHRAE2004(db, group, "Shipping/Receiving");
    InsertASHRAE2004(db, group, "Storage - Active");
    group = InsertGroup(db, "Food & Beverage Services");
    InsertASHRAE2004(db, group, "Atrium - Each additional floor");
    InsertASHRAE2004(db, group, "Atrium - First 3 floors");
    InsertASHRAE2004(db, group, "Break Room/Locker Room");
    InsertASHRAE2004(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2004(db, group, "Corridor/Transition");
    InsertASHRAE2004(db, group, "Dining: Bar, Lounge, Leisure Dining");
    InsertASHRAE2004(db, group, "Dining: Cafeteria/Fast Food");
    InsertASHRAE2004(db, group, "Dining: Family Dining");
    InsertASHRAE2004(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2004(db, group, "Lobby");
    InsertASHRAE2004(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2004(db, group, "Office - Enclosed");
    InsertASHRAE2004(db, group, "Restrooms");
    InsertASHRAE2004(db, group, "Sales Area");
    InsertASHRAE2004(db, group, "Shipping/Receiving");
    InsertASHRAE2004(db, group, "Storage - Active");
    group = InsertGroup(db, "Common Space Types");
    InsertASHRAE2004(db, group, "Electrical/Mechanical");
    InsertASHRAE2004(db, group, "Stairway");
    InsertASHRAE2004(db, group, "Storage - Inactive");
    InsertASHRAE2004(db, group, "Wood/Metal Shop");
    group = InsertGroup(db, "Hotel/Motel");
    InsertASHRAE2004(db, group, "Atrium - Each additional floor");
    InsertASHRAE2004(db, group, "Atrium - First 3 floors");
    InsertASHRAE2004(db, group, "Auditorium Seating Area");
    InsertASHRAE2004(db, group, "Break Room/Locker Room");
    InsertASHRAE2004(db, group, "Computer (not printing)");
    InsertASHRAE2004(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2004(db, group, "Corridor/Transition");
    InsertASHRAE2004(db, group, "Dining Area");
    InsertASHRAE2004(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2004(db, group, "Hotel Dining");
    InsertASHRAE2004(db, group, "Hotel Guest Room");
    InsertASHRAE2004(db, group, "Hotel Lobby/Prefunction");
    InsertASHRAE2004(db, group, "Laundry");
    InsertASHRAE2004(db, group, "Lobby");
    InsertASHRAE2004(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2004(db, group, "Motel Dining");
    InsertASHRAE2004(db, group, "Motel Guest Room");
    InsertASHRAE2004(db, group, "Multi-purpose Assembly");
    InsertASHRAE2004(db, group, "Office - Enclosed");
    InsertASHRAE2004(db, group, "Office - Open Plan");
    InsertASHRAE2004(db, group, "Restrooms");
    InsertASHRAE2004(db, group, "Sales Area");
    InsertASHRAE2004(db, group, "Shipping/Receiving");
    InsertASHRAE2004(db, group, "Storage - Active");
    group = InsertGroup(db, "Recreation & Entertainment");
    InsertASHRAE2010(db, group, "Atrium - First 40 ft in height");
    InsertASHRAE2010(db, group, "Atrium - Height above 40 ft");
    InsertASHRAE2010(db, group, "Auditorium Seating Area");
    InsertASHRAE2010(db, group, "Bowling Alley Seating Area");
    InsertASHRAE2010(db, group, "Break Room/Locker Room");
    InsertASHRAE2010(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2010(db, group, "Corridor/Transition");
    InsertASHRAE2010(db, group, "Dining Area");
    InsertASHRAE2010(db, group, "Disco/Dance Floor");
    InsertASHRAE2010(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2010(db, group, "Gambling Casinos");
    InsertASHRAE2010(db, group, "Game Arcades");
    InsertASHRAE2010(db, group, "Lecture Classroom");
    InsertASHRAE2010(db, group, "Lobby");
    InsertASHRAE2010(db, group, "Lobby - Elevator");
    InsertASHRAE2010(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Dry Materials");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Liquids/Gels");
    InsertASHRAE2010(db, group, "Office - Enclosed");
    InsertASHRAE2010(db, group, "Office - Open Plan");
    InsertASHRAE2010(db, group, "Restrooms");
    InsertASHRAE2010(db, group, "Sales Area");
    InsertASHRAE2010(db, group, "Shipping/Receiving");
    group = InsertGroup(db, "Public/Civil Services");
    InsertASHRAE2010(db, group, "Atrium - First 40 ft in height");
    InsertASHRAE2010(db, group, "Atrium - Height above 40 ft");
    InsertASHRAE2010(db, group, "Auditorium Seating Area");
    InsertASHRAE2010(db, group, "Banks - Banking Activity Area");
    InsertASHRAE2010(db, group, "Banks - Vault/Safe Deposit");
    InsertASHRAE2010(db, group, "Break Room/Locker Room");
    InsertASHRAE2010(db, group, "Computer (not printing)");
    InsertASHRAE2010(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2010(db, group, "Corridor/Transition");
    InsertASHRAE2010(db, group, "Dining Area");
    InsertASHRAE2010(db, group, "Fire Station - Engine Room");
    InsertASHRAE2010(db, group, "Fire Station - Sleeping Quarters");
    InsertASHRAE2010(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2010(db, group, "Lecture Classroom");
    InsertASHRAE2010(db, group, "Legislative Chambers");
    InsertASHRAE2010(db, group, "Lobby");
    InsertASHRAE2010(db, group, "Lobby - Elevator");
    InsertASHRAE2010(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Dry Materials");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Liquids/Gels");
    InsertASHRAE2010(db, group, "Office - Enclosed");
    InsertASHRAE2010(db, group, "Office - Open Plan");
    InsertASHRAE2010(db, group, "Post Office - Sorting Area");
    InsertASHRAE2010(db, group, "Restrooms");
    InsertASHRAE2010(db, group, "Sales Area");
    InsertASHRAE2010(db, group, "Shipping/Receiving");
    group = InsertGroup(db, "Office");
    InsertASHRAE2010(db, group, "Atrium - First 40 ft in height");
    InsertASHRAE2010(db, group, "Atrium - Height above 40 ft");
    InsertASHRAE2010(db, group, "Auditorium Seating Area");
    InsertASHRAE2010(db, group, "Break Room/Locker Room");
    InsertASHRAE2010(db, group, "Computer (not printing)");
    InsertASHRAE2010(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2010(db, group, "Corridor/Transition");
    InsertASHRAE2010(db, group, "Lecture Classroom");
    InsertASHRAE2010(db, group, "Lobby");
    InsertASHRAE2010(db, group, "Lobby - Elevator");
    InsertASHRAE2010(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Dry Materials");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Liquids/Gels");
    InsertASHRAE2010(db, group, "Office - Enclosed");
    InsertASHRAE2010(db, group, "Office - Open Plan");
    InsertASHRAE2010(db, group, "Reception Area");
    InsertASHRAE2010(db, group, "Restrooms");
    InsertASHRAE2010(db, group, "Sales Area");
    InsertASHRAE2010(db, group, "Shipping/Receiving");
    InsertASHRAE2010(db, group, "Telephone/Data Entry");
    group = InsertGroup(db, "Manufacturing & Warehouse");
    InsertASHRAE2010(db, group, "Auditorium Seating Area");
    InsertASHRAE2010(db, group, "Break Room/Locker Room");
    InsertASHRAE2010(db, group, "Computer (not printing)");
    InsertASHRAE2010(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2010(db, group, "Corridor/Transition");
    InsertASHRAE2010(db, group, "Dining Area");
    InsertASHRAE2010(db, group, "Equipment Room");
    InsertASHRAE2010(db, group, "Extra High Bay  (>50' floor-to-ceiling)");
    InsertASHRAE2010(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2010(db, group, "High Bay  (25 - 50' floor-to-ceiling)");
    InsertASHRAE2010(db, group, "Industrial Laboratory");
    InsertASHRAE2010(db, group, "Lecture Classroom");
    InsertASHRAE2010(db, group, "Lobby");
    InsertASHRAE2010(db, group, "Lobby - Elevator");
    InsertASHRAE2010(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2010(db, group, "Low Bay (<25' floor-to-ceiling)");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Dry Materials");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Liquids/Gels");
    InsertASHRAE2010(db, group, "Office - Enclosed");
    InsertASHRAE2010(db, group, "Office - Open Plan");
    InsertASHRAE2010(db, group, "Restrooms");
    InsertASHRAE2010(db, group, "Shipping/Receiving");
    InsertASHRAE2010(db, group, "Sorting, Packing, Light Assembly, Detailed Manufacturing");
    InsertASHRAE2010(db, group, "Warehouse - Fine Material Storage");
    InsertASHRAE2010(db, group, "Warehouse - General");
    InsertASHRAE2010(db, group, "Warehouse - Medium/Bulky Material Storage");
    group = InsertGroup(db, "Retail & Services");
    InsertASHRAE2010(db, group, "Atrium - First 40 ft in height");
    InsertASHRAE2010(db, group, "Atrium - Height above 40 ft");
    InsertASHRAE2010(db, group, "Automotive - Service/Repair");
    InsertASHRAE2010(db, group, "Barber Shop");
    InsertASHRAE2010(db, group, "Beauty and Nail Salons");
    InsertASHRAE2010(db, group, "Break Room/Locker Room");
    InsertASHRAE2010(db, group, "Coin-operated Laundries");
    InsertASHRAE2010(db, group, "Computer (not printing)");
    InsertASHRAE2010(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2010(db, group, "Corridor/Transition");
    InsertASHRAE2010(db, group, "Dining Area");
    InsertASHRAE2010(db, group, "Dressing Room");
    InsertASHRAE2010(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2010(db, group, "Lobby");
    InsertASHRAE2010(db, group, "Lobby - Elevator");
    InsertASHRAE2010(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2010(db, group, "Mall Concourse");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Dry Materials");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Liquids/Gels");
    InsertASHRAE2010(db, group, "Office - Enclosed");
    InsertASHRAE2010(db, group, "Office - Open Plan");
    InsertASHRAE2010(db, group, "Pet Shops (animal areas)");
    InsertASHRAE2010(db, group, "Pharmacy (prep area)");
    InsertASHRAE2010(db, group, "Photo Studios");
    InsertASHRAE2010(db, group, "Restrooms");
    InsertASHRAE2010(db, group, "Sales Area");
    InsertASHRAE2010(db, group, "Shipping/Receiving");
    InsertASHRAE2010(db, group, "Supermarket");
    group = InsertGroup(db, "Hospital");
    InsertASHRAE2010(db, group, "Atrium - First 40 ft in height");
    InsertASHRAE2010(db, group, "Atrium - Height above 40 ft");
    InsertASHRAE2010(db, group, "Auditorium Seating Area");
    InsertASHRAE2010(db, group, "Break Room/Locker Room");
    InsertASHRAE2010(db, group, "Computer (not printing)");
    InsertASHRAE2010(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2010(db, group, "Corridor/Transition");
    InsertASHRAE2010(db, group, "Dining Area");
    InsertASHRAE2010(db, group, "Emergency");
    InsertASHRAE2010(db, group, "Exam/Treatment");
    InsertASHRAE2010(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2010(db, group, "Health Care-Clinic");
    InsertASHRAE2010(db, group, "Hospital Storage");
    InsertASHRAE2010(db, group, "Laundry - Washing");
    InsertASHRAE2010(db, group, "Lecture Classroom");
    InsertASHRAE2010(db, group, "Lobby");
    InsertASHRAE2010(db, group, "Lobby - Elevator");
    InsertASHRAE2010(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2010(db, group, "Medical Laboratory");
    InsertASHRAE2010(db, group, "Medical Supply");
    InsertASHRAE2010(db, group, "Nurse Station");
    InsertASHRAE2010(db, group, "Nursery");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Dry Materials");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Liquids/Gels");
    InsertASHRAE2010(db, group, "Office - Enclosed");
    InsertASHRAE2010(db, group, "Office - Open Plan");
    InsertASHRAE2010(db, group, "Operating Room");
    InsertASHRAE2010(db, group, "Patient Room");
    InsertASHRAE2010(db, group, "Pharmacy");
    InsertASHRAE2010(db, group, "Physical Therapy");
    InsertASHRAE2010(db, group, "Radiology");
    InsertASHRAE2010(db, group, "Recovery");
    InsertASHRAE2010(db, group, "Restrooms");
    InsertASHRAE2010(db, group, "Sales Area");
    InsertASHRAE2010(db, group, "Shipping/Receiving");
    group = InsertGroup(db, "Dwelling Unit");
    InsertASHRAE2010(db, group, "Atrium - First 40 ft in height");
    InsertASHRAE2010(db, group, "Atrium - Height above 40 ft");
    InsertASHRAE2010(db, group, "Barracks - Sleeping Quarters");
    InsertASHRAE2010(db, group, "Break Room/Locker Room");
    InsertASHRAE2010(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2010(db, group, "Corridor/Transition");
    InsertASHRAE2010(db, group, "Dining Area");
    InsertASHRAE2010(db, group, "Dormitories/Barracks - Living Quarters");
    InsertASHRAE2010(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2010(db, group, "Lobby");
    InsertASHRAE2010(db, group, "Lobby - Elevator");
    InsertASHRAE2010(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2010(db, group, "Multi-Family Common Corridors");
    InsertASHRAE2010(db, group, "Multi-Family Dwelling Units");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Dry Materials");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Liquids/Gels");
    InsertASHRAE2010(db, group, "Office - Enclosed");
    InsertASHRAE2010(db, group, "Restrooms");
    InsertASHRAE2010(db, group, "Shipping/Receiving");
    group = InsertGroup(db, "School/University/Library");
    InsertASHRAE2010(db, group, "Art Classroom");
    InsertASHRAE2010(db, group, "Atrium - First 40 ft in height");
    InsertASHRAE2010(db, group, "Atrium - Height above 40 ft");
    InsertASHRAE2010(db, group, "Auditorium Seating Area");
    InsertASHRAE2010(db, group, "Break Room/Locker Room");
    InsertASHRAE2010(db, group, "Classrooms (age 5-8)");
    InsertASHRAE2010(db, group, "Classrooms (age 9+)");
    InsertASHRAE2010(db, group, "Computer (not printing)");
    InsertASHRAE2010(db, group, "Computer Lab/Media Center");
    InsertASHRAE2010(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2010(db, group, "Corridor/Transition");
    InsertASHRAE2010(db, group, "Daycare (through age 4)");
    InsertASHRAE2010(db, group, "Dining Area");
    InsertASHRAE2010(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2010(db, group, "Lecture Classroom");
    InsertASHRAE2010(db, group, "Lecture Hall (fixed seats)");
    InsertASHRAE2010(db, group, "Library - Card File and Cataloging");
    InsertASHRAE2010(db, group, "Library - Reading Area");
    InsertASHRAE2010(db, group, "Library - Stacks");
    InsertASHRAE2010(db, group, "Lobby");
    InsertASHRAE2010(db, group, "Lobby - Elevator");
    InsertASHRAE2010(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2010(db, group, "Multi-use Assembly");
    InsertASHRAE2010(db, group, "Music/Theater/Dance");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Dry Materials");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Liquids/Gels");
    InsertASHRAE2010(db, group, "Office - Enclosed");
    InsertASHRAE2010(db, group, "Office - Open Plan");
    InsertASHRAE2010(db, group, "Restrooms");
    InsertASHRAE2010(db, group, "Sales Area");
    InsertASHRAE2010(db, group, "Science/Classroom Laboratory");
    InsertASHRAE2010(db, group, "Shipping/Receiving");
    InsertASHRAE2010(db, group, "University/College/Research Laboratory");
    group = InsertGroup(db, "Sports & Exercise");
    InsertASHRAE2010(db, group, "Atrium - First 40 ft in height");
    InsertASHRAE2010(db, group, "Atrium - Height above 40 ft");
    InsertASHRAE2010(db, group, "Break Room/Locker Room");
    InsertASHRAE2010(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2010(db, group, "Corridor/Transition");
    InsertASHRAE2010(db, group, "Dining Area");
    InsertASHRAE2010(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2010(db, group, "Gym/Exercise/Fitness Center - Playing Area");
    InsertASHRAE2010(db, group, "Gym/Exercise/Fitness Center - Weight Room");
    InsertASHRAE2010(db, group, "Gym/Exercise/Fitness Center- Aerobics Room");
    InsertASHRAE2010(db, group, "Lobby");
    InsertASHRAE2010(db, group, "Lobby - Elevator");
    InsertASHRAE2010(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Dry Materials");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Liquids/Gels");
    InsertASHRAE2010(db, group, "Office - Enclosed");
    InsertASHRAE2010(db, group, "Office - Open Plan");
    InsertASHRAE2010(db, group, "Restrooms");
    InsertASHRAE2010(db, group, "Sales Area");
    InsertASHRAE2010(db, group, "Shipping/Receiving");
    InsertASHRAE2010(db, group, "Spectator Area");
    InsertASHRAE2010(db, group, "Sports Arena - Court Sports Class 1");
    InsertASHRAE2010(db, group, "Sports Arena - Court Sports Class 2");
    InsertASHRAE2010(db, group, "Sports Arena - Court Sports Class 3");
    InsertASHRAE2010(db, group, "Sports Arena - Court Sports Class 4");
    InsertASHRAE2010(db, group, "Sports Arena - Ring Sports");
    InsertASHRAE2010(db, group, "Swimming (pool & deck)");
    group = InsertGroup(db, "Theater");
    InsertASHRAE2010(db, group, "Atrium - First 40 ft in height");
    InsertASHRAE2010(db, group, "Atrium - Height above 40 ft");
    InsertASHRAE2010(db, group, "Break Room/Locker Room");
    InsertASHRAE2010(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2010(db, group, "Corridor/Transition");
    InsertASHRAE2010(db, group, "Dining Area");
    InsertASHRAE2010(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2010(db, group, "Lobby - Elevator");
    InsertASHRAE2010(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2010(db, group, "Motion Picture Theater");
    InsertASHRAE2010(db, group, "Motion Picture Theater - Audience/Seating Area");
    InsertASHRAE2010(db, group, "Motion Picture Theater - Lobby");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Dry Materials");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Liquids/Gels");
    InsertASHRAE2010(db, group, "Office - Enclosed");
    InsertASHRAE2010(db, group, "Office - Open Plan");
    InsertASHRAE2010(db, group, "Performing Arts Theater");
    InsertASHRAE2010(db, group, "Performing Arts Theater - Audience/Seating Area");
    InsertASHRAE2010(db, group, "Performing Arts Theater - Dressing/Fitting Room");
    InsertASHRAE2010(db, group, "Performing Arts Theater - Lobby");
    InsertASHRAE2010(db, group, "Restrooms");
    InsertASHRAE2010(db, group, "Sales Area");
    InsertASHRAE2010(db, group, "Shipping/Receiving");
    InsertASHRAE2010(db, group, "Stages, Studios");
    group = InsertGroup(db, "Transportation");
    InsertASHRAE2010(db, group, "Air/Train/Bus - Baggage Area");
    InsertASHRAE2010(db, group, "Airport - Concourse");
    InsertASHRAE2010(db, group, "Atrium - First 40 ft in height");
    InsertASHRAE2010(db, group, "Atrium - Height above 40 ft");
    InsertASHRAE2010(db, group, "Break Room/Locker Room");
    InsertASHRAE2010(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2010(db, group, "Corridor/Transition");
    InsertASHRAE2010(db, group, "Dining Area");
    InsertASHRAE2010(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2010(db, group, "Lobby");
    InsertASHRAE2010(db, group, "Lobby - Elevator");
    InsertASHRAE2010(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Dry Materials");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Liquids/Gels");
    InsertASHRAE2010(db, group, "Office - Enclosed");
    InsertASHRAE2010(db, group, "Office - Open Plan");
    InsertASHRAE2010(db, group, "Parking Garage");
    InsertASHRAE2010(db, group, "Restrooms");
    InsertASHRAE2010(db, group, "Sales Area");
    InsertASHRAE2010(db, group, "Seating/Waiting Area");
    InsertASHRAE2010(db, group, "Shipping/Receiving");
    InsertASHRAE2010(db, group, "Terminal - Ticket Counter");
    group = InsertGroup(db, "Courthouse/Police Station/Penitentiary");
    InsertASHRAE2010(db, group, "Atrium - First 40 ft in height");
    InsertASHRAE2010(db, group, "Atrium - Height above 40 ft");
    InsertASHRAE2010(db, group, "Auditorium Seating Area");
    InsertASHRAE2010(db, group, "Break Room/Locker Room");
    InsertASHRAE2010(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2010(db, group, "Confinement Cells");
    InsertASHRAE2010(db, group, "Corridor/Transition");
    InsertASHRAE2010(db, group, "Courtroom");
    InsertASHRAE2010(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2010(db, group, "Judges Chambers");
    InsertASHRAE2010(db, group, "Lobby");
    InsertASHRAE2010(db, group, "Lobby - Elevator");
    InsertASHRAE2010(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Dry Materials");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Liquids/Gels");
    InsertASHRAE2010(db, group, "Office - Enclosed");
    InsertASHRAE2010(db, group, "Office - Open Plan");
    InsertASHRAE2010(db, group, "Penitentiary - Booking/Waiting");
    InsertASHRAE2010(db, group, "Penitentiary - Classroom");
    InsertASHRAE2010(db, group, "Penitentiary - Day Room");
    InsertASHRAE2010(db, group, "Penitentiary - Dining Area");
    InsertASHRAE2010(db, group, "Penitentiary - Guard Station");
    InsertASHRAE2010(db, group, "Restrooms");
    InsertASHRAE2010(db, group, "Shipping/Receiving");
    group = InsertGroup(db, "Public Assembly");
    InsertASHRAE2010(db, group, "Atrium - First 40 ft in height");
    InsertASHRAE2010(db, group, "Atrium - Height above 40 ft");
    InsertASHRAE2010(db, group, "Auditorium Seating Area");
    InsertASHRAE2010(db, group, "Break Room/Locker Room");
    InsertASHRAE2010(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2010(db, group, "Convention - Audience Seating");
    InsertASHRAE2010(db, group, "Convention - Exhibit Space");
    InsertASHRAE2010(db, group, "Corridor/Transition");
    InsertASHRAE2010(db, group, "Dining Area");
    InsertASHRAE2010(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2010(db, group, "Lecture Classroom");
    InsertASHRAE2010(db, group, "Lobby");
    InsertASHRAE2010(db, group, "Lobby - Elevator");
    InsertASHRAE2010(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2010(db, group, "Museum - Children's");
    InsertASHRAE2010(db, group, "Museum - Exhibition");
    InsertASHRAE2010(db, group, "Museum - Restoration");
    InsertASHRAE2010(db, group, "Museum - Storage");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Dry Materials");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Liquids/Gels");
    InsertASHRAE2010(db, group, "Office - Enclosed");
    InsertASHRAE2010(db, group, "Office - Open Plan");
    InsertASHRAE2010(db, group, "Religious - Fellowship Hall");
    InsertASHRAE2010(db, group, "Religious - Worship Pulpit, Choir, Audience Seating");
    InsertASHRAE2010(db, group, "Restrooms");
    InsertASHRAE2010(db, group, "Sales Area");
    InsertASHRAE2010(db, group, "Shipping/Receiving");
    group = InsertGroup(db, "Food & Beverage Services");
    InsertASHRAE2010(db, group, "Atrium - First 40 ft in height");
    InsertASHRAE2010(db, group, "Atrium - Height above 40 ft");
    InsertASHRAE2010(db, group, "Break Room/Locker Room");
    InsertASHRAE2010(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2010(db, group, "Corridor/Transition");
    InsertASHRAE2010(db, group, "Dining: Bar, Lounge, Leisure Dining");
    InsertASHRAE2010(db, group, "Dining: Cafeteria/Fast Food");
    InsertASHRAE2010(db, group, "Dining: Family Dining");
    InsertASHRAE2010(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2010(db, group, "Lobby");
    InsertASHRAE2010(db, group, "Lobby - Elevator");
    InsertASHRAE2010(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Dry Materials");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Liquids/Gels");
    InsertASHRAE2010(db, group, "Office - Enclosed");
    InsertASHRAE2010(db, group, "Restrooms");
    InsertASHRAE2010(db, group, "Sales Area");
    InsertASHRAE2010(db, group, "Shipping/Receiving");
    group = InsertGroup(db, "Common Space Types");
    InsertASHRAE2010(db, group, "Electrical/Mechanical");
    InsertASHRAE2010(db, group, "Stairway");
    InsertASHRAE2010(db, group, "Wood/Metal Shop");
    group = InsertGroup(db, "Hotel/Motel");
    InsertASHRAE2010(db, group, "Atrium - First 40 ft in height");
    InsertASHRAE2010(db, group, "Atrium - Height above 40 ft");
    InsertASHRAE2010(db, group, "Auditorium Seating Area");
    InsertASHRAE2010(db, group, "Break Room/Locker Room");
    InsertASHRAE2010(db, group, "Computer (not printing)");
    InsertASHRAE2010(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2010(db, group, "Corridor/Transition");
    InsertASHRAE2010(db, group, "Dining Area");
    InsertASHRAE2010(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2010(db, group, "Hotel Dining");
    InsertASHRAE2010(db, group, "Hotel Guest Room");
    InsertASHRAE2010(db, group, "Hotel Lobby/Prefunction");
    InsertASHRAE2010(db, group, "Laundry");
    InsertASHRAE2010(db, group, "Lobby");
    InsertASHRAE2010(db, group, "Lobby - Elevator");
    InsertASHRAE2010(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2010(db, group, "Motel Dining");
    InsertASHRAE2010(db, group, "Motel Guest Room");
    InsertASHRAE2010(db, group, "Multi-purpose Assembly");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Dry Materials");
    InsertASHRAE2010(db, group, "Occupiable Storage Rooms for Liquids/Gels");
    InsertASHRAE2010(db, group, "Office - Enclosed");
    InsertASHRAE2010(db, group, "Office - Open Plan");
    InsertASHRAE2010(db, group, "Restrooms");
    InsertASHRAE2010(db, group, "Sales Area");
    InsertASHRAE2010(db, group, "Shipping/Receiving");
    group = InsertGroup(db, "Recreation & Entertainment");
    InsertASHRAE2007(db, group, "Atrium - Each additional floor");
    InsertASHRAE2007(db, group, "Atrium - First 3 floors");
    InsertASHRAE2007(db, group, "Auditorium Seating Area");
    InsertASHRAE2007(db, group, "Bowling Alley Seating Area");
    InsertASHRAE2007(db, group, "Break Room/Locker Room");
    InsertASHRAE2007(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2007(db, group, "Corridor/Transition");
    InsertASHRAE2007(db, group, "Dining Area");
    InsertASHRAE2007(db, group, "Disco/Dance Floor");
    InsertASHRAE2007(db, group, "Elevator Machine Room");
    InsertASHRAE2007(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2007(db, group, "Gambling Casinos");
    InsertASHRAE2007(db, group, "Game Arcades");
    InsertASHRAE2007(db, group, "Lecture Classroom");
    InsertASHRAE2007(db, group, "Lobby");
    InsertASHRAE2007(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2007(db, group, "Office - Enclosed");
    InsertASHRAE2007(db, group, "Office - Open Plan");
    InsertASHRAE2007(db, group, "Restrooms");
    InsertASHRAE2007(db, group, "Sales Area");
    InsertASHRAE2007(db, group, "Shipping/Receiving");
    InsertASHRAE2007(db, group, "Storage - Active");
    group = InsertGroup(db, "Public/Civil Services");
    InsertASHRAE2007(db, group, "Atrium - Each additional floor");
    InsertASHRAE2007(db, group, "Atrium - First 3 floors");
    InsertASHRAE2007(db, group, "Auditorium Seating Area");
    InsertASHRAE2007(db, group, "Banks - Banking Activity Area");
    InsertASHRAE2007(db, group, "Banks - Vault/Safe Deposit");
    InsertASHRAE2007(db, group, "Break Room/Locker Room");
    InsertASHRAE2007(db, group, "Computer (not printing)");
    InsertASHRAE2007(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2007(db, group, "Corridor/Transition");
    InsertASHRAE2007(db, group, "Dining Area");
    InsertASHRAE2007(db, group, "Elevator Machine Room");
    InsertASHRAE2007(db, group, "Fire Station - Engine Room");
    InsertASHRAE2007(db, group, "Fire Station - Sleeping Quarters");
    InsertASHRAE2007(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2007(db, group, "Lecture Classroom");
    InsertASHRAE2007(db, group, "Legislative Chambers");
    InsertASHRAE2007(db, group, "Lobby");
    InsertASHRAE2007(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2007(db, group, "Office - Enclosed");
    InsertASHRAE2007(db, group, "Office - Open Plan");
    InsertASHRAE2007(db, group, "Post Office - Sorting Area");
    InsertASHRAE2007(db, group, "Restrooms");
    InsertASHRAE2007(db, group, "Sales Area");
    InsertASHRAE2007(db, group, "Shipping/Receiving");
    InsertASHRAE2007(db, group, "Storage - Active");
    group = InsertGroup(db, "Office");
    InsertASHRAE2007(db, group, "Atrium - Each additional floor");
    InsertASHRAE2007(db, group, "Atrium - First 3 floors");
    InsertASHRAE2007(db, group, "Auditorium Seating Area");
    InsertASHRAE2007(db, group, "Break Room/Locker Room");
    InsertASHRAE2007(db, group, "Computer (not printing)");
    InsertASHRAE2007(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2007(db, group, "Corridor/Transition");
    InsertASHRAE2007(db, group, "Elevator Machine Room");
    InsertASHRAE2007(db, group, "Lecture Classroom");
    InsertASHRAE2007(db, group, "Lobby");
    InsertASHRAE2007(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2007(db, group, "Office - Enclosed");
    InsertASHRAE2007(db, group, "Office - Open Plan");
    InsertASHRAE2007(db, group, "Reception Area");
    InsertASHRAE2007(db, group, "Restrooms");
    InsertASHRAE2007(db, group, "Sales Area");
    InsertASHRAE2007(db, group, "Shipping/Receiving");
    InsertASHRAE2007(db, group, "Storage - Active");
    InsertASHRAE2007(db, group, "Telephone/Data Entry");
    group = InsertGroup(db, "Manufacturing & Warehouse");
    InsertASHRAE2007(db, group, "Auditorium Seating Area");
    InsertASHRAE2007(db, group, "Break Room/Locker Room");
    InsertASHRAE2007(db, group, "Computer (not printing)");
    InsertASHRAE2007(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2007(db, group, "Control room");
    InsertASHRAE2007(db, group, "Corridor/Transition");
    InsertASHRAE2007(db, group, "Dining Area");
    InsertASHRAE2007(db, group, "Elevator Machine Room");
    InsertASHRAE2007(db, group, "Equipment Room");
    InsertASHRAE2007(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2007(db, group, "High Bay  (25 - 50' floor-to-ceiling)");
    InsertASHRAE2007(db, group, "Industrial Laboratory");
    InsertASHRAE2007(db, group, "Lecture Classroom");
    InsertASHRAE2007(db, group, "Lobby");
    InsertASHRAE2007(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2007(db, group, "Low Bay (<25' floor-to-ceiling)");
    InsertASHRAE2007(db, group, "Office - Enclosed");
    InsertASHRAE2007(db, group, "Office - Open Plan");
    InsertASHRAE2007(db, group, "Restrooms");
    InsertASHRAE2007(db, group, "Shipping/Receiving");
    InsertASHRAE2007(db, group, "Sorting, Packing, Light Assembly, Detailed Manufacturing");
    InsertASHRAE2007(db, group, "Storage - Active");
    InsertASHRAE2007(db, group, "Warehouse - Fine Material Storage");
    InsertASHRAE2007(db, group, "Warehouse - General");
    InsertASHRAE2007(db, group, "Warehouse - Medium/Bulky Material Storage");
    group = InsertGroup(db, "Retail & Services");
    InsertASHRAE2007(db, group, "Atrium - Each additional floor");
    InsertASHRAE2007(db, group, "Atrium - First 3 floors");
    InsertASHRAE2007(db, group, "Automotive - Service/Repair");
    InsertASHRAE2007(db, group, "Barber Shop");
    InsertASHRAE2007(db, group, "Beauty and Nail Salons");
    InsertASHRAE2007(db, group, "Break Room/Locker Room");
    InsertASHRAE2007(db, group, "Coin-operated Laundries");
    InsertASHRAE2007(db, group, "Computer (not printing)");
    InsertASHRAE2007(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2007(db, group, "Corridor/Transition");
    InsertASHRAE2007(db, group, "Dining Area");
    InsertASHRAE2007(db, group, "Dressing Room");
    InsertASHRAE2007(db, group, "Elevator Machine Room");
    InsertASHRAE2007(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2007(db, group, "Lobby");
    InsertASHRAE2007(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2007(db, group, "Mall Concourse");
    InsertASHRAE2007(db, group, "Office - Enclosed");
    InsertASHRAE2007(db, group, "Office - Open Plan");
    InsertASHRAE2007(db, group, "Pet Shops (animal areas)");
    InsertASHRAE2007(db, group, "Pharmacy (prep area)");
    InsertASHRAE2007(db, group, "Photo Studios");
    InsertASHRAE2007(db, group, "Restrooms");
    InsertASHRAE2007(db, group, "Sales Area");
    InsertASHRAE2007(db, group, "Shipping/Receiving");
    InsertASHRAE2007(db, group, "Storage - Active");
    InsertASHRAE2007(db, group, "Supermarket");
    group = InsertGroup(db, "Hospital");
    InsertASHRAE2007(db, group, "Atrium - Each additional floor");
    InsertASHRAE2007(db, group, "Atrium - First 3 floors");
    InsertASHRAE2007(db, group, "Auditorium Seating Area");
    InsertASHRAE2007(db, group, "Break Room/Locker Room");
    InsertASHRAE2007(db, group, "Computer (not printing)");
    InsertASHRAE2007(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2007(db, group, "Corridor/Transition");
    InsertASHRAE2007(db, group, "Dining Area");
    InsertASHRAE2007(db, group, "Elevator Machine Room");
    InsertASHRAE2007(db, group, "Emergency");
    InsertASHRAE2007(db, group, "Exam/Treatment");
    InsertASHRAE2007(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2007(db, group, "Health Care-Clinic");
    InsertASHRAE2007(db, group, "Hospital Storage");
    InsertASHRAE2007(db, group, "Laundry - Washing");
    InsertASHRAE2007(db, group, "Lecture Classroom");
    InsertASHRAE2007(db, group, "Lobby");
    InsertASHRAE2007(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2007(db, group, "Medical Laboratory");
    InsertASHRAE2007(db, group, "Medical Supply");
    InsertASHRAE2007(db, group, "Nurse Station");
    InsertASHRAE2007(db, group, "Nursery");
    InsertASHRAE2007(db, group, "Office - Enclosed");
    InsertASHRAE2007(db, group, "Office - Open Plan");
    InsertASHRAE2007(db, group, "Operating Room");
    InsertASHRAE2007(db, group, "Patient Room");
    InsertASHRAE2007(db, group, "Pharmacy");
    InsertASHRAE2007(db, group, "Physical Therapy");
    InsertASHRAE2007(db, group, "Radiology");
    InsertASHRAE2007(db, group, "Recovery");
    InsertASHRAE2007(db, group, "Restrooms");
    InsertASHRAE2007(db, group, "Sales Area");
    InsertASHRAE2007(db, group, "Shipping/Receiving");
    InsertASHRAE2007(db, group, "Storage - Active");
    group = InsertGroup(db, "Dwelling Unit");
    InsertASHRAE2007(db, group, "Atrium - Each additional floor");
    InsertASHRAE2007(db, group, "Atrium - First 3 floors");
    InsertASHRAE2007(db, group, "Barracks - Sleeping Quarters");
    InsertASHRAE2007(db, group, "Break Room/Locker Room");
    InsertASHRAE2007(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2007(db, group, "Corridor/Transition");
    InsertASHRAE2007(db, group, "Dining Area");
    InsertASHRAE2007(db, group, "Dormitories/Barracks - Living Quarters");
    InsertASHRAE2007(db, group, "Elevator Machine Room");
    InsertASHRAE2007(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2007(db, group, "Lobby");
    InsertASHRAE2007(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2007(db, group, "Multi-Family Common Corridors");
    InsertASHRAE2007(db, group, "Multi-Family Dwelling Units");
    InsertASHRAE2007(db, group, "Office - Enclosed");
    InsertASHRAE2007(db, group, "Restrooms");
    InsertASHRAE2007(db, group, "Shipping/Receiving");
    InsertASHRAE2007(db, group, "Storage - Active");
    group = InsertGroup(db, "School/University/Library");
    InsertASHRAE2007(db, group, "Art Classroom");
    InsertASHRAE2007(db, group, "Atrium - Each additional floor");
    InsertASHRAE2007(db, group, "Atrium - First 3 floors");
    InsertASHRAE2007(db, group, "Auditorium Seating Area");
    InsertASHRAE2007(db, group, "Break Room/Locker Room");
    InsertASHRAE2007(db, group, "Classrooms (age 5-8)");
    InsertASHRAE2007(db, group, "Classrooms (age 9+)");
    InsertASHRAE2007(db, group, "Computer (not printing)");
    InsertASHRAE2007(db, group, "Computer Lab/Media Center");
    InsertASHRAE2007(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2007(db, group, "Corridor/Transition");
    InsertASHRAE2007(db, group, "Daycare (through age 4)");
    InsertASHRAE2007(db, group, "Dining Area");
    InsertASHRAE2007(db, group, "Elevator Machine Room");
    InsertASHRAE2007(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2007(db, group, "Lecture Classroom");
    InsertASHRAE2007(db, group, "Lecture Hall (fixed seats)");
    InsertASHRAE2007(db, group, "Library - Card File and Cataloging");
    InsertASHRAE2007(db, group, "Library - Reading Area");
    InsertASHRAE2007(db, group, "Library - Stacks");
    InsertASHRAE2007(db, group, "Lobby");
    InsertASHRAE2007(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2007(db, group, "Multi-use Assembly");
    InsertASHRAE2007(db, group, "Music/Theater/Dance");
    InsertASHRAE2007(db, group, "Office - Enclosed");
    InsertASHRAE2007(db, group, "Office - Open Plan");
    InsertASHRAE2007(db, group, "Restrooms");
    InsertASHRAE2007(db, group, "Sales Area");
    InsertASHRAE2007(db, group, "Science/Classroom Laboratory");
    InsertASHRAE2007(db, group, "Shipping/Receiving");
    InsertASHRAE2007(db, group, "Storage - Active");
    InsertASHRAE2007(db, group, "University/College/Research Laboratory");
    group = InsertGroup(db, "Sports & Exercise");
    InsertASHRAE2007(db, group, "Atrium - Each additional floor");
    InsertASHRAE2007(db, group, "Atrium - First 3 floors");
    InsertASHRAE2007(db, group, "Break Room/Locker Room");
    InsertASHRAE2007(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2007(db, group, "Corridor/Transition");
    InsertASHRAE2007(db, group, "Dining Area");
    InsertASHRAE2007(db, group, "Elevator Machine Room");
    InsertASHRAE2007(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2007(db, group, "Gym/Exercise/Fitness Center - Playing Area");
    InsertASHRAE2007(db, group, "Gym/Exercise/Fitness Center - Weight Room");
    InsertASHRAE2007(db, group, "Gym/Exercise/Fitness Center- Aerobics Room");
    InsertASHRAE2007(db, group, "Lobby");
    InsertASHRAE2007(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2007(db, group, "Office - Enclosed");
    InsertASHRAE2007(db, group, "Office - Open Plan");
    InsertASHRAE2007(db, group, "Restrooms");
    InsertASHRAE2007(db, group, "Sales Area");
    InsertASHRAE2007(db, group, "Shipping/Receiving");
    InsertASHRAE2007(db, group, "Spectator Area");
    InsertASHRAE2007(db, group, "Sports Arena - Court Sports");
    InsertASHRAE2007(db, group, "Sports Arena - Indoor Playing Field");
    InsertASHRAE2007(db, group, "Sports Arena - Ring Sports");
    InsertASHRAE2007(db, group, "Storage - Active");
    InsertASHRAE2007(db, group, "Swimming (pool & deck)");
    group = InsertGroup(db, "Theater");
    InsertASHRAE2007(db, group, "Atrium - Each additional floor");
    InsertASHRAE2007(db, group, "Atrium - First 3 floors");
    InsertASHRAE2007(db, group, "Break Room/Locker Room");
    InsertASHRAE2007(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2007(db, group, "Corridor/Transition");
    InsertASHRAE2007(db, group, "Dining Area");
    InsertASHRAE2007(db, group, "Elevator Machine Room");
    InsertASHRAE2007(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2007(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2007(db, group, "Motion Picture Theater");
    InsertASHRAE2007(db, group, "Motion Picture Theater - Audience/Seating Area");
    InsertASHRAE2007(db, group, "Motion Picture Theater - Lobby");
    InsertASHRAE2007(db, group, "Office - Enclosed");
    InsertASHRAE2007(db, group, "Office - Open Plan");
    InsertASHRAE2007(db, group, "Performing Arts Theater");
    InsertASHRAE2007(db, group, "Performing Arts Theater - Audience/Seating Area");
    InsertASHRAE2007(db, group, "Performing Arts Theater - Dressing/Fitting Room");
    InsertASHRAE2007(db, group, "Performing Arts Theater - Lobby");
    InsertASHRAE2007(db, group, "Restrooms");
    InsertASHRAE2007(db, group, "Sales Area");
    InsertASHRAE2007(db, group, "Shipping/Receiving");
    InsertASHRAE2007(db, group, "Stages, Studios");
    InsertASHRAE2007(db, group, "Storage - Active");
    group = InsertGroup(db, "Transportation");
    InsertASHRAE2007(db, group, "Air/Train/Bus - Baggage Area");
    InsertASHRAE2007(db, group, "Airport - Concourse");
    InsertASHRAE2007(db, group, "Atrium - Each additional floor");
    InsertASHRAE2007(db, group, "Atrium - First 3 floors");
    InsertASHRAE2007(db, group, "Break Room/Locker Room");
    InsertASHRAE2007(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2007(db, group, "Corridor/Transition");
    InsertASHRAE2007(db, group, "Dining Area");
    InsertASHRAE2007(db, group, "Elevator Machine Room");
    InsertASHRAE2007(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2007(db, group, "Lobby");
    InsertASHRAE2007(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2007(db, group, "Office - Enclosed");
    InsertASHRAE2007(db, group, "Office - Open Plan");
    InsertASHRAE2007(db, group, "Parking Garage");
    InsertASHRAE2007(db, group, "Restrooms");
    InsertASHRAE2007(db, group, "Sales Area");
    InsertASHRAE2007(db, group, "Seating/Waiting Area");
    InsertASHRAE2007(db, group, "Shipping/Receiving");
    InsertASHRAE2007(db, group, "Storage - Active");
    InsertASHRAE2007(db, group, "Terminal - Ticket Counter");
    group = InsertGroup(db, "Courthouse/Police Station/Penitentiary");
    InsertASHRAE2007(db, group, "Atrium - Each additional floor");
    InsertASHRAE2007(db, group, "Atrium - First 3 floors");
    InsertASHRAE2007(db, group, "Auditorium Seating Area");
    InsertASHRAE2007(db, group, "Break Room/Locker Room");
    InsertASHRAE2007(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2007(db, group, "Confinement Cells");
    InsertASHRAE2007(db, group, "Corridor/Transition");
    InsertASHRAE2007(db, group, "Courtroom");
    InsertASHRAE2007(db, group, "Elevator Machine Room");
    InsertASHRAE2007(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2007(db, group, "Judges Chambers");
    InsertASHRAE2007(db, group, "Lobby");
    InsertASHRAE2007(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2007(db, group, "Office - Enclosed");
    InsertASHRAE2007(db, group, "Office - Open Plan");
    InsertASHRAE2007(db, group, "Penitentiary - Booking/Waiting");
    InsertASHRAE2007(db, group, "Penitentiary - Classroom");
    InsertASHRAE2007(db, group, "Penitentiary - Day Room");
    InsertASHRAE2007(db, group, "Penitentiary - Dining Area");
    InsertASHRAE2007(db, group, "Penitentiary - Guard Station");
    InsertASHRAE2007(db, group, "Restrooms");
    InsertASHRAE2007(db, group, "Shipping/Receiving");
    InsertASHRAE2007(db, group, "Storage - Active");
    group = InsertGroup(db, "Public Assembly");
    InsertASHRAE2007(db, group, "Atrium - Each additional floor");
    InsertASHRAE2007(db, group, "Atrium - First 3 floors");
    InsertASHRAE2007(db, group, "Auditorium Seating Area");
    InsertASHRAE2007(db, group, "Break Room/Locker Room");
    InsertASHRAE2007(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2007(db, group, "Convention - Audience Seating");
    InsertASHRAE2007(db, group, "Convention - Exhibit Space");
    InsertASHRAE2007(db, group, "Corridor/Transition");
    InsertASHRAE2007(db, group, "Dining Area");
    InsertASHRAE2007(db, group, "Elevator Machine Room");
    InsertASHRAE2007(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2007(db, group, "Lecture Classroom");
    InsertASHRAE2007(db, group, "Lobby");
    InsertASHRAE2007(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2007(db, group, "Museum - Children's");
    InsertASHRAE2007(db, group, "Museum - Exhibition");
    InsertASHRAE2007(db, group, "Museum - Restoration");
    InsertASHRAE2007(db, group, "Museum - Storage");
    InsertASHRAE2007(db, group, "Office - Enclosed");
    InsertASHRAE2007(db, group, "Office - Open Plan");
    InsertASHRAE2007(db, group, "Religious - Fellowship Hall");
    InsertASHRAE2007(db, group, "Religious - Seating");
    InsertASHRAE2007(db, group, "Religious - Worship Pulpit, Choir");
    InsertASHRAE2007(db, group, "Restrooms");
    InsertASHRAE2007(db, group, "Sales Area");
    InsertASHRAE2007(db, group, "Shipping/Receiving");
    InsertASHRAE2007(db, group, "Storage - Active");
    group = InsertGroup(db, "Food & Beverage Services");
    InsertASHRAE2007(db, group, "Atrium - Each additional floor");
    InsertASHRAE2007(db, group, "Atrium - First 3 floors");
    InsertASHRAE2007(db, group, "Break Room/Locker Room");
    InsertASHRAE2007(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2007(db, group, "Corridor/Transition");
    InsertASHRAE2007(db, group, "Dining: Bar, Lounge, Leisure Dining");
    InsertASHRAE2007(db, group, "Dining: Cafeteria/Fast Food");
    InsertASHRAE2007(db, group, "Dining: Family Dining");
    InsertASHRAE2007(db, group, "Elevator Machine Room");
    InsertASHRAE2007(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2007(db, group, "Lobby");
    InsertASHRAE2007(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2007(db, group, "Office - Enclosed");
    InsertASHRAE2007(db, group, "Restrooms");
    InsertASHRAE2007(db, group, "Sales Area");
    InsertASHRAE2007(db, group, "Shipping/Receiving");
    InsertASHRAE2007(db, group, "Storage - Active");
    group = InsertGroup(db, "Common Space Types");
    InsertASHRAE2007(db, group, "Electrical/Mechanical");
    InsertASHRAE2007(db, group, "Stairway");
    InsertASHRAE2007(db, group, "Storage - Inactive");
    InsertASHRAE2007(db, group, "Wood/Metal Shop");
    group = InsertGroup(db, "Hotel/Motel");
    InsertASHRAE2007(db, group, "Atrium - Each additional floor");
    InsertASHRAE2007(db, group, "Atrium - First 3 floors");
    InsertASHRAE2007(db, group, "Auditorium Seating Area");
    InsertASHRAE2007(db, group, "Break Room/Locker Room");
    InsertASHRAE2007(db, group, "Computer (not printing)");
    InsertASHRAE2007(db, group, "Conference/Meeting/Multipurpose");
    InsertASHRAE2007(db, group, "Corridor/Transition");
    InsertASHRAE2007(db, group, "Dining Area");
    InsertASHRAE2007(db, group, "Elevator Machine Room");
    InsertASHRAE2007(db, group, "Food Preparation, Kitchen (cooking)");
    InsertASHRAE2007(db, group, "Hotel Dining");
    InsertASHRAE2007(db, group, "Hotel Guest Room");
    InsertASHRAE2007(db, group, "Hotel Lobby/Prefunction");
    InsertASHRAE2007(db, group, "Laundry");
    InsertASHRAE2007(db, group, "Lobby");
    InsertASHRAE2007(db, group, "Lounge/Recreation/Coffee Station");
    InsertASHRAE2007(db, group, "Motel Dining");
    InsertASHRAE2007(db, group, "Motel Guest Room");
    InsertASHRAE2007(db, group, "Multi-purpose Assembly");
    InsertASHRAE2007(db, group, "Office - Enclosed");
    InsertASHRAE2007(db, group, "Office - Open Plan");
    InsertASHRAE2007(db, group, "Restrooms");
    InsertASHRAE2007(db, group, "Sales Area");
    InsertASHRAE2007(db, group, "Shipping/Receiving");
    InsertASHRAE2007(db, group, "Storage - Active");
    group = InsertGroup(db, "Industrial building");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Chilled storage");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Cold storage");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Laboratory");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Process area");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Speculative industrial space");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    InsertCIBSE(db, group, "Warehouse chilled storage");
    InsertCIBSE(db, group, "Warehouse storage");
    InsertCIBSE(db, group, "Workshop - small");
    group = InsertGroup(db, "Telephone exchanges");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "IT equipment");
    InsertCIBSE(db, group, "IT workspace");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    group = InsertGroup(db, "Hotel");
    InsertCIBSE(db, group, "Bathroom");
    InsertCIBSE(db, group, "Bedroom");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Changing facilities");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Cold storage");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "Display area");
    InsertCIBSE(db, group, "Dry sports hall");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Fitness suite/gym");
    InsertCIBSE(db, group, "Hall/lecture theatre");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Laundry");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Swimming pool");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    group = InsertGroup(db, "Retail warehouses");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Changing facilities");
    InsertCIBSE(db, group, "Chilled storage");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Cold storage");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "Display area");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Sales - chilled");
    InsertCIBSE(db, group, "Sales - electrical");
    InsertCIBSE(db, group, "Sales - general");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    InsertCIBSE(db, group, "Workshop - small");
    group = InsertGroup(db, "Prisons");
    InsertCIBSE(db, group, "Bathroom");
    InsertCIBSE(db, group, "Cell (police/prison)");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Changing facilities");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Classroom");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "Consulting room");
    InsertCIBSE(db, group, "Dry sports hall");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Fitness suite/gym");
    InsertCIBSE(db, group, "Hall/lecture theatre");
    InsertCIBSE(db, group, "Laundry");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    InsertCIBSE(db, group, "Waiting room");
    InsertCIBSE(db, group, "Workshop - small");
    group = InsertGroup(db, "Hospital");
    InsertCIBSE(db, group, "A&E Consulting area");
    InsertCIBSE(db, group, "Bathroom");
    InsertCIBSE(db, group, "Bedroom");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Changing facilities");
    InsertCIBSE(db, group, "Chilled storage");
    InsertCIBSE(db, group, "Circulation area (private)");
    InsertCIBSE(db, group, "Circulation area (public)");
    InsertCIBSE(db, group, "Classroom");
    InsertCIBSE(db, group, "Cold storage");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "Consulting area");
    InsertCIBSE(db, group, "Diagnostic Imaging");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Hall/lecture theatre");
    InsertCIBSE(db, group, "Hydrotherapy pool");
    InsertCIBSE(db, group, "Intensive care unit");
    InsertCIBSE(db, group, "IT equipment");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Laboratory");
    InsertCIBSE(db, group, "Laundry");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Operating theatre");
    InsertCIBSE(db, group, "Patient accomodation (day)");
    InsertCIBSE(db, group, "Patient accomodation (wards)");
    InsertCIBSE(db, group, "Physiotherapy Studio");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Post mortem facility");
    InsertCIBSE(db, group, "Process area");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    InsertCIBSE(db, group, "Waiting room");
    InsertCIBSE(db, group, "Ward Common room");
    InsertCIBSE(db, group, "Ward offices");
    group = InsertGroup(db, "Emergency services");
    InsertCIBSE(db, group, "Bathroom");
    InsertCIBSE(db, group, "Bedroom");
    InsertCIBSE(db, group, "Cell (police/prison)");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Changing facilities");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "Dry sports hall");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "IT equipment");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    InsertCIBSE(db, group, "Workshop - small");
    group = InsertGroup(db, "Restaurant/public house");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Cold storage");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Stage");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    group = InsertGroup(db, "Universities");
    InsertCIBSE(db, group, "Bathroom");
    InsertCIBSE(db, group, "Bedroom");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Changing facilities");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Classroom");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "Consulting room");
    InsertCIBSE(db, group, "Dry sports hall");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Fitness suite/gym");
    InsertCIBSE(db, group, "Hall/lecture theatre");
    InsertCIBSE(db, group, "IT equipment");
    InsertCIBSE(db, group, "IT workspace");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Laboratory");
    InsertCIBSE(db, group, "Laundry");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Stage");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Swimming pool");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    InsertCIBSE(db, group, "Waiting room");
    InsertCIBSE(db, group, "Workshop - small");
    group = InsertGroup(db, "Sports/leisure centre");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Changing facilities");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "Dry sports hall");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Fitness Studio");
    InsertCIBSE(db, group, "Fitness suite/gym");
    InsertCIBSE(db, group, "Hall/lecture theatre");
    InsertCIBSE(db, group, "Ice rink");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Laundry");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Swimming pool");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    group = InsertGroup(db, "Laundrette");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Laundry");
    InsertCIBSE(db, group, "Storage area");
    group = InsertGroup(db, "Primary school");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Changing facilities");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Classroom");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "Dry sports hall");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Swimming pool");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    group = InsertGroup(db, "Secondary school");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Changing facilities");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Classroom");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "Dry sports hall");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Hall/lecture theatre");
    InsertCIBSE(db, group, "IT equipment");
    InsertCIBSE(db, group, "IT workspace");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Laboratory");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Swimming pool");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    InsertCIBSE(db, group, "Workshop - small");
    group = InsertGroup(db, "Hostels/nursing homes");
    InsertCIBSE(db, group, "Bathroom");
    InsertCIBSE(db, group, "Bedroom");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Laundry");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    group = InsertGroup(db, "Airport terminals");
    InsertCIBSE(db, group, "Baggage Reclaim area");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Check in area");
    InsertCIBSE(db, group, "Chilled storage");
    InsertCIBSE(db, group, "Circulation (public)");
    InsertCIBSE(db, group, "Circulation(private)");
    InsertCIBSE(db, group, "Cold storage");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "Display area");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "IT equipment");
    InsertCIBSE(db, group, "IT workspace");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Sales - chilled");
    InsertCIBSE(db, group, "Sales - general");
    InsertCIBSE(db, group, "Security check area");
    InsertCIBSE(db, group, "Speculative retail space");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    InsertCIBSE(db, group, "Waiting room");
    group = InsertGroup(db, "Libraries/museums");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Circulation (public)");
    InsertCIBSE(db, group, "Circulation(private)");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "Display area");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Hall/lecture theatre");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Laboratory");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Sales - general");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    InsertCIBSE(db, group, "Workshop - small");
    group = InsertGroup(db, "Crown/county courts");
    InsertCIBSE(db, group, "Cell (police/prison)");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Hall/lecture theatre");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    group = InsertGroup(db, "Sports ground arena");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Changing facilities");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "Display area");
    InsertCIBSE(db, group, "Dry sports hall");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Fitness Studio");
    InsertCIBSE(db, group, "Fitness suite/gym");
    InsertCIBSE(db, group, "Hall/lecture theatre");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Sales - general");
    InsertCIBSE(db, group, "Stage");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    InsertCIBSE(db, group, "Workshop - small");
    group = InsertGroup(db, "Warehouse and storage");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Changing facilities");
    InsertCIBSE(db, group, "Chilled storage");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Cold storage");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "IT equipment");
    InsertCIBSE(db, group, "IT workspace");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Speculative industrial space");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    InsertCIBSE(db, group, "Warehouse chilled storage");
    InsertCIBSE(db, group, "Warehouse storage");
    InsertCIBSE(db, group, "Workshop - small");
    group = InsertGroup(db, "Retail");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Changing facilities");
    InsertCIBSE(db, group, "Chilled storage");
    InsertCIBSE(db, group, "Circulation (public)");
    InsertCIBSE(db, group, "Circulation (private)");
    InsertCIBSE(db, group, "Cold storage");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "Display area");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Sales - chilled");
    InsertCIBSE(db, group, "Sales - electrical");
    InsertCIBSE(db, group, "Sales - general");
    InsertCIBSE(db, group, "Speculative retail space");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    InsertCIBSE(db, group, "Workshop - small");
    group = InsertGroup(db, "Dwelling");
    InsertCIBSE(db, group, "Bathroom");
    InsertCIBSE(db, group, "Bedroom");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Common circulation area");
    InsertCIBSE(db, group, "Dining room");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Lounge");
    InsertCIBSE(db, group, "Toilet");
    group = InsertGroup(db, "Office");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Changing facilities");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "Data centre (24hr)");
    InsertCIBSE(db, group, "Fitness suite/gym");
    InsertCIBSE(db, group, "High Density IT equipment (24hr)");
    InsertCIBSE(db, group, "IT equipment");
    InsertCIBSE(db, group, "IT equipment (24hr)");
    InsertCIBSE(db, group, "IT workspace");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Speculative office space");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    group = InsertGroup(db, "Primary health care");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Consulting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    InsertCIBSE(db, group, "Waiting room");
    group = InsertGroup(db, "Workshops");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Chilled storage");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Speculative industrial space");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    InsertCIBSE(db, group, "Warehouse chilled storage");
    InsertCIBSE(db, group, "Warehouse storage");
    InsertCIBSE(db, group, "Workshop - small");
    group = InsertGroup(db, "Social clubs");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Changing facilities");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Dry sports hall");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Fitness suite/gym");
    InsertCIBSE(db, group, "Hall/lecture theatre");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    InsertCIBSE(db, group, "Workshop - small");
    group = InsertGroup(db, "Theatres/cinemas");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Circulation (public)");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Display area");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Hall/lecture theatre");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Stage");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    InsertCIBSE(db, group, "Workshop - small");
    group = InsertGroup(db, "Community/day centre");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Changing facilities");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Common room");
    InsertCIBSE(db, group, "Consulting room");
    InsertCIBSE(db, group, "Dry sports hall");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Hall/lecture theatre");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    InsertCIBSE(db, group, "Waiting room");
    InsertCIBSE(db, group, "Workshop - small");
    group = InsertGroup(db, "Transport");
    InsertCIBSE(db, group, "Cellular office");
    InsertCIBSE(db, group, "Circulation (public)");
    InsertCIBSE(db, group, "Circulation area");
    InsertCIBSE(db, group, "Eating/drinking area");
    InsertCIBSE(db, group, "Kitchen");
    InsertCIBSE(db, group, "Meeting room");
    InsertCIBSE(db, group, "Open plan office");
    InsertCIBSE(db, group, "Plant room");
    InsertCIBSE(db, group, "Reception");
    InsertCIBSE(db, group, "Storage area");
    InsertCIBSE(db, group, "Tea making");
    InsertCIBSE(db, group, "Toilet");
    InsertCIBSE(db, group, "Waiting room");
    }
