/*--------------------------------------------------------------------------------------+
|
|     $Source: PublicAPI/WebServices/ConnectC/ConnectWsgGlobal/GlobalSchemaBufferGenPublic.h $
|
|  $Copyright: (c) 2017 Bentley Systems, Incorporated. All rights reserved. $
|
+--------------------------------------------------------------------------------------*/
#pragma once
//__PUBLISH_SECTION_START__
//--------------------------------------------------------------------------------------+
// <auto-generated>
//     This code was generated by the pyCApiGen tool on May 17, 2017.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//--------------------------------------------------------------------------------------+

/****************************************************************************************
* \defgroup BufferPropertyEnums ConnectWebServicesClientC Buffer Property Enumerations
* \{
****************************************************************************************/
/**
* \brief Organization_V2 
*/
typedef enum
    {
    ORGANIZATION_V2_BUFF_OBJECTID                       = 1, /**< \b ObjectId (generated property for instance id) . */
    ORGANIZATION_V2_BUFF_ORGANIZATIONGUID               = 2, /**< \b OrganizationGuid. */
    ORGANIZATION_V2_BUFF_ORGANIZATIONNAME               = 3, /**< \b OrganizationName. */
    } ORGANIZATION_V2_BUFF_PROPERTY;

/**
* \brief OrgProject 
*/
typedef enum
    {
    ORGPROJECT_BUFF_OBJECTID                       = 1, /**< \b ObjectId (generated property for instance id) . */
    ORGPROJECT_BUFF_NAME                           = 2, /**< \b Name. */
    ORGPROJECT_BUFF_NUMBER                         = 3, /**< \b Number. */
    ORGPROJECT_BUFF_STATUS                         = 4, /**< \b Status. */
    ORGPROJECT_BUFF_ISRBACENABLED                  = 5, /**< \b IsRbacEnabled. */
    } ORGPROJECT_BUFF_PROPERTY;

/**
* \brief Project_V4 
*/
typedef enum
    {
    PROJECT_V4_BUFF_OBJECTID                       = 1, /**< \b ObjectId (generated property for instance id) . */
    PROJECT_V4_BUFF_ULTIMATEREFID                  = 2, /**< \b UltimateRefId. */
    PROJECT_V4_BUFF_ISRBACENABLED                  = 3, /**< \b IsRbacEnabled. */
    PROJECT_V4_BUFF_NAME                           = 4, /**< \b Name. */
    PROJECT_V4_BUFF_NUMBER                         = 5, /**< \b Number. */
    PROJECT_V4_BUFF_INDUSTRY                       = 6, /**< \b Industry. */
    PROJECT_V4_BUFF_ASSETTYPE                      = 7, /**< \b AssetType. */
    PROJECT_V4_BUFF_LASTMODIFIED                   = 8, /**< \b LastModified. */
    PROJECT_V4_BUFF_LOCATION                       = 9, /**< \b Location. */
    PROJECT_V4_BUFF_LATITUDE                       = 10, /**< \b Latitude. */
    PROJECT_V4_BUFF_LONGITUDE                      = 11, /**< \b Longitude. */
    PROJECT_V4_BUFF_LOCATIONISUSINGLATLONG         = 12, /**< \b LocationIsUsingLatLong. */
    PROJECT_V4_BUFF_REGISTEREDDATE                 = 13, /**< \b RegisteredDate. */
    PROJECT_V4_BUFF_TIMEZONELOCATION               = 14, /**< \b TimeZoneLocation. */
    PROJECT_V4_BUFF_STATUS                         = 15, /**< \b Status. */
    PROJECT_V4_BUFF_DATA_LOCATION_GUID             = 16, /**< \b Data_Location_Guid. */
    PROJECT_V4_BUFF_COUNTRY_CODE                   = 17, /**< \b Country_Code. */
    } PROJECT_V4_BUFF_PROPERTY;

/**
* \brief ProjectFavorite_V4 
*/
typedef enum
    {
    PROJECTFAVORITE_V4_BUFF_OBJECTID                       = 1, /**< \b ObjectId (generated property for instance id) . */
    PROJECTFAVORITE_V4_BUFF_ULTIMATEREFID                  = 2, /**< \b UltimateRefId. */
    PROJECTFAVORITE_V4_BUFF_ISRBACENABLED                  = 3, /**< \b IsRbacEnabled. */
    PROJECTFAVORITE_V4_BUFF_NAME                           = 4, /**< \b Name. */
    PROJECTFAVORITE_V4_BUFF_NUMBER                         = 5, /**< \b Number. */
    PROJECTFAVORITE_V4_BUFF_INDUSTRY                       = 6, /**< \b Industry. */
    PROJECTFAVORITE_V4_BUFF_ASSETTYPE                      = 7, /**< \b AssetType. */
    PROJECTFAVORITE_V4_BUFF_LASTMODIFIED                   = 8, /**< \b LastModified. */
    PROJECTFAVORITE_V4_BUFF_LOCATION                       = 9, /**< \b Location. */
    PROJECTFAVORITE_V4_BUFF_LATITUDE                       = 10, /**< \b Latitude. */
    PROJECTFAVORITE_V4_BUFF_LONGITUDE                      = 11, /**< \b Longitude. */
    PROJECTFAVORITE_V4_BUFF_LOCATIONISUSINGLATLONG         = 12, /**< \b LocationIsUsingLatLong. */
    PROJECTFAVORITE_V4_BUFF_REGISTEREDDATE                 = 13, /**< \b RegisteredDate. */
    PROJECTFAVORITE_V4_BUFF_TIMEZONELOCATION               = 14, /**< \b TimeZoneLocation. */
    PROJECTFAVORITE_V4_BUFF_STATUS                         = 15, /**< \b Status. */
    PROJECTFAVORITE_V4_BUFF_DATA_LOCATION_GUID             = 16, /**< \b Data_Location_Guid. */
    PROJECTFAVORITE_V4_BUFF_COUNTRY_CODE                   = 17, /**< \b Country_Code. */
    } PROJECTFAVORITE_V4_BUFF_PROPERTY;

/**
* \brief ProjectMRU 
*/
typedef enum
    {
    PROJECTMRU_BUFF_OBJECTID                       = 1, /**< \b ObjectId (generated property for instance id) . */
    PROJECTMRU_BUFF_PROJECTGUID                    = 2, /**< \b ProjectGuid. */
    PROJECTMRU_BUFF_PROJECTNAME                    = 3, /**< \b ProjectName. */
    PROJECTMRU_BUFF_LASTMODIFIED                   = 4, /**< \b LastModified. */
    } PROJECTMRU_BUFF_PROPERTY;

/**
* \brief ProjectMRUDetail_V4 
*/
typedef enum
    {
    PROJECTMRUDETAIL_V4_BUFF_OBJECTID                       = 1, /**< \b ObjectId (generated property for instance id) . */
    PROJECTMRUDETAIL_V4_BUFF_ISFAVORITE                     = 2, /**< \b IsFavorite. */
    PROJECTMRUDETAIL_V4_BUFF_LASTACCESSEDBYUSER             = 3, /**< \b LastAccessedByUser. */
    PROJECTMRUDETAIL_V4_BUFF_ULTIMATEREFID                  = 4, /**< \b UltimateRefId. */
    PROJECTMRUDETAIL_V4_BUFF_ISRBACENABLED                  = 5, /**< \b IsRbacEnabled. */
    PROJECTMRUDETAIL_V4_BUFF_NAME                           = 6, /**< \b Name. */
    PROJECTMRUDETAIL_V4_BUFF_NUMBER                         = 7, /**< \b Number. */
    PROJECTMRUDETAIL_V4_BUFF_INDUSTRY                       = 8, /**< \b Industry. */
    PROJECTMRUDETAIL_V4_BUFF_ASSETTYPE                      = 9, /**< \b AssetType. */
    PROJECTMRUDETAIL_V4_BUFF_LASTMODIFIED                   = 10, /**< \b LastModified. */
    PROJECTMRUDETAIL_V4_BUFF_LOCATION                       = 11, /**< \b Location. */
    PROJECTMRUDETAIL_V4_BUFF_LATITUDE                       = 12, /**< \b Latitude. */
    PROJECTMRUDETAIL_V4_BUFF_LONGITUDE                      = 13, /**< \b Longitude. */
    PROJECTMRUDETAIL_V4_BUFF_LOCATIONISUSINGLATLONG         = 14, /**< \b LocationIsUsingLatLong. */
    PROJECTMRUDETAIL_V4_BUFF_REGISTEREDDATE                 = 15, /**< \b RegisteredDate. */
    PROJECTMRUDETAIL_V4_BUFF_TIMEZONELOCATION               = 16, /**< \b TimeZoneLocation. */
    PROJECTMRUDETAIL_V4_BUFF_STATUS                         = 17, /**< \b Status. */
    PROJECTMRUDETAIL_V4_BUFF_DATA_LOCATION_GUID             = 18, /**< \b Data_Location_Guid. */
    PROJECTMRUDETAIL_V4_BUFF_COUNTRY_CODE                   = 19, /**< \b Country_Code. */
    } PROJECTMRUDETAIL_V4_BUFF_PROPERTY;

/** \} */
/** \} */

