//:>--------------------------------------------------------------------------------------+
//:>
//:>     $Source: PublicApi/ImagePP/all/h/HFCFileModuleCodes.h $
//:>
//:>  $Copyright: (c) 2010 Bentley Systems, Incorporated. All rights reserved. $
//:>
//:>+--------------------------------------------------------------------------------------

#pragma once

#include "HFCErrorCodeBuilder.h"
#include "HFCErrorCodeHandler.h"
#include "HFCErrorCodeMacros.h"

// Note that the builder and handlers will be in the same class.
// We will refer to them as builders even though they are also handlers.


// HFC_FILE_EXCEPTION
HFC_ERRORCODE_START_DECLARATION_CLASS2(HFCFileExceptionBuilder, HFCErrorCodeBuilder, HFCErrorCodeHandler)
HFC_ERRORCODE_DECLARE_BUILDER_EXCEPTION
HFC_ERRORCODE_DECLARE_HANDLER
HFC_ERRORCODE_END_DECLARATION

// HFC_CANNOT_LOCK_FILE_EXCEPTION
HFC_ERRORCODE_START_DECLARATION_CLASS(HFCCannotLockFileExceptionBuilder, HFCFileExceptionBuilder)
HFC_ERRORCODE_DECLARE_BUILDER_EXCEPTION
HFC_ERRORCODE_DECLARE_HANDLER
HFC_ERRORCODE_END_DECLARATION

// HFC_CORRUPTED_FILE_EXCEPTION
HFC_ERRORCODE_START_DECLARATION_CLASS(HFCFileCorruptedExceptionBuilder, HFCFileExceptionBuilder)
HFC_ERRORCODE_DECLARE_BUILDER_EXCEPTION
HFC_ERRORCODE_DECLARE_HANDLER
HFC_ERRORCODE_END_DECLARATION

// HFC_FILE_NOT_FOUND_EXCEPTION
HFC_ERRORCODE_START_DECLARATION_CLASS(HFCFileNotFoundExceptionBuilder, HFCFileExceptionBuilder)
HFC_ERRORCODE_DECLARE_BUILDER_EXCEPTION
HFC_ERRORCODE_DECLARE_HANDLER
HFC_ERRORCODE_END_DECLARATION

// HFC_FILE_EXIST_EXCEPTION
HFC_ERRORCODE_START_DECLARATION_CLASS(HFCFileExistExceptionBuilder, HFCFileExceptionBuilder)
HFC_ERRORCODE_DECLARE_BUILDER_EXCEPTION
HFC_ERRORCODE_DECLARE_HANDLER
HFC_ERRORCODE_END_DECLARATION

// HFC_FILE_READ_ONLY_EXCEPTION
HFC_ERRORCODE_START_DECLARATION_CLASS(HFCFileReadOnlyExceptionBuilder, HFCFileExceptionBuilder)
HFC_ERRORCODE_DECLARE_BUILDER_EXCEPTION
HFC_ERRORCODE_DECLARE_HANDLER
HFC_ERRORCODE_END_DECLARATION

// HFC_FILE_NOT_CREATED_EXCEPTION
HFC_ERRORCODE_START_DECLARATION_CLASS(HFCFileNotCreatedExceptionBuilder, HFCFileExceptionBuilder)
HFC_ERRORCODE_DECLARE_BUILDER_EXCEPTION
HFC_ERRORCODE_DECLARE_HANDLER
HFC_ERRORCODE_END_DECLARATION

// HFC_FILE_NOT_SUPPORTED_EXCEPTION
HFC_ERRORCODE_START_DECLARATION_CLASS(HFCFileNotSupportedExceptionBuilder, HFCFileExceptionBuilder)
HFC_ERRORCODE_DECLARE_BUILDER_EXCEPTION
HFC_ERRORCODE_DECLARE_HANDLER
HFC_ERRORCODE_END_DECLARATION

// HFC_FILE_OUT_OF_RANGE_EXCEPTION
HFC_ERRORCODE_START_DECLARATION_CLASS(HFCFileOutOfRangeExceptionBuilder, HFCFileExceptionBuilder)
HFC_ERRORCODE_DECLARE_BUILDER_EXCEPTION
HFC_ERRORCODE_DECLARE_HANDLER
HFC_ERRORCODE_END_DECLARATION

// HFC_FILE_PERMISSION_DENIED_EXCEPTION
HFC_ERRORCODE_START_DECLARATION_CLASS(HFCFilePermissionDeniedExceptionBuilder, HFCFileExceptionBuilder)
HFC_ERRORCODE_DECLARE_BUILDER_EXCEPTION
HFC_ERRORCODE_DECLARE_HANDLER
HFC_ERRORCODE_END_DECLARATION

