//:>--------------------------------------------------------------------------------------+
//:>
//:>     $Source: PublicApi/ImagePP/all/h/HFCTestedExceptions.h $
//:>
//:>  $Copyright: (c) 2012 Bentley Systems, Incorporated. All rights reserved. $
//:>
//:>+--------------------------------------------------------------------------------------
//-----------------------------------------------------------------------------
// This header contains all the file formats headers
//-----------------------------------------------------------------------------
#pragma once

#include "HFCException.h"
#include "HFCErrorCodeException.h"
#include "HFSException.h"
#include "HGFException.h"
#include "HPAException.h"
#include "HPSException.h"
#include "HRFInternetImagingException.h"
#include "HRPException.h"
#include "HRFException.h"
#include "HCSException.h"
#include "HCPException.h"
#include "HCDException.h"
#include "HVEException.h"

#include "HRFPDFException.h"
#include "HRFOracleException.h"

#define HFC_REGISTER_EXCEPTION(pi_rLabelStr, pi_pClass) \
    HFCExceptionATP::GetInstance()->AddException(pi_rLabelStr, pi_pClass);

struct HFCExceptionRegister
    {
    HFCExceptionRegister()
        {
//HFC Exceptions To Test
        HFC_REGISTER_EXCEPTION(L"HFC_EXCEPTION",        new HFCException(HFC_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HFC_MEMORY_EXCEPTION",    new HFCException(HFC_MEMORY_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HFC_OUT_OF_MEMORY_EXCEPTION", new HFCException(HFC_OUT_OF_MEMORY_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HFC_FILE_EXCEPTION", new HFCFileException(L"FileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_CANNOT_LOCK_FILE_EXCEPTION", new HFCFileException(HFC_CANNOT_LOCK_FILE_EXCEPTION, L"UnlockableFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_LOCK_VIOLATION_FILE_EXCEPTION", new HFCFileException(HFC_LOCK_VIOLATION_FILE_EXCEPTION, L"LockViolationFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_CORRUPTED_FILE_EXCEPTION", new HFCFileException(HFC_CORRUPTED_FILE_EXCEPTION, L"CorruptedFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_FILE_NOT_FOUND_EXCEPTION", new HFCFileException(HFC_FILE_NOT_FOUND_EXCEPTION, L"NotFoundFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_FILE_EXIST_EXCEPTION", new HFCFileException(HFC_FILE_EXIST_EXCEPTION, L"ExistFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_FILE_READ_ONLY_EXCEPTION", new HFCFileException(HFC_FILE_READ_ONLY_EXCEPTION, L"ReadOnlyFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_FILE_NOT_CREATED_EXCEPTION", new HFCFileException(HFC_FILE_NOT_CREATED_EXCEPTION, L"NotCreatedFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_FILE_NOT_SUPPORTED_EXCEPTION", new HFCFileException(HFC_FILE_NOT_SUPPORTED_EXCEPTION, L"UnsupportedFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_FILE_OUT_OF_RANGE_EXCEPTION", new HFCFileException(HFC_FILE_OUT_OF_RANGE_EXCEPTION, L"OutOfRangeFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_FILE_PERMISSION_DENIED_EXCEPTION", new HFCFileException(HFC_FILE_PERMISSION_DENIED_EXCEPTION, L"PermissionDeniedFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_DLL_NOT_FOUND_EXCEPTION", new HFCFileException(HFC_DLL_NOT_FOUND_EXCEPTION, L"NotFoundDllName"))
        HFC_REGISTER_EXCEPTION(L"HFC_DEVICE_EXCEPTION", new HFCDeviceException(HFC_DEVICE_EXCEPTION, L"DeviceName"))
        HFC_REGISTER_EXCEPTION(L"HFC_NO_DISK_SPACE_LEFT_EXCEPTION", new HFCDeviceException(HFC_NO_DISK_SPACE_LEFT_EXCEPTION, L"NoDiskSpaceLeftDeviceName"))
        HFC_REGISTER_EXCEPTION(L"HFC_DEVICE_ABORT_EXCEPTION", new HFCDeviceException(HFC_DEVICE_ABORT_EXCEPTION, L"AbortDeviceName"))
        HFC_REGISTER_EXCEPTION(L"HFC_INTERNET_CONNECTION_EXCEPTION", new HFCInternetConnectionException(L"InternetConnectionDeviceName", HFCInternetConnectionException::CANNOT_BIND));
        HFC_REGISTER_EXCEPTION(L"HFC_OBJECT_NOT_IN_FACTORY_EXCEPTION", new HFCException(HFC_OBJECT_NOT_IN_FACTORY_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HFC_GEOMETRY_EXCEPTION", new HFCException(HFC_GEOMETRY_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HFC_ERROR_CODE_EXCEPTION", new HFCErrorCodeException(HFCErrorCode(L"[F1233210] ErrorMessage")))

        HFC_REGISTER_EXCEPTION(L"HFC_CANNOT_CREATE_SYNCHRO_OBJ_EXCEPTION", new HFCCannotCreateSynchroObjException(HFCCannotCreateSynchroObjException::MUTEX))
        HFC_REGISTER_EXCEPTION(L"HFC_INVALID_FILE_NAME_EXCEPTION", new HFCFileException(HFC_INVALID_FILE_NAME_EXCEPTION, L"InvalidFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_SHARING_VIOLATION_EXCEPTION", new HFCFileException(HFC_SHARING_VIOLATION_EXCEPTION, L"SharingViolationFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_CANNOT_UNLOCK_FILE_EXCEPTION", new HFCFileException(HFC_CANNOT_UNLOCK_FILE_EXCEPTION, L"CannotUnlockFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_INVALID_HTTP_REQUEST_STR_EXCEPTION", new HFCException(HFC_INVALID_HTTP_REQUEST_STR_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HFC_INVALID_OP_OR_VALUE_EXCEPTION", new HFCException(HFC_INVALID_OP_OR_VALUE_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HFC_BAD_NUMBER_OF_BYTE_READ_EXCEPTION", new HFCFileException(HFC_BAD_NUMBER_OF_BYTE_READ_EXCEPTION, L"BadNumberByteReadFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_CANNOT_OPEN_FILE_EXCEPTION", new HFCFileException(HFC_CANNOT_OPEN_FILE_EXCEPTION, L"CannotOpenFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_CORRUPTED_DLL_EXCEPTION", new HFCFileException(HFC_CORRUPTED_DLL_EXCEPTION, L"CorrutedDLLName"))
        HFC_REGISTER_EXCEPTION(L"HFC_CANNOT_CONNECT_TO_DB_EXCEPTION", new HFCFileException(HFC_CANNOT_CONNECT_TO_DB_EXCEPTION, L"CannotConnectToDBFileName"))
        
        HFC_REGISTER_EXCEPTION(L"HFC_INVALID_URL_FOR_SISTER_FILE_EXCEPTION", new HFCFileException(HFC_INVALID_URL_FOR_SISTER_FILE_EXCEPTION, L"InvalidUrlForSisterFileFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_DIRECTORY_READ_ONLY_EXCEPTION", new HFCFileException(HFC_DIRECTORY_READ_ONLY_EXCEPTION, L"DirectoryReadOnlyDirName"))
        HFC_REGISTER_EXCEPTION(L"HFC_SISTER_FILE_NOT_CREATED_EXCEPTION", new HFCFileException(HFC_SISTER_FILE_NOT_CREATED_EXCEPTION, L"SisterFileNotCreateFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_DIRECTORY_NOT_CREATED_EXCEPTION", new HFCFileException(HFC_DIRECTORY_NOT_CREATED_EXCEPTION, L"DirectoryNotCreateDirName"))
        HFC_REGISTER_EXCEPTION(L"HFC_CANNOT_CLOSE_FILE_EXCEPTION", new HFCFileException(HFC_CANNOT_CLOSE_FILE_EXCEPTION, L"CannotCloseFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_OLE_INVALID_STRUC_STORAGE_OBJ_EXCEPTION", new HFCOLEStructuredStorageException(HFC_OLE_INVALID_STRUC_STORAGE_OBJ_EXCEPTION, L"ObjectName"))
        HFC_REGISTER_EXCEPTION(L"HFC_OLE_OLDER_DLL_EXCEPTION", new HFCFileException(HFC_OLE_OLDER_DLL_EXCEPTION, L"OLEOlderDllFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_WRITE_FAULT_EXCEPTION", new HFCFileException(HFC_WRITE_FAULT_EXCEPTION, L"WriteFaultFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_READ_FAULT_EXCEPTION", new HFCDeviceException(HFC_READ_FAULT_EXCEPTION, L"ReadFaultFileName"))
        HFC_REGISTER_EXCEPTION(L"HFC_FILE_IO_ERROR_EXCEPTION", new HFCOLEStructuredStorageException(HFC_FILE_IO_ERROR_EXCEPTION, L"FileIOerrorFilename"))
        HFC_REGISTER_EXCEPTION(L"HFC_INTERNAL_ERROR_EXCEPTION", new HFCException(HFC_INTERNAL_ERROR_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HFC_TEMPORARY_FILE_RELATED_EXCEPTION", new HFCException(HFC_TEMPORARY_FILE_RELATED_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HFC_LOGIN_INFORMATION_NOT_AVAILABLE_EXCEPTION", new HFCException(HFC_LOGIN_INFORMATION_NOT_AVAILABLE_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HFC_FILE_NOT_SUPPORTED_IN_WRITE_MODE", new HFCFileException(HFC_FILE_NOT_SUPPORTED_IN_WRITE_MODE, L"FileNotSupportedInWriteModeName"))


//HCD Exceptions To Test
        HFC_REGISTER_EXCEPTION(L"HCD_EXCEPTION", new HCDException())
        HFC_REGISTER_EXCEPTION(L"HCD_IJL_ERROR_EXCEPTION", new HCDIJLErrorException(-1))
        HFC_REGISTER_EXCEPTION(L"HCD_IJL_CHANNEL_COUNT_NOT_SUPPORTED_EXCEPTION", new HCDException(HCD_IJL_CHANNEL_COUNT_NOT_SUPPORTED_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HCD_IJG_LIBRARY_ERROR_EXCEPTION", new HCDException(HCD_IJG_LIBRARY_ERROR_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HCD_CORRUPTED_PACKBITS_DATA_EXCEPTION", new HCDException(HCD_CORRUPTED_PACKBITS_DATA_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HCD_CORRUPTED_DATA_EXCEPTION", new HCDException(HCD_CORRUPTED_DATA_EXCEPTION))

//HFS Exceptions To Test
        HFC_REGISTER_EXCEPTION(L"HFS_EXCEPTION", new HFSException())
        HFC_REGISTER_EXCEPTION(L"HFS_INVALID_PATH_EXCEPTION", new HFSInvalidPathException(L"InvalidPath"))
        HFC_REGISTER_EXCEPTION(L"HFS_IBP_INVALID_RESPONSE_EXCEPTION", new HFSHIBPInvalidResponseException(L"HIBPRequest"))
        HFC_REGISTER_EXCEPTION(L"HFS_IBP_ERROR_EXCEPTION", new HFSHIBPErrorException(L"IBPErrorMessage"))
        HFC_REGISTER_EXCEPTION(L"HFS_URL_SCHEME_NOT_SUPPORTED_EXCEPTION", new HFSInvalidPathException(HFS_URL_SCHEME_NOT_SUPPORTED_EXCEPTION, L"URLSchemeNotSupportedPath"))
        HFC_REGISTER_EXCEPTION(L"HFS_IBP_PROTOCOL_NOT_SUPPORTED_EXCEPTION", new HFSException(HFS_IBP_PROTOCOL_NOT_SUPPORTED_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HFS_INVALID_DIRECTORY_PATH_EXCEPTION", new HFSInvalidPathException(HFS_INVALID_DIRECTORY_PATH_EXCEPTION, L"InvalidDirectoryPath"))
        HFC_REGISTER_EXCEPTION(L"HFS_CANNOT_START_NET_RESOURCE_ENUM_EXCEPTION", new HFSException(HFS_CANNOT_START_NET_RESOURCE_ENUM_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HFS_CANNOT_ENUM_NEXT_NET_RESOURCE_EXCEPTION", new HFSException(HFS_CANNOT_ENUM_NEXT_NET_RESOURCE_EXCEPTION))

//HGF Exceptions To Test
        HFC_REGISTER_EXCEPTION(L"HGF_REPROJECTION_EXCEPTION", new HGFException(HGF_REPROJECTION_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HGF_MZ_G_COORD_EXCEPTION", new HGFmzGCoordException(20))
        HFC_REGISTER_EXCEPTION(L"HGF_DOMAIN_EXCEPTION", new HGFException(HGF_DOMAIN_EXCEPTION))

        HPASourcePos StartPos;
        HPASourcePos EndPos;

        StartPos.m_Line      = 10;
        StartPos.m_Column = 11;

        EndPos.m_Line    = 10;
        EndPos.m_Column = 12;

//HPA Exceptions To Test
        HFCPtr<HPANode> pHPATestNode = new HPANode(0,
                                                   StartPos,
                                                   EndPos,
                                                   0);

        HFC_REGISTER_EXCEPTION(L"HPA_EXCEPTION", new HPAException(pHPATestNode))
        HFC_REGISTER_EXCEPTION(L"HPA_NO_TOKEN_EXCEPTION", new HPAException(HPA_NO_TOKEN_EXCEPTION, pHPATestNode))
        HFC_REGISTER_EXCEPTION(L"HPA_RECURSIVE_INCLUSION_EXCEPTION", new HPAException(HPA_RECURSIVE_INCLUSION_EXCEPTION, pHPATestNode))
        HFC_REGISTER_EXCEPTION(L"HPA_GENERIC_EXCEPTION", new HPAGenericException(pHPATestNode, L"HPAGenericExceptionMsg"))

        HFC_REGISTER_EXCEPTION(L"HPA_CANNOT_FIND_PRODUCTION_EXCEPTION", new HPAException(HPA_CANNOT_FIND_PRODUCTION_EXCEPTION, pHPATestNode))
        HFC_REGISTER_EXCEPTION(L"HPA_CANNOT_RESOLVE_START_RULE_EXCEPTION", new HPAException(HPA_CANNOT_RESOLVE_START_RULE_EXCEPTION, pHPATestNode))
        HFC_REGISTER_EXCEPTION(L"HPA_NODE_LEFT_TO_PARSE_EXCEPTION", new HPAException(HPA_NODE_LEFT_TO_PARSE_EXCEPTION, pHPATestNode))


//HPS Exceptions To Test

        StartPos.m_Line      = 11;
        StartPos.m_Column = 21;

        EndPos.m_Line    = 11;
        EndPos.m_Column = 22;


        HFCPtr<HPANode> pHPSTestNode = new HPANode(0,
                                                   StartPos,
                                                   EndPos,
                                                   0);

        HFC_REGISTER_EXCEPTION(L"HPS_EXCEPTION", new HPSException(pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_INCLUDE_NOT_FOUND_EXCEPTION", new HPSException(HPS_INCLUDE_NOT_FOUND_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_INVALID_OBJECT_EXCEPTION", new HPSException(HPS_INVALID_OBJECT_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_TYPE_MISMATCH_EXCEPTION", new HPSTypeMismatchException(pHPSTestNode, HPSTypeMismatchException::STRING))
        HFC_REGISTER_EXCEPTION(L"HPS_IMAGE_EXPECTED_EXCEPTION", new HPSTypeMismatchException(HPS_IMAGE_EXPECTED_EXCEPTION, pHPSTestNode, HPSTypeMismatchException::NUMBER))
        HFC_REGISTER_EXCEPTION(L"HPS_TRANSFO_EXPECTED_EXCEPTION", new HPSTypeMismatchException(HPS_TRANSFO_EXPECTED_EXCEPTION, pHPSTestNode, HPSTypeMismatchException::OBJECT))
        HFC_REGISTER_EXCEPTION(L"HPS_FILTER_EXPECTED_EXCEPTION", new HPSTypeMismatchException(HPS_FILTER_EXPECTED_EXCEPTION, pHPSTestNode, HPSTypeMismatchException::STRING))
        HFC_REGISTER_EXCEPTION(L"HPS_WORLD_EXPECTED_EXCEPTION", new HPSTypeMismatchException(HPS_WORLD_EXPECTED_EXCEPTION, pHPSTestNode, HPSTypeMismatchException::NUMBER))
        HFC_REGISTER_EXCEPTION(L"HPS_QUALIFIER_EXPECTED_EXCEPTION", new HPSException(HPS_QUALIFIER_EXPECTED_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_EXPRESSION_EXPECTED_EXCEPTION", new HPSException(HPS_EXPRESSION_EXPECTED_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_INVALID_NUMERIC_EXCEPTION", new HPSException(HPS_INVALID_NUMERIC_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_INVALID_URL_EXCEPTION", new HPSException(HPS_INVALID_URL_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_FILE_NOT_FOUND_EXCEPTION", new HPSException(HPS_FILE_NOT_FOUND_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_NO_IMAGE_IN_FILE_EXCEPTION", new HPSException(HPS_NO_IMAGE_IN_FILE_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_OUT_OF_RANGE_EXCEPTION", new HPSOutOfRangeException(pHPSTestNode, 10.5, 20.6))
        HFC_REGISTER_EXCEPTION(L"HPS_ALPHA_PALETTE_NOT_SUPPORTED_EXCEPTION", new HPSException(HPS_ALPHA_PALETTE_NOT_SUPPORTED_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_INVALID_WORLD_EXCEPTION", new HPSException(HPS_INVALID_WORLD_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_TOO_FEW_PARAM_EXCEPTION", new HPSException(HPS_TOO_FEW_PARAM_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_TOO_MANY_PARAM_EXCEPTION", new HPSException(HPS_TOO_MANY_PARAM_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_ALREADY_DEFINED_EXCEPTION", new HPSAlreadyDefinedException(pHPSTestNode, L"AlreadyDefinedIdentificator"))
        HFC_REGISTER_EXCEPTION(L"HPS_TRANSFO_PARAMETERS_INVALID_EXCEPTION", new HPSException(HPS_TRANSFO_PARAMETERS_INVALID_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_IMAGE_HAS_NO_SIZE_EXCEPTION", new HPSException(HPS_IMAGE_HAS_NO_SIZE_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_INVALID_COORDS_EXCEPTION", new HPSException(HPS_INVALID_COORDS_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_PAGE_NOT_FOUND_EXCEPTION", new HPSException(HPS_PAGE_NOT_FOUND_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_INVALID_POLYGON_EXCEPTION", new HPSException(HPS_INVALID_POLYGON_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_SHAPE_EXPECTED_EXCEPTION", new HPSException(HPS_SHAPE_EXPECTED_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_WORLD_ALREADY_USED_EXCEPTION", new HPSException(HPS_WORLD_ALREADY_USED_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_COLOR_SET_EXPECTED_EXCEPTION", new HPSTypeMismatchException(HPS_COLOR_SET_EXPECTED_EXCEPTION, pHPSTestNode, HPSTypeMismatchException::OBJECT))
        HFC_REGISTER_EXCEPTION(L"HPS_TRANSLUCENT_INFO_NOT_FOUND_EXCEPTION", new HPSException(HPS_TRANSLUCENT_INFO_NOT_FOUND_EXCEPTION, pHPSTestNode))
        HFC_REGISTER_EXCEPTION(L"HPS_IMAGE_CONTEXT_EXPECTED_EXCEPTION", new HPSException(HPS_IMAGE_CONTEXT_EXPECTED_EXCEPTION, pHPSTestNode))

//HRFII Exceptions To Test
        HFC_REGISTER_EXCEPTION(L"HRFII_CONNECTION_EXCEPTION", new HRFInternetImagingConnectionException(L"ConnectionUrl", HRFInternetImagingConnectionException::CANNOT_CONNECT))
        HFC_REGISTER_EXCEPTION(L"HRFII_SERVER_EXCEPTION", new HRFInternetImagingServerException(L"RequestedUrl", 2, 3, L"ErrorObject", L"ErrorMessage"))
        HFC_REGISTER_EXCEPTION(L"HRFII_CANCELLED_EXCEPTION", new HRFInternetImagingException(HRFII_CANCELLED_EXCEPTION, L"CancelledUrl"))
        HFC_REGISTER_EXCEPTION(L"HRFII_INVALID_DATA_FORMAT_EXCEPTION", new HRFIIHandlerException(HRFII_INVALID_DATA_FORMAT_EXCEPTION, L"InvalidDataFormatUrl", HRFIIHandlerException::HIP_TILE))
        HFC_REGISTER_EXCEPTION(L"HRFII_INVALID_VALUE_EXCEPTION", new HRFIIHandlerException(HRFII_INVALID_VALUE_EXCEPTION, L"InvalidValueUrl", HRFIIHandlerException::HIP_REDIRECT))
        HFC_REGISTER_EXCEPTION(L"HRFII_TILE_NOT_FOUND_EXCEPTION", new HRFInternetImagingException(HRFII_TILE_NOT_FOUND_EXCEPTION, L"TileNotFoundUrl"))               //Class to throw : HRFInternetImagingException
        HFC_REGISTER_EXCEPTION(L"HRFII_NO_RESOLUTION_INDEX_LEFT_EXCEPTION", new HRFInternetImagingException(HRFII_NO_RESOLUTION_INDEX_LEFT_EXCEPTION, L"NoResolutionIndexLeft"))
        HFC_REGISTER_EXCEPTION(L"HRFII_INVALID_RESPONSE_EXCEPTION", new HRFInternetImagingException(HRFII_INVALID_RESPONSE_EXCEPTION, L"InvalidResponseUrl"))
        HFC_REGISTER_EXCEPTION(L"HRFII_INVALID_PROTOCOL_CHARSET_EXCEPTION", new HRFInternetImagingException(HRFII_INVALID_PROTOCOL_CHARSET_EXCEPTION, L"InvalidProtocolCharsetUrl"))
        HFC_REGISTER_EXCEPTION(L"HRFII_INVALID_RESOLUTION_VALUE_EXCEPTION", new HRFIIHandlerException(HRFII_INVALID_RESOLUTION_VALUE_EXCEPTION, L"InvalidResValueUrl", HRFIIHandlerException::RESOLUTION))
        HFC_REGISTER_EXCEPTION(L"HRFII_INVALID_REDIRECTION_URL_EXCEPTION", new HRFInternetImagingException(HRFII_INVALID_REDIRECTION_URL_EXCEPTION, L"InvalidRedirectionUrl"))


//HRP Exceptions To Test
        HFC_REGISTER_EXCEPTION(L"HRP_EXCEPTION", new HRPException())
        HFC_REGISTER_EXCEPTION(L"HRP_PALETTE_FULL_EXCEPTION", new HRPException(HRP_PALETTE_FULL_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HRP_NO_ENTRY_EXCEPTION", new HRPException(HRP_NO_ENTRY_EXCEPTION))

        HFC_REGISTER_EXCEPTION(L"HRP_NO_COMPATIBLE_PIXEL_TYPE_FOUND_IN_FACTORY", new HRPException(HRP_NO_COMPATIBLE_PIXEL_TYPE_FOUND_IN_FACTORY))

//HRF Exceptions To Test
        HFC_REGISTER_EXCEPTION(L"HRF_EXCEPTION", new HRFException(L"FileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_BAD_PAGE_NUMBER_EXCEPTION", new HRFException(HRF_BAD_PAGE_NUMBER_EXCEPTION, L"BadPageNumberFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_BAD_SUB_IMAGE_EXCEPTION", new HRFException(HRF_BAD_SUB_IMAGE_EXCEPTION, L"BadSubImageFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_WRITE_ERROR_EXCEPTION", new HRFException(HRF_WRITE_ERROR_EXCEPTION, L"WriteErrorFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_PIXEL_TYPE_NOT_SUPPORTED_EXCEPTION", new HRFException(HRF_PIXEL_TYPE_NOT_SUPPORTED_EXCEPTION, L"PixelTypeNotSupportedFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_CODEC_NOT_SUPPORTED_EXCEPTION", new HRFException(HRF_CODEC_NOT_SUPPORTED_EXCEPTION, L"CodecNotSupportedFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_MULTI_PAGE_NOT_SUPPORTED_EXCEPTION", new HRFException(HRF_MULTI_PAGE_NOT_SUPPORTED_EXCEPTION, L"MultiPageSupportedFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_ACCESS_MODE_FOR_PIXEL_TYPE_NOT_SUPPORTED_EXCEPTION", new HRFException(HRF_ACCESS_MODE_FOR_PIXEL_TYPE_NOT_SUPPORTED_EXCEPTION, L"AccessForPixelTypeNotSuppFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_ACCESS_MODE_FOR_CODEC_NOT_SUPPORTED_EXCEPTION", new HRFException(HRF_ACCESS_MODE_FOR_CODEC_NOT_SUPPORTED_EXCEPTION, L"AccessForCodecNotSuppFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_INVALID_FILE_TYPE_EXCEPTION", new HRFException(HRF_INVALID_FILE_TYPE_EXCEPTION, L"InvalidFileTypeFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_TRANSFO_MODEL_NOT_SUPPORTED_EXCEPTION", new HRFException(HRF_TRANSFO_MODEL_NOT_SUPPORTED_EXCEPTION, L"TranfoModelNotSuppFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_CODEC_LZW_NOT_SUPPORTED_EXCEPTION", new HRFException(HRF_CODEC_LZW_NOT_SUPPORTED_EXCEPTION, L"CodecLzwNotSuppFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_NO_BLOCK_ADAPTER_FOUND_EXCEPTION", new HRFException(HRF_NO_BLOCK_ADAPTER_FOUND_EXCEPTION, L"NoBlockAdaptFoundFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_XCH_FILE_EXCEPTION", new HRFException(HRF_XCH_FILE_EXCEPTION, L"XchFileExceptionFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_XCH_CHANNELS_ARE_NOT_OF_THE_SAME_FORMAT_EXCEPTION", new HRFException(HRF_XCH_CHANNELS_ARE_NOT_OF_THE_SAME_FORMAT_EXCEPTION, L"XchChannelsNotSameFormatFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_XCH_CHANNELS_DO_NOT_HAVE_THE_SAME_COMPRESSION_EXCEPTION", new HRFException(HRF_XCH_CHANNELS_DO_NOT_HAVE_THE_SAME_COMPRESSION_EXCEPTION, L"XchChannelsNotSameCompressionFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_XCH_CHANNEL_IS_NOT_A_VALID_GRAYSCALE_EXCEPTION", new HRFException(HRF_XCH_CHANNEL_IS_NOT_A_VALID_GRAYSCALE_EXCEPTION, L"XchChannelsNotAvalidGrayscaleFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_XCH_CHANNELS_DO_NOT_HAVE_THE_SAME_DIMENSIONS_EXCEPTION", new HRFException(HRF_XCH_CHANNELS_DO_NOT_HAVE_THE_SAME_DIMENSIONS_EXCEPTION, L"XchChannelsNotSameDimensionFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_XCH_CHANNELS_DO_NOT_HAVE_THE_SAME_RES_COUNT_EXCEPTION", new HRFException(HRF_XCH_CHANNELS_DO_NOT_HAVE_THE_SAME_RES_COUNT_EXCEPTION, L"XchChannelsNotSameResCountFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_NEED_OPEN_PASSWORD_EXCEPTION", new HRFException(HRF_NEED_OPEN_PASSWORD_EXCEPTION, L"NeedOpenPasswordFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_NEED_RESTRICTION_PASSWORD_EXCEPTION", new HRFException(HRF_NEED_RESTRICTION_PASSWORD_EXCEPTION, L"NeedRestrictionPasswordFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_INVALID_OPEN_PASSWORD_EXCEPTION", new HRFException(HRF_INVALID_OPEN_PASSWORD_EXCEPTION, L"InvalidOpenPasswordFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_INVALID_RESTRICTION_PASSWORD_EXCEPTION", new HRFException(HRF_INVALID_RESTRICTION_PASSWORD_EXCEPTION, L"InvalidRestrictionPasswordFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_UNSUPPORTED_ITIFF_VERSION_EXCEPTION", new HRFException(HRF_UNSUPPORTED_ITIFF_VERSION_EXCEPTION, L"UnsupportedITiffVerFileName"))

        HFC_REGISTER_EXCEPTION(L"HRF_GEOTIFF_COMPRESSED_TABLE_LOCK_EXCEPTION", new HRFException(HRF_GEOTIFF_COMPRESSED_TABLE_LOCK_EXCEPTION, L"GeotiffCompressedTableLockFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_PW_NO_HANDLER_EXCEPTION", new HRFException(HRF_PW_NO_HANDLER_EXCEPTION, L"PWnoHandlerFileName"))

        HFC_REGISTER_EXCEPTION(L"HRF_WMS_EXCEPTION", new HRFWMSException(L"WmsExceptionFileName", L"XMLdata"))

        HFC_REGISTER_EXCEPTION(L"HRF_CANNOT_OPEN_CHILD_FILE_EXCEPTION", new HRFChildFileException(HRF_CANNOT_OPEN_CHILD_FILE_EXCEPTION, L"ParentFileName", L"CannotOpenChildFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_CANNOT_FIND_CHILD_FILE_EXCEPTION", new HRFChildFileException(HRF_CANNOT_FIND_CHILD_FILE_EXCEPTION, L"ParentFileName", L"CannotFindChildFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_INVALID_CHILD_FILE_URL_EXCEPTION", new HRFChildFileException(HRF_INVALID_CHILD_FILE_URL_EXCEPTION, L"ParentFileName", L"InvalidChildFileName"))


        HFC_REGISTER_EXCEPTION(L"HRF_CHILD_FILE_INVALID_PARAM_VALUE_EXCEPTION", new HRFChildFileParameterException(HRF_CHILD_FILE_INVALID_PARAM_VALUE_EXCEPTION, L"ParentFileName", L"ChildFileName", L"InvalidParameterName"))
        HFC_REGISTER_EXCEPTION(L"HRF_CHILD_FILE_MISSING_PARAMETER_EXCEPTION", new HRFChildFileParameterException(HRF_CHILD_FILE_MISSING_PARAMETER_EXCEPTION, L"ParentFileName", L"ChildFileName", L"MissingParameterName"))
        HFC_REGISTER_EXCEPTION(L"HRF_SISTER_FILE_INVALID_PARAM_VALUE_EXCEPTION", new HRFFileParameterException(HRF_SISTER_FILE_INVALID_PARAM_VALUE_EXCEPTION, L"SisterFileName", L"InvalidParameterName"))
        HFC_REGISTER_EXCEPTION(L"HRF_SISTER_FILE_MISSING_PARAMETER_EXCEPTION", new HRFFileParameterException(HRF_SISTER_FILE_MISSING_PARAMETER_EXCEPTION, L"SisterFileName", L"MissingParameterName"))
        HFC_REGISTER_EXCEPTION(L"HRF_SISTER_FILE_MISSING_PARAMETER_GROUP_EXCEPTION", new HRFFileParameterException(HRF_SISTER_FILE_MISSING_PARAMETER_GROUP_EXCEPTION, L"SisterFileName", L"MissingParameterGroupName"))
        HFC_REGISTER_EXCEPTION(L"HRF_SISTER_FILE_SLO_NOT_SUPPORTED_EXCEPTION", new HRFException(HRF_SISTER_FILE_SLO_NOT_SUPPORTED_EXCEPTION, L"SLONotSupportedSisterFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_INVALID_SISTER_FILE_EXCEPTION", new HRFException(HRF_INVALID_SISTER_FILE_EXCEPTION, L"InvalidSisterFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_INVALID_TRANSFO_FOR_SISTER_FILE_EXCEPTION", new HRFException(HRF_INVALID_TRANSFO_FOR_SISTER_FILE_EXCEPTION, L"InvalidTransfoForSisterFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_INVALID_PARAM_VALUE_EXCEPTION", new HRFFileParameterException(HRF_INVALID_PARAM_VALUE_EXCEPTION, L"FileName", L"InvalidParameterName"))
        HFC_REGISTER_EXCEPTION(L"HRF_XCH_CHANNELS_BLOCK_DIMENSIONS_DIFFER_EXCEPTION", new HRFException(HRF_XCH_CHANNELS_BLOCK_DIMENSIONS_DIFFER_EXCEPTION, L"XChBlockDimDifferFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_MIME_FORMAT_NOT_SUPPORTED_EXCEPTION", new HRFFileParameterException(HRF_MIME_FORMAT_NOT_SUPPORTED_EXCEPTION, L"FileName", L"MIMEParameterName"))
        HFC_REGISTER_EXCEPTION(L"HRF_MISSING_PARAMETER_EXCEPTION", new HRFFileParameterException(HRF_MISSING_PARAMETER_EXCEPTION, L"FileName", L"MissingParameterName"))
        HFC_REGISTER_EXCEPTION(L"HRF_URL_NOT_SUPPORTED_EXCEPTION", new HRFException(HRF_URL_NOT_SUPPORTED_EXCEPTION, L"UnsupportedURL"))
        HFC_REGISTER_EXCEPTION(L"HRF_UNSUPPORTED_xWMS_VERSION_EXCEPTION", new HRFException(HRF_UNSUPPORTED_xWMS_VERSION_EXCEPTION, L"UnsupportedXWMSfileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_USGS_BAND_NOT_FOUND_IN_HEADER_FILE_EXCEPTION", new HRFFileParameterException(HRF_USGS_BAND_NOT_FOUND_IN_HEADER_FILE_EXCEPTION, L"usgsFileName", L"GREEN"))

        HTIFFError::TagIOErInfo* pErInfo = new HTIFFError::TagIOErInfo;
        pErInfo->m_DataLength = 10;
        pErInfo->m_TagName    = L"StripOffsets";
        pErInfo->m_TagFileNb  = 3;

        HTIFFError TIFFError(HTIFFError::TAG_READ_ERROR,
                             pErInfo,
                             true);

        HFC_REGISTER_EXCEPTION(L"HRF_TIFF_ERROR_EXCEPTION", new HRFTiffErrorException(L"TIFFFileName", TIFFError))
        HFC_REGISTER_EXCEPTION(L"HRF_SLO_NOT_SUPPORTED_EXCEPTION", new HRFException(HRF_SLO_NOT_SUPPORTED_EXCEPTION, L"SLONotSupportedFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_INVALID_RAW_FILE_PARAMS_EXCEPTION", new HRFException(HRF_INVALID_RAW_FILE_PARAMS_EXCEPTION, L"InvalidRawFileParamFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_CANNOT_CREATE_PNG_COMP_INFO_EXCEPTION", new HRFException(HRF_CANNOT_CREATE_PNG_COMP_INFO_EXCEPTION, L"PNGFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_SUB_RES_ACCESS_DIFFER_READ_ONLY_EXCEPTION", new HRFException(HRF_SUB_RES_ACCESS_DIFFER_READ_ONLY_EXCEPTION, L"DifferentResAccessFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_INTERGRAPH_LUT_READ_ONLY_EXCEPTION", new HRFException(HRF_INTERGRAPH_LUT_READ_ONLY_EXCEPTION, L"LutReadOnlyIntergraphFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_PIXEL_TYPE_CODEC_NOT_SUPPORTED_EXCEPTION", new HRFException(HRF_PIXEL_TYPE_CODEC_NOT_SUPPORTED_EXCEPTION, L"PixelTypeCodecFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_HMR_DIRECTORY_NOT_FOUND_EXCEPTION", new HRFException(HRF_HMR_DIRECTORY_NOT_FOUND_EXCEPTION, L"HMRDirNotFoundFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_ANIMATED_GIF_READ_ONLY_EXCEPTION", new HRFException(HRF_ANIMATED_GIF_READ_ONLY_EXCEPTION, L"UnsupportedXWMSfileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_MORE_THAN_24_TIE_POINTS_READ_ONLY_EXCEPTION", new HRFException(HRF_MORE_THAN_24_TIE_POINTS_READ_ONLY_EXCEPTION, L"UnsupportedXWMSfileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_UNSUPPORTED_BMP_VERSION_EXCEPTION", new HRFException(HRF_UNSUPPORTED_BMP_VERSION_EXCEPTION, L"UnsupportedBmpVersionFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_TRANSFO_CANNOT_BE_A_MATRIX_EXCEPTION", new HRFException(HRF_TRANSFO_CANNOT_BE_A_MATRIX_EXCEPTION, L"TransfoCannotBeAmatrixFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_UNSUPPORTED_HGR_VERSION_EXCEPTION", new HRFException(HRF_UNSUPPORTED_HGR_VERSION_EXCEPTION, L"UnsupportedHGRversionFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_CANNOT_DOWNLOAD_TO_INTERNET_CACHE_EXCEPTION", new HRFException(HRF_CANNOT_DOWNLOAD_TO_INTERNET_CACHE_EXCEPTION, L"CannotDownloadToInternetCacheURL"))
        HFC_REGISTER_EXCEPTION(L"HRF_WMS_CANNOT_UNCOMPRESS_DATA", new HRFException(HRF_WMS_CANNOT_UNCOMPRESS_DATA, L"CannotUncompressWMSFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_WMS_CANNOT_CONNECT_TO_SERVER", new HRFException(HRF_WMS_CANNOT_CONNECT_TO_SERVER, L"CannotConnectWMSFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_ERS_DATA_FOUND_OUTSIDE_DATASET_HEADER_EXCEPTION", new HRFFileParameterException(HRF_ERS_DATA_FOUND_OUTSIDE_DATASET_HEADER_EXCEPTION, L"ERSfileName", L"InvalidExtraParameter"))
        HFC_REGISTER_EXCEPTION(L"HRF_ERS_UNMATCH_REG_SPACE_COORD_TYPE_EXCEPTION", new HRFException(HRF_ERS_UNMATCH_REG_SPACE_COORD_TYPE_EXCEPTION, L"UnmatchRegSpaceCsERSfileURL"))
        HFC_REGISTER_EXCEPTION(L"HRF_ERS_UNMATCH_REG_COORD_TYPE_EXCEPTION", new HRFException(HRF_ERS_UNMATCH_REG_COORD_TYPE_EXCEPTION, L"UnmatchRegCsERSfileURL"))
        HFC_REGISTER_EXCEPTION(L"HRF_TOO_SMALL_FOR_ECW_COMPRESSION_EXCEPTION", new HRFException(HRF_TOO_SMALL_FOR_ECW_COMPRESSION_EXCEPTION, L"TooSmallForEcwCompressionURL"))
        HFC_REGISTER_EXCEPTION(L"HRF_INVALID_EXPORT_OPTION_EXCEPTION", new HRFException(HRF_INVALID_EXPORT_OPTION_EXCEPTION, L"InvalidExportOptionURL"))
        HFC_REGISTER_EXCEPTION(L"HRF_ACCESS_MODE_FOR_BLOCK_TYPE_NOT_SUPPORTED_EXCEPTION", new HRFException(HRF_ACCESS_MODE_FOR_BLOCK_TYPE_NOT_SUPPORTED_EXCEPTION, L"AccessModeBlockTypeNotSupportedURL"))
        HFC_REGISTER_EXCEPTION(L"HRF_OPERATION_RESTRICTED_PDF_NOT_SUPPORTED_EXCEPTION", new HRFException(HRF_OPERATION_RESTRICTED_PDF_NOT_SUPPORTED_EXCEPTION, L"OperationRestrictedPDFNotSupportedFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_DIMENSION_TOO_LARGE_FOR_FILE_CREATION_EXCEPTION", new HRFInvalidNewFileDimensionException(HRF_DIMENSION_TOO_LARGE_FOR_FILE_CREATION_EXCEPTION, L"DimensionTooLargeForNewFileName", 49999999998, 49999999999))
        HFC_REGISTER_EXCEPTION(L"HRF_DATA_HAVE_BEEN_SCALED_READ_ONLY_EXCEPTION", new HRFException(HRF_DATA_HAVE_BEEN_SCALED_READ_ONLY_EXCEPTION, L"DataHaveBeenScaledReadOnlyFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_PDF_EXCEPTION", new HRFPDFException(L"PDFFileName", 1)) // See AcroErr.h
        HFC_REGISTER_EXCEPTION(L"HRF_AUTHENTICATION_MAX_RETRY_COUNT_REACHED_EXCEPTION", new HRFException(HRF_AUTHENTICATION_MAX_RETRY_COUNT_REACHED_EXCEPTION, L"AuthenticationMaxRetryCountReachedFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_ORACLE_EXCEPTION", new HRFOracleException(L"OracleFileName", L"OracleOriginalMessage", 1))
        HFC_REGISTER_EXCEPTION(L"HRF_AUTHENTICATION_CANCELLED_EXCEPTION", new HRFException(HRF_AUTHENTICATION_CANCELLED_EXCEPTION, L"AuthenticationCancelledFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_AUTHENTICATION_INVALID_LOGIN_EXCEPTION", new HRFException(HRF_AUTHENTICATION_INVALID_LOGIN_EXCEPTION, L"AuthenticationInvalidLoginFileName"))
        HFC_REGISTER_EXCEPTION(L"HRF_AUTHENTICATION_INVALID_SERVICE_EXCEPTION", new HRFException(HRF_AUTHENTICATION_INVALID_SERVICE_EXCEPTION, L"AuthenticationInvalidServiceFileName"))


//HCS Exceptions To Test
        HFC_REGISTER_EXCEPTION(L"HCS_EXCEPTION", new HCSException(HCS_EXCEPTION, L"ConnectionServerDeviceName"))

        HFC_REGISTER_EXCEPTION(L"HCS_NOT_CONNECTED_EXCEPTION", new HCSException(HCS_NOT_CONNECTED_EXCEPTION, L"NotConnectedDeviceName"))
        HFC_REGISTER_EXCEPTION(L"HCS_CANNOT_ACCEPT_CONNECTION_EXCEPTION", new HCSException(HCS_CANNOT_ACCEPT_CONNECTION_EXCEPTION, L"CannotAcceptConnectionDeviceName"))
        HFC_REGISTER_EXCEPTION(L"HCS_CANNOT_GET_NAME_EXCEPTION", new HCSException(HCS_CANNOT_GET_NAME_EXCEPTION, L"CannotGetNameDeviceName"))
        HFC_REGISTER_EXCEPTION(L"HCS_CANNOT_LISTEN_EXCEPTION", new HCSException(HCS_CANNOT_LISTEN_EXCEPTION, L"CannotListenDeviceName"))
        HFC_REGISTER_EXCEPTION(L"HCS_CANNOT_BIND_EXCEPTION", new HCSException(HCS_CANNOT_BIND_EXCEPTION, L"CannotBindDeviceName"))
        HFC_REGISTER_EXCEPTION(L"HCS_INVALID_DOMAIN_NAME_EXCEPTION", new HCSException(HCS_INVALID_DOMAIN_NAME_EXCEPTION, L"InvalidDomainNameDeviceName"))
        HFC_REGISTER_EXCEPTION(L"HCS_CANNOT_CREATE_EXCEPTION", new HCSException(HCS_CANNOT_CREATE_EXCEPTION, L"CannotCreateDeviceName"))

//HCP Exceptions To Test
        HFC_REGISTER_EXCEPTION(L"HCP_GCOORD_EXCEPTION", new HCPGCoordException(6))

//HVE Exceptions To Test
        HFC_REGISTER_EXCEPTION(L"HVE_EXCEPTION ", new HVEException(HVE_EXCEPTION ))
        HFC_REGISTER_EXCEPTION(L"HVE_INVALID_ARRAY_ENCODED_SHAPE_EXCEPTION", new HVEException(HVE_INVALID_ARRAY_ENCODED_SHAPE_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HVE_NO_POINT_FOUND_SHAPE_DECOMP_EXCEPTION", new HVEException(HVE_NO_POINT_FOUND_SHAPE_DECOMP_EXCEPTION))
        HFC_REGISTER_EXCEPTION(L"HVE_TOLERANCE_TOO_SMALL_POSSIBLE_INFINITE_LOOP", new HVEException(HVE_TOLERANCE_TOO_SMALL_POSSIBLE_INFINITE_LOOP))
        }
    };