set PTVORTEX_STREAM_OVERRIDE=TRUE
set PTVORTEX_STREAM_MIN_BUDGET=500000
set PTVORTEX_STREAM_MAX_BUDGET=10000000
set PTVORTEX_STREAM_MIN_VOXEL_BUDGET=256
set PTVORTEX_STREAM_MAX_READS=2000
set PTVORTEX_STREAM_SCALAR=1.4

"C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE\devenv.exe" %PointoolsVortex%\PointoolsVortexAPI.sln

