/*--------------------------------------------------------------------------------------+
|
|     $Source: PublicAPI/WebServices/ConnectC/CWSCCGenBufferPublic.h $
|
|  $Copyright: (c) 2016 Bentley Systems, Incorporated. All rights reserved. $
|
+--------------------------------------------------------------------------------------*/
#pragma once
//__PUBLISH_SECTION_START__
//--------------------------------------------------------------------------------------+
// <auto-generated>
//     This code was generated by the pyApiGen tool on May 03, 2016.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//--------------------------------------------------------------------------------------+

#include <WebServices/ConnectC/CWSCCGenPublic.h>

using namespace std;
/************************************************************************************//**
* \defgroup BufferPropertyEnums ConnectWebServicesClientC Buffer Property Enumerations
* \{
****************************************************************************************/
/**
* \brief ConnectUser 
*/
typedef enum
    {
    CONNECTUSER_BUFF_USERNAME                       = 1, /**< \b UserName. */
    CONNECTUSER_BUFF_USEREMAIL                      = 2, /**< \b UserEmail. */
    CONNECTUSER_BUFF_CONNECTORGGUID                 = 3, /**< \b ConnectOrgGuid. */
    CONNECTUSER_BUFF_ULTIMATESITEID                 = 4, /**< \b UltimateSiteId. */
    CONNECTUSER_BUFF_ORGNAME                        = 5, /**< \b OrgName. */
    } CONNECTUSER_BUFF_PROPERTY;

/**
* \brief Organization 
*/
typedef enum
    {
    ORGANIZATION_BUFF_ORGANIZATIONGUID               = 1, /**< \b OrganizationGuid. */
    ORGANIZATION_BUFF_ORGANIZATIONNAME               = 2, /**< \b OrganizationName. */
    } ORGANIZATION_BUFF_PROPERTY;

/**
* \brief Project 
*/
typedef enum
    {
    PROJECT_BUFF_NAME                           = 1, /**< \b Name. */
    PROJECT_BUFF_NUMBER                         = 2, /**< \b Number. */
    PROJECT_BUFF_ORGANIZATIONID                 = 3, /**< \b OrganizationId. */
    PROJECT_BUFF_ACTIVE                         = 4, /**< \b Active. */
    PROJECT_BUFF_INDUSTRY                       = 5, /**< \b Industry. */
    PROJECT_BUFF_ASSETTYPE                      = 6, /**< \b AssetType. */
    PROJECT_BUFF_LASTMODIFIED                   = 7, /**< \b LastModified. */
    PROJECT_BUFF_LOCATION                       = 8, /**< \b Location. */
    PROJECT_BUFF_LATITUDE                       = 9, /**< \b Latitude. */
    PROJECT_BUFF_LONGITUDE                      = 10, /**< \b Longitude. */
    PROJECT_BUFF_LOCATIONISUSINGLATLONG         = 11, /**< \b LocationIsUsingLatLong. */
    PROJECT_BUFF_REGISTEREDDATE                 = 12, /**< \b RegisteredDate. */
    PROJECT_BUFF_TIMEZONELOCATION               = 13, /**< \b TimeZoneLocation. */
    PROJECT_BUFF_STATUS                         = 14, /**< \b Status. */
    PROJECT_BUFF_EBBACKED                       = 15, /**< \b eBBacked. */
    PROJECT_BUFF_LINKTOASSETTYPE                = 16, /**< \b LinkToAssetType. */
    PROJECT_BUFF_LINKTOINDUSTRY                 = 17, /**< \b LinkToIndustry. */
    PROJECT_BUFF_LINKTOINDUSTRYASSETS           = 18, /**< \b LinkToIndustryAssets. */
    PROJECT_BUFF_PWDMINVITATIONID               = 19, /**< \b PWDMInvitationId. */
    } PROJECT_BUFF_PROPERTY;

/**
* \brief ProjectFavorite 
*/
typedef enum
    {
    PROJECTFAVORITE_BUFF_EBBACKED                       = 1, /**< \b eBBacked. */
    PROJECTFAVORITE_BUFF_NAME                           = 2, /**< \b Name. */
    PROJECTFAVORITE_BUFF_NUMBER                         = 3, /**< \b Number. */
    PROJECTFAVORITE_BUFF_ORGANIZATIONID                 = 4, /**< \b OrganizationId. */
    PROJECTFAVORITE_BUFF_ACTIVE                         = 5, /**< \b Active. */
    PROJECTFAVORITE_BUFF_INDUSTRY                       = 6, /**< \b Industry. */
    PROJECTFAVORITE_BUFF_ASSETTYPE                      = 7, /**< \b AssetType. */
    PROJECTFAVORITE_BUFF_LASTMODIFIED                   = 8, /**< \b LastModified. */
    PROJECTFAVORITE_BUFF_LOCATION                       = 9, /**< \b Location. */
    PROJECTFAVORITE_BUFF_LATITUDE                       = 10, /**< \b Latitude. */
    PROJECTFAVORITE_BUFF_LONGITUDE                      = 11, /**< \b Longitude. */
    PROJECTFAVORITE_BUFF_LOCATIONISUSINGLATLONG         = 12, /**< \b LocationIsUsingLatLong. */
    PROJECTFAVORITE_BUFF_REGISTEREDDATE                 = 13, /**< \b RegisteredDate. */
    PROJECTFAVORITE_BUFF_TIMEZONELOCATION               = 14, /**< \b TimeZoneLocation. */
    PROJECTFAVORITE_BUFF_STATUS                         = 15, /**< \b Status. */
    PROJECTFAVORITE_BUFF_PWDMINVITATIONID               = 16, /**< \b PWDMInvitationId. */
    } PROJECTFAVORITE_BUFF_PROPERTY;

/**
* \brief ProjectMRU 
*/
typedef enum
    {
    PROJECTMRU_BUFF_PROJECTGUID                    = 1, /**< \b ProjectGuid. */
    PROJECTMRU_BUFF_PROJECTNAME                    = 2, /**< \b ProjectName. */
    PROJECTMRU_BUFF_LASTMODIFIED                   = 3, /**< \b LastModified. */
    } PROJECTMRU_BUFF_PROPERTY;

/**
* \brief ProjectMRUDetail 
*/
typedef enum
    {
    PROJECTMRUDETAIL_BUFF_ISFAVORITE                     = 1, /**< \b IsFavorite. */
    PROJECTMRUDETAIL_BUFF_LASTACCESSEDBYUSER             = 2, /**< \b LastAccessedByUser. */
    PROJECTMRUDETAIL_BUFF_EBBACKED                       = 3, /**< \b eBBacked. */
    PROJECTMRUDETAIL_BUFF_LINKTOASSETTYPE                = 4, /**< \b LinkToAssetType. */
    PROJECTMRUDETAIL_BUFF_LINKTOINDUSTRY                 = 5, /**< \b LinkToIndustry. */
    PROJECTMRUDETAIL_BUFF_LINKTOINDUSTRYASSETS           = 6, /**< \b LinkToIndustryAssets. */
    PROJECTMRUDETAIL_BUFF_NAME                           = 7, /**< \b Name. */
    PROJECTMRUDETAIL_BUFF_NUMBER                         = 8, /**< \b Number. */
    PROJECTMRUDETAIL_BUFF_ORGANIZATIONID                 = 9, /**< \b OrganizationId. */
    PROJECTMRUDETAIL_BUFF_ACTIVE                         = 10, /**< \b Active. */
    PROJECTMRUDETAIL_BUFF_INDUSTRY                       = 11, /**< \b Industry. */
    PROJECTMRUDETAIL_BUFF_ASSETTYPE                      = 12, /**< \b AssetType. */
    PROJECTMRUDETAIL_BUFF_LASTMODIFIED                   = 13, /**< \b LastModified. */
    PROJECTMRUDETAIL_BUFF_LOCATION                       = 14, /**< \b Location. */
    PROJECTMRUDETAIL_BUFF_LATITUDE                       = 15, /**< \b Latitude. */
    PROJECTMRUDETAIL_BUFF_LONGITUDE                      = 16, /**< \b Longitude. */
    PROJECTMRUDETAIL_BUFF_LOCATIONISUSINGLATLONG         = 17, /**< \b LocationIsUsingLatLong. */
    PROJECTMRUDETAIL_BUFF_REGISTEREDDATE                 = 18, /**< \b RegisteredDate. */
    PROJECTMRUDETAIL_BUFF_TIMEZONELOCATION               = 19, /**< \b TimeZoneLocation. */
    PROJECTMRUDETAIL_BUFF_STATUS                         = 20, /**< \b Status. */
    PROJECTMRUDETAIL_BUFF_PWDMINVITATIONID               = 21, /**< \b PWDMInvitationId. */
    } PROJECTMRUDETAIL_BUFF_PROPERTY;

/**
* \brief ProjectTemplate 
*/
typedef enum
    {
    PROJECTTEMPLATE_BUFF_NAME                           = 1, /**< \b Name. */
    PROJECTTEMPLATE_BUFF_NUMBER                         = 2, /**< \b Number. */
    PROJECTTEMPLATE_BUFF_ORGANIZATIONID                 = 3, /**< \b OrganizationId. */
    PROJECTTEMPLATE_BUFF_ACTIVE                         = 4, /**< \b Active. */
    PROJECTTEMPLATE_BUFF_INDUSTRY                       = 5, /**< \b Industry. */
    PROJECTTEMPLATE_BUFF_ASSETTYPE                      = 6, /**< \b AssetType. */
    PROJECTTEMPLATE_BUFF_LASTMODIFIED                   = 7, /**< \b LastModified. */
    PROJECTTEMPLATE_BUFF_LOCATION                       = 8, /**< \b Location. */
    PROJECTTEMPLATE_BUFF_LATITUDE                       = 9, /**< \b Latitude. */
    PROJECTTEMPLATE_BUFF_LONGITUDE                      = 10, /**< \b Longitude. */
    PROJECTTEMPLATE_BUFF_LOCATIONISUSINGLATLONG         = 11, /**< \b LocationIsUsingLatLong. */
    PROJECTTEMPLATE_BUFF_REGISTEREDDATE                 = 12, /**< \b RegisteredDate. */
    PROJECTTEMPLATE_BUFF_TIMEZONELOCATION               = 13, /**< \b TimeZoneLocation. */
    PROJECTTEMPLATE_BUFF_STATUS                         = 14, /**< \b Status. */
    PROJECTTEMPLATE_BUFF_EBBACKED                       = 15, /**< \b eBBacked. */
    PROJECTTEMPLATE_BUFF_LINKTOASSETTYPE                = 16, /**< \b LinkToAssetType. */
    PROJECTTEMPLATE_BUFF_LINKTOINDUSTRY                 = 17, /**< \b LinkToIndustry. */
    PROJECTTEMPLATE_BUFF_LINKTOINDUSTRYASSETS           = 18, /**< \b LinkToIndustryAssets. */
    } PROJECTTEMPLATE_BUFF_PROPERTY;

/** \} */

/************************************************************************************//**
* \defgroup BufferFunctions ConnectWebServicesClientC Data Buffer Functions
* \{
****************************************************************************************/
/************************************************************************************//**
* \brief Free an allocated data buffer
* \param[in] apiHandle Handle to api
* \param[in] dataBuffer Data buffer
****************************************************************************************/
CWSCC_EXPORT CallStatus ConnectWebServicesClientC_DataBufferFree
(
CWSCCHANDLE apiHandle,
CWSCCDATABUFHANDLE dataBuffer
);
/************************************************************************************//**
* \brief Get a count of the number of items in a data buffer
* \param[in] dataBuffer Data buffer
* \return Object count
****************************************************************************************/
CWSCC_EXPORT uint64_t ConnectWebServicesClientC_DataBufferGetCount
(
CWSCCDATABUFHANDLE dataBuffer
);
/************************************************************************************//**
* \brief Get a String property from a data buffer
* \param[in] apiHandle handle to api
* \param[in] dataBuffer Data buffer
* \param[in] bufferProperty buffer property
* \param[in] index buffer index
* \param[in] strLength buffer length
* \param[out] str Pointer to buffer to store string property
* \return Success or error code. See \ref ConnectWebServicesClientCStatusCodes
****************************************************************************************/
CWSCC_EXPORT CallStatus ConnectWebServicesClientC_DataBufferGetStringProperty
(
CWSCCHANDLE apiHandle,
CWSCCDATABUFHANDLE dataBuffer,
int16_t bufferProperty,
uint32_t index,
uint32_t strLength,
WCharP str
);

/************************************************************************************//**
* \brief Get a Stringlength property from a data buffer
* \param[in] apiHandle handle to api
* \param[in] dataBuffer Data buffer
* \param[in] bufferProperty buffer property
* \param[in] index buffer index
* \param[out] outStringSize Pointer to store the string length
* \return Success or error code. See \ref ConnectWebServicesClientCStatusCodes
****************************************************************************************/
CWSCC_EXPORT CallStatus ConnectWebServicesClientC_DataBufferGetStringLength
(
CWSCCHANDLE apiHandle,
CWSCCDATABUFHANDLE dataBuffer,
int16_t bufferProperty,
uint32_t index,
size_t* outStringSize
);

/************************************************************************************//**
* \brief Get a Guid property from a data buffer
* \param[in] apiHandle handle to api
* \param[in] dataBuffer Data buffer
* \param[in] bufferProperty buffer property
* \param[in] index buffer index
* \param[in] strLength guid-buffer length
* \param[out] guid Pointer to buffer to store GUID property
* \return Success or error code. See \ref ConnectWebServicesClientCStatusCodes
****************************************************************************************/
CWSCC_EXPORT CallStatus ConnectWebServicesClientC_DataBufferGetGuidProperty
(
CWSCCHANDLE apiHandle,
CWSCCDATABUFHANDLE dataBuffer,
int16_t bufferProperty,
uint32_t index,
uint32_t strLength,
WCharP guid
);

/************************************************************************************//**
* \brief Get a Boolean property from a data buffer
* \param[in] apiHandle handle to api
* \param[in] dataBuffer Data buffer
* \param[in] bufferProperty buffer property
* \param[in] index buffer index
* \param[out] boolean Pointer to bool to store property
* \return Success or error code. See \ref ConnectWebServicesClientCStatusCodes
****************************************************************************************/
CWSCC_EXPORT CallStatus ConnectWebServicesClientC_DataBufferGetBooleanProperty
(
CWSCCHANDLE apiHandle,
CWSCCDATABUFHANDLE dataBuffer,
int16_t bufferProperty,
uint32_t index,
bool* boolean
);

/************************************************************************************//**
* \brief Get a Int property from a data buffer
* \param[in] apiHandle handle to api
* \param[in] dataBuffer Data buffer
* \param[in] bufferProperty buffer property
* \param[in] index buffer index
* \param[out] integer Pointer to int to store property
* \return Success or error code. See \ref ConnectWebServicesClientCStatusCodes
****************************************************************************************/
CWSCC_EXPORT CallStatus ConnectWebServicesClientC_DataBufferGetIntProperty
(
CWSCCHANDLE apiHandle,
CWSCCDATABUFHANDLE dataBuffer,
int16_t bufferProperty,
uint32_t index,
int32_t* integer
);

/************************************************************************************//**
* \brief Get a Double property from a data buffer
* \param[in] apiHandle handle to api
* \param[in] dataBuffer Data buffer
* \param[in] bufferProperty buffer property
* \param[in] index buffer index
* \param[out] pDouble Pointer to double to store property
* \return Success or error code. See \ref ConnectWebServicesClientCStatusCodes
****************************************************************************************/
CWSCC_EXPORT CallStatus ConnectWebServicesClientC_DataBufferGetDoubleProperty
(
CWSCCHANDLE apiHandle,
CWSCCDATABUFHANDLE dataBuffer,
int16_t bufferProperty,
uint32_t index,
double* pDouble
);

/************************************************************************************//**
* \brief Get a Long property from a data buffer
* \param[in] apiHandle handle to api
* \param[in] dataBuffer Data buffer
* \param[in] bufferProperty buffer property
* \param[in] index buffer index
* \param[out] pLong Pointer to long to store property
* \return Success or error code. See \ref ConnectWebServicesClientCStatusCodes
****************************************************************************************/
CWSCC_EXPORT CallStatus ConnectWebServicesClientC_DataBufferGetLongProperty
(
CWSCCHANDLE apiHandle,
CWSCCDATABUFHANDLE dataBuffer,
int16_t bufferProperty,
uint32_t index,
int64_t* pLong
);

/** \} */
