/*--------------------------------------------------------------------------------------+
|
|     $Source: Formats/InroadsTM/utiuirsc.h $
|
|  $Copyright: (c) 2014 Bentley Systems, Incorporated. All rights reserved. $
|
+--------------------------------------------------------------------------------------*/
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by civutiui.rc
//

#define DTM_M_BADBND                    1007
#define DTM_M_BADLIN                    1008
#define DTM_M_CRSSTN                    1033
#define DTM_S_RNDPNTNAM                 1037
#define DTM_S_RNDPNTDES                 1041
#define DTM_M_DISCRS                    1043
#define DTM_M_DTMVER                    1066
#define DTM_M_DUPSNM                    1067
#define DTM_M_FILNTF                    1070
#define DTM_M_INTERSECT                 1093
#define DTM_M_INVDAT                    1094
#define DTM_M_INVDFF                    1096
#define DTM_M_MEMALF                    1107
#define DTM_M_MISELV                    1108
#define DTM_M_MRKBND                    1109
#define DTM_M_MRKDUP                    1110
#define DTM_M_MRKRNG                    1111
#define DTM_M_NOCRSSL                   1116
#define DTM_M_NODATF                    1117
#define DTM_M_NOFTRF                    1119
#define DTM_M_NONAME                    1121
#define DTM_M_NOPNTF                    1122
#define DTM_M_NOPRJS                    1125
#define DTM_M_NOSETF                    1126
#define DTM_M_NOSIDE                    1127
#define DTM_M_NOSRFF                    1129
#define DTM_M_NOSRFS                    1130
#define DTM_M_NOSWAP                    1131
#define DTM_M_NOTHIN                    1133
#define DTM_M_NOTINF                    1134
#define DTM_M_OPFILF                    1138
#define DTM_M_OVERLP                    1141
#define DTM_M_PNTNIN                    1147
#define DTM_M_PRCINT                    1149
#define DTM_M_PROCES                    1150
#define DTM_M_RDFILF                    1151
#define DTM_M_TINLOCKED                 1154
#define DTM_M_SEGCONFLICT               1165
#define DTM_M_SEGMENT1                  1166
#define DTM_M_SEGMENT2                  1168
#define DTM_M_STPPRC                    1182
#define DTM_M_SVPNTS                    1183
#define DTM_M_SVTINS                    1184
#define DTM_M_TOLPRB                    1185
#define DTM_M_TRILIN                    1186
#define DTM_M_TRIREG                    1188
#define DTM_M_UNCROS                    1190
#define DTM_M_WRFILF                    1196
#define DTM_M_XNGEXT                    1197
#define DTM_M_XSECBN                    1198
#define DTM_M_SVFTRS                    1200
#define DTM_M_BADFTRTYP                 1209
#define DTM_M_NOSTYF                    1210
#define DTM_M_DUP_SRF                   1211
#define DTM_M_PNTFTRNAME                1214
#define DTM_M_BRKFTRNAME                1215
#define DTM_M_EXTFTRNAME                1216
#define DTM_M_INTFTRNAME                1217
#define DTM_M_CTRFTRNAME                1218
#define DTM_M_RNDFTRSTY                 1223
#define DTM_M_FILREADONLY               1234
#define DTM_M_NOFTRNAME                 1236
#define DTM_M_TINCOR                    1243
#define DTM_M_XNGFTR                    1245
#define DTM_M_XNGFTRI                   1246

#define ALG_S_FAILURE                   335
#define ALG_W_1ST_IS_FREE               347
#define ALG_W_ADJACENT_FREES            349
#define ALG_W_ADJACENT_STRAIGHTS        350
#define ALG_W_ALG_ACT                   351
#define ALG_W_ALG_NOT_FOUND             355
#define ALG_W_ALIGNMENT_NOT_LOCKED      356
#define ALG_W_BLANK                     358
#define ALG_W_COGO_NOT_LOCKED           359
#define ALG_W_COLINEAR                  361
#define ALG_W_CONFUSED                  366
#define ALG_W_CONVERGE_FAILURE          367
#define ALG_W_DUP_ALG                   369
#define ALG_W_DUP_PRJ                   370
#define ALG_W_DUPLICATE_PT_ID           371
#define ALG_W_ELE_ACT                   372
#define ALG_W_ELE_CPY                   373
#define ALG_W_ELE_DEL                   374
#define ALG_W_EMPTY_ALIGNMENT           375
#define ALG_W_FAIL_NEXT_NAME            381
#define ALG_W_FILE_OPEN_ERROR           386
#define ALG_W_FLOAT_NOT_FIXABLE         389
#define ALG_W_ILLEGAL_PLACEMENT         392
#define ALG_W_ILLEGAL_RADIUS            394
#define ALG_W_INV_ELE                   398
#define ALG_W_INVALID_ALIGN             399
#define ALG_W_INVALID_DATA              401
#define ALG_W_INVALID_DISTANCE          404
#define ALG_W_INVALID_ELE_TYPE          405
#define ALG_W_INVALID_FILE_TYPE         407
#define ALG_W_INVALID_INPUT             408
#define ALG_W_INVALID_RADIUS            411
#define ALG_W_INVALID_SCALE             412
#define ALG_W_INVALID_STATION           414
#define ALG_W_LAST_IS_FREE              417
#define ALG_W_MULTI_INTERSECT_HALG      420
#define ALG_W_NO_ACTIVE_COGO            421
#define ALG_W_NO_ACTIVE_EQUATION        422
#define ALG_W_NO_ACTIVE_EVENT           423
#define ALG_W_NO_ACTIVE_HORIZONTAL      424
#define ALG_W_NO_ACTIVE_PROJECT         425
#define ALG_W_NO_ACTIVE_SUPER           426
#define ALG_W_NO_ACTIVE_TURNOUT         427
#define ALG_W_NO_ACTIVE_VERTICAL        428
#define ALG_W_NO_ALIGNMENT              430
#define ALG_W_NO_ELEMENT                434
#define ALG_W_NO_INTERSECT              437
#define ALG_W_NO_LEADING                438
#define ALG_W_NO_MEMORY                 439
#define ALG_W_NO_NAME                   440
#define ALG_W_NO_PATH_N_FILE            445
#define ALG_W_NO_POINT                  446
#define ALG_W_NO_PROJECT                448
#define ALG_W_NO_SOLUTION               449
#define ALG_W_NO_TRAILING               450
#define ALG_W_NO_TURNING_POINT          451
#define ALG_W_NO_TURNOUT                452
#define ALG_W_NOT_A_TURNOUT             455
#define ALG_W_NOT_COINCIDENT            456
#define ALG_W_NOT_COLINEAR              457
#define ALG_W_NOT_FIXABLE               459
#define ALG_W_NOT_WI_LIMITS             461
#define ALG_W_NOTHING_TO_REPORT         463
#define ALG_W_OVERLAP                   467
#define ALG_W_POS_NONZERO               469
#define ALG_W_POSSIBLE_DISCONTINUTY     470
#define ALG_W_PRJ_ACT                   472
#define ALG_W_PRJ_NOT_FOUND             475
#define ALG_W_QUESTIONABLE_STATUS       476
#define ALG_W_READ_FILE_ERROR           478
#define ALG_W_UNEQUAL_TANGENT           484
#define ALG_W_UNKNOWN_STATUS            486
#define ALG_W_UNSOLVABLE_FIXED          487
#define ALG_W_UNSTABLE_RADIUS           488
#define ALG_W_UNSTABLE_SPIRAL           489
#define ALG_W_UNSUPPORTED               490
#define ALG_W_ZERO_DEFLECTION           500
#define ALG_W_ZERO_LENGTH               504
#define ALG_W_ZERO_OFFSET               506
#define ALG_W_ZERO_RADIUS               507
#define ALG_W_ZERO_TANGENT              508
#define ALG_W_PARTIAL_READ              613
#define ALG_W_UNSUPPORTED_COMPOUND_CUBIC 662
#define ALG_S_PW_UPDATED                669
#define ALG_S_PW_COMMA_SPACE            670
#define ALG_S_PW_SPACE_AND_SPACE        671
#define ALG_S_PW_PERIOD                 672
#define ALG_S_PW_FREED                  673
#define ALG_S_PW_CHECKED_IN             675
#define ALG_S_PW_CHECKED_OUT            676
#define ALG_W_UNABLE_TO_LOCK_FILE       677

#define ALG_W_PROJECTWISE_PULL_FAILURE  686
#define ALG_W_PROJECTWISE_PUSH_FAILURE  687
#define ALG_W_UNABLE_TO_CREATE_LOCKFILE 688
#define REG_W_TOO_MANY_FREE_PARAMETERS  13901
#define REG_W_TOO_FEW_FREE_PARAMETERS   13902
#define REG_W_CHAIN_INTEGRITY_VIOLATIONS 13903
#define REG_W_COLLAPSED_ELEMENT         13904
#define REG_W_CHAIN_EE_DISCONNECTION    13906
#define REG_W_CHAIN_BE_FREE             13907
#define REG_W_TOO_FEW_REGRESSION_POINTS 13908
#define REG_W_TOO_MANY_CONNECTING_ELEMENTS 13909
#define REG_W_CHAIN_UNSUPPORTED         13910
#define REG_W_UNSUPPORTED_SPIRAL_POSITION 13911
#define REG_W_EXCEEDS_ELEMENT_BOUNDS   13912
#define REG_W_INSUFFICIENT_DATA         13913
#define REG_W_PROJECTION_BEHIND_EE_PEND 13914
#define REG_W_CONVERGE_FAILURE          13917
#define REG_W_UNSUPPORTED               13918
#define REG_W_NO_ALIGNMENT              13919
#define REG_W_NO_POINTS                 13920
#define REG_W_NO_MEMORY                 13921
#define REG_W_NO_SOLUTION               13922
#define REG_W_NO_ELEMENT                13923
#define REG_W_PROGRAM_LOGIC_ISSUE       13925
#define ALG_S_PW_UPDATED_ON_CLOSE   691

#define AEC_E_BAD_ELEMENT               101
#define AEC_E_CELL_DISP                 102
#define AEC_E_ERROR                     103
#define AEC_E_FENCE_VIEW_NOT_TOP        104
#define AEC_E_FILE_OPEN_ERROR           105
#define AEC_E_FILE_WRITE_ERROR          106
#define AEC_E_INVCDP                    108
#define AEC_E_INVDAT                    109
#define AEC_E_MEMALF                    112
#define AEC_E_NOCELL                    114
#define AEC_E_NOFILE_NAME               116
#define AEC_E_OVERWRITE                 117
#define AEC_E_PRCINT                    118
#define AEC_E_SNGMAT                    119
#define AEC_E_THDNTE                    121
#define AEC_E_INVALIDSHEETSIZE          124
#define AEC_M_BLANK                     129
#define AEC_M_BYLEVEL                   137
#define AEC_M_CIVILPRJGSFCOD            138
#define AEC_M_FINLOD                    145
#define AEC_M_FINSAV                    146
#define AEC_M_USELITERAL                174
#define AEC_S_PROCES                    176
#define AEC_E_IDXOUTOFRNG               178
#define AEC_E_PWKEYNOTFND               205
#define AEC_E_LOADLIBFAILED             207
#define AEC_M_FILEEXISTSNOREPLACE       209
#define AEC_M_CANTCHECKOUT              210

#define AEC_ROT_AccessControlDetails_Type 101
#define AEC_LBX_ApplicationsAddins_Available 102
#define AEC_ROT_ApplicationsAddins_Description1 103
#define AEC_BTN_Color1                  104
#define AEC_BTN_Color2                  105
#define AEC_BTN_Color3                  106
#define AEC_BTN_Color4                  107
#define AEC_BTN_Color5                  108
#define AEC_BTN_Color6                  109
#define AEC_BTN_Color7                  110
#define AEC_BTN_Color8                  111
#define AEC_BTN_Color9                  112
#define AEC_BTN_Color250                113
#define AEC_BTN_Color251                114
#define AEC_BTN_Color252                115
#define AEC_BTN_Color253                116
#define AEC_BTN_Color254                117
#define AEC_BTN_Color255                118
#define AEC_BTN_ColorPalette_ByLayer    119
#define AEC_TXT_ColorPalette_Color      120
#define AEC_BTN_Common_Apply            121
#define AEC_BTN_Common_Browse           122
#define AEC_BTN_Common_Cancel           123
#define AEC_BTN_Common_Close            124
#define AEC_BTN_Common_Edit             125
#define AEC_BTN_Common_Help             126
#define AEC_BTN_Common_No               127
#define AEC_BTN_Common_NoToAll          128
#define AEC_BTN_Common_OK               129
#define AEC_BTN_Common_Preferences      130
#define AEC_BTN_Common_Save             131
#define AEC_BTN_Common_SaveAs           132
#define AEC_BTN_Common_Yes              133
#define AEC_BTN_Common_YesToAll         134
#define AEC_TXT_CreateMessage_Message   135
#define AEC_CBX_Defaults_AcresHectaresP 136
#define AEC_CBX_Defaults_AngularFGEN    137
#define AEC_CBX_Defaults_AngularMode    138
#define AEC_CBX_Defaults_AngularP       139
#define AEC_TXT_Defaults_AngularT       140
#define AEC_CBX_Defaults_AngularUGEN    141
#define AEC_CBX_Defaults_AreaUnitsP     142
#define AEC_CHK_Defaults_AutomaticDialogCollapse 143
#define AEC_CHK_Defaults_AutomaticLayerListUpdate 144
#define AEC_CHK_Defaults_ReloadCommandsOnPreferenceChange 145
#define AEC_CBX_Defaults_Aspect         146
#define AEC_CBX_Defaults_AspectP        147
#define AEC_TXT_Defaults_ChordHeightT   148
#define AEC_CBX_Defaults_CoordSeq       149
#define AEC_CBX_Defaults_CubicUnitsP    150
#define AEC_CBX_Defaults_DefaultBlock   151
#define AEC_LBL_Defaults_DefaultBlock   152
#define AEC_LBL_Defaults_EastingNorthingP 153
#define AEC_CBX_Defaults_Editor         154
#define AEC_LBL_Defaults_Editor         155
#define AEC_LBL_Defaults_EditorName     156
#define AEC_TXT_Defaults_EditorName     157
#define AEC_CBX_Defaults_ElevationP     158
#define AEC_CHK_Defaults_FirstPage      159
#define AEC_CBX_Defaults_HorizontalArcDefinition 160
#define AEC_CBX_Defaults_ICSSequenceCoordinate 161
#define AEC_CBX_Defaults_Linear         162
#define AEC_CBX_Defaults_LinearP        163
#define AEC_LBL_Defaults_LineWidthFAC   164
#define AEC_TXT_Defaults_LineWidthFAC   165
#define AEC_CHK_Defaults_LocatePoint    166
#define AEC_CBX_Defaults_NorthingEastingP 167
#define AEC_LBL_Defaults_NorthingEastingP 168
#define AEC_TXT_Defaults_PlottingHeight 169
#define AEC_CBX_Defaults_PointNamesDuringEdits 170
#define AEC_TXT_Defaults_PositionalT    171
#define AEC_CBX_Defaults_ScaleP         172
#define AEC_TXT_Defaults_SeedAlignmentName 173
#define AEC_TXT_Defaults_SeedPointName  174
#define AEC_CBX_Defaults_Slope          175
#define AEC_CBX_Defaults_SlopeP         176
#define AEC_CBX_Defaults_SpiralDefinition 177
#define AEC_CBX_Defaults_Station        178
#define AEC_CBX_Defaults_StationP       179
#define AEC_CBX_Defaults_TabStyle       180
#define AEC_TXT_Defaults_TextScaleFAC   181
#define AEC_TXT_Defaults_UnitDegreeOfCurve 182
#define AEC_CBX_Defaults_VerticalAngleReference 183
#define AEC_CBX_Defaults_VerticalArcDefinition 184
#define AEC_TXT_EditBlockSymbology_Angle 185
#define AEC_RBN_EditBlockSymbology_AngleRelative 186
#define AEC_RBN_EditBlockSymbology_AngleAbsolute 187
#define AEC_CBX_EditBlockSymbology_BlockName 188
#define AEC_LBX_EditBlockSymbology_Layer 189
#define AEC_BTN_EditLineSymbology_Color 190
#define AEC_CBX_EditBlockSymbology_StyleName 191
#define AEC_ROT_EditLineSymbology_Color 192
#define AEC_TXT_EditLineSymbology_Color 193
#define AEC_CBX_EditLineSymbology_Layer 194
#define AEC_LVW_EditLineSymbology_LineType 195
#define AEC_CBX_EditLineSymbology_Weight 196
#define AEC_LBL_EditLineSymbology_Weight 197
#define AEC_BTN_EditSymbolSymbology_Color 198
#define AEC_CBX_EditLineSymbology_Style 199
#define AEC_ROT_EditSymbolSymbology_Color 200
#define AEC_TXT_EditSymbolSymbology_Color 201
#define AEC_CBX_EditSymbolSymbology_LayerName 202
#define AEC_TXT_EditSymbolSymbology_Height 203
#define AEC_CBX_EditSymbolSymbology_Weight 204
#define AEC_LBL_EditSymbolSymbology_Weight 205
#define AEC_RBN_EditTextSymbology_AbsoluteAngle 206
#define AEC_RBN_EditTextSymbology_AfterRotation 207
#define AEC_CBX_EditSymbolSymbology_StyleName 208
#define AEC_LBL_EditTextSymbology_Angle 209
#define AEC_TXT_EditTextSymbology_Angle 210
#define AEC_RBN_EditTextSymbology_AngleRelativeToObject 211
#define AEC_RBN_EditTextSymbology_BeforeRotation 212
#define AEC_BTN_EditTextSymbology_Color 213
#define AEC_ROT_EditTextSymbology_Color 214
#define AEC_TXT_EditTextSymbology_Color 215
#define AEC_LBL_EditTextSymbology_HorizontalOffset 216
#define AEC_EDT_EditTextSymbology_HZOffset 217
#define AEC_CBX_EditTextSymbology_Justification 218
#define AEC_LBL_EditTextSymbology_Justification 219
#define AEC_CBX_EditTextSymbology_Layer 220
#define AEC_LBL_EditTextSymbology_Layer 221
#define AEC_LBL_EditTextSymbology_LineSpacing 222
#define AEC_TXT_EditTextSymbology_LineSpacing 223
#define AEC_GRP_EditTextSymbology_Offsets 224
#define AEC_GRP_EditTextSymbology_Rotation 225
#define AEC_TXT_EditTextSymbology_TextHeight 226
#define AEC_LVW_EditTextSymbology_TextStyle 227
#define AEC_LBL_EditTextSymbology_VerticalOffset 228
#define AEC_EDT_EditTextSymbology_VTOffset 229
#define AEC_CBX_EditTextSymbology_Style 230
#define AEC_BTN_OddColors               232
#define AEC_TXT_Options_PerMilleCS      233
#define AEC_RBN_Options_ROHorizAlignACC 234
#define AEC_RBN_Options_RWHorizAlignACC 235
#define AEC_RBN_Options_ROCogoBufferACC 236
#define AEC_RBN_Options_RWCogoBufferACC 237
#define AEC_BTN_Preferences_Delete      238
#define AEC_BTN_Preferences_Load        239
#define AEC_LBX_Preferences_Name        240
#define AEC_ROT_Preferences_Message     241
#define AEC_BTN_Preferences_Save        242
#define AEC_BTN_Preferences_SaveAs      243
#define AEC_LBX_ProjectOptions_Add      244
#define AEC_TXT_ProjectOptions_FileName 245
#define AEC_BTN_Results_Append          246
#define AEC_BTN_Results_Display         247
#define AEC_BTN_Results_Print           248
#define AEC_LBX_Results_Results         249
#define AEC_BTN_Results_SaveAs          250
#define AEC_CBX_SaveAs_Active           251
#define AEC_LBL_SaveAs_Active           252
#define AEC_BTN_SaveAs_Options          253
#define AEC_TXT_SaveFilesAtExit_Message 254
#define AEC_TXT_SavePreferenceAs_Name   255
#define AEC_ROT_Startup_Company         256
#define AEC_ROT_Startup_Copyright       257
#define AEC_ROT_Startup_Organization    258
#define AEC_ROT_Startup_UserName        259
#define AEC_ROT_Startup_Version         260
#define IDC_ALPHAVIEW_INPUT             261
#define IDC_ALPHAVIEW_OUTPUT            262
#define IDC_ALPHAVIEW_STATUS            263
#define AEC_BTN_EvenColors              264
#define AEC_BTN_EditNamedSymbology_Delete 265
#define AEC_BTN_EditNamedSymbology_Apply 266
#define AEC_BTN_EditNamedSymbology_Edit 267
#define AEC_BTN_EditNamedSymbology_Previous 268
#define AEC_BTN_EditNamedSymbology_Next 269
#define AEC_RBN_Defaults_UnitStationAlongArc 270
#define AEC_RBN_Defaults_UnitStationAlongChord 271
#define AEC_CHK_Defaults_HorizontalArcDefinitionConfirm 272
#define AEC_CHK_Defaults_VerticalArcDefinitionConfirm 273
#define AEC_BTN_EditNamedSymbology_ClearSelection 274
#define AEC_CBX_PreferenceManager_ActivePreference 275
#define AEC_LBX_PreferenceManager_Object 276
#define AEC_BTN_PreferenceManager_Edit  277
#define AEC_CBX_Defaults_PreferredPreferenceName 278
#define AEC_CBX_PencilToInk_ConvertBy   279
#define AEC_LBL_PencilToInk_Level       280
#define AEC_CBX_PencilToInk_Level       281
#define AEC_ROT_SymbologyMgr_PreferenceFile 282
#define AEC_BTN_SymbologyMgr_New        283
#define AEC_BTN_SymbologyMgr_Edit       284
#define AEC_BTN_SymbologyMgr_Copy       285
#define AEC_BTN_SymbologyMgr_Delete     286
#define AEC_CBX_CopySymbology_NameFRM   287
#define AEC_TXT_CopySymbology_NameTO    288
#define AEC_TXT_EditNamedSymbology_Name 290
#define AEC_CBX_EditPointSymbology_DisplayAs 292
#define AEC_CBX_EditPointSymbology_LayerNameCELL 293
#define AEC_CBX_EditPointSymbology_BlockName 294
#define AEC_TXT_EditPointSymbology_Color 295
#define AEC_BTN_EditPointSymbology_Color 296
#define AEC_ROT_EditPointSymbology_Color 297
#define AEC_LBL_EditPointSymbology_Character 298
#define AEC_TXT_EditPointSymbology_Character 299
#define AEC_LBL_EditPointSymbology_Height 300
#define AEC_TXT_EditPointSymbology_Height 301
#define AEC_CBX_EditPointSymbology_StyleName 305
#define AEC_LVW_EditPointSymbology_TextStyle 306
#define AEC_BTN_PreferenceManager_Uninitialize 307
#define AEC_RBN_EditPointSymbology_RelativeAngleCELL 309
#define AEC_RBN_EditPointSymbology_AbsoluteAngleCELL 310
#define AEC_TXT_EditPointSymbology_AngleCELL 311
#define AEC_BTN_Common_FeatureFilter    317
#define AEC_BTN_Common_FeatureStyles    318
#define AEC_BTN_Common_Filter           319
#define AEC_BTN_Common_Results          320
#define AEC_BTN_Common_Styles           321
#define AEC_BTN_Common_EditFeatureStyle 322
#define AEC_BTN_Common_NewFeatureStyle  323
#define AEC_CHK_Defaults_OmitAutomaticGraphicsRefresh 324
#define AEC_TXT_Defaults_UnitStationLength 325
#define AEC_CBX_SetConfigurationDefaults_ConfigurationName 326
#define AEC_LBL_SetConfigurationDefaults_ProjectDefaultDirectory 327
#define AEC_TXT_SetConfigurationDefaults_ProjectDefaultDirectory 328
#define AEC_LBL_SetConfigurationDefaults_Project 329
#define AEC_TXT_SetConfigurationDefaults_Project 330
#define AEC_LBL_SetConfigurationDefaults_Surface 331
#define AEC_TXT_SetConfigurationDefaults_Surface 332
#define AEC_LBL_SetConfigurationDefaults_Geometry 333
#define AEC_TXT_SetConfigurationDefaults_Geometry 334
#define AEC_LBL_SetConfigurationDefaults_TemplateLibrary 335
#define AEC_TXT_SetConfigurationDefaults_TemplateLibrary 336
#define AEC_LBL_SetConfigurationDefaults_RoadwayLibrary 337
#define AEC_TXT_SetConfigurationDefaults_RoadwayLibrary 338
#define AEC_LBL_SetConfigurationDefaults_SurveyData 339
#define AEC_TXT_SetConfigurationDefaults_SurveyData 340
#define AEC_LBL_SetConfigurationDefaults_Drainage 341
#define AEC_TXT_SetConfigurationDefaults_Drainage 342
#define AEC_BTN_SetConfigurationDefaults_Import 343
#define AEC_BTN_SetConfigurationDefaults_Export 344
#define AEC_LBL_SetConfigurationDefaults_XMLPreferences 345
#define AEC_TXT_SetConfigurationDefaults_XMLPreferences 346
#define HAEC_PROJECTBROWSE              347
#define HAEC_PROJECTIMPORT              348
#define HAEC_PROJECTEXPORT              349
#define AEC_LBL_Defaults_BlockScaleFAC  350
#define AEC_TXT_Defaults_BlockScaleFAC  351
#define AEC_LBL_Defaults_LinestyleScaleFAC 352
#define AEC_TXT_Defaults_LinestyleScaleFAC 353
#define AEC_TXT_EditPointSymbology_X    354
#define AEC_TXT_EditPointSymbology_Y    355
#define AEC_TXT_EditPointSymbology_Z    356
#define AEC_TXT_EditLineSymbology_LinetypeScale 357
#define AEC_BTN_Common_Settings         358
#define AEC_LBL_RailSuperelevationOptions_DesignSpeed 359
#define AEC_TXT_RailSuperelevationOptions_DesignSpeed 360
#define AEC_TXT_RailSuperelevationOptions_EquilibriumConstant 361
#define AEC_TXT_RailSuperelevationOptions_AppliedConstant 362
#define AEC_LBL_RailSuperelevationOptions_CantRoundingConstant 363
#define AEC_TXT_RailSuperelevationOptions_CantRoundingConstant 364
#define AEC_TXT_RailSuperelevationOptions_RailToRailDistance 365
#define AEC_TXT_RailSuperelevationOptions_VirtualLength 366
#define AEC_CBX_RailSuperelevationOptions_RotateCantAbout 367
#define AEC_CHK_RailSuperelevationOptions_CantAtSpiralToSpiral 368
#define AEC_TXT_RailSuperelevationOptions_PercentOnLinear 369
#define AEC_BTN_SetConfigurationDefaults_New 370
#define AEC_BTN_SetConfigurationDefaults_Copy 371
#define AEC_BTN_SetConfigurationDefaults_Rename 372
#define AEC_TXT_SetConfigurationDefaults_Input 373
#define AEC_BTN_SetConfigurationDefaults_Delete 374
#define AEC_TXT_NewConfiguration_Name   375
#define AEC_TXT_CopyRenameConfiguration_NameTO 376
#define AEC_LBL_CopyRenameConfiguration_NameFrom 377
#define AEC_LBL_BentleyLicensing_ComputerCode 378
#define AEC_LBL_BentleyLicensing_ComputerName 379
#define AEC_BTN_BentleyLicensing_DemoMode 380
#define AEC_BTN_BentleyLicensing_Quit   381
#define AEC_CHK_SetConfigurationDefaults_ActiveOnly 382
#define AEC_CHK_RailSuperelevationOptions_ComputeTurnoutsBasedOnCant 383
#define AEC_BTN_StartWithDelay_Start    384
#define AEC_BTN_StartWithDelay_Quit     385
#define AEC_LVW_EditNamedSymbology_List 386
#define AEC_LBL_SetConfigurationDefaults_Turnouts 387
#define AEC_TXT_SetConfigurationDefaults_Turnouts 388
#define AEC_ROT_CopyRight               389
#define AEC_CHK_Defaults_AutoTriangulate 390
#define AEC_RBN_Defaults_DefineTransitionsByLength 391
#define AEC_RBN_Defaults_DefineTransitionsByConstant 392
#define AEC_BTN_Defaults_ScaleFactorLockUSTN 393
#define AEC_BTN_Defaults_ScaleFactorLockACAD 394
#define AEC_CHK_Defaults_Text_Scale_Lock 395
#define AEC_LVW_ApplicationsAddins_CommandsAvailable 396
#define AEC_BTN_ScalePointSymLockACAD   397
#define AEC_TXT_EditSymbolSymbology_Symbol 399
#define AEC_TRE_Common_Tree             400
#define AEC_FRM_CommonTree_ChildDialogArea 401
#define AEC_LIN_CommonTree_Line         402
#define AEC_CHK_EditPointSymbology_Display 403
#define AEC_CHK_EditPointSymbology_DisplayBlock 404
#define AEC_TXT_Options_PCAbbreviationCS 405
#define AEC_TXT_Options_PIAbbreviationCS 406
#define AEC_TXT_Options_CCAbbreviationCS 407
#define AEC_TXT_Options_PTAbbreviationCS 408
#define AEC_TXT_Options_TSAbbreviationCS 409
#define AEC_TXT_Options_SCAbbreviationCS 410
#define AEC_TXT_Options_CSAbbreviationCS 411
#define AEC_TXT_Options_STAbbreviationCS 412
#define AEC_TXT_Options_SPIAbbreviationCS 413
#define AEC_TXT_Options_PCCAbbreviationCS 414
#define AEC_TXT_Options_PRCAbbreviationCS 415
#define AEC_TXT_Options_SSAbbreviationCS 416
#define AEC_TXT_Options_POBAbbreviationCS 417
#define AEC_TXT_Options_POEAbbreviationCS 418
#define AEC_TXT_Options_EQNAbbreviationCS 419
#define AEC_TXT_Options_EQNBKAbbreviationCS 420
#define AEC_TXT_Options_EQNAHDAbbreviationCS 421
#define AEC_TXT_Options_EVTAbbreviationCS 422
#define AEC_TXT_Options_POTAbbreviationCS 423
#define AEC_TXT_Options_POCAbbreviationCS 424
#define AEC_TXT_Options_POSAbbreviationCS 425
#define AEC_TXT_Options_COGOAbbreviationCS 426
#define AEC_TXT_Options_PVCAbbreviationCS 427
#define AEC_TXT_Options_PVIAbbreviationCS 428
#define AEC_TXT_Options_PVTAbbreviationCS 429
#define AEC_TXT_Options_PVCCAbbreviationCS 430
#define AEC_TXT_Options_PVRCAbbreviationCS 431
#define AEC_TXT_Options_POVTAbbreviationCS 432
#define AEC_TXT_Options_POVCAbbreviationCS 433
#define AEC_TXT_Options_VEVTAbbreviationCS 434
#define AEC_TXT_Options_VLOWAbbreviationCS 435
#define AEC_TXT_Options_VHIGHAbbreviationCS 436
#define AEC_LBL_SetConfigurationDefaults_ProjectWiseDirectory 437
#define AEC_TXT_SetConfigurationDefaults_ProjectWiseDirectory 438
#define AEC_TXT_SetConfigurationDefaults_StyleSheets 439
#define AEC_TXT_SetConfigurationDefaults_XMLData 440
#define AEC_LBL_SetConfigurationDefaults_StyleSheets 441
#define AEC_LBL_SetConfigurationDefaults_XMLData 442
#define AEC_LVW_ProjectOptions_XMLPrf   443
#define AEC_LBL_SetConfigurationDefaults_DraftingNotes 444
#define AEC_TXT_SetConfigurationDefaults_DraftingNotes 445
#define AEC_TXT_Options_StationPrefixCS 446
#define AEC_TXT_Options_StationSuffixCS 447
#define AEC_TXT_Options_LeftOffsetPrefixCS 448
#define AEC_TXT_Options_LeftOffsetSuffixCS 449
#define AEC_TXT_Options_RightOffsetPrefixCS 450
#define AEC_TXT_Options_RightOffsetSuffixCS 451
#define AEC_TXT_Options_DualDimPrefixCS 452
#define AEC_TXT_Options_DualDimSuffixCS 453
#define AEC_TXT_SetConfigurationDefaults_StructuresFile 454
#define AEC_TXT_Options_DiscontPrefixCS 454
#define AEC_LBL_SetConfigurationDefaults_StructuresFile 455
#define AEC_TXT_Options_DualDimSuffixCS2 455
#define AEC_TXT_Options_DiscontSuffixCS 455
#define AEC_TXT_SetConfigurationDefaults_RainfallData 456
#define AEC_LBL_SetConfigurationDefaults_RainfallData 457
#define AEC_GRP_ApplicationsAddins_Description 458
#define AEC_CHK_SetConfigurationDefaults_GeneralPreferences 459
#define AEC_CHK_SetConfigurationDefaults_Turnouts 460
#define AEC_CHK_SetConfigurationDefaults_DrainageStructures 461
#define AEC_CHK_SetConfigurationDefaults_RainfallData 462
#define AEC_CHK_SetConfigurationDefaults_DraftingNotes 463
#define AEC_LBL_SetConfigurationDefaults_ReadOnly 464
#define AEC_GRP_Saveas_Vault            465
#define AEC_ROT_Saveas_Vault            466
#define AEC_BTN_Saveas_VaultChange      467
#define AEC_CBX_Saveas_Application      468
#define AEC_CBX_Saveas_Department       469
#define AEC_TXT_Saveas_Name             470
#define AEC_TXT_Saveas_Filename         471
#define AEC_TXT_Saveas_Description      472
#define AEC_CBX_Saveas_Filetype         473
#define AEC_BTN_SymbologyMgr_Rename     474
#define AEC_TXT_RenameNamedSymbology_NameTO 475
#define AEC_CBX_RenameNamedSymbology_NameFROM 476
#define AEC_BTN_Common_Interactive      477
#define AEC_TXT_RenameNamedSymbology_DescriptionTO 477
#define AEC_BTN_EditNamedSymbology_Copy 478
#define AEC_CBX_CopyIndividualSymbology_From 479
#define AEC_CBX_CopyIndividualSymbology_To 480
#define AEC_LBL_SetConfigurationDefaults_PayItems 481
#define AEC_CHK_SetConfigurationDefaults_PayItems 482
#define AEC_TXT_SetConfigurationDefaults_PayItems 483
#define AEC_LBL_SetConfigurationDefaults_QuantityManager 484
#define AEC_TXT_SetConfigurationDefaults_QuantityManager 485
#define AEC_ROT_ChooseMacroDirectory_Name 486
#define AEC_TRE_ChooseMacroDirectory_Tree 487
#define AEC_CBX_ChooseMacroDirectory_Drive 488
#define AEC_TXT_EditNamedSymbology_Description 489
#define AEC_LVW_SymbologyMgr_NameList   490
#define AEC_LBL_EditPointSymbology_Color 491
#define AEC_LBL_EditPointSymbology_X    493
#define AEC_LBL_EditPointSymbology_Y    494
#define AEC_LBL_EditPointSymbology_Z    495
#define AEC_TXT_Defaults_VerticalChordHeightT 497
#define AEC_TXT_CopySinglePreference_NameTO 498
#define AEC_TXT_CopyMultiplePreferences_NameTO 499
#define AEC_CBX_CopySinglePreference_NameFRM 500
#define AEC_CBX_CopyMultiplePreferences_NameFRM 501
#define AEC_RBN_CopyMultiplePreferences_Replace 502
#define AEC_RBN_CopyMultiplePreferences_Skip 503
#define AEC_LBL_SetConfigurationDefaults_Sections 504
#define AEC_TXT_SetConfigurationDefaults_Sections 505
#define AEC_CHK_SetConfigurationDefaults_Sections 506
#define AEC_LBX_ProductAddins_Available 507
#define AEC_ROT_ProductAddins_Description 510
#define AEC_DLG_XINDetails_Details      511
#define AEC_GRP_PreferenceManager_Commands 512
#define AEC_GRP_EditPointSymbology_CellBlock 513
#define AEC_LBL_EditPointSymbology_AngleCELL 514
#define AEC_GRP_EditPointSymbology_RotationCELL 515
#define AEC_GRP_EditPointSymbology_RotationSYMB 516
#define AEC_RBN_EditPointSymbology_RelativeAngleSYMB 517
#define AEC_RBN_EditPointSymbology_AbsoluteAngleSYMB 518
#define AEC_TXT_EditPointSymbology_AngleSYMB 519
#define AEC_CBX_EditPointSymbology_LayerNameSYMB 520
#define AEC_LBL_EditPointSymbology_Font 521
#define AEC_LBL_EditPointSymbology_AngleSYMB 522
#define AEC_LBL_EditPointSymbology_LayerNameCELL 524
#define AEC_LBL_EditPointSymbology_LayerNameSYMB 525
#define AEC_CHK_SymbologyMgr_IncludeDefault 536
#define AEC_CHK_SymbologyMgr_IncludePlan 537
#define AEC_CHK_SymbologyMgr_IncludeProfile 538
#define AEC_CHK_SymbologyMgr_IncludeXSection 539
#define AEC_BTN_SymbologyMgr_Invert     540
#define AEC_GRP_SymbologyMgr_ShowProperties 548
#define AEC_CHK_Common_DontShow         553
#define AEC_ROT_Common_Message          554
#define AEC_LBL_RailSuperelevationOptions_CenterOfGravity 555
#define AEC_TXT_RailSuperelevationOptions_CenterOfGravity 556
#define AEC_CHK_ProductAddins_Persist   557
#define AEC_TXT_Defaults_EyeHeight      558
#define AEC_TXT_Defaults_StopObjHeight  559
#define AEC_TXT_Defaults_PassObjHeight  560
#define AEC_BTN_Common_ResizeGrip       561
#define AEC_BTN_Saveas_DocumentChange   562
#define AEC_GRP_PWSaveAs_Document       564
#define AEC_GRP_PWSaveAsRet_Document    565
#define AEC_TVW_Training_Lessons        566
#define AEC_CBX_Training_Modules        567
#define AEC_ROT_Training_DocumentNumber 572
#define AEC_ROT_Training_InRoadsVersion 573
#define AEC_TXT_TrainingDirectory_Directory 575
#define AEC_CHK_RailSuperelevationOptions_ForceCollinearity 576
#define AEC_CHK_RailSuperelevationOptions_NonlinearAsSimple 577
#define AEC_CHK_RailSuperelevationOptions_SlewSignage 578
#define AEC_CBX_Defaults_CubicParabolaDefinition 581
#define AEC_CHK_Defaults_VerticalAlignmentHealing 582
#define UTI_CHK_CopyIndividualSymbology_DefaultLine 583
#define UTI_CHK_CopyIndividualSymbology_DefaultText 584
#define UTI_CHK_CopyIndividualSymbology_DefaultPoint 585
#define UTI_CHK_CopyIndividualSymbology_PlanLine 586
#define UTI_CHK_CopyIndividualSymbology_PlanText 587
#define UTI_CHK_CopyIndividualSymbology_PlanPoint 588
#define UTI_CHK_CopyIndividualSymbology_ProfileLine 589
#define UTI_CHK_CopyIndividualSymbology_ProfileText 590
#define UTI_CHK_CopyIndividualSymbology_ProfilePoint 591
#define UTI_CHK_CopyIndividualSymbology_XSLine 592
#define UTI_CHK_CopyIndividualSymbology_XSText 593
#define UTI_CHK_CopyIndividualSymbology_XSPoint 594
#define AEC_ROT_RenameNamedSymbology_DescriptionFROM 598
#define AEC_TXT_CopySymbology_DescriptionTO 600
#define AEC_ROT_CopySymbology_DescriptionFROM 601
#define AEC_FRM_ChildDialogArea         607
#define AEC_LIN_Line                    608
#define AEC_BTN_Previous                609
#define AEC_BTN_Next                    610
#define AEC_BTN_New                     611
#define AEC_TXT_Defaults_Autosave       613
#define AEC_CBX_Defaults_LatLongP       614
#define AEC_ROT_Defaults_PreferredPreferenceName 619
#define AEC_ROT_UAC_Configuration       620
#define AEC_BTN_UserAccessControl       621
#define AEC_TRE_UserAccessControl       622
#define AEC_LBL_SetConfigurationDefaults_DesignRules 623
#define AEC_TXT_SetConfigurationDefaults_DesignRules 624
#define AEC_TXT_Options_StationDelimiter 625
#define AEC_CHK_RailSuperelevationOptions_InterpolateSpeed 626
#define AEC_BTN_Results_Copy            627
#define AEC_CBX_UstnEditLineSymbology_Style 628
#define AEC_CHK_UstnEditLineSymbology_Scale 629
#define AEC_TXT_UstnEditLineSymbology_Scale 630
#define AEC_CBX_UstnEditLineSymbology_Level 631
#define AEC_CHK_UstnEditLineSymbology_Fill 632
#define AEC_TXT_UstnEditLineSymbology_Color 633
#define AEC_BTN_UstnEditLineSymbology_Color 634
#define AEC_TXT_UstnEditTextSymbology_Color 635
#define AEC_TXT_UstnEditTextSymbology_Height 636
#define AEC_BTN_UstnEditTextSymbology_Color 637
#define AEC_LBL_UstnEditTextSymbology_HorizontalOffset 638
#define AEC_LBL_UstnEditTextSymbology_VerticalOffset 639
#define AEC_RBN_UstnEditTextSymbology_AngleRelativeToObject 640
#define AEC_RBN_UstnEditTextSymbology_AbsoluteAngle 641
#define AEC_RBN_UstnEditTextSymbology_AfterRotation 642
#define AEC_RBN_UstnEditTextSymbology_BeforeRotation 1016
#define AEC_CBX_UstnEditTextSymbology_Justification 1017
#define AEC_EDT_UstnEditTextSymbology_HZOffset 1018
#define AEC_EDT_UstnEditTextSymbology_VTOffset 1019
#define AEC_TXT_UstnEditTextSymbology_Angle 1020
#define AEC_TXT_UstnEditTextSymbology_LineSpacing 1021
#define AEC_CBX_UstnEditTextSymbology_Font 1022
#define AEC_TXT_UstnEditTextSymbology_Width 1023
#define AEC_CHK_UstnEditTextSymbology_ViewIndependent 1024
#define AEC_BTN_UstnEditSymbolSymbology_Color 1035
#define AEC_CBX_UstnEditLineSymbology_StyleName 1043
#define AEC_CBX_UstnEditTextSymbology_StyleName 1044
#define AEC_CBX_UstnEditPointSymbology_DisplayAs 1047
#define AEC_CBX_UstnEditPointSymbology_CellName 1048
#define AEC_TXT_UstnEditPointSymbology_Color 1049
#define AEC_BTN_UstnEditPointSymbology_Color 1050
#define AEC_LBL_UstnEditPointSymbology_XScale 1051
#define AEC_TXT_UstnEditPointSymbology_XScale 1052
#define AEC_LBL_UstnEditPointSymbology_YScale 1053
#define AEC_TXT_UstnEditPointSymbology_YScale 1054
#define AEC_LBL_UstnEditPointSymbology_ZScale 1055
#define AEC_TXT_UstnEditPointSymbology_ZScale 1056
#define AEC_LBL_UstnEditPointSymbology_Font 1057
#define AEC_CBX_UstnEditPointSymbology_Font 1058
#define AEC_TXT_UstnEditPointSymbology_Character 1059
#define AEC_LBL_UstnEditPointSymbology_Height 1060
#define AEC_TXT_UstnEditPointSymbology_Height 1061
#define AEC_LBL_UstnEditPointSymbology_Width 1062
#define AEC_TXT_UstnEditPointSymbology_Width 1063
#define AEC_CBX_UstnEditPointSymbology_SymbologyName 1064
#define AEC_TXT_UstnEditPointSymbology_Angle 1067
#define AEC_LBL_UstnEditPointSymbology_Character 1068
#define AEC_BTN_UstnColorPalette_ByLevel 1069
#define AEC_RBN_UstnEditPointSymbology_AngleRelativeCELL 1069
#define AEC_BTN_Text_Lock               1070
#define AEC_RBN_UstnEditPointSymbology_AngleAbsoluteCELL 1070
#define AEC_BTN_ScalePointSymLockUSTN   1071
#define AEC_CBX_UstnEditPointSymbology_Level 1072
#define AEC_CBX_UstnEditTextSymbology_Level 1073
#define AEC_CBX_UstnEditPointSymbology_LevelCELL 1073
#define AEC_BTN_TextSym2_LockUSTN       1074
#define AEC_TXT_UstnEditPointSymbology_Angle2 1074
#define AEC_TXT_UstnEditPointSymbology_AngleCELL 1074
#define AEC_CHK_UstnEditPointSymbology_Display 1075
#define AEC_CHK_UstnEditPointSymbology_DisplayCell 1076
#define AEC_BTN_TextPointSymUSTN        1077
#define AEC_LBL_UstnEditPointSymbology_Color 1078
#define AEC_LBL_UstnEditPointSymbology_Weight 1079
#define AEC_CBX_UstnEditLineSymbology_Weight 1080
#define AEC_CHK_UstnEditPointSymbology_DisplayCell2 1080
#define AEC_CBX_UstnEditTextSymbology_Weight 1081
#define AEC_CBX_UstnEditPointSymbology_Weight 1082
#define AEC_CBX_UstnEditTextSymbology_TextStyle 1083
#define AEC_CBX_UstnEditPointSymbology_LevelSYMB 1085
#define AEC_RBN_UstnEditPointSymbology_AngleRelativeSYMB 1086
#define AEC_GRP_UstnEditPointSymbology_RotationSYMB 1087
#define AEC_RBN_UstnEditPointSymbology_AngleAbsoluteSYMB 1088
#define AEC_TXT_UstnEditPointSymbology_AngleSYMB 1089
#define AEC_LBL_UstnEditPointSymbology_AngleSYMB 1090
#define AEC_LBL_UstnEditPointSymbology_AngleCELL 1091
#define AEC_GRP_UstnEditPointSymbology_RotationCELL 1092
#define AEC_LBL_UstnEditPointSymbology_LevelSYMB 1093
#define AEC_LBL_UstnEditPointSymbology_LevelCELL 1094
#define AEC_GRP_UstnEditPointSymbology_CellBlock 1095
#define AEC_LBL_UstnEditTextSymbology_Weight 1096
#define AEC_LBL_UstnEditTextSymbology_Justification 1097
#define AEC_LBL_UstnEditLineSymbology_Level 1098
#define AEC_LBL_UstnEditLineSymbology_Style 1099
#define AEC_LBL_UstnEditLineSymbology_Weight 1100
#define AEC_LBL_UstnEditTextSymbology_Angle 1101
#define AEC_LBL_UstnEditTextSymbology_LineSpacing 1102
#define AEC_LBL_UstnEditTextSymbology_TextStyle 1103
#define AEC_LBL_UstnEditLineSymbology_Material 1104
#define AEC_CBX_UstnEditLineSymbology_Material 1105
#define AEC_DLG_ExplorerWindow          1365
#define AEC_FIRST_TREE_BMP              1366
#define AEC_DLG_Open                    1367
#define AEC_LAST_TREE_BMP               1368
#define AEC_DLG_SaveAs                  1373
#define AEC_DLG_SaveFilesAtExit         1374
#define AEC_ICO_QuestionMark            1380
#define AEC_LOCATE1DISABLE              1381
#define AEC_LOCATEBUTTON1DOWN           1385
#define AEC_LOCATEBUTTON1UP             1386
#define AEC_WND_STATUS_BAR              1394
#define IDI_SWDIALOG                    1396
#define AEC_BMP_FolderClosed            1462
#define AEC_BMP_FolderOpen              1463
#define GLZOOMINUP                      1466
#define GLZOOMINDOWN                    1467
#define GLFITDOWN                       1468
#define GLFITUP                         1469
#define GLREDOFOCUS                     1470
#define GLZOOMINFOCUS                   1471
#define GLZOOMOUTDOWN                   1472
#define GLUNDOFOCUS                     1473
#define GLWINDOWAREAFOCUS               1474
#define GLWINDOWAREAUP                  1475
#define GLWINDOWAREADOWN                1476
#define GLZOOMOUTFOCUS                  1477
#define GLUNDOUP                        1478
#define GLREDOUP                        1479
#define GLREDODOWN                      1480
#define GLUNDODOWN                      1481
#define GLFITFOCUS                      1482
#define GLZOOMINXUP                     1483
#define GLZOOMINXFOCUS                  1484
#define GLZOOMINXDOWN                   1485
#define GLZOOMINYUP                     1486
#define GLZOOMINYFOCUS                  1487
#define GLZOOMINYDOWN                   1488
#define GLZOOMOUTUP                     1489
#define GLZOOMOUTYUP                    1490
#define GLZOOMOUTYFOCUS                 1491
#define GLZOOMOUTYDOWN                  1492
#define GLZOOMOUTXUP                    1493
#define GLZOOMOUTXFOCUS                 1494
#define GLZOOMOUTXDOWN                  1495
#define GLACCUDRAWUP                    1496
#define GLACCUDRAWFOCUS                 1497
#define GLACCUDRAWDOWN                  1498
#define GLREDODISABLED                  1499
#define GLUNDODISABLED                  1500
#define AEC_MNU_ColumnHeaderControl     1527
#define AEC_BMP_ResizeGrip              1531
#define AEC_TXT_RailSuperelevationOptions_InsideToInsideDistance 1535
#define AEC_DLG_TextScaleFactorWarning  1536
#define AEC_TXT_RailSuperelevationOptions_NominalRailWidth 1537
#define ACADMSG_P_ACCEPT                3805
#define ACADMSG_P_ACCEPT_REJECT         3806
#define ACADMSG_P_ACCEPT_REJECT_2ND     3807
#define ACADMSG_P_ACCEPT_REJECT_CLOSE   3808
#define ACADMSG_P_ACCEPT_REJECT_FINAL   3809
#define ACADMSG_P_ACCEPT_REJECT_FIRST   3810
#define ACADMSG_P_DTMIFYDIR             3816
#define ACADMSG_P_DTMIFYPT1             3817
#define ACADMSG_P_ENDPNT                3820
#define ACADMSG_P_ENTERNEXTPNTDONE      3821
#define ACADMSG_P_FEATUREACCEPT         3823
#define ACADMSG_P_FEATURENEXTELE        3824
#define ACADMSG_P_IDALGORDISCULDLG      3838
#define ACADMSG_P_IDBEG                 3840
#define ACADMSG_P_IDELEMENT             3841
#define ACADMSG_P_IDELEMENT_STOP        3842
#define ACADMSG_P_IDEND                 3843
#define ACADMSG_P_IDENTIFY_BACKUP       3844
#define ACADMSG_P_IDENTIFY_R_RESET      3846
#define ACADMSG_P_IDENTIFYNEXTALGORNEW  3847
#define ACADMSG_P_IDENTIFYPARALLEL      3848
#define ACADMSG_P_IDFEATUREELE          3849
#define ACADMSG_P_IDFIRSTALGORSTOP      3850
#define ACADMSG_P_IDFIRSTDIRPOINT       3851
#define ACADMSG_P_IDFIRSTPOINT          3852
#define ACADMSG_P_IDPOINT               3855
#define ACADMSG_P_IDPOINT_STOP          3856
#define ACADMSG_P_IDPOINTORNEWALG       3857
#define ACADMSG_P_IDQUADORNEWSECALG     3858
#define ACADMSG_P_IDSECALGORNEWFIRST    3859
#define ACADMSG_P_IDSECONDDIRPOINT      3860
#define ACADMSG_P_IDSECONDPOINT         3861
#define ACADMSG_P_PAD_PLACE_PNT         3871
#define ACADMSG_P_REJECT                3875
#define AEC_M_ACTPRF                    3889
#define AEC_M_CANCEL                    3895
#define AEC_M_CLOSE                     3896
#define AEC_M_DELPRF                    3898
#define AEC_M_INVALIDINPUT              3910
#define AEC_M_PRFDEL                    3923
#define AEC_M_PRFEXT                    3924
#define AEC_M_PRFLOD                    3925
#define AEC_M_PRFNTF                    3926
#define AEC_M_PRFSAV                    3927
#define AEC_M_PRINTER_CANTINIT          3928
#define AEC_M_PRINTER_INITABORT         3929
#define AEC_M_PRINTER_UNEXPECTED        3930
#define AEC_M_SAVE                      3934
#define ACADMSG_P_IDFEATURE             3950
#define ALL_FILE                        3958
#define END_FILE_LIST                   3969
#define PRFTXT_UTI_BLOCKSYM_0           3978
#define PRFTXT_UTI_BLOCKSYM_INR_PLUS    3979
#define PRFTXT_UTI_TEXTSYM_0            3980
#define PRFTXT_UTI_TEXTSYM_STANDARD     3981
#define ITL_FILE                        3994
#define TXT_FILE                        3997
#define USTNMSG_P_ACCEPT_REJECT         3998
#define USTNMSG_P_ACCEPT_REJECT_2ND     3999
#define USTNMSG_P_ACCEPT_REJECT_CLOSE   4000
#define USTNMSG_P_ACCEPT_REJECT_FINAL   4001
#define USTNMSG_P_ACCEPT_REJECT_FIRST   4002
#define USTNMSG_P_DTMIFYDIR             4003
#define USTNMSG_P_DTMIFYPT1             4004
#define USTNMSG_P_ENDPNT                4005
#define USTNMSG_P_ENTERNEXTPNTDONE      4006
#define USTNMSG_P_FEATUREACCEPT         4007
#define USTNMSG_P_FEATURENEXTELE        4008
#define USTNMSG_P_IDALGORDISCULDLG      4009
#define USTNMSG_P_IDBEG                 4010
#define USTNMSG_P_IDELEMENT_STOP        4011
#define USTNMSG_P_IDEND                 4012
#define USTNMSG_P_IDENTIFY_BACKUP       4013
#define USTNMSG_P_IDENTIFY_R_RESET      4014
#define USTNMSG_P_IDENTIFYNEXTALGORNEW  4015
#define USTNMSG_P_IDENTIFYPARALLEL      4016
#define USTNMSG_P_IDFEATUREELE          4017
#define USTNMSG_P_IDFIRSTALGORSTOP      4018
#define USTNMSG_P_IDPOINT_STOP          4019
#define USTNMSG_P_IDPOINTORNEWALG       4020
#define USTNMSG_P_IDQUADORNEWSECALG     4021
#define USTNMSG_P_IDSECALGORNEWFIRST    4022
#define USTNMSG_P_PAD_PLACE_PNT         4023
#define UTI_FMT_BYPERCENTS              4033
#define UTI_FMT_MAXDBL                  4034
#define UTI_FMT_MAXINT                  4035
#define UTI_FMT_MINDBL                  4036
#define UTI_FMT_MININT                  4037
#define UTI_FNT_MSSANSSERIF             4043
#define UTI_HASHDEF_AECINPUTACADNEEDED  4044
#define UTI_HASHDEF_AECINPUTALLOW       4045
#define UTI_HASHDEF_AECINPUTCALLBACK    4046
#define UTI_HASHDEF_AECINPUTEVENT       4047
#define UTI_HASHDEF_AECINPUTSTALLED     4048
#define UTI_HASHDEF_AECINPUTWAITDISABLE 4049
#define UTI_HASHDEF_AECINPUTWHEREAMI    4050
#define UTI_MBX_IMPROPERFILENAME        4052
#define UTI_STR_CONTINUOUS              4073
#define IRD_FILE                        4075
#define UTI_TITLE_APPEND                4076
#define UTI_TITLE_BROWSE                4077
#define UTI_TITLE_OPEN                  4081
#define UTI_TITLE_SAVEAS                4083
#define XSC_FILE                        4105
#define XMLPRF_FILE                     4109
#define SH_FILE                         4112
#define XD_FILE                         4113
#define UTI_MSG_NOTINITIALIZED          4114
#define AEC_MSG_CONFIRMDELETE           4180
#define UTI_TXT_NEWNAMEDSYMBOLOGY       4181
#define AEC_MSG_SYMBOLOGYHASCHANGED     4182
#define UTI_TXT_ALREADYEXISTS           4208
#define UTI_FMT_MINDBL2                 4209
#define UTI_FMT_MAXLONG                 4248
#define UTI_FMT_MINLONG                 4249
#define AEC_MSG_INPUTCMDACTIVE_PROMPT   4251
#define AEC_M_NAME                      4257
#define AEC_M_OBJECT                    4259
#define ACADMSG_P_PLACEUNDO             4299
#define USTNMSG_P_PLACEUNDO             4300
#define IDS_SYMBOLTYPE_TRIANGLE         4304
#define IDS_SYMBOLTYPE_INVTRIANGLE      4305
#define IDS_SYMBOLTYPE_CIRCLE           4306
#define IDS_SYMBOLTYPE_SQUARE           4307
#define IDS_SYMBOLTYPE_PLUSSIGN         4308
#define IDS_SYMBOLTYPE_CROSS            4309
#define IDS_SYMBOLTYPE_DUMBBELL         4310
#define IDS_SYMBOLTYPE_TARGET           4311
#define IDS_SYMBOLTYPE_SYMBOL           4312
#define ACAD_TXTJUST_LT                 4314
#define ACAD_TXTJUST_CT                 4315
#define ACAD_TXTJUST_RT                 4316
#define ACAD_TXTJUST_LM                 4317
#define ACAD_TXTJUST_CM                 4318
#define ACAD_TXTJUST_RM                 4319
#define ACAD_TXTJUST_LB                 4320
#define ACAD_TXTJUST_CB                 4321
#define ACAD_TXTJUST_RB                 4322
#define AEC_M_USE                       4323
#define UTI_MSG_DEFAULT_LINE            4324
#define UTI_MSG_CROSS_SECTION_POINT     4335
#define UTI_M_CONFIRM_DELETE            4359
#define UTI_S_ZoomIn                    4363
#define AEC_M_None                      4374
#define AEC_M_CHOOSEVAULT               4375
#define AEC_M_NOFILE                    4376
#define AEC_MSG_SUCCESS                 4396
#define UTI_TXTJUST_LT                  4397
#define UTI_TXTJUST_CT                  4398
#define UTI_TXTJUST_RT                  4399
#define UTI_TXTJUST_LC                  4400
#define UTI_TXTJUST_CC                  4401
#define UTI_TXTJUST_RC                  4402
#define UTI_TXTJUST_LB                  4403
#define UTI_TXTJUST_CB                  4404
#define UTI_TXTJUST_RB                  4405
#define UTI_MSG_INVALIDLEVEL            4406
#define EAV_FILE                        4407
#define UTI_TXT_WINDOWAREAFIRSTPOINT    4413
#define UTI_TXT_WINDOWAREAOPPOSITEPOINT 4414
#define AEC_M_UNDEFINED                 4423
#define UTI_TXT_SYMMGR_Desc             4438
#define AEC_E_INVALIDNAME               4451
#define AEC_M_DETAILS_READONLY          4455
#define AEC_M_DETAILS_READWRITE         4456
#define UTI_TXT_BYLEVEL                 4457
#define AEC_MSG_AMREADONLY_SHARE        4467
#define AEC_MSG_HOSTFILE                4566
#define AEC_BTN_Preferences_Rename      4602
#define AEC_CBX_RenamePreference_From   4603
#define AEC_TXT_RenamePreference_To     4604
#define USTN_S_LEVEL                    4613
#define USTN_S_CELL                     4614
#define USTN_MSG_INVALIDLEVEL           4615
#define AEC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        1550
#define _APS_NEXT_COMMAND_VALUE         4616
#define _APS_NEXT_CONTROL_VALUE         628
#define _APS_NEXT_SYMED_VALUE           100
#endif
#endif
