//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geo_Web_Publisher_Unit_Testing_App.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class GeoWebPublisherUnitTestingApp : global::System.Configuration.ApplicationSettingsBase {
        
        private static GeoWebPublisherUnitTestingApp defaultInstance = ((GeoWebPublisherUnitTestingApp)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GeoWebPublisherUnitTestingApp())));
        
        public static GeoWebPublisherUnitTestingApp Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("681")]
        public int WindowSizeH {
            get {
                return ((int)(this["WindowSizeH"]));
            }
            set {
                this["WindowSizeH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("963")]
        public int WindowSizeW {
            get {
                return ((int)(this["WindowSizeW"]));
            }
            set {
                this["WindowSizeW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int WindowLocationX {
            get {
                return ((int)(this["WindowLocationX"]));
            }
            set {
                this["WindowLocationX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int WindowLocationY {
            get {
                return ((int)(this["WindowLocationY"]));
            }
            set {
                this["WindowLocationY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int GridViewIdWidth {
            get {
                return ((int)(this["GridViewIdWidth"]));
            }
            set {
                this["GridViewIdWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int GridViewIdOrder {
            get {
                return ((int)(this["GridViewIdOrder"]));
            }
            set {
                this["GridViewIdOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public int GridViewNameWidth {
            get {
                return ((int)(this["GridViewNameWidth"]));
            }
            set {
                this["GridViewNameWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int GridViewNameOrder {
            get {
                return ((int)(this["GridViewNameOrder"]));
            }
            set {
                this["GridViewNameOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public int GridViewDescriptionWidth {
            get {
                return ((int)(this["GridViewDescriptionWidth"]));
            }
            set {
                this["GridViewDescriptionWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int GridViewDescriptionOrder {
            get {
                return ((int)(this["GridViewDescriptionOrder"]));
            }
            set {
                this["GridViewDescriptionOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int GridViewCategoryWidth {
            get {
                return ((int)(this["GridViewCategoryWidth"]));
            }
            set {
                this["GridViewCategoryWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int GridViewCategoryOrder {
            get {
                return ((int)(this["GridViewCategoryOrder"]));
            }
            set {
                this["GridViewCategoryOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public int GridViewUrlWidth {
            get {
                return ((int)(this["GridViewUrlWidth"]));
            }
            set {
                this["GridViewUrlWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int GridViewUrlOrder {
            get {
                return ((int)(this["GridViewUrlOrder"]));
            }
            set {
                this["GridViewUrlOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51")]
        public int GridViewStatusWidth {
            get {
                return ((int)(this["GridViewStatusWidth"]));
            }
            set {
                this["GridViewStatusWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int GridViewStatusOrder {
            get {
                return ((int)(this["GridViewStatusOrder"]));
            }
            set {
                this["GridViewStatusOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DatabaseName {
            get {
                return ((string)(this["DatabaseName"]));
            }
            set {
                this["DatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8087/")]
        public string UrlPrefix {
            get {
                return ((string)(this["UrlPrefix"]));
            }
            set {
                this["UrlPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2fe1933d-79b3-47b7-8f33-b789fdf432fa.mapdef?SERVICE=wms&REQUEST=getmap&VERSION=1." +
            "1.1&LAYERS=Parcel,Landmark&SRS=None&BBOX=486125.24935000005,5540979.5728,514069." +
            "3070499998,5559608.9446&WIDTH=600&HEIGHT=400&QUALITY=100&FORMAT=image/jpeg")]
        public string TestRequest {
            get {
                return ((string)(this["TestRequest"]));
            }
            set {
                this["TestRequest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color BackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["BackgroundColor"]));
            }
            set {
                this["BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color SmallDifferenceColor {
            get {
                return ((global::System.Drawing.Color)(this["SmallDifferenceColor"]));
            }
            set {
                this["SmallDifferenceColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color BigDifferenceColor {
            get {
                return ((global::System.Drawing.Color)(this["BigDifferenceColor"]));
            }
            set {
                this["BigDifferenceColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoCheckUpdate {
            get {
                return ((bool)(this["AutoCheckUpdate"]));
            }
            set {
                this["AutoCheckUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8087/")]
        public string UpdateServerInfo {
            get {
                return ((string)(this["UpdateServerInfo"]));
            }
            set {
                this["UpdateServerInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int GridViewUpToDateWidth {
            get {
                return ((int)(this["GridViewUpToDateWidth"]));
            }
            set {
                this["GridViewUpToDateWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int GridViewUpToDateOrder {
            get {
                return ((int)(this["GridViewUpToDateOrder"]));
            }
            set {
                this["GridViewUpToDateOrder"] = value;
            }
        }
    }
}
