#include <DgnPlatform/DelegatedElementECEnabler.h>
#include <DgnPlatform/DimensionStyleProps.r.h>

/*************************************************************************************
 * DO NOT EDIT DO NOT EDIT DO NOT EDIT DO NOT EDIT DO NOT EDIT DO NOT EDIT DO NOT EDIT
 * This file automatically generated by DimStyleSchemaGenerator.exe
 * It is included here for use by Android compilation targets.
 ************************************************************************************/

struct DimStylePropEntry {
  DimStyleProp dimStyleProp;
  DimStyleProp_Type dimStylePropType;
};

// Autogenerated enum for class Placement
enum PlacementPropertyIndex {
	BESINDEX_Placement_Level = 1,
	BESINDEX_Placement_IgnoreLevelSymb = 2,
	BESINDEX_Placement_Alignment = 3,
	BESINDEX_Placement_AnnotationScale = 4,
	BESINDEX_Placement_Location = 5,
	BESINDEX_Placement_LiftDimLine = 6,
	BESINDEX_Placement_UseReferenceScale = 7,
	BESINDEX_Placement_RelativeDimLine = 8,
	BESINDEX_Placement_CenterSize = 9,
	BESINDEX_Placement_CompatibleV3 = 10,
};

// Autogenerated map for class Placement
static const ElementECDelegate::MapEntry s_BESMAP_Placement[] = {
	BESINDEX_Placement_Level, L"Level", NULL_MAP,
	BESINDEX_Placement_IgnoreLevelSymb, L"IgnoreLevelSymb", NULL_MAP,
	BESINDEX_Placement_Alignment, L"Alignment", NULL_MAP,
	BESINDEX_Placement_AnnotationScale, L"AnnotationScale", NULL_MAP,
	BESINDEX_Placement_Location, L"Location", NULL_MAP,
	BESINDEX_Placement_LiftDimLine, L"LiftDimLine", NULL_MAP,
	BESINDEX_Placement_UseReferenceScale, L"UseReferenceScale", NULL_MAP,
	BESINDEX_Placement_RelativeDimLine, L"RelativeDimLine", NULL_MAP,
	BESINDEX_Placement_CenterSize, L"CenterSize", NULL_MAP,
	BESINDEX_Placement_CompatibleV3, L"CompatibleV3", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class Tolerance
enum TolerancePropertyIndex {
	BESINDEX_Tolerance_Enable = 1,
	BESINDEX_Tolerance_Type = 2,
	BESINDEX_Tolerance_UpperValue = 3,
	BESINDEX_Tolerance_LowerValue = 4,
	BESINDEX_Tolerance_StackEqual = 5,
	BESINDEX_Tolerance_ShowSignForZero = 6,
	BESINDEX_Tolerance_PrimaryAccuracy = 7,
	BESINDEX_Tolerance_PrimaryRetainFraction = 8,
	BESINDEX_Tolerance_SecondaryAccuracy = 9,
	BESINDEX_Tolerance_SecondaryRetainFraction = 10,
	BESINDEX_Tolerance_TextSize = 11,
	BESINDEX_Tolerance_LeftMargin = 12,
	BESINDEX_Tolerance_SepMargin = 13,
	BESINDEX_Tolerance_Prefix = 14,
	BESINDEX_Tolerance_Suffix = 15,
};

// Autogenerated map for class Tolerance
static const ElementECDelegate::MapEntry s_BESMAP_Tolerance[] = {
	BESINDEX_Tolerance_Enable, L"Enable", NULL_MAP,
	BESINDEX_Tolerance_Type, L"Type", NULL_MAP,
	BESINDEX_Tolerance_UpperValue, L"UpperValue", NULL_MAP,
	BESINDEX_Tolerance_LowerValue, L"LowerValue", NULL_MAP,
	BESINDEX_Tolerance_StackEqual, L"StackEqual", NULL_MAP,
	BESINDEX_Tolerance_ShowSignForZero, L"ShowSignForZero", NULL_MAP,
	BESINDEX_Tolerance_PrimaryAccuracy, L"PrimaryAccuracy", NULL_MAP,
	BESINDEX_Tolerance_PrimaryRetainFraction, L"PrimaryRetainFraction", NULL_MAP,
	BESINDEX_Tolerance_SecondaryAccuracy, L"SecondaryAccuracy", NULL_MAP,
	BESINDEX_Tolerance_SecondaryRetainFraction, L"SecondaryRetainFraction", NULL_MAP,
	BESINDEX_Tolerance_TextSize, L"TextSize", NULL_MAP,
	BESINDEX_Tolerance_LeftMargin, L"LeftMargin", NULL_MAP,
	BESINDEX_Tolerance_SepMargin, L"SepMargin", NULL_MAP,
	BESINDEX_Tolerance_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_Tolerance_Suffix, L"Suffix", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class General
enum GeneralPropertyIndex {
	BESINDEX_General_Placement = 1,
	BESINDEX_General_Tolerance = 12,
	BESINDEX_General_Name = 28,
	BESINDEX_General_Description = 29,
};

// Autogenerated map for class General
static const ElementECDelegate::MapEntry s_BESMAP_General[] = {
	BESINDEX_General_Placement, L"Placement", s_BESMAP_Placement,
	BESINDEX_General_Tolerance, L"Tolerance", s_BESMAP_Tolerance,
	BESINDEX_General_Name, L"Name", NULL_MAP,
	BESINDEX_General_Description, L"Description", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class Angle
enum AnglePropertyIndex {
	BESINDEX_Angle_Units = 1,
	BESINDEX_Angle_Display = 2,
	BESINDEX_Angle_Accuracy = 3,
	BESINDEX_Angle_LeadingZero = 4,
	BESINDEX_Angle_TrailingZeros = 5,
};

// Autogenerated map for class Angle
static const ElementECDelegate::MapEntry s_BESMAP_Angle[] = {
	BESINDEX_Angle_Units, L"Units", NULL_MAP,
	BESINDEX_Angle_Display, L"Display", NULL_MAP,
	BESINDEX_Angle_Accuracy, L"Accuracy", NULL_MAP,
	BESINDEX_Angle_LeadingZero, L"LeadingZero", NULL_MAP,
	BESINDEX_Angle_TrailingZeros, L"TrailingZeros", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class Metric
enum MetricPropertyIndex {
	BESINDEX_Metric_DecimalComma = 1,
	BESINDEX_Metric_UnitsSeparator = 2,
};

// Autogenerated map for class Metric
static const ElementECDelegate::MapEntry s_BESMAP_Metric[] = {
	BESINDEX_Metric_DecimalComma, L"DecimalComma", NULL_MAP,
	BESINDEX_Metric_UnitsSeparator, L"UnitsSeparator", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class StackedFractions
enum StackedFractionsPropertyIndex {
	BESINDEX_StackedFractions_Enable = 1,
	BESINDEX_StackedFractions_Type = 2,
	BESINDEX_StackedFractions_Alignment = 3,
	BESINDEX_StackedFractions_Scale = 4,
};

// Autogenerated map for class StackedFractions
static const ElementECDelegate::MapEntry s_BESMAP_StackedFractions[] = {
	BESINDEX_StackedFractions_Enable, L"Enable", NULL_MAP,
	BESINDEX_StackedFractions_Type, L"Type", NULL_MAP,
	BESINDEX_StackedFractions_Alignment, L"Alignment", NULL_MAP,
	BESINDEX_StackedFractions_Scale, L"Scale", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class Primary
enum PrimaryPropertyIndex {
	BESINDEX_Primary_UseWorkingUnits = 1,
	BESINDEX_Primary_LabelFormat = 2,
	BESINDEX_Primary_MasterUnits = 3,
	BESINDEX_Primary_SubUnits = 4,
	BESINDEX_Primary_MuLabel = 5,
	BESINDEX_Primary_SuLabel = 6,
	BESINDEX_Primary_Accuracy = 7,
	BESINDEX_Primary_RetainFraction = 8,
	BESINDEX_Primary_LeadingZero = 9,
	BESINDEX_Primary_TrailingZeros = 10,
	BESINDEX_Primary_ShowZeroMasterUnit = 11,
	BESINDEX_Primary_ShowZeroSubUnit = 12,
	BESINDEX_Primary_MainPrefix = 13,
	BESINDEX_Primary_UpperPrefix = 14,
	BESINDEX_Primary_MainSuffix = 15,
	BESINDEX_Primary_UpperSuffix = 16,
	BESINDEX_Primary_SpaceAfterFraction = 17,
};

// Autogenerated map for class Primary
static const ElementECDelegate::MapEntry s_BESMAP_Primary[] = {
	BESINDEX_Primary_UseWorkingUnits, L"UseWorkingUnits", NULL_MAP,
	BESINDEX_Primary_LabelFormat, L"LabelFormat", NULL_MAP,
	BESINDEX_Primary_MasterUnits, L"MasterUnits", NULL_MAP,
	BESINDEX_Primary_SubUnits, L"SubUnits", NULL_MAP,
	BESINDEX_Primary_MuLabel, L"MuLabel", NULL_MAP,
	BESINDEX_Primary_SuLabel, L"SuLabel", NULL_MAP,
	BESINDEX_Primary_Accuracy, L"Accuracy", NULL_MAP,
	BESINDEX_Primary_RetainFraction, L"RetainFraction", NULL_MAP,
	BESINDEX_Primary_LeadingZero, L"LeadingZero", NULL_MAP,
	BESINDEX_Primary_TrailingZeros, L"TrailingZeros", NULL_MAP,
	BESINDEX_Primary_ShowZeroMasterUnit, L"ShowZeroMasterUnit", NULL_MAP,
	BESINDEX_Primary_ShowZeroSubUnit, L"ShowZeroSubUnit", NULL_MAP,
	BESINDEX_Primary_MainPrefix, L"MainPrefix", NULL_MAP,
	BESINDEX_Primary_UpperPrefix, L"UpperPrefix", NULL_MAP,
	BESINDEX_Primary_MainSuffix, L"MainSuffix", NULL_MAP,
	BESINDEX_Primary_UpperSuffix, L"UpperSuffix", NULL_MAP,
	BESINDEX_Primary_SpaceAfterFraction, L"SpaceAfterFraction", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class PrimaryAlternate
enum PrimaryAlternatePropertyIndex {
	BESINDEX_PrimaryAlternate_Enable = 1,
	BESINDEX_PrimaryAlternate_ThresholdComparison = 2,
	BESINDEX_PrimaryAlternate_Threshold = 3,
	BESINDEX_PrimaryAlternate_Accuracy = 4,
	BESINDEX_PrimaryAlternate_RetainFraction = 5,
	BESINDEX_PrimaryAlternate_LabelFormat = 6,
	BESINDEX_PrimaryAlternate_ShowZeroMasterUnit = 7,
	BESINDEX_PrimaryAlternate_ShowZeroSubUnit = 8,
};

// Autogenerated map for class PrimaryAlternate
static const ElementECDelegate::MapEntry s_BESMAP_PrimaryAlternate[] = {
	BESINDEX_PrimaryAlternate_Enable, L"Enable", NULL_MAP,
	BESINDEX_PrimaryAlternate_ThresholdComparison, L"ThresholdComparison", NULL_MAP,
	BESINDEX_PrimaryAlternate_Threshold, L"Threshold", NULL_MAP,
	BESINDEX_PrimaryAlternate_Accuracy, L"Accuracy", NULL_MAP,
	BESINDEX_PrimaryAlternate_RetainFraction, L"RetainFraction", NULL_MAP,
	BESINDEX_PrimaryAlternate_LabelFormat, L"LabelFormat", NULL_MAP,
	BESINDEX_PrimaryAlternate_ShowZeroMasterUnit, L"ShowZeroMasterUnit", NULL_MAP,
	BESINDEX_PrimaryAlternate_ShowZeroSubUnit, L"ShowZeroSubUnit", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class Secondary
enum SecondaryPropertyIndex {
	BESINDEX_Secondary_Enable = 1,
	BESINDEX_Secondary_LabelFormat = 2,
	BESINDEX_Secondary_MasterUnits = 3,
	BESINDEX_Secondary_SubUnits = 4,
	BESINDEX_Secondary_MuLabel = 5,
	BESINDEX_Secondary_SuLabel = 6,
	BESINDEX_Secondary_Accuracy = 7,
	BESINDEX_Secondary_RetainFraction = 8,
	BESINDEX_Secondary_LeadingZero = 9,
	BESINDEX_Secondary_TrailingZeros = 10,
	BESINDEX_Secondary_ShowZeroMasterUnit = 11,
	BESINDEX_Secondary_ShowZeroSubUnit = 12,
	BESINDEX_Secondary_Prefix = 13,
	BESINDEX_Secondary_Suffix = 14,
};

// Autogenerated map for class Secondary
static const ElementECDelegate::MapEntry s_BESMAP_Secondary[] = {
	BESINDEX_Secondary_Enable, L"Enable", NULL_MAP,
	BESINDEX_Secondary_LabelFormat, L"LabelFormat", NULL_MAP,
	BESINDEX_Secondary_MasterUnits, L"MasterUnits", NULL_MAP,
	BESINDEX_Secondary_SubUnits, L"SubUnits", NULL_MAP,
	BESINDEX_Secondary_MuLabel, L"MuLabel", NULL_MAP,
	BESINDEX_Secondary_SuLabel, L"SuLabel", NULL_MAP,
	BESINDEX_Secondary_Accuracy, L"Accuracy", NULL_MAP,
	BESINDEX_Secondary_RetainFraction, L"RetainFraction", NULL_MAP,
	BESINDEX_Secondary_LeadingZero, L"LeadingZero", NULL_MAP,
	BESINDEX_Secondary_TrailingZeros, L"TrailingZeros", NULL_MAP,
	BESINDEX_Secondary_ShowZeroMasterUnit, L"ShowZeroMasterUnit", NULL_MAP,
	BESINDEX_Secondary_ShowZeroSubUnit, L"ShowZeroSubUnit", NULL_MAP,
	BESINDEX_Secondary_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_Secondary_Suffix, L"Suffix", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class SecondaryAlternate
enum SecondaryAlternatePropertyIndex {
	BESINDEX_SecondaryAlternate_Enable = 1,
	BESINDEX_SecondaryAlternate_ThresholdComparison = 2,
	BESINDEX_SecondaryAlternate_Threshold = 3,
	BESINDEX_SecondaryAlternate_Accuracy = 4,
	BESINDEX_SecondaryAlternate_RetainFraction = 5,
	BESINDEX_SecondaryAlternate_LabelFormat = 6,
	BESINDEX_SecondaryAlternate_ShowZeroMasterUnit = 7,
	BESINDEX_SecondaryAlternate_ShowZeroSubUnit = 8,
};

// Autogenerated map for class SecondaryAlternate
static const ElementECDelegate::MapEntry s_BESMAP_SecondaryAlternate[] = {
	BESINDEX_SecondaryAlternate_Enable, L"Enable", NULL_MAP,
	BESINDEX_SecondaryAlternate_ThresholdComparison, L"ThresholdComparison", NULL_MAP,
	BESINDEX_SecondaryAlternate_Threshold, L"Threshold", NULL_MAP,
	BESINDEX_SecondaryAlternate_Accuracy, L"Accuracy", NULL_MAP,
	BESINDEX_SecondaryAlternate_RetainFraction, L"RetainFraction", NULL_MAP,
	BESINDEX_SecondaryAlternate_LabelFormat, L"LabelFormat", NULL_MAP,
	BESINDEX_SecondaryAlternate_ShowZeroMasterUnit, L"ShowZeroMasterUnit", NULL_MAP,
	BESINDEX_SecondaryAlternate_ShowZeroSubUnit, L"ShowZeroSubUnit", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class DINDimensioning
enum DINDimensioningPropertyIndex {
	BESINDEX_DINDimensioning_Superscript = 1,
	BESINDEX_DINDimensioning_SuperscriptChar = 2,
	BESINDEX_DINDimensioning_Rounding = 3,
};

// Autogenerated map for class DINDimensioning
static const ElementECDelegate::MapEntry s_BESMAP_DINDimensioning[] = {
	BESINDEX_DINDimensioning_Superscript, L"Superscript", NULL_MAP,
	BESINDEX_DINDimensioning_SuperscriptChar, L"SuperscriptChar", NULL_MAP,
	BESINDEX_DINDimensioning_Rounding, L"Rounding", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class Units
enum UnitsPropertyIndex {
	BESINDEX_Units_Angle = 1,
	BESINDEX_Units_Metric = 7,
	BESINDEX_Units_StackedFractions = 10,
	BESINDEX_Units_Primary = 15,
	BESINDEX_Units_PrimaryAlternate = 33,
	BESINDEX_Units_Secondary = 42,
	BESINDEX_Units_SecondaryAlternate = 57,
	BESINDEX_Units_DINDimensioning = 66,
	BESINDEX_Units_ScaleFactor = 70,
};

// Autogenerated map for class Units
static const ElementECDelegate::MapEntry s_BESMAP_Units[] = {
	BESINDEX_Units_Angle, L"Angle", s_BESMAP_Angle,
	BESINDEX_Units_Metric, L"Metric", s_BESMAP_Metric,
	BESINDEX_Units_StackedFractions, L"StackedFractions", s_BESMAP_StackedFractions,
	BESINDEX_Units_Primary, L"Primary", s_BESMAP_Primary,
	BESINDEX_Units_PrimaryAlternate, L"PrimaryAlternate", s_BESMAP_PrimaryAlternate,
	BESINDEX_Units_Secondary, L"Secondary", s_BESMAP_Secondary,
	BESINDEX_Units_SecondaryAlternate, L"SecondaryAlternate", s_BESMAP_SecondaryAlternate,
	BESINDEX_Units_DINDimensioning, L"DINDimensioning", s_BESMAP_DINDimensioning,
	BESINDEX_Units_ScaleFactor, L"ScaleFactor", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class DimensionLines
enum DimensionLinesPropertyIndex {
	BESINDEX_DimensionLines_StackOffset = 1,
	BESINDEX_DimensionLines_Color = 2,
	BESINDEX_DimensionLines_LineStyle = 3,
	BESINDEX_DimensionLines_Weight = 4,
};

// Autogenerated map for class DimensionLines
static const ElementECDelegate::MapEntry s_BESMAP_DimensionLines[] = {
	BESINDEX_DimensionLines_StackOffset, L"StackOffset", NULL_MAP,
	BESINDEX_DimensionLines_Color, L"Color", NULL_MAP,
	BESINDEX_DimensionLines_LineStyle, L"LineStyle", NULL_MAP,
	BESINDEX_DimensionLines_Weight, L"Weight", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class ExtensionLines
enum ExtensionLinesPropertyIndex {
	BESINDEX_ExtensionLines_Enable = 1,
	BESINDEX_ExtensionLines_Color = 2,
	BESINDEX_ExtensionLines_LineStyle = 3,
	BESINDEX_ExtensionLines_Weight = 4,
	BESINDEX_ExtensionLines_Offset = 5,
	BESINDEX_ExtensionLines_Extension = 6,
	BESINDEX_ExtensionLines_JoinWhenTextOutside = 7,
};

// Autogenerated map for class ExtensionLines
static const ElementECDelegate::MapEntry s_BESMAP_ExtensionLines[] = {
	BESINDEX_ExtensionLines_Enable, L"Enable", NULL_MAP,
	BESINDEX_ExtensionLines_Color, L"Color", NULL_MAP,
	BESINDEX_ExtensionLines_LineStyle, L"LineStyle", NULL_MAP,
	BESINDEX_ExtensionLines_Weight, L"Weight", NULL_MAP,
	BESINDEX_ExtensionLines_Offset, L"Offset", NULL_MAP,
	BESINDEX_ExtensionLines_Extension, L"Extension", NULL_MAP,
	BESINDEX_ExtensionLines_JoinWhenTextOutside, L"JoinWhenTextOutside", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class Terminators
enum TerminatorsPropertyIndex {
	BESINDEX_Terminators_Arrowhead = 1,
	BESINDEX_Terminators_Width = 2,
	BESINDEX_Terminators_Height = 3,
	BESINDEX_Terminators_Color = 4,
	BESINDEX_Terminators_LineStyle = 5,
	BESINDEX_Terminators_Weight = 6,
	BESINDEX_Terminators_UniformCellScale = 7,
};

// Autogenerated map for class Terminators
static const ElementECDelegate::MapEntry s_BESMAP_Terminators[] = {
	BESINDEX_Terminators_Arrowhead, L"Arrowhead", NULL_MAP,
	BESINDEX_Terminators_Width, L"Width", NULL_MAP,
	BESINDEX_Terminators_Height, L"Height", NULL_MAP,
	BESINDEX_Terminators_Color, L"Color", NULL_MAP,
	BESINDEX_Terminators_LineStyle, L"LineStyle", NULL_MAP,
	BESINDEX_Terminators_Weight, L"Weight", NULL_MAP,
	BESINDEX_Terminators_UniformCellScale, L"UniformCellScale", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class FitOptions
enum FitOptionsPropertyIndex {
	BESINDEX_FitOptions_FitOption = 1,
	BESINDEX_FitOptions_InsideMinLeader = 2,
	BESINDEX_FitOptions_SuppressUnfitTerms = 3,
	BESINDEX_FitOptions_TightFitTextAbove = 4,
	BESINDEX_FitOptions_FitInclinedTextBox = 5,
	BESINDEX_FitOptions_ExtendDimUnderline = 6,
};

// Autogenerated map for class FitOptions
static const ElementECDelegate::MapEntry s_BESMAP_FitOptions[] = {
	BESINDEX_FitOptions_FitOption, L"FitOption", NULL_MAP,
	BESINDEX_FitOptions_InsideMinLeader, L"InsideMinLeader", NULL_MAP,
	BESINDEX_FitOptions_SuppressUnfitTerms, L"SuppressUnfitTerms", NULL_MAP,
	BESINDEX_FitOptions_TightFitTextAbove, L"TightFitTextAbove", NULL_MAP,
	BESINDEX_FitOptions_FitInclinedTextBox, L"FitInclinedTextBox", NULL_MAP,
	BESINDEX_FitOptions_ExtendDimUnderline, L"ExtendDimUnderline", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class Graphics
enum GraphicsPropertyIndex {
	BESINDEX_Graphics_DimensionLines = 1,
	BESINDEX_Graphics_ExtensionLines = 6,
	BESINDEX_Graphics_Terminators = 14,
	BESINDEX_Graphics_FitOptions = 22,
};

// Autogenerated map for class Graphics
static const ElementECDelegate::MapEntry s_BESMAP_Graphics[] = {
	BESINDEX_Graphics_DimensionLines, L"DimensionLines", s_BESMAP_DimensionLines,
	BESINDEX_Graphics_ExtensionLines, L"ExtensionLines", s_BESMAP_ExtensionLines,
	BESINDEX_Graphics_Terminators, L"Terminators", s_BESMAP_Terminators,
	BESINDEX_Graphics_FitOptions, L"FitOptions", s_BESMAP_FitOptions,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class Format
enum FormatPropertyIndex {
	BESINDEX_Format_Orientation = 1,
	BESINDEX_Format_Location = 2,
	BESINDEX_Format_DimJustification = 3,
	BESINDEX_Format_Frame = 4,
	BESINDEX_Format_LeftMargin = 5,
	BESINDEX_Format_LowerMargin = 6,
	BESINDEX_Format_InlineLeft = 7,
	BESINDEX_Format_LabelLineFormat = 8,
};

// Autogenerated map for class Format
static const ElementECDelegate::MapEntry s_BESMAP_Format[] = {
	BESINDEX_Format_Orientation, L"Orientation", NULL_MAP,
	BESINDEX_Format_Location, L"Location", NULL_MAP,
	BESINDEX_Format_DimJustification, L"DimJustification", NULL_MAP,
	BESINDEX_Format_Frame, L"Frame", NULL_MAP,
	BESINDEX_Format_LeftMargin, L"LeftMargin", NULL_MAP,
	BESINDEX_Format_LowerMargin, L"LowerMargin", NULL_MAP,
	BESINDEX_Format_InlineLeft, L"InlineLeft", NULL_MAP,
	BESINDEX_Format_LabelLineFormat, L"LabelLineFormat", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class Style
enum StylePropertyIndex {
	BESINDEX_Style_TextStyle = 1,
	BESINDEX_Style_Color = 2,
	BESINDEX_Style_Weight = 3,
	BESINDEX_Style_Font = 4,
	BESINDEX_Style_Height = 5,
	BESINDEX_Style_Width = 6,
	BESINDEX_Style_Underline = 7,
};

// Autogenerated map for class Style
static const ElementECDelegate::MapEntry s_BESMAP_Style[] = {
	BESINDEX_Style_TextStyle, L"TextStyle", NULL_MAP,
	BESINDEX_Style_Color, L"Color", NULL_MAP,
	BESINDEX_Style_Weight, L"Weight", NULL_MAP,
	BESINDEX_Style_Font, L"Font", NULL_MAP,
	BESINDEX_Style_Height, L"Height", NULL_MAP,
	BESINDEX_Style_Width, L"Width", NULL_MAP,
	BESINDEX_Style_Underline, L"Underline", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class DimWithLeader
enum DimWithLeaderPropertyIndex {
	BESINDEX_DimWithLeader_Mode = 1,
	BESINDEX_DimWithLeader_LeaderType = 2,
	BESINDEX_DimWithLeader_Terminator = 3,
	BESINDEX_DimWithLeader_Alignment = 4,
	BESINDEX_DimWithLeader_InlineLeader = 5,
	BESINDEX_DimWithLeader_NoTextDock = 6,
	BESINDEX_DimWithLeader_LeaderLength = 7,
};

// Autogenerated map for class DimWithLeader
static const ElementECDelegate::MapEntry s_BESMAP_DimWithLeader[] = {
	BESINDEX_DimWithLeader_Mode, L"Mode", NULL_MAP,
	BESINDEX_DimWithLeader_LeaderType, L"LeaderType", NULL_MAP,
	BESINDEX_DimWithLeader_Terminator, L"Terminator", NULL_MAP,
	BESINDEX_DimWithLeader_Alignment, L"Alignment", NULL_MAP,
	BESINDEX_DimWithLeader_InlineLeader, L"InlineLeader", NULL_MAP,
	BESINDEX_DimWithLeader_NoTextDock, L"NoTextDock", NULL_MAP,
	BESINDEX_DimWithLeader_LeaderLength, L"LeaderLength", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class Text
enum TextPropertyIndex {
	BESINDEX_Text_Format = 1,
	BESINDEX_Text_Style = 10,
	BESINDEX_Text_DimWithLeader = 18,
};

// Autogenerated map for class Text
static const ElementECDelegate::MapEntry s_BESMAP_Text[] = {
	BESINDEX_Text_Format, L"Format", s_BESMAP_Format,
	BESINDEX_Text_Style, L"Style", s_BESMAP_Style,
	BESINDEX_Text_DimWithLeader, L"DimWithLeader", s_BESMAP_DimWithLeader,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class Notes
enum NotesPropertyIndex {
	BESINDEX_Notes_LeaderType = 1,
	BESINDEX_Notes_Terminator = 2,
	BESINDEX_Notes_Frame = 3,
	BESINDEX_Notes_InlineLeader = 4,
	BESINDEX_Notes_LeaderLength = 5,
	BESINDEX_Notes_LeftMargin = 6,
	BESINDEX_Notes_LowerMargin = 7,
	BESINDEX_Notes_TextRotation = 8,
	BESINDEX_Notes_VerticalJust = 9,
	BESINDEX_Notes_DimJust = 10,
	BESINDEX_Notes_HorizontalAttach = 11,
	BESINDEX_Notes_LeftAttach = 12,
	BESINDEX_Notes_RightAttach = 13,
	BESINDEX_Notes_ScaleFrame = 14,
	BESINDEX_Notes_FrameScale = 15,
};

// Autogenerated map for class Notes
static const ElementECDelegate::MapEntry s_BESMAP_Notes[] = {
	BESINDEX_Notes_LeaderType, L"LeaderType", NULL_MAP,
	BESINDEX_Notes_Terminator, L"Terminator", NULL_MAP,
	BESINDEX_Notes_Frame, L"Frame", NULL_MAP,
	BESINDEX_Notes_InlineLeader, L"InlineLeader", NULL_MAP,
	BESINDEX_Notes_LeaderLength, L"LeaderLength", NULL_MAP,
	BESINDEX_Notes_LeftMargin, L"LeftMargin", NULL_MAP,
	BESINDEX_Notes_LowerMargin, L"LowerMargin", NULL_MAP,
	BESINDEX_Notes_TextRotation, L"TextRotation", NULL_MAP,
	BESINDEX_Notes_VerticalJust, L"VerticalJust", NULL_MAP,
	BESINDEX_Notes_DimJust, L"DimJust", NULL_MAP,
	BESINDEX_Notes_HorizontalAttach, L"HorizontalAttach", NULL_MAP,
	BESINDEX_Notes_LeftAttach, L"LeftAttach", NULL_MAP,
	BESINDEX_Notes_RightAttach, L"RightAttach", NULL_MAP,
	BESINDEX_Notes_ScaleFrame, L"ScaleFrame", NULL_MAP,
	BESINDEX_Notes_FrameScale, L"FrameScale", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class ArrowTerm
enum ArrowTermPropertyIndex {
	BESINDEX_ArrowTerm_Type = 1,
	BESINDEX_ArrowTerm_CellName = 2,
	BESINDEX_ArrowTerm_Font = 3,
	BESINDEX_ArrowTerm_Character = 4,
	BESINDEX_ArrowTerm_DimLineThru = 5,
};

// Autogenerated map for class ArrowTerm
static const ElementECDelegate::MapEntry s_BESMAP_ArrowTerm[] = {
	BESINDEX_ArrowTerm_Type, L"Type", NULL_MAP,
	BESINDEX_ArrowTerm_CellName, L"CellName", NULL_MAP,
	BESINDEX_ArrowTerm_Font, L"Font", NULL_MAP,
	BESINDEX_ArrowTerm_Character, L"Character", NULL_MAP,
	BESINDEX_ArrowTerm_DimLineThru, L"DimLineThru", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class StrokeTerm
enum StrokeTermPropertyIndex {
	BESINDEX_StrokeTerm_Type = 1,
	BESINDEX_StrokeTerm_CellName = 2,
	BESINDEX_StrokeTerm_Font = 3,
	BESINDEX_StrokeTerm_Character = 4,
	BESINDEX_StrokeTerm_DimLineThru = 5,
};

// Autogenerated map for class StrokeTerm
static const ElementECDelegate::MapEntry s_BESMAP_StrokeTerm[] = {
	BESINDEX_StrokeTerm_Type, L"Type", NULL_MAP,
	BESINDEX_StrokeTerm_CellName, L"CellName", NULL_MAP,
	BESINDEX_StrokeTerm_Font, L"Font", NULL_MAP,
	BESINDEX_StrokeTerm_Character, L"Character", NULL_MAP,
	BESINDEX_StrokeTerm_DimLineThru, L"DimLineThru", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class OriginTerm
enum OriginTermPropertyIndex {
	BESINDEX_OriginTerm_Type = 1,
	BESINDEX_OriginTerm_CellName = 2,
	BESINDEX_OriginTerm_Font = 3,
	BESINDEX_OriginTerm_Character = 4,
	BESINDEX_OriginTerm_DimLineThru = 5,
};

// Autogenerated map for class OriginTerm
static const ElementECDelegate::MapEntry s_BESMAP_OriginTerm[] = {
	BESINDEX_OriginTerm_Type, L"Type", NULL_MAP,
	BESINDEX_OriginTerm_CellName, L"CellName", NULL_MAP,
	BESINDEX_OriginTerm_Font, L"Font", NULL_MAP,
	BESINDEX_OriginTerm_Character, L"Character", NULL_MAP,
	BESINDEX_OriginTerm_DimLineThru, L"DimLineThru", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class DotTerm
enum DotTermPropertyIndex {
	BESINDEX_DotTerm_Type = 1,
	BESINDEX_DotTerm_CellName = 2,
	BESINDEX_DotTerm_Font = 3,
	BESINDEX_DotTerm_Character = 4,
	BESINDEX_DotTerm_DimLineThru = 5,
};

// Autogenerated map for class DotTerm
static const ElementECDelegate::MapEntry s_BESMAP_DotTerm[] = {
	BESINDEX_DotTerm_Type, L"Type", NULL_MAP,
	BESINDEX_DotTerm_CellName, L"CellName", NULL_MAP,
	BESINDEX_DotTerm_Font, L"Font", NULL_MAP,
	BESINDEX_DotTerm_Character, L"Character", NULL_MAP,
	BESINDEX_DotTerm_DimLineThru, L"DimLineThru", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class NoteTerm
enum NoteTermPropertyIndex {
	BESINDEX_NoteTerm_Type = 1,
	BESINDEX_NoteTerm_CellName = 2,
	BESINDEX_NoteTerm_Font = 3,
	BESINDEX_NoteTerm_Character = 4,
};

// Autogenerated map for class NoteTerm
static const ElementECDelegate::MapEntry s_BESMAP_NoteTerm[] = {
	BESINDEX_NoteTerm_Type, L"Type", NULL_MAP,
	BESINDEX_NoteTerm_CellName, L"CellName", NULL_MAP,
	BESINDEX_NoteTerm_Font, L"Font", NULL_MAP,
	BESINDEX_NoteTerm_Character, L"Character", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class Prefix
enum PrefixPropertyIndex {
	BESINDEX_Prefix_Type = 1,
	BESINDEX_Prefix_CellName = 2,
	BESINDEX_Prefix_Font = 3,
	BESINDEX_Prefix_Character = 4,
};

// Autogenerated map for class Prefix
static const ElementECDelegate::MapEntry s_BESMAP_Prefix[] = {
	BESINDEX_Prefix_Type, L"Type", NULL_MAP,
	BESINDEX_Prefix_CellName, L"CellName", NULL_MAP,
	BESINDEX_Prefix_Font, L"Font", NULL_MAP,
	BESINDEX_Prefix_Character, L"Character", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class Suffix
enum SuffixPropertyIndex {
	BESINDEX_Suffix_Type = 1,
	BESINDEX_Suffix_CellName = 2,
	BESINDEX_Suffix_Font = 3,
	BESINDEX_Suffix_Character = 4,
};

// Autogenerated map for class Suffix
static const ElementECDelegate::MapEntry s_BESMAP_Suffix[] = {
	BESINDEX_Suffix_Type, L"Type", NULL_MAP,
	BESINDEX_Suffix_CellName, L"CellName", NULL_MAP,
	BESINDEX_Suffix_Font, L"Font", NULL_MAP,
	BESINDEX_Suffix_Character, L"Character", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class DiameterSymb
enum DiameterSymbPropertyIndex {
	BESINDEX_DiameterSymb_Type = 1,
	BESINDEX_DiameterSymb_Font = 2,
	BESINDEX_DiameterSymb_Character = 3,
};

// Autogenerated map for class DiameterSymb
static const ElementECDelegate::MapEntry s_BESMAP_DiameterSymb[] = {
	BESINDEX_DiameterSymb_Type, L"Type", NULL_MAP,
	BESINDEX_DiameterSymb_Font, L"Font", NULL_MAP,
	BESINDEX_DiameterSymb_Character, L"Character", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class PlusMinus
enum PlusMinusPropertyIndex {
	BESINDEX_PlusMinus_Type = 1,
	BESINDEX_PlusMinus_Character = 2,
};

// Autogenerated map for class PlusMinus
static const ElementECDelegate::MapEntry s_BESMAP_PlusMinus[] = {
	BESINDEX_PlusMinus_Type, L"Type", NULL_MAP,
	BESINDEX_PlusMinus_Character, L"Character", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class Symbols
enum SymbolsPropertyIndex {
	BESINDEX_Symbols_ArrowTerm = 1,
	BESINDEX_Symbols_StrokeTerm = 7,
	BESINDEX_Symbols_OriginTerm = 13,
	BESINDEX_Symbols_DotTerm = 19,
	BESINDEX_Symbols_NoteTerm = 25,
	BESINDEX_Symbols_Prefix = 30,
	BESINDEX_Symbols_Suffix = 35,
	BESINDEX_Symbols_DiameterSymb = 40,
	BESINDEX_Symbols_PlusMinus = 44,
};

// Autogenerated map for class Symbols
static const ElementECDelegate::MapEntry s_BESMAP_Symbols[] = {
	BESINDEX_Symbols_ArrowTerm, L"ArrowTerm", s_BESMAP_ArrowTerm,
	BESINDEX_Symbols_StrokeTerm, L"StrokeTerm", s_BESMAP_StrokeTerm,
	BESINDEX_Symbols_OriginTerm, L"OriginTerm", s_BESMAP_OriginTerm,
	BESINDEX_Symbols_DotTerm, L"DotTerm", s_BESMAP_DotTerm,
	BESINDEX_Symbols_NoteTerm, L"NoteTerm", s_BESMAP_NoteTerm,
	BESINDEX_Symbols_Prefix, L"Prefix", s_BESMAP_Prefix,
	BESINDEX_Symbols_Suffix, L"Suffix", s_BESMAP_Suffix,
	BESINDEX_Symbols_DiameterSymb, L"DiameterSymb", s_BESMAP_DiameterSymb,
	BESINDEX_Symbols_PlusMinus, L"PlusMinus", s_BESMAP_PlusMinus,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class SizeArrow
enum SizeArrowPropertyIndex {
	BESINDEX_SizeArrow_LeftTerminator = 1,
	BESINDEX_SizeArrow_RightTerminator = 2,
	BESINDEX_SizeArrow_FirstTerminator = 3,
	BESINDEX_SizeArrow_JointTerminator = 4,
	BESINDEX_SizeArrow_LeftExtension = 5,
	BESINDEX_SizeArrow_RightExtension = 6,
	BESINDEX_SizeArrow_StackDimensions = 7,
	BESINDEX_SizeArrow_ArcSymbol = 8,
	BESINDEX_SizeArrow_Prefix = 9,
	BESINDEX_SizeArrow_Suffix = 10,
	BESINDEX_SizeArrow_Text = 11,
};

// Autogenerated map for class SizeArrow
static const ElementECDelegate::MapEntry s_BESMAP_SizeArrow[] = {
	BESINDEX_SizeArrow_LeftTerminator, L"LeftTerminator", NULL_MAP,
	BESINDEX_SizeArrow_RightTerminator, L"RightTerminator", NULL_MAP,
	BESINDEX_SizeArrow_FirstTerminator, L"FirstTerminator", NULL_MAP,
	BESINDEX_SizeArrow_JointTerminator, L"JointTerminator", NULL_MAP,
	BESINDEX_SizeArrow_LeftExtension, L"LeftExtension", NULL_MAP,
	BESINDEX_SizeArrow_RightExtension, L"RightExtension", NULL_MAP,
	BESINDEX_SizeArrow_StackDimensions, L"StackDimensions", NULL_MAP,
	BESINDEX_SizeArrow_ArcSymbol, L"ArcSymbol", NULL_MAP,
	BESINDEX_SizeArrow_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_SizeArrow_Suffix, L"Suffix", NULL_MAP,
	BESINDEX_SizeArrow_Text, L"Text", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class SizeStroke
enum SizeStrokePropertyIndex {
	BESINDEX_SizeStroke_LeftTerminator = 1,
	BESINDEX_SizeStroke_RightTerminator = 2,
	BESINDEX_SizeStroke_FirstTerminator = 3,
	BESINDEX_SizeStroke_JointTerminator = 4,
	BESINDEX_SizeStroke_LeftExtension = 5,
	BESINDEX_SizeStroke_RightExtension = 6,
	BESINDEX_SizeStroke_StackDimensions = 7,
	BESINDEX_SizeStroke_ArcSymbol = 8,
	BESINDEX_SizeStroke_Prefix = 9,
	BESINDEX_SizeStroke_Suffix = 10,
	BESINDEX_SizeStroke_Text = 11,
};

// Autogenerated map for class SizeStroke
static const ElementECDelegate::MapEntry s_BESMAP_SizeStroke[] = {
	BESINDEX_SizeStroke_LeftTerminator, L"LeftTerminator", NULL_MAP,
	BESINDEX_SizeStroke_RightTerminator, L"RightTerminator", NULL_MAP,
	BESINDEX_SizeStroke_FirstTerminator, L"FirstTerminator", NULL_MAP,
	BESINDEX_SizeStroke_JointTerminator, L"JointTerminator", NULL_MAP,
	BESINDEX_SizeStroke_LeftExtension, L"LeftExtension", NULL_MAP,
	BESINDEX_SizeStroke_RightExtension, L"RightExtension", NULL_MAP,
	BESINDEX_SizeStroke_StackDimensions, L"StackDimensions", NULL_MAP,
	BESINDEX_SizeStroke_ArcSymbol, L"ArcSymbol", NULL_MAP,
	BESINDEX_SizeStroke_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_SizeStroke_Suffix, L"Suffix", NULL_MAP,
	BESINDEX_SizeStroke_Text, L"Text", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class SingleLocation
enum SingleLocationPropertyIndex {
	BESINDEX_SingleLocation_LeftTerminator = 1,
	BESINDEX_SingleLocation_RightTerminator = 2,
	BESINDEX_SingleLocation_FirstTerminator = 3,
	BESINDEX_SingleLocation_JointTerminator = 4,
	BESINDEX_SingleLocation_LeftExtension = 5,
	BESINDEX_SingleLocation_RightExtension = 6,
	BESINDEX_SingleLocation_StackDimensions = 7,
	BESINDEX_SingleLocation_ArcSymbol = 8,
	BESINDEX_SingleLocation_Prefix = 9,
	BESINDEX_SingleLocation_Suffix = 10,
	BESINDEX_SingleLocation_Text = 11,
};

// Autogenerated map for class SingleLocation
static const ElementECDelegate::MapEntry s_BESMAP_SingleLocation[] = {
	BESINDEX_SingleLocation_LeftTerminator, L"LeftTerminator", NULL_MAP,
	BESINDEX_SingleLocation_RightTerminator, L"RightTerminator", NULL_MAP,
	BESINDEX_SingleLocation_FirstTerminator, L"FirstTerminator", NULL_MAP,
	BESINDEX_SingleLocation_JointTerminator, L"JointTerminator", NULL_MAP,
	BESINDEX_SingleLocation_LeftExtension, L"LeftExtension", NULL_MAP,
	BESINDEX_SingleLocation_RightExtension, L"RightExtension", NULL_MAP,
	BESINDEX_SingleLocation_StackDimensions, L"StackDimensions", NULL_MAP,
	BESINDEX_SingleLocation_ArcSymbol, L"ArcSymbol", NULL_MAP,
	BESINDEX_SingleLocation_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_SingleLocation_Suffix, L"Suffix", NULL_MAP,
	BESINDEX_SingleLocation_Text, L"Text", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class StackedLocation
enum StackedLocationPropertyIndex {
	BESINDEX_StackedLocation_LeftTerminator = 1,
	BESINDEX_StackedLocation_RightTerminator = 2,
	BESINDEX_StackedLocation_FirstTerminator = 3,
	BESINDEX_StackedLocation_JointTerminator = 4,
	BESINDEX_StackedLocation_LeftExtension = 5,
	BESINDEX_StackedLocation_RightExtension = 6,
	BESINDEX_StackedLocation_StackDimensions = 7,
	BESINDEX_StackedLocation_ArcSymbol = 8,
	BESINDEX_StackedLocation_Prefix = 9,
	BESINDEX_StackedLocation_Suffix = 10,
	BESINDEX_StackedLocation_Text = 11,
};

// Autogenerated map for class StackedLocation
static const ElementECDelegate::MapEntry s_BESMAP_StackedLocation[] = {
	BESINDEX_StackedLocation_LeftTerminator, L"LeftTerminator", NULL_MAP,
	BESINDEX_StackedLocation_RightTerminator, L"RightTerminator", NULL_MAP,
	BESINDEX_StackedLocation_FirstTerminator, L"FirstTerminator", NULL_MAP,
	BESINDEX_StackedLocation_JointTerminator, L"JointTerminator", NULL_MAP,
	BESINDEX_StackedLocation_LeftExtension, L"LeftExtension", NULL_MAP,
	BESINDEX_StackedLocation_RightExtension, L"RightExtension", NULL_MAP,
	BESINDEX_StackedLocation_StackDimensions, L"StackDimensions", NULL_MAP,
	BESINDEX_StackedLocation_ArcSymbol, L"ArcSymbol", NULL_MAP,
	BESINDEX_StackedLocation_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_StackedLocation_Suffix, L"Suffix", NULL_MAP,
	BESINDEX_StackedLocation_Text, L"Text", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class AngleSize
enum AngleSizePropertyIndex {
	BESINDEX_AngleSize_LeftTerminator = 1,
	BESINDEX_AngleSize_RightTerminator = 2,
	BESINDEX_AngleSize_LeftExtension = 3,
	BESINDEX_AngleSize_RightExtension = 4,
	BESINDEX_AngleSize_StackDimensions = 5,
	BESINDEX_AngleSize_ArcSymbol = 6,
	BESINDEX_AngleSize_Prefix = 7,
	BESINDEX_AngleSize_Suffix = 8,
};

// Autogenerated map for class AngleSize
static const ElementECDelegate::MapEntry s_BESMAP_AngleSize[] = {
	BESINDEX_AngleSize_LeftTerminator, L"LeftTerminator", NULL_MAP,
	BESINDEX_AngleSize_RightTerminator, L"RightTerminator", NULL_MAP,
	BESINDEX_AngleSize_LeftExtension, L"LeftExtension", NULL_MAP,
	BESINDEX_AngleSize_RightExtension, L"RightExtension", NULL_MAP,
	BESINDEX_AngleSize_StackDimensions, L"StackDimensions", NULL_MAP,
	BESINDEX_AngleSize_ArcSymbol, L"ArcSymbol", NULL_MAP,
	BESINDEX_AngleSize_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_AngleSize_Suffix, L"Suffix", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class ArcSize
enum ArcSizePropertyIndex {
	BESINDEX_ArcSize_LeftTerminator = 1,
	BESINDEX_ArcSize_RightTerminator = 2,
	BESINDEX_ArcSize_LeftExtension = 3,
	BESINDEX_ArcSize_RightExtension = 4,
	BESINDEX_ArcSize_StackDimensions = 5,
	BESINDEX_ArcSize_ArcSymbol = 6,
	BESINDEX_ArcSize_ChordAlign = 7,
	BESINDEX_ArcSize_Prefix = 8,
	BESINDEX_ArcSize_Suffix = 9,
};

// Autogenerated map for class ArcSize
static const ElementECDelegate::MapEntry s_BESMAP_ArcSize[] = {
	BESINDEX_ArcSize_LeftTerminator, L"LeftTerminator", NULL_MAP,
	BESINDEX_ArcSize_RightTerminator, L"RightTerminator", NULL_MAP,
	BESINDEX_ArcSize_LeftExtension, L"LeftExtension", NULL_MAP,
	BESINDEX_ArcSize_RightExtension, L"RightExtension", NULL_MAP,
	BESINDEX_ArcSize_StackDimensions, L"StackDimensions", NULL_MAP,
	BESINDEX_ArcSize_ArcSymbol, L"ArcSymbol", NULL_MAP,
	BESINDEX_ArcSize_ChordAlign, L"ChordAlign", NULL_MAP,
	BESINDEX_ArcSize_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_ArcSize_Suffix, L"Suffix", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class AngleLocation
enum AngleLocationPropertyIndex {
	BESINDEX_AngleLocation_LeftTerminator = 1,
	BESINDEX_AngleLocation_RightTerminator = 2,
	BESINDEX_AngleLocation_FirstTerminator = 3,
	BESINDEX_AngleLocation_LeftExtension = 4,
	BESINDEX_AngleLocation_RightExtension = 5,
	BESINDEX_AngleLocation_StackDimensions = 6,
	BESINDEX_AngleLocation_ArcSymbol = 7,
	BESINDEX_AngleLocation_Prefix = 8,
	BESINDEX_AngleLocation_Suffix = 9,
};

// Autogenerated map for class AngleLocation
static const ElementECDelegate::MapEntry s_BESMAP_AngleLocation[] = {
	BESINDEX_AngleLocation_LeftTerminator, L"LeftTerminator", NULL_MAP,
	BESINDEX_AngleLocation_RightTerminator, L"RightTerminator", NULL_MAP,
	BESINDEX_AngleLocation_FirstTerminator, L"FirstTerminator", NULL_MAP,
	BESINDEX_AngleLocation_LeftExtension, L"LeftExtension", NULL_MAP,
	BESINDEX_AngleLocation_RightExtension, L"RightExtension", NULL_MAP,
	BESINDEX_AngleLocation_StackDimensions, L"StackDimensions", NULL_MAP,
	BESINDEX_AngleLocation_ArcSymbol, L"ArcSymbol", NULL_MAP,
	BESINDEX_AngleLocation_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_AngleLocation_Suffix, L"Suffix", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class ArcLocation
enum ArcLocationPropertyIndex {
	BESINDEX_ArcLocation_LeftTerminator = 1,
	BESINDEX_ArcLocation_RightTerminator = 2,
	BESINDEX_ArcLocation_FirstTerminator = 3,
	BESINDEX_ArcLocation_LeftExtension = 4,
	BESINDEX_ArcLocation_RightExtension = 5,
	BESINDEX_ArcLocation_StackDimensions = 6,
	BESINDEX_ArcLocation_ArcSymbol = 7,
	BESINDEX_ArcLocation_Prefix = 8,
	BESINDEX_ArcLocation_Suffix = 9,
};

// Autogenerated map for class ArcLocation
static const ElementECDelegate::MapEntry s_BESMAP_ArcLocation[] = {
	BESINDEX_ArcLocation_LeftTerminator, L"LeftTerminator", NULL_MAP,
	BESINDEX_ArcLocation_RightTerminator, L"RightTerminator", NULL_MAP,
	BESINDEX_ArcLocation_FirstTerminator, L"FirstTerminator", NULL_MAP,
	BESINDEX_ArcLocation_LeftExtension, L"LeftExtension", NULL_MAP,
	BESINDEX_ArcLocation_RightExtension, L"RightExtension", NULL_MAP,
	BESINDEX_ArcLocation_StackDimensions, L"StackDimensions", NULL_MAP,
	BESINDEX_ArcLocation_ArcSymbol, L"ArcSymbol", NULL_MAP,
	BESINDEX_ArcLocation_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_ArcLocation_Suffix, L"Suffix", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class AngleLines
enum AngleLinesPropertyIndex {
	BESINDEX_AngleLines_LeftTerminator = 1,
	BESINDEX_AngleLines_RightTerminator = 2,
	BESINDEX_AngleLines_LeftExtension = 3,
	BESINDEX_AngleLines_RightExtension = 4,
	BESINDEX_AngleLines_StackDimensions = 5,
	BESINDEX_AngleLines_ArcSymbol = 6,
	BESINDEX_AngleLines_Prefix = 7,
	BESINDEX_AngleLines_Suffix = 8,
};

// Autogenerated map for class AngleLines
static const ElementECDelegate::MapEntry s_BESMAP_AngleLines[] = {
	BESINDEX_AngleLines_LeftTerminator, L"LeftTerminator", NULL_MAP,
	BESINDEX_AngleLines_RightTerminator, L"RightTerminator", NULL_MAP,
	BESINDEX_AngleLines_LeftExtension, L"LeftExtension", NULL_MAP,
	BESINDEX_AngleLines_RightExtension, L"RightExtension", NULL_MAP,
	BESINDEX_AngleLines_StackDimensions, L"StackDimensions", NULL_MAP,
	BESINDEX_AngleLines_ArcSymbol, L"ArcSymbol", NULL_MAP,
	BESINDEX_AngleLines_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_AngleLines_Suffix, L"Suffix", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class AngleAxis
enum AngleAxisPropertyIndex {
	BESINDEX_AngleAxis_LeftTerminator = 1,
	BESINDEX_AngleAxis_RightTerminator = 2,
	BESINDEX_AngleAxis_LeftExtension = 3,
	BESINDEX_AngleAxis_RightExtension = 4,
	BESINDEX_AngleAxis_StackDimensions = 5,
	BESINDEX_AngleAxis_ArcSymbol = 6,
	BESINDEX_AngleAxis_Prefix = 7,
	BESINDEX_AngleAxis_Suffix = 8,
};

// Autogenerated map for class AngleAxis
static const ElementECDelegate::MapEntry s_BESMAP_AngleAxis[] = {
	BESINDEX_AngleAxis_LeftTerminator, L"LeftTerminator", NULL_MAP,
	BESINDEX_AngleAxis_RightTerminator, L"RightTerminator", NULL_MAP,
	BESINDEX_AngleAxis_LeftExtension, L"LeftExtension", NULL_MAP,
	BESINDEX_AngleAxis_RightExtension, L"RightExtension", NULL_MAP,
	BESINDEX_AngleAxis_StackDimensions, L"StackDimensions", NULL_MAP,
	BESINDEX_AngleAxis_ArcSymbol, L"ArcSymbol", NULL_MAP,
	BESINDEX_AngleAxis_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_AngleAxis_Suffix, L"Suffix", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class Radius
enum RadiusPropertyIndex {
	BESINDEX_Radius_Leader = 1,
	BESINDEX_Radius_StackDimensions = 2,
	BESINDEX_Radius_ArcSymbol = 3,
	BESINDEX_Radius_CenterMark = 4,
	BESINDEX_Radius_Prefix = 5,
	BESINDEX_Radius_Suffix = 6,
};

// Autogenerated map for class Radius
static const ElementECDelegate::MapEntry s_BESMAP_Radius[] = {
	BESINDEX_Radius_Leader, L"Leader", NULL_MAP,
	BESINDEX_Radius_StackDimensions, L"StackDimensions", NULL_MAP,
	BESINDEX_Radius_ArcSymbol, L"ArcSymbol", NULL_MAP,
	BESINDEX_Radius_CenterMark, L"CenterMark", NULL_MAP,
	BESINDEX_Radius_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_Radius_Suffix, L"Suffix", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class RadiusExt
enum RadiusExtPropertyIndex {
	BESINDEX_RadiusExt_Leader = 1,
	BESINDEX_RadiusExt_StackDimensions = 2,
	BESINDEX_RadiusExt_ArcSymbol = 3,
	BESINDEX_RadiusExt_CenterMark = 4,
	BESINDEX_RadiusExt_Prefix = 5,
	BESINDEX_RadiusExt_Suffix = 6,
};

// Autogenerated map for class RadiusExt
static const ElementECDelegate::MapEntry s_BESMAP_RadiusExt[] = {
	BESINDEX_RadiusExt_Leader, L"Leader", NULL_MAP,
	BESINDEX_RadiusExt_StackDimensions, L"StackDimensions", NULL_MAP,
	BESINDEX_RadiusExt_ArcSymbol, L"ArcSymbol", NULL_MAP,
	BESINDEX_RadiusExt_CenterMark, L"CenterMark", NULL_MAP,
	BESINDEX_RadiusExt_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_RadiusExt_Suffix, L"Suffix", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class Diameter
enum DiameterPropertyIndex {
	BESINDEX_Diameter_Leader = 1,
	BESINDEX_Diameter_StackDimensions = 2,
	BESINDEX_Diameter_ArcSymbol = 3,
	BESINDEX_Diameter_CenterMark = 4,
	BESINDEX_Diameter_Prefix = 5,
	BESINDEX_Diameter_Suffix = 6,
};

// Autogenerated map for class Diameter
static const ElementECDelegate::MapEntry s_BESMAP_Diameter[] = {
	BESINDEX_Diameter_Leader, L"Leader", NULL_MAP,
	BESINDEX_Diameter_StackDimensions, L"StackDimensions", NULL_MAP,
	BESINDEX_Diameter_ArcSymbol, L"ArcSymbol", NULL_MAP,
	BESINDEX_Diameter_CenterMark, L"CenterMark", NULL_MAP,
	BESINDEX_Diameter_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_Diameter_Suffix, L"Suffix", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class DiameterExt
enum DiameterExtPropertyIndex {
	BESINDEX_DiameterExt_Leader = 1,
	BESINDEX_DiameterExt_StackDimensions = 2,
	BESINDEX_DiameterExt_ArcSymbol = 3,
	BESINDEX_DiameterExt_CenterMark = 4,
	BESINDEX_DiameterExt_Prefix = 5,
	BESINDEX_DiameterExt_Suffix = 6,
};

// Autogenerated map for class DiameterExt
static const ElementECDelegate::MapEntry s_BESMAP_DiameterExt[] = {
	BESINDEX_DiameterExt_Leader, L"Leader", NULL_MAP,
	BESINDEX_DiameterExt_StackDimensions, L"StackDimensions", NULL_MAP,
	BESINDEX_DiameterExt_ArcSymbol, L"ArcSymbol", NULL_MAP,
	BESINDEX_DiameterExt_CenterMark, L"CenterMark", NULL_MAP,
	BESINDEX_DiameterExt_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_DiameterExt_Suffix, L"Suffix", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class DiameterParallel
enum DiameterParallelPropertyIndex {
	BESINDEX_DiameterParallel_LeftTerminator = 1,
	BESINDEX_DiameterParallel_RightTerminator = 2,
	BESINDEX_DiameterParallel_LeftExtension = 3,
	BESINDEX_DiameterParallel_RightExtension = 4,
	BESINDEX_DiameterParallel_StackDimensions = 5,
	BESINDEX_DiameterParallel_ArcSymbol = 6,
	BESINDEX_DiameterParallel_Prefix = 7,
	BESINDEX_DiameterParallel_Suffix = 8,
};

// Autogenerated map for class DiameterParallel
static const ElementECDelegate::MapEntry s_BESMAP_DiameterParallel[] = {
	BESINDEX_DiameterParallel_LeftTerminator, L"LeftTerminator", NULL_MAP,
	BESINDEX_DiameterParallel_RightTerminator, L"RightTerminator", NULL_MAP,
	BESINDEX_DiameterParallel_LeftExtension, L"LeftExtension", NULL_MAP,
	BESINDEX_DiameterParallel_RightExtension, L"RightExtension", NULL_MAP,
	BESINDEX_DiameterParallel_StackDimensions, L"StackDimensions", NULL_MAP,
	BESINDEX_DiameterParallel_ArcSymbol, L"ArcSymbol", NULL_MAP,
	BESINDEX_DiameterParallel_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_DiameterParallel_Suffix, L"Suffix", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class DiameterPerp
enum DiameterPerpPropertyIndex {
	BESINDEX_DiameterPerp_LeftTerminator = 1,
	BESINDEX_DiameterPerp_RightTerminator = 2,
	BESINDEX_DiameterPerp_LeftExtension = 3,
	BESINDEX_DiameterPerp_RightExtension = 4,
	BESINDEX_DiameterPerp_StackDimensions = 5,
	BESINDEX_DiameterPerp_ArcSymbol = 6,
	BESINDEX_DiameterPerp_Prefix = 7,
	BESINDEX_DiameterPerp_Suffix = 8,
};

// Autogenerated map for class DiameterPerp
static const ElementECDelegate::MapEntry s_BESMAP_DiameterPerp[] = {
	BESINDEX_DiameterPerp_LeftTerminator, L"LeftTerminator", NULL_MAP,
	BESINDEX_DiameterPerp_RightTerminator, L"RightTerminator", NULL_MAP,
	BESINDEX_DiameterPerp_LeftExtension, L"LeftExtension", NULL_MAP,
	BESINDEX_DiameterPerp_RightExtension, L"RightExtension", NULL_MAP,
	BESINDEX_DiameterPerp_StackDimensions, L"StackDimensions", NULL_MAP,
	BESINDEX_DiameterPerp_ArcSymbol, L"ArcSymbol", NULL_MAP,
	BESINDEX_DiameterPerp_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_DiameterPerp_Suffix, L"Suffix", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class CustomLinear
enum CustomLinearPropertyIndex {
	BESINDEX_CustomLinear_LeftTerminator = 1,
	BESINDEX_CustomLinear_RightTerminator = 2,
	BESINDEX_CustomLinear_FirstTerminator = 3,
	BESINDEX_CustomLinear_JointTerminator = 4,
	BESINDEX_CustomLinear_LeftExtension = 5,
	BESINDEX_CustomLinear_RightExtension = 6,
	BESINDEX_CustomLinear_StackDimensions = 7,
	BESINDEX_CustomLinear_ArcSymbol = 8,
	BESINDEX_CustomLinear_Prefix = 9,
	BESINDEX_CustomLinear_Suffix = 10,
	BESINDEX_CustomLinear_Text = 11,
};

// Autogenerated map for class CustomLinear
static const ElementECDelegate::MapEntry s_BESMAP_CustomLinear[] = {
	BESINDEX_CustomLinear_LeftTerminator, L"LeftTerminator", NULL_MAP,
	BESINDEX_CustomLinear_RightTerminator, L"RightTerminator", NULL_MAP,
	BESINDEX_CustomLinear_FirstTerminator, L"FirstTerminator", NULL_MAP,
	BESINDEX_CustomLinear_JointTerminator, L"JointTerminator", NULL_MAP,
	BESINDEX_CustomLinear_LeftExtension, L"LeftExtension", NULL_MAP,
	BESINDEX_CustomLinear_RightExtension, L"RightExtension", NULL_MAP,
	BESINDEX_CustomLinear_StackDimensions, L"StackDimensions", NULL_MAP,
	BESINDEX_CustomLinear_ArcSymbol, L"ArcSymbol", NULL_MAP,
	BESINDEX_CustomLinear_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_CustomLinear_Suffix, L"Suffix", NULL_MAP,
	BESINDEX_CustomLinear_Text, L"Text", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class Ordinate
enum OrdinatePropertyIndex {
	BESINDEX_Ordinate_StackDimensions = 1,
	BESINDEX_Ordinate_ArcSymbol = 2,
	BESINDEX_Ordinate_Prefix = 3,
	BESINDEX_Ordinate_Suffix = 4,
	BESINDEX_Ordinate_DecrementReverse = 5,
	BESINDEX_Ordinate_DatumValue = 6,
	BESINDEX_Ordinate_FreeLocation = 7,
};

// Autogenerated map for class Ordinate
static const ElementECDelegate::MapEntry s_BESMAP_Ordinate[] = {
	BESINDEX_Ordinate_StackDimensions, L"StackDimensions", NULL_MAP,
	BESINDEX_Ordinate_ArcSymbol, L"ArcSymbol", NULL_MAP,
	BESINDEX_Ordinate_Prefix, L"Prefix", NULL_MAP,
	BESINDEX_Ordinate_Suffix, L"Suffix", NULL_MAP,
	BESINDEX_Ordinate_DecrementReverse, L"DecrementReverse", NULL_MAP,
	BESINDEX_Ordinate_DatumValue, L"DatumValue", NULL_MAP,
	BESINDEX_Ordinate_FreeLocation, L"FreeLocation", NULL_MAP,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class ToolsSpecific
enum ToolsSpecificPropertyIndex {
	BESINDEX_ToolsSpecific_SizeArrow = 1,
	BESINDEX_ToolsSpecific_SizeStroke = 13,
	BESINDEX_ToolsSpecific_SingleLocation = 25,
	BESINDEX_ToolsSpecific_StackedLocation = 37,
	BESINDEX_ToolsSpecific_AngleSize = 49,
	BESINDEX_ToolsSpecific_ArcSize = 58,
	BESINDEX_ToolsSpecific_AngleLocation = 68,
	BESINDEX_ToolsSpecific_ArcLocation = 78,
	BESINDEX_ToolsSpecific_AngleLines = 88,
	BESINDEX_ToolsSpecific_AngleAxis = 97,
	BESINDEX_ToolsSpecific_Radius = 106,
	BESINDEX_ToolsSpecific_RadiusExt = 113,
	BESINDEX_ToolsSpecific_Diameter = 120,
	BESINDEX_ToolsSpecific_DiameterExt = 127,
	BESINDEX_ToolsSpecific_DiameterParallel = 134,
	BESINDEX_ToolsSpecific_DiameterPerp = 143,
	BESINDEX_ToolsSpecific_CustomLinear = 152,
	BESINDEX_ToolsSpecific_Ordinate = 164,
};

// Autogenerated map for class ToolsSpecific
static const ElementECDelegate::MapEntry s_BESMAP_ToolsSpecific[] = {
	BESINDEX_ToolsSpecific_SizeArrow, L"SizeArrow", s_BESMAP_SizeArrow,
	BESINDEX_ToolsSpecific_SizeStroke, L"SizeStroke", s_BESMAP_SizeStroke,
	BESINDEX_ToolsSpecific_SingleLocation, L"SingleLocation", s_BESMAP_SingleLocation,
	BESINDEX_ToolsSpecific_StackedLocation, L"StackedLocation", s_BESMAP_StackedLocation,
	BESINDEX_ToolsSpecific_AngleSize, L"AngleSize", s_BESMAP_AngleSize,
	BESINDEX_ToolsSpecific_ArcSize, L"ArcSize", s_BESMAP_ArcSize,
	BESINDEX_ToolsSpecific_AngleLocation, L"AngleLocation", s_BESMAP_AngleLocation,
	BESINDEX_ToolsSpecific_ArcLocation, L"ArcLocation", s_BESMAP_ArcLocation,
	BESINDEX_ToolsSpecific_AngleLines, L"AngleLines", s_BESMAP_AngleLines,
	BESINDEX_ToolsSpecific_AngleAxis, L"AngleAxis", s_BESMAP_AngleAxis,
	BESINDEX_ToolsSpecific_Radius, L"Radius", s_BESMAP_Radius,
	BESINDEX_ToolsSpecific_RadiusExt, L"RadiusExt", s_BESMAP_RadiusExt,
	BESINDEX_ToolsSpecific_Diameter, L"Diameter", s_BESMAP_Diameter,
	BESINDEX_ToolsSpecific_DiameterExt, L"DiameterExt", s_BESMAP_DiameterExt,
	BESINDEX_ToolsSpecific_DiameterParallel, L"DiameterParallel", s_BESMAP_DiameterParallel,
	BESINDEX_ToolsSpecific_DiameterPerp, L"DiameterPerp", s_BESMAP_DiameterPerp,
	BESINDEX_ToolsSpecific_CustomLinear, L"CustomLinear", s_BESMAP_CustomLinear,
	BESINDEX_ToolsSpecific_Ordinate, L"Ordinate", s_BESMAP_Ordinate,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// Autogenerated enum for class DimensionStyle
enum DimensionStylePropertyIndex {
	BESINDEX_DimensionStyle_General = 1,
	BESINDEX_DimensionStyle_Units = 31,
	BESINDEX_DimensionStyle_Graphics = 102,
	BESINDEX_DimensionStyle_Text = 131,
	BESINDEX_DimensionStyle_Notes = 157,
	BESINDEX_DimensionStyle_Symbols = 173,
	BESINDEX_DimensionStyle_ToolsSpecific = 220,
};

// Autogenerated map for class DimensionStyle
static const ElementECDelegate::MapEntry s_BESMAP_DimensionStyle[] = {
	BESINDEX_DimensionStyle_General, L"General", s_BESMAP_General,
	BESINDEX_DimensionStyle_Units, L"Units", s_BESMAP_Units,
	BESINDEX_DimensionStyle_Graphics, L"Graphics", s_BESMAP_Graphics,
	BESINDEX_DimensionStyle_Text, L"Text", s_BESMAP_Text,
	BESINDEX_DimensionStyle_Notes, L"Notes", s_BESMAP_Notes,
	BESINDEX_DimensionStyle_Symbols, L"Symbols", s_BESMAP_Symbols,
	BESINDEX_DimensionStyle_ToolsSpecific, L"ToolsSpecific", s_BESMAP_ToolsSpecific,
	ElementECDelegate::END_OF_MAP, NULL_ACCESSOR, NULL_MAP
};

// LUT indexed by EC property index to access DimStyle property and type, used by Get/SetValue()
static const DimStylePropEntry s_DimStyleECProperties[] = {
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)502, (DimStyleProp_Type)9,
	(DimStyleProp)308, (DimStyleProp_Type)2,
	(DimStyleProp)301, (DimStyleProp_Type)7,
	(DimStyleProp)507, (DimStyleProp_Type)6,
	(DimStyleProp)504, (DimStyleProp_Type)7,
	(DimStyleProp)802, (DimStyleProp_Type)2,
	(DimStyleProp)505, (DimStyleProp_Type)2,
	(DimStyleProp)314, (DimStyleProp_Type)2,
	(DimStyleProp)302, (DimStyleProp_Type)5,
	(DimStyleProp)501, (DimStyleProp_Type)2,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)903, (DimStyleProp_Type)2,
	(DimStyleProp)902, (DimStyleProp_Type)2,
	(DimStyleProp)909, (DimStyleProp_Type)5,
	(DimStyleProp)901, (DimStyleProp_Type)5,
	(DimStyleProp)904, (DimStyleProp_Type)2,
	(DimStyleProp)912, (DimStyleProp_Type)2,
	(DimStyleProp)910, (DimStyleProp_Type)1,
	(DimStyleProp)1044, (DimStyleProp_Type)2,
	(DimStyleProp)911, (DimStyleProp_Type)1,
	(DimStyleProp)1063, (DimStyleProp_Type)2,
	(DimStyleProp)906, (DimStyleProp_Type)6,
	(DimStyleProp)905, (DimStyleProp_Type)6,
	(DimStyleProp)908, (DimStyleProp_Type)6,
	(DimStyleProp)620, (DimStyleProp_Type)3,
	(DimStyleProp)621, (DimStyleProp_Type)3,
	(DimStyleProp)306, (DimStyleProp_Type)11,
	(DimStyleProp)305, (DimStyleProp_Type)11,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)1025, (DimStyleProp_Type)2,
	(DimStyleProp)1023, (DimStyleProp_Type)7,
	(DimStyleProp)1026, (DimStyleProp_Type)7,
	(DimStyleProp)1024, (DimStyleProp_Type)2,
	(DimStyleProp)1027, (DimStyleProp_Type)2,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)806, (DimStyleProp_Type)2,
	(DimStyleProp)1072, (DimStyleProp_Type)7,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)830, (DimStyleProp_Type)2,
	(DimStyleProp)831, (DimStyleProp_Type)7,
	(DimStyleProp)829, (DimStyleProp_Type)7,
	(DimStyleProp)832, (DimStyleProp_Type)6,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)1054, (DimStyleProp_Type)2,
	(DimStyleProp)1066, (DimStyleProp_Type)7,
	(DimStyleProp)1073, (DimStyleProp_Type)12,
	(DimStyleProp)1074, (DimStyleProp_Type)12,
	(DimStyleProp)1049, (DimStyleProp_Type)11,
	(DimStyleProp)1052, (DimStyleProp_Type)11,
	(DimStyleProp)1001, (DimStyleProp_Type)1,
	(DimStyleProp)1042, (DimStyleProp_Type)2,
	(DimStyleProp)813, (DimStyleProp_Type)2,
	(DimStyleProp)1039, (DimStyleProp_Type)2,
	(DimStyleProp)1041, (DimStyleProp_Type)2,
	(DimStyleProp)1078, (DimStyleProp_Type)2,
	(DimStyleProp)606, (DimStyleProp_Type)3,
	(DimStyleProp)622, (DimStyleProp_Type)3,
	(DimStyleProp)607, (DimStyleProp_Type)3,
	(DimStyleProp)623, (DimStyleProp_Type)3,
	(DimStyleProp)1085, (DimStyleProp_Type)2,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)1003, (DimStyleProp_Type)2,
	(DimStyleProp)1070, (DimStyleProp_Type)7,
	(DimStyleProp)1021, (DimStyleProp_Type)5,
	(DimStyleProp)1002, (DimStyleProp_Type)1,
	(DimStyleProp)1043, (DimStyleProp_Type)2,
	(DimStyleProp)1067, (DimStyleProp_Type)7,
	(DimStyleProp)1020, (DimStyleProp_Type)2,
	(DimStyleProp)1079, (DimStyleProp_Type)2,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)821, (DimStyleProp_Type)2,
	(DimStyleProp)1068, (DimStyleProp_Type)7,
	(DimStyleProp)1075, (DimStyleProp_Type)12,
	(DimStyleProp)1076, (DimStyleProp_Type)12,
	(DimStyleProp)1050, (DimStyleProp_Type)11,
	(DimStyleProp)1051, (DimStyleProp_Type)11,
	(DimStyleProp)1029, (DimStyleProp_Type)1,
	(DimStyleProp)1061, (DimStyleProp_Type)2,
	(DimStyleProp)820, (DimStyleProp_Type)2,
	(DimStyleProp)1033, (DimStyleProp_Type)2,
	(DimStyleProp)1035, (DimStyleProp_Type)2,
	(DimStyleProp)1080, (DimStyleProp_Type)2,
	(DimStyleProp)604, (DimStyleProp_Type)3,
	(DimStyleProp)605, (DimStyleProp_Type)3,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)1005, (DimStyleProp_Type)2,
	(DimStyleProp)1071, (DimStyleProp_Type)7,
	(DimStyleProp)1013, (DimStyleProp_Type)5,
	(DimStyleProp)1004, (DimStyleProp_Type)1,
	(DimStyleProp)1062, (DimStyleProp_Type)2,
	(DimStyleProp)1069, (DimStyleProp_Type)7,
	(DimStyleProp)1012, (DimStyleProp_Type)2,
	(DimStyleProp)1081, (DimStyleProp_Type)2,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)1045, (DimStyleProp_Type)2,
	(DimStyleProp)839, (DimStyleProp_Type)7,
	(DimStyleProp)1028, (DimStyleProp_Type)2,
	(DimStyleProp)304, (DimStyleProp_Type)6,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)317, (DimStyleProp_Type)5,
	(DimStyleProp)303, (DimStyleProp_Type)4,
	(DimStyleProp)309, (DimStyleProp_Type)10,
	(DimStyleProp)318, (DimStyleProp_Type)15,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)211, (DimStyleProp_Type)2,
	(DimStyleProp)201, (DimStyleProp_Type)4,
	(DimStyleProp)205, (DimStyleProp_Type)10,
	(DimStyleProp)212, (DimStyleProp_Type)15,
	(DimStyleProp)206, (DimStyleProp_Type)6,
	(DimStyleProp)202, (DimStyleProp_Type)6,
	(DimStyleProp)203, (DimStyleProp_Type)2,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)729, (DimStyleProp_Type)7,
	(DimStyleProp)735, (DimStyleProp_Type)6,
	(DimStyleProp)711, (DimStyleProp_Type)6,
	(DimStyleProp)705, (DimStyleProp_Type)4,
	(DimStyleProp)714, (DimStyleProp_Type)10,
	(DimStyleProp)734, (DimStyleProp_Type)15,
	(DimStyleProp)741, (DimStyleProp_Type)2,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)319, (DimStyleProp_Type)7,
	(DimStyleProp)715, (DimStyleProp_Type)6,
	(DimStyleProp)320, (DimStyleProp_Type)2,
	(DimStyleProp)322, (DimStyleProp_Type)2,
	(DimStyleProp)324, (DimStyleProp_Type)2,
	(DimStyleProp)326, (DimStyleProp_Type)2,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)810, (DimStyleProp_Type)2,
	(DimStyleProp)835, (DimStyleProp_Type)7,
	(DimStyleProp)812, (DimStyleProp_Type)7,
	(DimStyleProp)837, (DimStyleProp_Type)7,
	(DimStyleProp)811, (DimStyleProp_Type)6,
	(DimStyleProp)824, (DimStyleProp_Type)6,
	(DimStyleProp)838, (DimStyleProp_Type)6,
	(DimStyleProp)1077, (DimStyleProp_Type)7,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)828, (DimStyleProp_Type)7,
	(DimStyleProp)805, (DimStyleProp_Type)4,
	(DimStyleProp)825, (DimStyleProp_Type)15,
	(DimStyleProp)307, (DimStyleProp_Type)8,
	(DimStyleProp)809, (DimStyleProp_Type)5,
	(DimStyleProp)826, (DimStyleProp_Type)5,
	(DimStyleProp)822, (DimStyleProp_Type)2,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)110, (DimStyleProp_Type)7,
	(DimStyleProp)103, (DimStyleProp_Type)7,
	(DimStyleProp)102, (DimStyleProp_Type)7,
	(DimStyleProp)101, (DimStyleProp_Type)7,
	(DimStyleProp)105, (DimStyleProp_Type)2,
	(DimStyleProp)106, (DimStyleProp_Type)2,
	(DimStyleProp)107, (DimStyleProp_Type)6,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)405, (DimStyleProp_Type)2,
	(DimStyleProp)736, (DimStyleProp_Type)7,
	(DimStyleProp)401, (DimStyleProp_Type)7,
	(DimStyleProp)403, (DimStyleProp_Type)2,
	(DimStyleProp)108, (DimStyleProp_Type)6,
	(DimStyleProp)410, (DimStyleProp_Type)6,
	(DimStyleProp)411, (DimStyleProp_Type)6,
	(DimStyleProp)406, (DimStyleProp_Type)7,
	(DimStyleProp)404, (DimStyleProp_Type)7,
	(DimStyleProp)402, (DimStyleProp_Type)7,
	(DimStyleProp)407, (DimStyleProp_Type)7,
	(DimStyleProp)408, (DimStyleProp_Type)7,
	(DimStyleProp)409, (DimStyleProp_Type)7,
	(DimStyleProp)412, (DimStyleProp_Type)2,
	(DimStyleProp)413, (DimStyleProp_Type)6,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)704, (DimStyleProp_Type)7,
	(DimStyleProp)701, (DimStyleProp_Type)11,
	(DimStyleProp)703, (DimStyleProp_Type)8,
	(DimStyleProp)702, (DimStyleProp_Type)3,
	(DimStyleProp)742, (DimStyleProp_Type)2,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)733, (DimStyleProp_Type)7,
	(DimStyleProp)730, (DimStyleProp_Type)11,
	(DimStyleProp)732, (DimStyleProp_Type)8,
	(DimStyleProp)731, (DimStyleProp_Type)3,
	(DimStyleProp)745, (DimStyleProp_Type)2,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)724, (DimStyleProp_Type)7,
	(DimStyleProp)721, (DimStyleProp_Type)11,
	(DimStyleProp)723, (DimStyleProp_Type)8,
	(DimStyleProp)722, (DimStyleProp_Type)3,
	(DimStyleProp)744, (DimStyleProp_Type)2,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)709, (DimStyleProp_Type)7,
	(DimStyleProp)706, (DimStyleProp_Type)11,
	(DimStyleProp)708, (DimStyleProp_Type)8,
	(DimStyleProp)707, (DimStyleProp_Type)3,
	(DimStyleProp)743, (DimStyleProp_Type)2,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)737, (DimStyleProp_Type)7,
	(DimStyleProp)738, (DimStyleProp_Type)11,
	(DimStyleProp)740, (DimStyleProp_Type)8,
	(DimStyleProp)739, (DimStyleProp_Type)3,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)614, (DimStyleProp_Type)7,
	(DimStyleProp)611, (DimStyleProp_Type)11,
	(DimStyleProp)613, (DimStyleProp_Type)8,
	(DimStyleProp)612, (DimStyleProp_Type)3,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)619, (DimStyleProp_Type)7,
	(DimStyleProp)616, (DimStyleProp_Type)11,
	(DimStyleProp)618, (DimStyleProp_Type)8,
	(DimStyleProp)617, (DimStyleProp_Type)3,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)603, (DimStyleProp_Type)7,
	(DimStyleProp)602, (DimStyleProp_Type)8,
	(DimStyleProp)601, (DimStyleProp_Type)3,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)609, (DimStyleProp_Type)7,
	(DimStyleProp)608, (DimStyleProp_Type)3,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)713, (DimStyleProp_Type)13,
	(DimStyleProp)728, (DimStyleProp_Type)13,
	(DimStyleProp)710, (DimStyleProp_Type)13,
	(DimStyleProp)712, (DimStyleProp_Type)13,
	(DimStyleProp)204, (DimStyleProp_Type)13,
	(DimStyleProp)210, (DimStyleProp_Type)13,
	(DimStyleProp)316, (DimStyleProp_Type)13,
	(DimStyleProp)801, (DimStyleProp_Type)13,
	(DimStyleProp)610, (DimStyleProp_Type)13,
	(DimStyleProp)615, (DimStyleProp_Type)13,
	(DimStyleProp)836, (DimStyleProp_Type)13,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)713, (DimStyleProp_Type)13,
	(DimStyleProp)728, (DimStyleProp_Type)13,
	(DimStyleProp)710, (DimStyleProp_Type)13,
	(DimStyleProp)712, (DimStyleProp_Type)13,
	(DimStyleProp)204, (DimStyleProp_Type)13,
	(DimStyleProp)210, (DimStyleProp_Type)13,
	(DimStyleProp)316, (DimStyleProp_Type)13,
	(DimStyleProp)801, (DimStyleProp_Type)13,
	(DimStyleProp)610, (DimStyleProp_Type)13,
	(DimStyleProp)615, (DimStyleProp_Type)13,
	(DimStyleProp)836, (DimStyleProp_Type)13,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)713, (DimStyleProp_Type)13,
	(DimStyleProp)728, (DimStyleProp_Type)13,
	(DimStyleProp)710, (DimStyleProp_Type)13,
	(DimStyleProp)712, (DimStyleProp_Type)13,
	(DimStyleProp)204, (DimStyleProp_Type)13,
	(DimStyleProp)210, (DimStyleProp_Type)13,
	(DimStyleProp)316, (DimStyleProp_Type)13,
	(DimStyleProp)801, (DimStyleProp_Type)13,
	(DimStyleProp)610, (DimStyleProp_Type)13,
	(DimStyleProp)615, (DimStyleProp_Type)13,
	(DimStyleProp)836, (DimStyleProp_Type)13,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)713, (DimStyleProp_Type)13,
	(DimStyleProp)728, (DimStyleProp_Type)13,
	(DimStyleProp)710, (DimStyleProp_Type)13,
	(DimStyleProp)712, (DimStyleProp_Type)13,
	(DimStyleProp)204, (DimStyleProp_Type)13,
	(DimStyleProp)210, (DimStyleProp_Type)13,
	(DimStyleProp)316, (DimStyleProp_Type)13,
	(DimStyleProp)801, (DimStyleProp_Type)13,
	(DimStyleProp)610, (DimStyleProp_Type)13,
	(DimStyleProp)615, (DimStyleProp_Type)13,
	(DimStyleProp)836, (DimStyleProp_Type)13,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)713, (DimStyleProp_Type)13,
	(DimStyleProp)728, (DimStyleProp_Type)13,
	(DimStyleProp)204, (DimStyleProp_Type)13,
	(DimStyleProp)210, (DimStyleProp_Type)13,
	(DimStyleProp)316, (DimStyleProp_Type)13,
	(DimStyleProp)801, (DimStyleProp_Type)13,
	(DimStyleProp)610, (DimStyleProp_Type)13,
	(DimStyleProp)615, (DimStyleProp_Type)13,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)713, (DimStyleProp_Type)13,
	(DimStyleProp)728, (DimStyleProp_Type)13,
	(DimStyleProp)204, (DimStyleProp_Type)13,
	(DimStyleProp)210, (DimStyleProp_Type)13,
	(DimStyleProp)316, (DimStyleProp_Type)13,
	(DimStyleProp)801, (DimStyleProp_Type)13,
	(DimStyleProp)213, (DimStyleProp_Type)13,
	(DimStyleProp)610, (DimStyleProp_Type)13,
	(DimStyleProp)615, (DimStyleProp_Type)13,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)713, (DimStyleProp_Type)13,
	(DimStyleProp)728, (DimStyleProp_Type)13,
	(DimStyleProp)710, (DimStyleProp_Type)13,
	(DimStyleProp)204, (DimStyleProp_Type)13,
	(DimStyleProp)210, (DimStyleProp_Type)13,
	(DimStyleProp)316, (DimStyleProp_Type)13,
	(DimStyleProp)801, (DimStyleProp_Type)13,
	(DimStyleProp)610, (DimStyleProp_Type)13,
	(DimStyleProp)615, (DimStyleProp_Type)13,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)713, (DimStyleProp_Type)13,
	(DimStyleProp)728, (DimStyleProp_Type)13,
	(DimStyleProp)710, (DimStyleProp_Type)13,
	(DimStyleProp)204, (DimStyleProp_Type)13,
	(DimStyleProp)210, (DimStyleProp_Type)13,
	(DimStyleProp)316, (DimStyleProp_Type)13,
	(DimStyleProp)801, (DimStyleProp_Type)13,
	(DimStyleProp)610, (DimStyleProp_Type)13,
	(DimStyleProp)615, (DimStyleProp_Type)13,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)713, (DimStyleProp_Type)13,
	(DimStyleProp)728, (DimStyleProp_Type)13,
	(DimStyleProp)204, (DimStyleProp_Type)13,
	(DimStyleProp)210, (DimStyleProp_Type)13,
	(DimStyleProp)316, (DimStyleProp_Type)13,
	(DimStyleProp)801, (DimStyleProp_Type)13,
	(DimStyleProp)610, (DimStyleProp_Type)13,
	(DimStyleProp)615, (DimStyleProp_Type)13,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)713, (DimStyleProp_Type)13,
	(DimStyleProp)728, (DimStyleProp_Type)13,
	(DimStyleProp)204, (DimStyleProp_Type)13,
	(DimStyleProp)210, (DimStyleProp_Type)13,
	(DimStyleProp)316, (DimStyleProp_Type)13,
	(DimStyleProp)801, (DimStyleProp_Type)13,
	(DimStyleProp)610, (DimStyleProp_Type)13,
	(DimStyleProp)615, (DimStyleProp_Type)13,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)710, (DimStyleProp_Type)13,
	(DimStyleProp)316, (DimStyleProp_Type)13,
	(DimStyleProp)801, (DimStyleProp_Type)13,
	(DimStyleProp)315, (DimStyleProp_Type)13,
	(DimStyleProp)610, (DimStyleProp_Type)13,
	(DimStyleProp)615, (DimStyleProp_Type)13,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)710, (DimStyleProp_Type)13,
	(DimStyleProp)316, (DimStyleProp_Type)13,
	(DimStyleProp)801, (DimStyleProp_Type)13,
	(DimStyleProp)315, (DimStyleProp_Type)13,
	(DimStyleProp)610, (DimStyleProp_Type)13,
	(DimStyleProp)615, (DimStyleProp_Type)13,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)710, (DimStyleProp_Type)13,
	(DimStyleProp)316, (DimStyleProp_Type)13,
	(DimStyleProp)801, (DimStyleProp_Type)13,
	(DimStyleProp)315, (DimStyleProp_Type)13,
	(DimStyleProp)610, (DimStyleProp_Type)13,
	(DimStyleProp)615, (DimStyleProp_Type)13,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)710, (DimStyleProp_Type)13,
	(DimStyleProp)316, (DimStyleProp_Type)13,
	(DimStyleProp)801, (DimStyleProp_Type)13,
	(DimStyleProp)315, (DimStyleProp_Type)13,
	(DimStyleProp)610, (DimStyleProp_Type)13,
	(DimStyleProp)615, (DimStyleProp_Type)13,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)713, (DimStyleProp_Type)13,
	(DimStyleProp)728, (DimStyleProp_Type)13,
	(DimStyleProp)204, (DimStyleProp_Type)13,
	(DimStyleProp)210, (DimStyleProp_Type)13,
	(DimStyleProp)316, (DimStyleProp_Type)13,
	(DimStyleProp)801, (DimStyleProp_Type)13,
	(DimStyleProp)610, (DimStyleProp_Type)13,
	(DimStyleProp)615, (DimStyleProp_Type)13,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)713, (DimStyleProp_Type)13,
	(DimStyleProp)728, (DimStyleProp_Type)13,
	(DimStyleProp)204, (DimStyleProp_Type)13,
	(DimStyleProp)210, (DimStyleProp_Type)13,
	(DimStyleProp)316, (DimStyleProp_Type)13,
	(DimStyleProp)801, (DimStyleProp_Type)13,
	(DimStyleProp)610, (DimStyleProp_Type)13,
	(DimStyleProp)615, (DimStyleProp_Type)13,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)713, (DimStyleProp_Type)13,
	(DimStyleProp)728, (DimStyleProp_Type)13,
	(DimStyleProp)710, (DimStyleProp_Type)13,
	(DimStyleProp)712, (DimStyleProp_Type)13,
	(DimStyleProp)204, (DimStyleProp_Type)13,
	(DimStyleProp)210, (DimStyleProp_Type)13,
	(DimStyleProp)316, (DimStyleProp_Type)13,
	(DimStyleProp)801, (DimStyleProp_Type)13,
	(DimStyleProp)610, (DimStyleProp_Type)13,
	(DimStyleProp)615, (DimStyleProp_Type)13,
	(DimStyleProp)836, (DimStyleProp_Type)13,
	(DimStyleProp)0, (DimStyleProp_Type)0,
	(DimStyleProp)316, (DimStyleProp_Type)13,
	(DimStyleProp)801, (DimStyleProp_Type)13,
	(DimStyleProp)610, (DimStyleProp_Type)13,
	(DimStyleProp)615, (DimStyleProp_Type)13,
	(DimStyleProp)1055, (DimStyleProp_Type)2,
	(DimStyleProp)1057, (DimStyleProp_Type)5,
	(DimStyleProp)1065, (DimStyleProp_Type)2,
};

