#include <ScalableMeshPCH.h>

#include "Tracer.h"

BEGIN_BENTLEY_SCALABLEMESH_NAMESPACE

std::string typeDesc[(int)EventType::TYPE_QTY] = { "LOAD (CREATE) MESH", " ACQUIRE CACHED MESH ", " LOAD (CREATE) TEX ", " ACQUIRE CACHED TEX " ,
"RELEASE CACHED MESH", "RELEASE CACHED TEX" ,"SWITCH TO VRAM(MESH)" ," SWITCH TO VRAM(TEX)", "LOAD NODE", "UNLOAD NODE", "OVERVIEW 1", "LOADNODEDISPLAYDATA", "PRELOADOVERVIEW",
"ADDITEM", "REMOVEITEM", "GETITEM", "INCREMENT", "DECREMENT", "BEFORE_SWITCH_VIDEO_TEX", "DELETEITEM" };


CachedDataEventTracer* CachedDataEventTracer::s_instance;

END_BENTLEY_SCALABLEMESH_NAMESPACE