default: basic_conversion

.PHONY: basic_conversion
basic_conversion:
	./basic_conversion/basic.test.sh

## all_bis possible ovveride variables:
# DIR_BIM0200
# ^^ Path to target bim0200* directory used for conversion.
# DIR_GIT
# ^^ Path to the git monorepo.
.PHONY: all_bis
all_bis:
	./all_bis/all_bis.bim0200.sh
