/*---------------------------------------------------------------------------------------------
* Copyright (c) Bentley Systems, Incorporated. All rights reserved.
* See LICENSE.md in the repository root for full copyright notice.
*--------------------------------------------------------------------------------------------*/
#include "../TestFixture/DgnDbTestFixtures.h"
#include <UnitTests/BackDoor/DgnPlatform/DgnDbTestUtils.h>

USING_NAMESPACE_BENTLEY_EC;

//========================================================================================
// @bsiclass
//========================================================================================
struct LinkTableRelationshipTests : public DgnDbTestFixture
{
};

//---------------------------------------------------------------------------------------
// @bsimethod
//---------------------------------------------------------------------------------------
TEST_F(LinkTableRelationshipTests, CRUD)
    {
    SetupSeedProject();
    ASSERT_EQ(BentleyStatus::SUCCESS, m_db->Schemas().CreateClassViewsInDb());

    ECRelationshipClassCP relationshipClass = m_db->Schemas().GetClass(BIS_ECSCHEMA_NAME, "CategorySelectorRefersToCategories")->GetRelationshipClassCP();
    ASSERT_NE(relationshipClass, nullptr);

    CategorySelectorPtr categorySelector = new CategorySelector(m_db->GetDictionaryModel(), "MyCategorySelector");
    ASSERT_TRUE(categorySelector.IsValid());
    ASSERT_TRUE(categorySelector->Insert().IsValid());

    DgnCategoryId categoryId[5];
    ECInstanceKey instanceKey[5];

    for (int i=0; i<_countof(categoryId); i++)
        {
        Utf8PrintfString categoryName("MyCategory%d", i);
        categoryId[i] = DgnDbTestUtils::InsertSpatialCategory(*m_db, categoryName.c_str());
        ASSERT_EQ(BE_SQLITE_OK, m_db->InsertLinkTableRelationship(instanceKey[i], *relationshipClass, categorySelector->GetElementId(), categoryId[i]));
        }
    ASSERT_EQ(_countof(categoryId), DgnDbTestUtils::SelectCountFromECClass(*m_db, BIS_SCHEMA("CategorySelectorRefersToCategories")));

    int count = 0;
    ECSqlStatement statement;
    ASSERT_EQ(ECSqlStatus::Success, statement.Prepare(*m_db, "SELECT ECInstanceId,SourceECInstanceId,TargetECInstanceId FROM " BIS_SCHEMA("CategorySelectorRefersToCategories") " ORDER BY ECInstanceId"));
    while (BE_SQLITE_ROW == statement.Step())
        {
        ASSERT_EQ(statement.GetValueId<ECInstanceId>(0), instanceKey[count].GetInstanceId());
        ASSERT_EQ(statement.GetValueId<DgnElementId>(1), categorySelector->GetElementId());
        ASSERT_EQ(statement.GetValueId<DgnCategoryId>(2), categoryId[count]);
        count++;
        }
    ASSERT_EQ(_countof(categoryId), count);

    ASSERT_EQ(BE_SQLITE_OK, m_db->DeleteLinkTableRelationships(BIS_SCHEMA("CategorySelectorRefersToCategories"), DgnElementId(), categoryId[3]));
    ASSERT_EQ(BE_SQLITE_OK, m_db->DeleteLinkTableRelationships(BIS_SCHEMA("CategorySelectorRefersToCategories"), DgnElementId(), categoryId[1]));
    ASSERT_EQ(_countof(categoryId)-2, DgnDbTestUtils::SelectCountFromECClass(*m_db, BIS_SCHEMA("CategorySelectorRefersToCategories")));
    }

//---------------------------------------------------------------------------------------
// @bsimethod
//---------------------------------------------------------------------------------------
TEST_F(LinkTableRelationshipTests, ExtendAutoGeneratedSystemIndex)
    {
    SetupSeedProject();

    auto relationshipClass = m_db->Schemas().GetClass(BIS_ECSCHEMA_NAME, "CategorySelectorRefersToCategories")->GetRelationshipClassCP();
    ASSERT_TRUE(relationshipClass);

    CategorySelectorPtr categorySelector = new CategorySelector(m_db->GetDictionaryModel(), "TestCategorySelector");
    ASSERT_TRUE(categorySelector.IsValid());
    ASSERT_TRUE(categorySelector->Insert().IsValid());

    SpatialCategory category(m_db->GetDictionaryModel(), "TestCategory", DgnCategory::Rank::Application);
    auto spatialCategory = category.Insert(DgnSubCategory::Appearance());
    EXPECT_TRUE(spatialCategory.IsValid());

    ECInstanceKey relationshipInstanceKeys[5];
    {
    // Try to insert duplicate link table relationships
    const auto sourceId = ECInstanceId(categorySelector->GetElementId().GetValue());
    const auto targetId = ECInstanceId(spatialCategory->GetCategoryId().GetValue());
    ASSERT_EQ(BE_SQLITE_OK, m_db->InsertLinkTableRelationship(relationshipInstanceKeys[0], *relationshipClass, sourceId, targetId));

    // Second insert should fail as the index has not been extended to include the new MemberPriority property
    ASSERT_EQ(BE_SQLITE_CONSTRAINT_UNIQUE, m_db->InsertLinkTableRelationship(relationshipInstanceKeys[1], *relationshipClass, sourceId, targetId));
    }

    // Import new dummy BisCore which has the new DbIndex added to ElementRefersToElements
    ECSchemaPtr schema = nullptr;
    auto context = ECSchemaReadContext::CreateContext();
    context->AddSchemaLocater(m_db->GetSchemaLocater());
    auto bisCoreSchemaPath = T_HOST.GetIKnownLocationsAdmin().GetDgnPlatformAssetsDirectory();
    bisCoreSchemaPath.AppendToPath(L"ECSchemas\\BisCoreDummy.01.00.17.ecschema.xml");
    ASSERT_EQ(SchemaReadStatus::Success, ECSchema::ReadFromXmlFile(schema, bisCoreSchemaPath.GetName(), *context));

    ASSERT_EQ(SchemaStatus::Success, m_db->ImportSchemas(context->GetCache().GetSchemas(), true));
    m_db->SaveChanges();

    // Try to insert duplicate link table relationships with different MemberPriority values
    // Should succeed
    relationshipClass = m_db->Schemas().GetClass(BIS_ECSCHEMA_NAME, "CategorySelectorRefersToCategories")->GetRelationshipClassCP();
    ASSERT_TRUE(relationshipClass);

    auto relationshipEnabler = StandaloneECRelationshipEnabler::CreateStandaloneRelationshipEnabler(*relationshipClass);

    for (const auto& memberPriorityValue : { 1, 2, 3 })
        {
        IECRelationshipInstancePtr relationshipInstance = relationshipEnabler->CreateRelationshipInstance();
        ASSERT_NE(relationshipInstance, nullptr);

        ECValue value;
        value.SetInteger(memberPriorityValue);
        relationshipInstance->SetValue("MemberPriority", value);

        ASSERT_EQ(BE_SQLITE_OK, m_db->InsertLinkTableRelationship(relationshipInstanceKeys[memberPriorityValue], *relationshipClass, ECInstanceId(categorySelector->GetElementId().GetValue()), 
            ECInstanceId(spatialCategory->GetCategoryId().GetValue()), relationshipInstance.get())) << "Failed when inserting element with member priority value " << memberPriorityValue << "\n";
        }

    m_db->SaveChanges();

    // Check if the all valid relationships were inserted correctly
    ECSqlStatement statement;
    ASSERT_EQ(ECSqlStatus::Success, statement.Prepare(*m_db, "SELECT * FROM " BIS_SCHEMA("CategorySelectorRefersToCategories") " ORDER BY MemberPriority"));
    auto rowCount = 0;
    while (BE_SQLITE_ROW == statement.Step())
        {
        EXPECT_EQ(statement.GetValueId<ECInstanceId>(0), relationshipInstanceKeys[rowCount].GetInstanceId());
        EXPECT_EQ(statement.GetValueId<ECClassId>(1), relationshipInstanceKeys[rowCount].GetClassId());
        EXPECT_EQ(statement.GetValueInt(2), rowCount);
        EXPECT_EQ(statement.GetValueId<DgnElementId>(3), categorySelector->GetElementId());
        EXPECT_EQ(statement.GetValueId<DgnClassId>(4), categorySelector->GetElementClassId());
        EXPECT_EQ(statement.GetValueId<DgnElementId>(5), spatialCategory->GetCategoryId());
        EXPECT_EQ(statement.GetValueId<DgnElementId>(6), spatialCategory->GetElementClassId());
        ++rowCount;
        }
    EXPECT_EQ(rowCount, 4);
    }
