/*--------------------------------------------------------------------------------------+
|
|     $Source: RealityPlatform/WMSTag.h $
|
|  $Copyright: (c) 2015 Bentley Systems, Incorporated. All rights reserved. $
|
+--------------------------------------------------------------------------------------*/
#pragma once

#define WMS_PREFIX                      "wms"
#define WMS_NAMESPACE_1_0               "http://www.bentley.com/RealityDataServer/1.0"
#define WMS_VERSION_1_0                 "1.0"

#define WMS_ROOT_ELEMENT                "WMT_MS_Capabilities"
#define WMS_ROOT_ATTRIBUTE_Version      "version"

#define WMS_ELEMENT_Service             "Service"
#define WMS_ELEMENT_Capability          "Capability"

#define WMS_ELEMENT_Name                "Name"
#define WMS_ELEMENT_Title               "Title"
#define WMS_ELEMENT_Abstract            "Abstract"
#define WMS_ELEMENT_KeywordList         "KeywordList"
#define WMS_ELEMENT_OnlineResource      "OnlineResource"
#define WMS_ELEMENT_Fees                "Fees"
#define WMS_ELEMENT_AccessConstraints   "AccessConstraints"
#define WMS_ELEMENT_LayerLimit          "LayerLimit"
#define WMS_ELEMENT_MaxWidth            "MaxWidth"
#define WMS_ELEMENT_MaxHeight           "MaxHeight"

#define WMS_ELEMENT_ContactInformation  "ContactInformation"
#define WMS_ELEMENT_ContactPerson       "ContactPersonPrimary"
#define WMS_ELEMENT_Person              "ContactPerson"
#define WMS_ELEMENT_Organization        "ContactOrganization"
#define WMS_ELEMENT_Position            "ContactPosition"
#define WMS_ELEMENT_ContactAddress      "ContactAddress"
#define WMS_ELEMENT_Type                "AddressType"
#define WMS_ELEMENT_Address             "Address"
#define WMS_ELEMENT_City                "City"
#define WMS_ELEMENT_StateProv           "StateOrProvince"
#define WMS_ELEMENT_PostCode            "PostCode"
#define WMS_ELEMENT_Country             "Country"
#define WMS_ELEMENT_VoiceTel            "ContactVoiceTelephone"
#define WMS_ELEMENT_FacsimileTel        "ContactFacsimileTelephone"
#define WMS_ELEMENT_EmailAddress        "ContactElectronicMailAddress"

#define WMS_ELEMENT_Request             "Request"
#define WMS_ELEMENT_GetCapabilities     "GetCapabilities"
#define WMS_ELEMENT_GetMap              "GetMap"
#define WMS_ELEMENT_GetFeatureInfo      "GetFeatureInfo"
#define WMS_ELEMENT_FormatList          "Format"
#define WMS_ELEMENT_DCPType             "DCPType"
#define WMS_ELEMENT_Http                "HTTP"
#define WMS_ELEMENT_HttpGet             "Get"
#define WMS_ELEMENT_HttpPost            "Post"
#define WMS_ELEMENT_Exception           "Exception"
#define WMS_ELEMENT_Layer               "Layer"
#define WMS_ELEMENT_CRS                 "CRS"
#define WMS_ELEMENT_SRS                 "SRS"
#define WMS_ELEMENT_GeoBoundingBox      "EX_GeographicBoundingBox"
#define WMS_ELEMENT_LatLongBoundingBox  "LatLonBoundingBox"
#define WMS_ELEMENT_WestBoundLong       "westBoundLongitude"
#define WMS_ELEMENT_EastBoundLong       "eastBoundLongitude"
#define WMS_ELEMENT_SouthBoundLat       "southBoundLatitude"
#define WMS_ELEMENT_NorthBoundLat       "northBoundLatitude"
#define WMS_ELEMENT_BoundingBox         "BoundingBox"
#define WMS_ELEMENT_Dimension           "Dimension"
#define WMS_ELEMENT_Attribution         "Attribution"
#define WMS_ELEMENT_LogoURL             "LogoURL"
#define WMS_ELEMENT_AuthorityURL        "AuthorityURL"
#define WMS_ELEMENT_Identifier          "Identifier"
#define WMS_ELEMENT_MetadataURL         "MetadataURL"
#define WMS_ELEMENT_DataURL             "DataURL"
#define WMS_ELEMENT_FeatureListURL      "FeatureListURL"
#define WMS_ELEMENT_Style               "Style"
#define WMS_ELEMENT_LegendURL           "LegendURL"
#define WMS_ELEMENT_StyleSheetURL       "StyleSheetURL"
#define WMS_ELEMENT_StyleURL            "StyleURL"
#define WMS_ELEMENT_MinScaleDenom       "MinScaleDenominator"
#define WMS_ELEMENT_MaxScaleDenom       "MaxScaleDenominator"
