/*--------------------------------------------------------------------------------------+
|
|     $Source: PublicAPI/DgnPlatform/DgnView.h $
|
|  $Copyright: (c) 2016 Bentley Systems, Incorporated. All rights reserved. $
|
+--------------------------------------------------------------------------------------*/
#pragma once
//__PUBLISH_SECTION_START__

#include "DgnDb.h"
#include "DgnElement.h"
#include "ElementHandler.h"
#include "ECSqlStatementIterator.h"
#include "DgnMarkupProject.h"

#define BIS_CLASS_ViewDefinition "ViewDefinition"
#define BIS_CLASS_ViewDefinition3d "ViewDefinition3d"
#define BIS_CLASS_SpatialViewDefinition "SpatialViewDefinition"
#define BIS_CLASS_OrthographicViewDefinition "OrthographicViewDefinition"
#define BIS_CLASS_CameraViewDefinition "CameraViewDefinition"
#define BIS_CLASS_DrawingViewDefinition "DrawingViewDefinition"
#define BIS_CLASS_SheetViewDefinition "SheetViewDefinition"
#define MARKUP_CLASSNAME_RedlineViewDefinition "RedlineViewDefinition"

BEGIN_BENTLEY_DGN_NAMESPACE

namespace dgn_ElementHandler {struct CameraViewDef; struct OrthographicViewDef; struct DrawingViewDef; struct SheetViewDef; struct RedlineViewDef;}

//=======================================================================================
//! The source for the creation a ViewDefinition.
//! @ingroup GROUP_DgnView
//=======================================================================================
enum class DgnViewSource
{
    User      = 1<<0,      //!< created by a user
    Generated = 1<<1,      //!< automatically generated by a program, may be relevant to user
    Private   = 1<<2,      //!< used internally and should not be presented to user
};

//=======================================================================================
//! Holds the definition of a view.
//! @ingroup GROUP_DgnView
// @bsiclass                                                      Paul.Connelly   10/15
//=======================================================================================
struct EXPORT_VTABLE_ATTRIBUTE ViewDefinition : DefinitionElement
{
    DEFINE_T_SUPER(DefinitionElement);
public:

    //! Parameters used to construct a ViewDefinition
    struct CreateParams : T_Super::CreateParams
    {
    protected:
        CreateParams(DgnDbR db, DgnClassId classId, DgnCode const& code, Utf8CP label=nullptr, DgnElementId parentId=DgnElementId())
            : T_Super(db, DgnModel::DictionaryId(), classId, code, label, parentId) {}

        DGNPLATFORM_EXPORT CreateParams(DgnDbR db, DgnCode const& code, DgnClassId classId);
    public:
        DEFINE_T_SUPER(ViewDefinition::T_Super::CreateParams);

        //! Constructor from base CreateParams. Chiefly for internal use.
        explicit CreateParams(DgnElement::CreateParams const& params) : T_Super(params) { }
    };
private:
    DgnDbStatus DeleteReferences() const;
    static bool IsValidCode(DgnCode const& code);
protected:
    explicit ViewDefinition(CreateParams const& params) : T_Super(params) { }

    virtual DgnCode _GenerateDefaultCode() const override { return DgnCode(); }
    virtual bool _SupportsCodeAuthority(DgnAuthorityCR auth) const override { return ResourceAuthority::IsResourceAuthority(auth); }

    DGNPLATFORM_EXPORT virtual DgnDbStatus _OnDelete() const override;

    virtual DgnDbStatus _SetParentId(DgnElementId) override { return DgnDbStatus::InvalidParent; }
    virtual DgnDbStatus _OnChildInsert(DgnElementCR) const override { return DgnDbStatus::InvalidParent; }
    virtual DgnDbStatus _OnChildUpdate(DgnElementCR, DgnElementCR) const override { return DgnDbStatus::InvalidParent; }

    virtual ViewControllerPtr _SupplyController() const = 0;
    virtual bool _IsValidBaseModel(DgnModelCR model) const { return true; }

    virtual SpatialViewDefinitionCP _ToSpatialView() const { return nullptr; }
    virtual DrawingViewDefinitionCP _ToDrawingView() const { return nullptr; }
    virtual SheetViewDefinitionCP _ToSheetView() const { return nullptr; }

public:
    DgnViewId GetViewId() const { return DgnViewId(GetElementId().GetValue()); } //!< This view definition's ID
    Utf8String GetName() const { return GetCode().GetValue(); } //!< The name of the view definition
    DGNPLATFORM_EXPORT Utf8StringCR GetDescr() const; //!< This view definition's description
    DGNPLATFORM_EXPORT DgnViewSource GetSource() const; //!< This view definition's source

    DgnDbStatus SetName(Utf8StringCR name) { return SetCode(CreateCode(name)); } //!< Change this view definition's name
    DGNPLATFORM_EXPORT void SetDescr(Utf8StringCR descr); //!< Change this view definition's description
    DGNPLATFORM_EXPORT void SetSource(DgnViewSource source); //!< Change this view definition's source
    DGNPLATFORM_EXPORT void SetBaseModelId(DgnModelId modelId); //!< Change the base model ID

    //! Inserts into the database and returns the new persistent copy.
    ViewDefinitionCPtr Insert(DgnDbStatus* status=nullptr) { return GetDgnDb().Elements().Insert<ViewDefinition>(*this, status); }
    //! Updates in the database and returns the updated persistent copy.
    ViewDefinitionCPtr Update(DgnDbStatus* status=nullptr) { return GetDgnDb().Elements().Update<ViewDefinition>(*this, status); }

    //! Specifies whether or not models associated with a ViewDefinition should be filled when loading a ViewController
    enum class FillModels
    {
    No=0, //!< Don't fill models
    Yes=1 //!< Fill models
    };

    //! Instantiate a ViewController for this ViewDefinition in order to render the view
    DGNPLATFORM_EXPORT ViewControllerPtr LoadViewController(FillModels fillModels=FillModels::No) const;
    //! Instantiate a ViewController for the ViewDefinition with the specified ID in order to render the view
    DGNPLATFORM_EXPORT static ViewControllerPtr LoadViewController(DgnViewId viewId, DgnDbR db, FillModels fillModels=FillModels::No);

    //! Create a DgnCode for a view with the specified name
    static DgnCode CreateCode(Utf8StringCR name) { return ResourceAuthority::CreateResourceCode(name, BIS_CLASS_ViewDefinition); }

    //! Look up the ID of the view with the specified DgnCode
    DGNPLATFORM_EXPORT static DgnViewId QueryViewId(DgnCode const& code, DgnDbR db);

    //! Look up the ID of the view with the specified name
    static DgnViewId QueryViewId(Utf8StringCR name, DgnDbR db) { return QueryViewId(CreateCode(name), db); }

    //! Look up a view by ID
    static ViewDefinitionCPtr QueryView(DgnViewId viewId, DgnDbR db) { return db.Elements().Get<ViewDefinition>(viewId); }

    //! Look up a view by name
    static ViewDefinitionCPtr QueryView(Utf8StringCR name, DgnDbR db) { return QueryView(QueryViewId(name, db), db); }

    DGNVIEW_EXPORT BeSQLite::DbResult RenderAndSaveThumbnail(int resolution, Render::RenderMode renderModeOverride) const;

    //! An entry in an iterator over the views in a DgnDb
    struct Entry : ECSqlStatementEntry
    {
        friend struct ECSqlStatementIterator<Entry>;
        friend struct DgnView;
    private:
        Entry(BeSQLite::EC::ECSqlStatement* stmt=nullptr) : ECSqlStatementEntry(stmt) { }
    public:
        DgnViewId GetId() const { return m_statement->GetValueId<DgnViewId>(0); } //!< The view ID
        Utf8CP GetName() const { return m_statement->GetValueText(1); } //!< The name of the view
        DgnViewSource GetSource() const { return static_cast<DgnViewSource>(m_statement->GetValueInt(2)); } //!< The view source
        DgnModelId GetBaseModelId() const { return m_statement->GetValueId<DgnModelId>(3); } //!< The view's base model
        Utf8CP GetDescr() const { return m_statement->GetValueText(4); } //!< The view's description
        DgnClassId GetClassId() const { return m_statement->GetValueId<DgnClassId>(5); } //!< The view's ECClass ID

        DGNPLATFORM_EXPORT bool IsSpatialView() const;
        DGNPLATFORM_EXPORT bool IsDrawingView() const;
        DGNPLATFORM_EXPORT bool IsSheetView() const;
    };

    //! An iterator over the view definitions stored in a DgnDb
    struct Iterator : ECSqlStatementIterator<Entry>
    {
        // Options controlling ViewDefinition iteration
        struct Options
        {
            //! Defines the order in which results should be returned
            enum class Order : uint8_t
            {
                Unordered, //!< No meaningful order
                Ascending, //!< Order by name ascending
            };

            //! Defines the view source(s) to include in the query
            enum class Source : uint8_t
            {
                User = (uint8_t)DgnViewSource::User, //!< Include user-defined views
                Generated = (uint8_t)DgnViewSource::Generated, //!< Include program-generated views
                Private = (uint8_t)DgnViewSource::Private, //!< Include internally-defined views
                All = User | Generated | Private, //!< Include views from all sources
            };
        private:
            Utf8String m_customECSql;
            Order m_order;
            Source m_source;

            Options(Order order, Source source, Utf8StringCR ecsql)
                : m_customECSql(ecsql), m_order(order), m_source(source) { }
        public:
            //! Constructor
            //! @param[in]      order       Optional order in which to return results
            //! @param[in]      source      Optional view source(s) to include
            explicit Options(Order order=Order::Unordered, Source source=Source::All) : Options(order, source, Utf8String()) { }

            //! Constructor
            //! @param[in]      source      View source by which to filter
            //! @param[in]      order       Optional order in which to return results
            explicit Options(Source source, Order order=Order::Unordered) : Options(order, source, Utf8String()) { }

            //! Constructor
            //! @param[in]      ecsql Custom ECSql which is to be appended to the SELECT statement
            explicit Options(Utf8StringCR ecsql) : Options(Order::Unordered, Source::All, ecsql) { }

            //! Returns true if these options do not restrict the results
            bool IsEmpty() const { return m_customECSql.empty() && Order::Unordered == m_order && Source::All == m_source; }

            //! Convert these options to an ECSql string
            Utf8String ToString() const;
        };

        //! Construct an iterator over the view definitions within the specified DgnDb
        DGNPLATFORM_EXPORT Iterator(DgnDbR db, Options const& options);
    };

    //! Create an iterator over the view definitions within the specified DgnDb
    static Iterator MakeIterator(DgnDbR db, Iterator::Options const& options=Iterator::Options()) { return Iterator(db, options); }

    //! Return the number of view definitions in the specific DgnDb
    DGNPLATFORM_EXPORT static size_t QueryCount(DgnDbR db, Iterator::Options const& options=Iterator::Options());

    bool IsSpatialView() const { return nullptr != _ToSpatialView(); }
    bool IsDrawingView() const { return nullptr != _ToDrawingView(); }
    bool IsSheetView() const { return nullptr != _ToSheetView(); }
    SpatialViewDefinitionCP ToSpatialView() const { return _ToSpatialView(); }
    DrawingViewDefinitionCP ToDrawingView() const { return _ToDrawingView(); }
    SheetViewDefinitionCP ToSheetView() const { return _ToSheetView(); }
    SpatialViewDefinitionP ToSpatialViewP() { return const_cast<SpatialViewDefinitionP>(ToSpatialView()); }
    DrawingViewDefinitionP ToDrawingViewP() { return const_cast<DrawingViewDefinitionP>(ToDrawingView()); }
    SheetViewDefinitionP ToSheetViewP() { return const_cast<SheetViewDefinitionP>(ToSheetView()); }

    ViewControllerPtr LoadViewController(bool allowOverrides, FillModels fillModels) const; //!< @private

    DGNPLATFORM_EXPORT DgnElementId GetCategorySelector() const; //!< Get the CategorySelector used by this view
    DGNPLATFORM_EXPORT DgnElementId GetDisplayStyle() const; //!< Get the DisplayStyle used by this view
    DGNPLATFORM_EXPORT DgnDbStatus SetCategorySelector(DgnElementId); //!< Set the CategorySelector used by this view
    DGNPLATFORM_EXPORT DgnDbStatus SetDisplayStyle(DgnElementId); //!< Set the DisplayStyle used by this view
};

//=======================================================================================
//! Defines a view of a 3d model.
// @bsiclass                                                      Shaun.Sewall    02/16
//=======================================================================================
struct EXPORT_VTABLE_ATTRIBUTE ViewDefinition3d : ViewDefinition
{
    DGNELEMENT_DECLARE_MEMBERS(BIS_CLASS_ViewDefinition3d, ViewDefinition);
protected:
    explicit ViewDefinition3d(CreateParams const& params) : T_Super(params) {}
    DGNPLATFORM_EXPORT ViewDefinition3d(CreateParams const& params, DgnElementId modelSelector);

    DGNPLATFORM_EXPORT DgnElementId GetModelSelector() const; //!< Get the ModelSelector used by this view
    DGNPLATFORM_EXPORT DgnElementId GetClipVolume() const; //!< Get the ClipVolume used by this view
    DGNPLATFORM_EXPORT DgnDbStatus SetModelSelector(DgnElementId) const; //!< Set the ModelSelector used by this view
    DGNPLATFORM_EXPORT DgnDbStatus SetClipVolume(DgnElementId) const; //!< Set the ClipVolume used by this view
    static DgnClassId QueryClassId(DgnDbR db) { return DgnClassId(db.Schemas().GetECClassId(BIS_ECSCHEMA_NAME, BIS_CLASS_ViewDefinition3d)); }
};

//=======================================================================================
//! Defines a view of one or more SpatialModels.
//! The list of viewed models is stored in the view's settings in the DgnDb's settings
//! table.
// @bsiclass                                                      Paul.Connelly   10/15
//=======================================================================================
struct EXPORT_VTABLE_ATTRIBUTE SpatialViewDefinition : ViewDefinition3d
{
    DGNELEMENT_DECLARE_MEMBERS(BIS_CLASS_SpatialViewDefinition, ViewDefinition3d);
protected:
    virtual SpatialViewDefinitionCP _ToSpatialView() const override { return this; }
    virtual void _MakeAbstract() = 0;
    DGNPLATFORM_EXPORT ViewControllerPtr _SupplyController() const override;
    explicit SpatialViewDefinition(CreateParams const& params) : T_Super(params) { }
public:
    //! Construct a new SpatialViewDefinition
    SpatialViewDefinition(CreateParams const& params, DgnElementId modelSelector) : T_Super(params, modelSelector) {}
    
    //! Look up the ECClass ID used for SpatialViewDefinitions within the specified DgnDb
    static DgnClassId QueryClassId(DgnDbR db) { return DgnClassId(db.Schemas().GetECClassId(BIS_ECSCHEMA_NAME, BIS_CLASS_SpatialViewDefinition)); }
};

//=======================================================================================
//! Defines a view of one or more SpatialModels that displays
//! world-coordinate geometry on the image plane using a parallel orthographic projection.
// @bsiclass                                                      Sam.Wilson    08/16
//=======================================================================================
struct EXPORT_VTABLE_ATTRIBUTE OrthographicViewDefinition : SpatialViewDefinition
    {
    DGNELEMENT_DECLARE_MEMBERS(BIS_CLASS_OrthographicViewDefinition, SpatialViewDefinition);    
    friend struct dgn_ElementHandler::OrthographicViewDef;
protected:
    void _MakeAbstract() override{;}
    explicit OrthographicViewDefinition(CreateParams const& params) : T_Super(params) {}
public:
    //! Construct a new OrthographicViewDefinition
    OrthographicViewDefinition(CreateParams const& params, DgnElementId modelSelector) : T_Super(params, modelSelector) {}

    //! Look up the ECClass ID used for OrthographicViewDefinitions within the specified DgnDb
    static DgnClassId QueryClassId(DgnDbR db) { return DgnClassId(db.Schemas().GetECClassId(BIS_ECSCHEMA_NAME, BIS_CLASS_OrthographicViewDefinition)); }

    DGNPLATFORM_EXPORT DPoint3d GetOrigin() const; //!< Get the origin of the viewed volume on the lower, back, rear
    DGNPLATFORM_EXPORT DVec3d GetExtents() const; //!< Get the size of the view diagonal
    DGNPLATFORM_EXPORT YawPitchRollAngles GetViewDirection() const; //!< Get the view direction

    DGNPLATFORM_EXPORT void SetOrigin(DPoint3dCR); //!< Set the origin of the viewed volume on the lower, back, rear
    DGNPLATFORM_EXPORT void SetExtents(DVec3dCR); //!< Set the size of the view diagonal
    DGNPLATFORM_EXPORT void SetViewDirection(YawPitchRollAnglesCR); //!< Set the view direction
    };

//=======================================================================================
//! Defines a view of one or more SpatialModels, which supports a camera that displays
//! world-coordinate geometry onto the image plane through a perspective projection.
// @bsiclass                                                      Paul.Connelly   10/15
//=======================================================================================
struct EXPORT_VTABLE_ATTRIBUTE CameraViewDefinition : SpatialViewDefinition
{
    DGNELEMENT_DECLARE_MEMBERS(BIS_CLASS_CameraViewDefinition, SpatialViewDefinition);
    friend struct dgn_ElementHandler::CameraViewDef;
protected:
    void _MakeAbstract() override { ; }
    explicit CameraViewDefinition(CreateParams const& params) : T_Super(params) { }

public:
    //! Construct a new CameraViewDefinition
    CameraViewDefinition(CreateParams const& params, DgnElementId modelSelector) : T_Super(params, modelSelector) {}

    //! Look up the ECClass ID used for CameraViewDefinitions within the specified DgnDb
    static DgnClassId QueryClassId(DgnDbR db) { return DgnClassId(db.Schemas().GetECClassId(BIS_ECSCHEMA_NAME, BIS_CLASS_CameraViewDefinition)); }

    DGNPLATFORM_EXPORT DPoint3d GetBackOrigin() const; //!< Get the origin of the focus plane projected to the back plane
    DGNPLATFORM_EXPORT double GetWidth() const; //!< Get the extent in x on the focus plane in meters
    DGNPLATFORM_EXPORT double GetHeight() const; //!< Get the extent in y on the focus plane in meters
    DGNPLATFORM_EXPORT double GetDepth() const; //!< Get the distance between front and back planes in meters
    DGNPLATFORM_EXPORT DPoint3d GetEyePoint() const; //!< Get the camera eye point
    DGNPLATFORM_EXPORT double GetLensAngle() const; //!< Get the camera lens angle in degrees
    DGNPLATFORM_EXPORT double GetFocusDistance() const; //!< Get the camera focus distance in meters
    DGNPLATFORM_EXPORT YawPitchRollAngles GetViewDirection() const; //!< Get the view direction

    DGNPLATFORM_EXPORT void SetBackOrigin(DPoint3dCR); //!< Set the origin of the focus plane projected to the back plane
    DGNPLATFORM_EXPORT void SetWidth(double); //!< Set the extent in x on the focus plane in meters
    DGNPLATFORM_EXPORT void SetHeight(double); //!< Set the extent in y on the focus plane in meters
    DGNPLATFORM_EXPORT void SetDepth(double); //!< Set the distance between front and back planes in meters
    DGNPLATFORM_EXPORT void SetEyePoint(DPoint3dCR); //!< Set the camera eye point
    DGNPLATFORM_EXPORT void SetLensAngle(double); //!< Set the camera lens angle in degrees
    DGNPLATFORM_EXPORT void SetFocusDistance(double); //!< Set the camera focus distance in meters
    DGNPLATFORM_EXPORT void SetViewDirection(YawPitchRollAnglesCR); //!< Set the view direction
};

//=======================================================================================
//! Defines a view of a 2d model.
// @bsiclass                                                      Paul.Connelly   10/15
//=======================================================================================
struct EXPORT_VTABLE_ATTRIBUTE ViewDefinition2d : ViewDefinition
{
    DEFINE_T_SUPER(ViewDefinition);
protected:
    DGNPLATFORM_EXPORT virtual void _RemapIds(DgnImportContext& importer) override;
    DGNPLATFORM_EXPORT DgnDbStatus _SetProperty(Utf8CP name, ECN::ECValueCR value) override; // *** TBD: Verify basemodelid is valid
protected:
    explicit ViewDefinition2d(CreateParams const& params) : T_Super(params) {}
public:
    DGNPLATFORM_EXPORT ViewDefinition2d(CreateParams const& params, DgnModelId baseModelId);
    DGNPLATFORM_EXPORT bool IsBaseModelValid() const;
    DGNPLATFORM_EXPORT DgnModelId GetBaseModelId() const; //!< Get the base model ID
    DGNPLATFORM_EXPORT DgnDbStatus SetBaseModelId(DgnModelId); //!< Get the base model ID

    DGNPLATFORM_EXPORT DPoint2d GetOrigin  () const; //!< Get the lower left corner of the viewed area.
    DGNPLATFORM_EXPORT DVec2d GetExtents () const; //!< Get the size of the view diagonal
    DGNPLATFORM_EXPORT AngleInDegrees GetRotationAngle() const; //!< Get the rotation angle of the viewed area.

    DGNPLATFORM_EXPORT void SetOrigin(DPoint2dCR); //!< Set the lower left corner of the viewed area.
    DGNPLATFORM_EXPORT void SetExtents(DVec2dCR); //!< Set the size of the view diagonal
    DGNPLATFORM_EXPORT void SetRotationAngle(AngleInDegrees const&); //!< Set the rotation angle of the viewed area.
    };

//=======================================================================================
//! Defines a view of a DrawingModel.
// @bsiclass                                                      Paul.Connelly   10/15
//=======================================================================================
struct EXPORT_VTABLE_ATTRIBUTE DrawingViewDefinition : ViewDefinition2d
{
    DGNELEMENT_DECLARE_MEMBERS(BIS_CLASS_DrawingViewDefinition, ViewDefinition2d);
    friend struct dgn_ElementHandler::DrawingViewDef;
public:
    //! Parameters used to construct a DrawingViewDefinition
    struct CreateParams : T_Super::CreateParams
    {
        DEFINE_T_SUPER(DrawingViewDefinition::T_Super::CreateParams);
    protected:
        CreateParams(DgnDbR db, DgnCode const& code, DgnClassId classId) : T_Super(db, code, classId) { }
    public:
        //! Constructor from base params. Chiefly for internal use.
        explicit CreateParams(DgnElement::CreateParams const& params) : T_Super(params) { }
        //! Constructor
        CreateParams(DgnDbR db, Utf8StringCR name) : CreateParams(db, ViewDefinition::CreateCode(name), DrawingViewDefinition::QueryClassId(db)) { }
    };
protected:
    DGNPLATFORM_EXPORT ViewControllerPtr _SupplyController() const override;

    virtual DrawingViewDefinitionCP _ToDrawingView() const override { return this; }
    //! Construct a DrawingViewDefinition from the supplied params prior to loading
    explicit DrawingViewDefinition(CreateParams const& params) : T_Super(params) {}

public:
    //! Construct a DrawingViewDefinition
    DrawingViewDefinition(CreateParams const& params, DgnModelId baseModelId) : T_Super(params, baseModelId) {;}

    //! Look up the ECClass ID used for DrawingViewDefinitions in the specified DgnDb
    static DgnClassId QueryClassId(DgnDbR db) { return DgnClassId(db.Schemas().GetECClassId(BIS_ECSCHEMA_NAME, BIS_CLASS_DrawingViewDefinition)); }
};

//=======================================================================================
//! Defines a view of a SheetModel
// @bsiclass                                                      Paul.Connelly   10/15
//=======================================================================================
struct EXPORT_VTABLE_ATTRIBUTE SheetViewDefinition : ViewDefinition2d
{
    DGNELEMENT_DECLARE_MEMBERS(BIS_CLASS_SheetViewDefinition, ViewDefinition2d);
    friend struct dgn_ElementHandler::SheetViewDef;
public:
    //! Parameters used to construct a SheetViewDefinition
    struct CreateParams : T_Super::CreateParams
    {
        DEFINE_T_SUPER(SheetViewDefinition::T_Super::CreateParams);
    protected:
        CreateParams(DgnDbR db, DgnCode const& code, DgnClassId classId) : T_Super(db, code, classId) { }
    public:
        //! Constructor from base params. Chiefly for internal use.
        explicit CreateParams(DgnElement::CreateParams const& params) : T_Super(params) { }
        //! Constructor
        CreateParams(DgnDbR db, Utf8StringCR name) : CreateParams(db, ViewDefinition::CreateCode(name), SheetViewDefinition::QueryClassId(db)) { }
    };
protected:
    DGNPLATFORM_EXPORT ViewControllerPtr _SupplyController() const override;

    virtual SheetViewDefinitionCP _ToSheetView() const { return this; }
    
    //! Construct a SheetViewDefinition from the supplied params
    explicit SheetViewDefinition(CreateParams const& params) : T_Super(params) {}
public:
    //! Construct a SheetViewDefinition
    SheetViewDefinition(CreateParams const& params, DgnModelId baseModelId) : T_Super(params, baseModelId) {;}

    //! Look up the ECClass ID used for SheetViewDefinitions in the specified DgnDb
    static DgnClassId QueryClassId(DgnDbR db) { return DgnClassId(db.Schemas().GetECClassId(BIS_ECSCHEMA_NAME, BIS_CLASS_SheetViewDefinition)); }
};

//=======================================================================================
//! Defines a view of a RedlineModel
// @bsiclass                                                      Paul.Connelly   10/15
//=======================================================================================
struct EXPORT_VTABLE_ATTRIBUTE RedlineViewDefinition : SheetViewDefinition
{
    DGNELEMENT_DECLARE_MEMBERS(MARKUP_CLASSNAME_RedlineViewDefinition, SheetViewDefinition);
    friend struct dgn_ElementHandler::RedlineViewDef;
public:
    //! Parameters used to construct a RedlineViewDefinition
    struct CreateParams : T_Super::CreateParams
    {
        DEFINE_T_SUPER(RedlineViewDefinition::T_Super::CreateParams);
    protected:
        CreateParams(DgnDbR db, DgnCode const& code, DgnClassId classId) : T_Super(db, code, classId) { }
    public:
        //! Constructor from base params. Chiefly for internal use.
        explicit CreateParams(DgnElement::CreateParams const& params) : T_Super(params) { }
        //! Constructor
        CreateParams(DgnDbR db, Utf8StringCR name) : CreateParams(db, ViewDefinition::CreateCode(name), RedlineViewDefinition::QueryClassId(db)) { }
    };

protected:
    //! Construct a RedlineViewDefinition from the supplied params
    explicit RedlineViewDefinition(CreateParams const& params) : T_Super(params) { }

public:
    //! Construct a RedlineViewDefinition
    RedlineViewDefinition(CreateParams const& params, DgnModelId baseModelId) : T_Super(params, baseModelId) {;}

    //! Look up the ECClass ID used for RedlineViewDefinitions in the specified DgnDb
    static DgnClassId QueryClassId(DgnDbR db) { return DgnClassId(db.Schemas().GetECClassId(MARKUP_SCHEMA_NAME, MARKUP_CLASSNAME_RedlineViewDefinition)); }
};

namespace dgn_ElementHandler
{
    //=======================================================================================
    //! The handler for OrthographicViewDefinition elements
    // @bsiclass                                                      Paul.Connelly   10/15
    //=======================================================================================
    struct OrthographicViewDef : Definition
        {
        ELEMENTHANDLER_DECLARE_MEMBERS(BIS_CLASS_OrthographicViewDefinition, OrthographicViewDefinition, OrthographicViewDef, Definition, DGNPLATFORM_EXPORT);
        };

    //=======================================================================================
    //! The handler for CameraViewDefinition elements
    // @bsiclass                                                      Paul.Connelly   10/15
    //=======================================================================================
    struct CameraViewDef : Definition
    {
        ELEMENTHANDLER_DECLARE_MEMBERS(BIS_CLASS_CameraViewDefinition, CameraViewDefinition, CameraViewDef, Definition, DGNPLATFORM_EXPORT);
    };

    //=======================================================================================
    //! The handler for DrawingViewDefinition elements
    // @bsiclass                                                      Paul.Connelly   10/15
    //=======================================================================================
    struct DrawingViewDef : Definition
    {
        ELEMENTHANDLER_DECLARE_MEMBERS(BIS_CLASS_DrawingViewDefinition, DrawingViewDefinition, DrawingViewDef, Definition, DGNPLATFORM_EXPORT);
    };

    //=======================================================================================
    //! The handler for SheetViewDefinition elements
    // @bsiclass                                                      Paul.Connelly   10/15
    //=======================================================================================
    struct SheetViewDef : Definition
    {
        ELEMENTHANDLER_DECLARE_MEMBERS(BIS_CLASS_SheetViewDefinition, SheetViewDefinition, SheetViewDef, Definition, DGNPLATFORM_EXPORT);
    };

    //=======================================================================================
    //! The handler for RedlineViewDefinition elements
    // @bsiclass                                                      Paul.Connelly   10/15
    //=======================================================================================
    struct RedlineViewDef : SheetViewDef
    {
    ELEMENTHANDLER_DECLARE_MEMBERS(MARKUP_CLASSNAME_RedlineViewDefinition, RedlineViewDefinition, RedlineViewDef, SheetViewDef, DGNPLATFORM_EXPORT);
    };
};

typedef dgn_ElementHandler::DrawingViewDef DrawingViewHandler;
typedef dgn_ElementHandler::SheetViewDef SheetViewHandler;

//=======================================================================================
//! Handler extension applied to a ViewDefinition handler to override the type of
//! ViewController supplied for ViewDefinitions of that handler's type.
// @bsiclass                                                      Paul.Connelly   10/15
//=======================================================================================
struct EXPORT_VTABLE_ATTRIBUTE ViewControllerOverride : DgnDomain::Handler::Extension
{
    HANDLER_EXTENSION_DECLARE_MEMBERS(ViewControllerOverride, DGNPLATFORM_EXPORT);
public:
    //! @param[in] view The ViewDefinition
    //! @return an instance of a ViewController for the supplied ViewDefinition, or nullptr if the ViewDefinition is not of interest.
    virtual ViewControllerPtr _SupplyController(ViewDefinitionCR view) = 0;
};

ENUM_IS_FLAGS(ViewDefinition::Iterator::Options::Source);

END_BENTLEY_DGN_NAMESPACE

