#ifndef COMMONCLASSES_INTERFACE_111103
#define COMMONCLASSES_INTERFACE_111103

#ifdef COMMONCLASSES_EXPORTS
#define CCLASSES_API EXPORT_ATTRIBUTE
#else
	#ifdef POINTOOLS_API_INCLUDE
		#define CCLASSES_API 
	#else
		#define CCLASSES_API IMPORT_ATTRIBUTE
	#endif
#endif

#endif