/*--------------------------------------------------------------------------------------+
|
|     $Source: ConnectC/CWSCCGen.cpp $
|
|  $Copyright: (c) 2016 Bentley Systems, Incorporated. All rights reserved. $
|
+--------------------------------------------------------------------------------------*/
#pragma once
//--------------------------------------------------------------------------------------+
// <auto-generated>
//     This code was generated by the pyApiGen tool on April 21, 2016.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//--------------------------------------------------------------------------------------+

#include "CWSCCInternal.h"

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
static std::wstring guidToString(LPCGUID guid)
    {
    WCHAR stringBuf[4096];
    if (0 == StringFromGUID2(*guid, stringBuf, _countof(stringBuf)))
        return std::wstring();
    return std::wstring(stringBuf, _countof(stringBuf) - 1);
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CALLSTATUS wsresultToConnectWebServicesClientCStatus(WSError::Id errorId, Utf8StringCR errorMessage, Utf8StringCR errorDescription)
    {
    switch(errorId)
        {
        case WSError::Id::Unknown:
            return CALLSTATUS {ERROR500, errorMessage.c_str(), errorDescription.c_str()};
        case WSError::Id::RepositoryNotFound:
            return CALLSTATUS {ERROR400, errorMessage.c_str(), errorDescription.c_str()};
        case WSError::Id::SchemaNotFound:
            return CALLSTATUS {ERROR400, errorMessage.c_str(), errorDescription.c_str()};
        case WSError::Id::ClassNotFound:
            return CALLSTATUS {ERROR400, errorMessage.c_str(), errorDescription.c_str()};
        case WSError::Id::PropertyNotFound:
            return CALLSTATUS {ERROR404, errorMessage.c_str(), errorDescription.c_str()};
        case WSError::Id::InstanceNotFound:
            return CALLSTATUS {ERROR404, errorMessage.c_str(), errorDescription.c_str()};
        case WSError::Id::NotSupported:
            return CALLSTATUS {ERROR400, errorMessage.c_str(), errorDescription.c_str()};
        case WSError::Id::ServerError:
            return CALLSTATUS {ERROR500, errorMessage.c_str(), errorDescription.c_str()};
        case WSError::Id::BadRequest:
            return CALLSTATUS {ERROR400, errorMessage.c_str(), errorDescription.c_str()};
        case WSError::Id::Conflict:
            return CALLSTATUS {ERROR409, errorMessage.c_str(), errorDescription.c_str()};
        default:
            return CALLSTATUS {ERROR500, errorMessage.c_str(), errorDescription.c_str()};
        }
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CALLSTATUS ConnectWebServicesClientC_FreeApi(CWSCCHANDLE apiHandle)
    {
    if (NULL == apiHandle)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "The apiHandle passed into the function is NULL."};

    LPCWSCC api = (LPCWSCC) apiHandle;
    free(api);
    return CALLSTATUS {SUCCESS, "Successful operation", "The ConnectWebServicesClientC_FreeApi completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_ReadConnectUserList
(
CWSCCHANDLE apiHandle,
CWSCCDATABUFHANDLE* connectuserBuffer
)
    {
    VERIFY_API

    if (connectuserBuffer == NULL)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "connectuserBuffer is NULL."};

    auto result = api->m_wsRepositoryClientPtr->SendQueryRequest(WSQuery("GlobalSchema", "ConnectUser"))->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    int instanceCount = 0;
    for (WSObjectsReader::Instance instance : result.GetValue().GetInstances())
        instanceCount++;
    LPCWSCCCONNECTUSERBUFFER connectuserBuf = (LPCWSCCCONNECTUSERBUFFER) calloc(instanceCount, sizeof(CWSCCCONNECTUSERBUFFER));
    instanceCount = 0;
    for (WSObjectsReader::Instance instance : result.GetValue().GetInstances())
        {
        LPCWSCCCONNECTUSERBUFFER bufToFill = connectuserBuf + instanceCount++;
        ConnectUserBufferStuffer(bufToFill, instance.GetProperties());
        }

    CWSCCBUFFER* buf = (CWSCCBUFFER*) calloc(1, sizeof(CWSCCBUFFER));
    if (buf == NULL)
        {
        free(connectuserBuf);
        return CALLSTATUS {INTERNAL_MEMORY_ERROR, "Memory failed to initialize interally.", "Failed to calloc memory for CWSCCBUFFER."};
        }

    buf->lCount = instanceCount;
    buf->lType = BUFF_TYPE_CONNECTUSER;
    buf->lpItems = connectuserBuf;

    *connectuserBuffer = (CWSCCDATABUFHANDLE) buf;

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_ReadConnectUserList completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_CreateConnectUser
(
CWSCCHANDLE apiHandle,
LPCWSTR UserName,
LPCWSTR UserEmail,
LPGUID ConnectOrgGuid,
LPCWSTR UltimateSiteId,
LPCWSTR OrgName
)
    {
    VERIFY_API

    Json::Value instance;
    instance["schemaName"] = "GlobalSchema";
    instance["className"] = "ConnectUser";

    Json::Value propertiesJson;
    if (UserName != NULL) propertiesJson["UserName"] = Utf8String(UserName);
    if (UserEmail != NULL) propertiesJson["UserEmail"] = Utf8String(UserEmail);
    if (ConnectOrgGuid != NULL) propertiesJson["ConnectOrgGuid"] = *guidToString(ConnectOrgGuid).c_str();
    if (UltimateSiteId != NULL) propertiesJson["UltimateSiteId"] = Utf8String(UltimateSiteId);
    if (OrgName != NULL) propertiesJson["OrgName"] = Utf8String(OrgName);
    if (propertiesJson.size() == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "There were not any valid ConnectUser properties passed in."};
    instance["properties"] = propertiesJson;

    Json::Value objectCreationJson;
    objectCreationJson["instance"] = instance;

    auto result = api->m_wsRepositoryClientPtr->SendCreateObjectRequest(objectCreationJson)->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_CreateConnectUser completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_ReadConnectUser
(
CWSCCHANDLE apiHandle,
LPCWSTR connectuserId,
CWSCCDATABUFHANDLE* connectuserBuffer
)
    {
    VERIFY_API

    if (connectuserBuffer == NULL || connectuserId == NULL || wcslen(connectuserId) == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "connectuserBuffer is NULL or connectuserId is NULL or empty."};

    auto result = api->m_wsRepositoryClientPtr->SendGetObjectRequest({"GlobalSchema", "ConnectUser", Utf8String(connectuserId)})->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    LPCWSCCCONNECTUSERBUFFER connectuserBuf = (LPCWSCCCONNECTUSERBUFFER) calloc(1, sizeof(CWSCCCONNECTUSERBUFFER));
    ConnectUserBufferStuffer(connectuserBuf, (*result.GetValue().GetInstances().begin()).GetProperties());

    CWSCCBUFFER* buf = (CWSCCBUFFER*) calloc(1, sizeof(CWSCCBUFFER));
    if (buf == NULL)
        {
        free(connectuserBuf);
        return CALLSTATUS {INTERNAL_MEMORY_ERROR, "Memory failed to initialize interally.", "Failed to calloc memory for CWSCCBUFFER."};
        }

    buf->lCount = 1;
    buf->lType = BUFF_TYPE_CONNECTUSER;
    buf->lpItems = connectuserBuf;

    *connectuserBuffer = (CWSCCDATABUFHANDLE) buf;

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_ReadConnectUser completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_UpdateConnectUser
(
CWSCCHANDLE apiHandle,
LPCWSTR connectuserId,
LPCWSTR UserName,
LPCWSTR UserEmail,
LPGUID ConnectOrgGuid,
LPCWSTR UltimateSiteId,
LPCWSTR OrgName
)
    {
    VERIFY_API

    Json::Value propertiesJson;
    if (UserName != NULL) propertiesJson["UserName"] = Utf8String(UserName);
    if (UserEmail != NULL) propertiesJson["UserEmail"] = Utf8String(UserEmail);
    if (ConnectOrgGuid != NULL) propertiesJson["ConnectOrgGuid"] = *guidToString(ConnectOrgGuid).c_str();
    if (UltimateSiteId != NULL) propertiesJson["UltimateSiteId"] = Utf8String(UltimateSiteId);
    if (OrgName != NULL) propertiesJson["OrgName"] = Utf8String(OrgName);
    if (propertiesJson.size() == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "There were not any valid ConnectUser properties passed in."};

    auto result = api->m_wsRepositoryClientPtr->SendUpdateObjectRequest({"GlobalSchema", "ConnectUser", Utf8String(connectuserId)}, propertiesJson)->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_UpdateConnectUser completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_DeleteConnectUser
(
CWSCCHANDLE apiHandle,
LPCWSTR connectuserId
)
    {
    VERIFY_API

    if (connectuserId == NULL || wcslen(connectuserId) == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "connectuserId is NULL or empty."};

    auto result = api->m_wsRepositoryClientPtr->SendDeleteObjectRequest({"GlobalSchema", "ConnectUser", Utf8String(connectuserId)})->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_DeleteConnectUser completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_ReadOrganizationList
(
CWSCCHANDLE apiHandle,
CWSCCDATABUFHANDLE* organizationBuffer
)
    {
    VERIFY_API

    if (organizationBuffer == NULL)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "organizationBuffer is NULL."};

    auto result = api->m_wsRepositoryClientPtr->SendQueryRequest(WSQuery("GlobalSchema", "Organization"))->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    int instanceCount = 0;
    for (WSObjectsReader::Instance instance : result.GetValue().GetInstances())
        instanceCount++;
    LPCWSCCORGANIZATIONBUFFER organizationBuf = (LPCWSCCORGANIZATIONBUFFER) calloc(instanceCount, sizeof(CWSCCORGANIZATIONBUFFER));
    instanceCount = 0;
    for (WSObjectsReader::Instance instance : result.GetValue().GetInstances())
        {
        LPCWSCCORGANIZATIONBUFFER bufToFill = organizationBuf + instanceCount++;
        OrganizationBufferStuffer(bufToFill, instance.GetProperties());
        }

    CWSCCBUFFER* buf = (CWSCCBUFFER*) calloc(1, sizeof(CWSCCBUFFER));
    if (buf == NULL)
        {
        free(organizationBuf);
        return CALLSTATUS {INTERNAL_MEMORY_ERROR, "Memory failed to initialize interally.", "Failed to calloc memory for CWSCCBUFFER."};
        }

    buf->lCount = instanceCount;
    buf->lType = BUFF_TYPE_ORGANIZATION;
    buf->lpItems = organizationBuf;

    *organizationBuffer = (CWSCCDATABUFHANDLE) buf;

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_ReadOrganizationList completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_CreateOrganization
(
CWSCCHANDLE apiHandle,
LPGUID OrganizationGuid,
LPCWSTR OrganizationName
)
    {
    VERIFY_API

    Json::Value instance;
    instance["schemaName"] = "GlobalSchema";
    instance["className"] = "Organization";

    Json::Value propertiesJson;
    if (OrganizationGuid != NULL) propertiesJson["OrganizationGuid"] = *guidToString(OrganizationGuid).c_str();
    if (OrganizationName != NULL) propertiesJson["OrganizationName"] = Utf8String(OrganizationName);
    if (propertiesJson.size() == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "There were not any valid Organization properties passed in."};
    instance["properties"] = propertiesJson;

    Json::Value objectCreationJson;
    objectCreationJson["instance"] = instance;

    auto result = api->m_wsRepositoryClientPtr->SendCreateObjectRequest(objectCreationJson)->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_CreateOrganization completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_ReadOrganization
(
CWSCCHANDLE apiHandle,
LPCWSTR organizationId,
CWSCCDATABUFHANDLE* organizationBuffer
)
    {
    VERIFY_API

    if (organizationBuffer == NULL || organizationId == NULL || wcslen(organizationId) == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "organizationBuffer is NULL or organizationId is NULL or empty."};

    auto result = api->m_wsRepositoryClientPtr->SendGetObjectRequest({"GlobalSchema", "Organization", Utf8String(organizationId)})->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    LPCWSCCORGANIZATIONBUFFER organizationBuf = (LPCWSCCORGANIZATIONBUFFER) calloc(1, sizeof(CWSCCORGANIZATIONBUFFER));
    OrganizationBufferStuffer(organizationBuf, (*result.GetValue().GetInstances().begin()).GetProperties());

    CWSCCBUFFER* buf = (CWSCCBUFFER*) calloc(1, sizeof(CWSCCBUFFER));
    if (buf == NULL)
        {
        free(organizationBuf);
        return CALLSTATUS {INTERNAL_MEMORY_ERROR, "Memory failed to initialize interally.", "Failed to calloc memory for CWSCCBUFFER."};
        }

    buf->lCount = 1;
    buf->lType = BUFF_TYPE_ORGANIZATION;
    buf->lpItems = organizationBuf;

    *organizationBuffer = (CWSCCDATABUFHANDLE) buf;

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_ReadOrganization completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_UpdateOrganization
(
CWSCCHANDLE apiHandle,
LPCWSTR organizationId,
LPGUID OrganizationGuid,
LPCWSTR OrganizationName
)
    {
    VERIFY_API

    Json::Value propertiesJson;
    if (OrganizationGuid != NULL) propertiesJson["OrganizationGuid"] = *guidToString(OrganizationGuid).c_str();
    if (OrganizationName != NULL) propertiesJson["OrganizationName"] = Utf8String(OrganizationName);
    if (propertiesJson.size() == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "There were not any valid Organization properties passed in."};

    auto result = api->m_wsRepositoryClientPtr->SendUpdateObjectRequest({"GlobalSchema", "Organization", Utf8String(organizationId)}, propertiesJson)->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_UpdateOrganization completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_DeleteOrganization
(
CWSCCHANDLE apiHandle,
LPCWSTR organizationId
)
    {
    VERIFY_API

    if (organizationId == NULL || wcslen(organizationId) == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "organizationId is NULL or empty."};

    auto result = api->m_wsRepositoryClientPtr->SendDeleteObjectRequest({"GlobalSchema", "Organization", Utf8String(organizationId)})->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_DeleteOrganization completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_ReadProjectList
(
CWSCCHANDLE apiHandle,
CWSCCDATABUFHANDLE* projectBuffer
)
    {
    VERIFY_API

    if (projectBuffer == NULL)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "projectBuffer is NULL."};

    auto result = api->m_wsRepositoryClientPtr->SendQueryRequest(WSQuery("GlobalSchema", "Project"))->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    int instanceCount = 0;
    for (WSObjectsReader::Instance instance : result.GetValue().GetInstances())
        instanceCount++;
    LPCWSCCPROJECTBUFFER projectBuf = (LPCWSCCPROJECTBUFFER) calloc(instanceCount, sizeof(CWSCCPROJECTBUFFER));
    instanceCount = 0;
    for (WSObjectsReader::Instance instance : result.GetValue().GetInstances())
        {
        LPCWSCCPROJECTBUFFER bufToFill = projectBuf + instanceCount++;
        ProjectBufferStuffer(bufToFill, instance.GetProperties());
        }

    CWSCCBUFFER* buf = (CWSCCBUFFER*) calloc(1, sizeof(CWSCCBUFFER));
    if (buf == NULL)
        {
        free(projectBuf);
        return CALLSTATUS {INTERNAL_MEMORY_ERROR, "Memory failed to initialize interally.", "Failed to calloc memory for CWSCCBUFFER."};
        }

    buf->lCount = instanceCount;
    buf->lType = BUFF_TYPE_PROJECT;
    buf->lpItems = projectBuf;

    *projectBuffer = (CWSCCDATABUFHANDLE) buf;

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_ReadProjectList completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_CreateProject
(
CWSCCHANDLE apiHandle,
LPCWSTR Name,
LPCWSTR Number,
LPCWSTR OrganizationId,
bool* Active,
LPCWSTR Industry,
LPCWSTR AssetType,
LPCWSTR LastModified,
LPCWSTR Location,
double* Latitude,
double* Longitude,
bool* LocationIsUsingLatLong,
LPCWSTR RegisteredDate,
LPCWSTR TimeZoneLocation,
int* Status,
LPCWSTR PWDMInvitationId
)
    {
    VERIFY_API

    Json::Value instance;
    instance["schemaName"] = "GlobalSchema";
    instance["className"] = "Project";

    Json::Value propertiesJson;
    if (Name != NULL) propertiesJson["Name"] = Utf8String(Name);
    if (Number != NULL) propertiesJson["Number"] = Utf8String(Number);
    if (OrganizationId != NULL) propertiesJson["OrganizationId"] = Utf8String(OrganizationId);
    if (Active != NULL) propertiesJson["Active"] = *Active;
    if (Industry != NULL) propertiesJson["Industry"] = Utf8String(Industry);
    if (AssetType != NULL) propertiesJson["AssetType"] = Utf8String(AssetType);
    if (LastModified != NULL) propertiesJson["LastModified"] = Utf8String(LastModified);
    if (Location != NULL) propertiesJson["Location"] = Utf8String(Location);
    if (Latitude != NULL) propertiesJson["Latitude"] = *Latitude;
    if (Longitude != NULL) propertiesJson["Longitude"] = *Longitude;
    if (LocationIsUsingLatLong != NULL) propertiesJson["LocationIsUsingLatLong"] = *LocationIsUsingLatLong;
    if (RegisteredDate != NULL) propertiesJson["RegisteredDate"] = Utf8String(RegisteredDate);
    if (TimeZoneLocation != NULL) propertiesJson["TimeZoneLocation"] = Utf8String(TimeZoneLocation);
    if (Status != NULL) propertiesJson["Status"] = *Status;
    if (PWDMInvitationId != NULL) propertiesJson["PWDMInvitationId"] = Utf8String(PWDMInvitationId);
    if (propertiesJson.size() == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "There were not any valid Project properties passed in."};
    instance["properties"] = propertiesJson;

    Json::Value objectCreationJson;
    objectCreationJson["instance"] = instance;

    auto result = api->m_wsRepositoryClientPtr->SendCreateObjectRequest(objectCreationJson)->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_CreateProject completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_ReadProject
(
CWSCCHANDLE apiHandle,
LPCWSTR projectId,
CWSCCDATABUFHANDLE* projectBuffer
)
    {
    VERIFY_API

    if (projectBuffer == NULL || projectId == NULL || wcslen(projectId) == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "projectBuffer is NULL or projectId is NULL or empty."};

    auto result = api->m_wsRepositoryClientPtr->SendGetObjectRequest({"GlobalSchema", "Project", Utf8String(projectId)})->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    LPCWSCCPROJECTBUFFER projectBuf = (LPCWSCCPROJECTBUFFER) calloc(1, sizeof(CWSCCPROJECTBUFFER));
    ProjectBufferStuffer(projectBuf, (*result.GetValue().GetInstances().begin()).GetProperties());

    CWSCCBUFFER* buf = (CWSCCBUFFER*) calloc(1, sizeof(CWSCCBUFFER));
    if (buf == NULL)
        {
        free(projectBuf);
        return CALLSTATUS {INTERNAL_MEMORY_ERROR, "Memory failed to initialize interally.", "Failed to calloc memory for CWSCCBUFFER."};
        }

    buf->lCount = 1;
    buf->lType = BUFF_TYPE_PROJECT;
    buf->lpItems = projectBuf;

    *projectBuffer = (CWSCCDATABUFHANDLE) buf;

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_ReadProject completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_UpdateProject
(
CWSCCHANDLE apiHandle,
LPCWSTR projectId,
LPCWSTR Name,
LPCWSTR Number,
LPCWSTR OrganizationId,
bool* Active,
LPCWSTR Industry,
LPCWSTR AssetType,
LPCWSTR LastModified,
LPCWSTR Location,
double* Latitude,
double* Longitude,
bool* LocationIsUsingLatLong,
LPCWSTR RegisteredDate,
LPCWSTR TimeZoneLocation,
int* Status,
LPCWSTR PWDMInvitationId
)
    {
    VERIFY_API

    Json::Value propertiesJson;
    if (Name != NULL) propertiesJson["Name"] = Utf8String(Name);
    if (Number != NULL) propertiesJson["Number"] = Utf8String(Number);
    if (OrganizationId != NULL) propertiesJson["OrganizationId"] = Utf8String(OrganizationId);
    if (Active != NULL) propertiesJson["Active"] = *Active;
    if (Industry != NULL) propertiesJson["Industry"] = Utf8String(Industry);
    if (AssetType != NULL) propertiesJson["AssetType"] = Utf8String(AssetType);
    if (LastModified != NULL) propertiesJson["LastModified"] = Utf8String(LastModified);
    if (Location != NULL) propertiesJson["Location"] = Utf8String(Location);
    if (Latitude != NULL) propertiesJson["Latitude"] = *Latitude;
    if (Longitude != NULL) propertiesJson["Longitude"] = *Longitude;
    if (LocationIsUsingLatLong != NULL) propertiesJson["LocationIsUsingLatLong"] = *LocationIsUsingLatLong;
    if (RegisteredDate != NULL) propertiesJson["RegisteredDate"] = Utf8String(RegisteredDate);
    if (TimeZoneLocation != NULL) propertiesJson["TimeZoneLocation"] = Utf8String(TimeZoneLocation);
    if (Status != NULL) propertiesJson["Status"] = *Status;
    if (PWDMInvitationId != NULL) propertiesJson["PWDMInvitationId"] = Utf8String(PWDMInvitationId);
    if (propertiesJson.size() == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "There were not any valid Project properties passed in."};

    auto result = api->m_wsRepositoryClientPtr->SendUpdateObjectRequest({"GlobalSchema", "Project", Utf8String(projectId)}, propertiesJson)->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_UpdateProject completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_DeleteProject
(
CWSCCHANDLE apiHandle,
LPCWSTR projectId
)
    {
    VERIFY_API

    if (projectId == NULL || wcslen(projectId) == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "projectId is NULL or empty."};

    auto result = api->m_wsRepositoryClientPtr->SendDeleteObjectRequest({"GlobalSchema", "Project", Utf8String(projectId)})->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_DeleteProject completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_ReadProjectFavoriteList
(
CWSCCHANDLE apiHandle,
CWSCCDATABUFHANDLE* projectfavoriteBuffer
)
    {
    VERIFY_API

    if (projectfavoriteBuffer == NULL)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "projectfavoriteBuffer is NULL."};

    auto result = api->m_wsRepositoryClientPtr->SendQueryRequest(WSQuery("GlobalSchema", "ProjectFavorite"))->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    int instanceCount = 0;
    for (WSObjectsReader::Instance instance : result.GetValue().GetInstances())
        instanceCount++;
    LPCWSCCPROJECTFAVORITEBUFFER projectfavoriteBuf = (LPCWSCCPROJECTFAVORITEBUFFER) calloc(instanceCount, sizeof(CWSCCPROJECTFAVORITEBUFFER));
    instanceCount = 0;
    for (WSObjectsReader::Instance instance : result.GetValue().GetInstances())
        {
        LPCWSCCPROJECTFAVORITEBUFFER bufToFill = projectfavoriteBuf + instanceCount++;
        ProjectFavoriteBufferStuffer(bufToFill, instance.GetProperties());
        }

    CWSCCBUFFER* buf = (CWSCCBUFFER*) calloc(1, sizeof(CWSCCBUFFER));
    if (buf == NULL)
        {
        free(projectfavoriteBuf);
        return CALLSTATUS {INTERNAL_MEMORY_ERROR, "Memory failed to initialize interally.", "Failed to calloc memory for CWSCCBUFFER."};
        }

    buf->lCount = instanceCount;
    buf->lType = BUFF_TYPE_PROJECTFAVORITE;
    buf->lpItems = projectfavoriteBuf;

    *projectfavoriteBuffer = (CWSCCDATABUFHANDLE) buf;

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_ReadProjectFavoriteList completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_CreateProjectFavorite
(
CWSCCHANDLE apiHandle,
LPCWSTR Name,
LPCWSTR Number,
LPCWSTR OrganizationId,
bool* Active,
LPCWSTR Industry,
LPCWSTR AssetType,
LPCWSTR LastModified,
LPCWSTR Location,
double* Latitude,
double* Longitude,
bool* LocationIsUsingLatLong,
LPCWSTR RegisteredDate,
LPCWSTR TimeZoneLocation,
int* Status,
LPCWSTR PWDMInvitationId
)
    {
    VERIFY_API

    Json::Value instance;
    instance["schemaName"] = "GlobalSchema";
    instance["className"] = "ProjectFavorite";

    Json::Value propertiesJson;
    if (Name != NULL) propertiesJson["Name"] = Utf8String(Name);
    if (Number != NULL) propertiesJson["Number"] = Utf8String(Number);
    if (OrganizationId != NULL) propertiesJson["OrganizationId"] = Utf8String(OrganizationId);
    if (Active != NULL) propertiesJson["Active"] = *Active;
    if (Industry != NULL) propertiesJson["Industry"] = Utf8String(Industry);
    if (AssetType != NULL) propertiesJson["AssetType"] = Utf8String(AssetType);
    if (LastModified != NULL) propertiesJson["LastModified"] = Utf8String(LastModified);
    if (Location != NULL) propertiesJson["Location"] = Utf8String(Location);
    if (Latitude != NULL) propertiesJson["Latitude"] = *Latitude;
    if (Longitude != NULL) propertiesJson["Longitude"] = *Longitude;
    if (LocationIsUsingLatLong != NULL) propertiesJson["LocationIsUsingLatLong"] = *LocationIsUsingLatLong;
    if (RegisteredDate != NULL) propertiesJson["RegisteredDate"] = Utf8String(RegisteredDate);
    if (TimeZoneLocation != NULL) propertiesJson["TimeZoneLocation"] = Utf8String(TimeZoneLocation);
    if (Status != NULL) propertiesJson["Status"] = *Status;
    if (PWDMInvitationId != NULL) propertiesJson["PWDMInvitationId"] = Utf8String(PWDMInvitationId);
    if (propertiesJson.size() == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "There were not any valid ProjectFavorite properties passed in."};
    instance["properties"] = propertiesJson;

    Json::Value objectCreationJson;
    objectCreationJson["instance"] = instance;

    auto result = api->m_wsRepositoryClientPtr->SendCreateObjectRequest(objectCreationJson)->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_CreateProjectFavorite completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_ReadProjectFavorite
(
CWSCCHANDLE apiHandle,
LPCWSTR projectfavoriteId,
CWSCCDATABUFHANDLE* projectfavoriteBuffer
)
    {
    VERIFY_API

    if (projectfavoriteBuffer == NULL || projectfavoriteId == NULL || wcslen(projectfavoriteId) == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "projectfavoriteBuffer is NULL or projectfavoriteId is NULL or empty."};

    auto result = api->m_wsRepositoryClientPtr->SendGetObjectRequest({"GlobalSchema", "ProjectFavorite", Utf8String(projectfavoriteId)})->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    LPCWSCCPROJECTFAVORITEBUFFER projectfavoriteBuf = (LPCWSCCPROJECTFAVORITEBUFFER) calloc(1, sizeof(CWSCCPROJECTFAVORITEBUFFER));
    ProjectFavoriteBufferStuffer(projectfavoriteBuf, (*result.GetValue().GetInstances().begin()).GetProperties());

    CWSCCBUFFER* buf = (CWSCCBUFFER*) calloc(1, sizeof(CWSCCBUFFER));
    if (buf == NULL)
        {
        free(projectfavoriteBuf);
        return CALLSTATUS {INTERNAL_MEMORY_ERROR, "Memory failed to initialize interally.", "Failed to calloc memory for CWSCCBUFFER."};
        }

    buf->lCount = 1;
    buf->lType = BUFF_TYPE_PROJECTFAVORITE;
    buf->lpItems = projectfavoriteBuf;

    *projectfavoriteBuffer = (CWSCCDATABUFHANDLE) buf;

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_ReadProjectFavorite completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_UpdateProjectFavorite
(
CWSCCHANDLE apiHandle,
LPCWSTR projectfavoriteId,
LPCWSTR Name,
LPCWSTR Number,
LPCWSTR OrganizationId,
bool* Active,
LPCWSTR Industry,
LPCWSTR AssetType,
LPCWSTR LastModified,
LPCWSTR Location,
double* Latitude,
double* Longitude,
bool* LocationIsUsingLatLong,
LPCWSTR RegisteredDate,
LPCWSTR TimeZoneLocation,
int* Status,
LPCWSTR PWDMInvitationId
)
    {
    VERIFY_API

    Json::Value propertiesJson;
    if (Name != NULL) propertiesJson["Name"] = Utf8String(Name);
    if (Number != NULL) propertiesJson["Number"] = Utf8String(Number);
    if (OrganizationId != NULL) propertiesJson["OrganizationId"] = Utf8String(OrganizationId);
    if (Active != NULL) propertiesJson["Active"] = *Active;
    if (Industry != NULL) propertiesJson["Industry"] = Utf8String(Industry);
    if (AssetType != NULL) propertiesJson["AssetType"] = Utf8String(AssetType);
    if (LastModified != NULL) propertiesJson["LastModified"] = Utf8String(LastModified);
    if (Location != NULL) propertiesJson["Location"] = Utf8String(Location);
    if (Latitude != NULL) propertiesJson["Latitude"] = *Latitude;
    if (Longitude != NULL) propertiesJson["Longitude"] = *Longitude;
    if (LocationIsUsingLatLong != NULL) propertiesJson["LocationIsUsingLatLong"] = *LocationIsUsingLatLong;
    if (RegisteredDate != NULL) propertiesJson["RegisteredDate"] = Utf8String(RegisteredDate);
    if (TimeZoneLocation != NULL) propertiesJson["TimeZoneLocation"] = Utf8String(TimeZoneLocation);
    if (Status != NULL) propertiesJson["Status"] = *Status;
    if (PWDMInvitationId != NULL) propertiesJson["PWDMInvitationId"] = Utf8String(PWDMInvitationId);
    if (propertiesJson.size() == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "There were not any valid ProjectFavorite properties passed in."};

    auto result = api->m_wsRepositoryClientPtr->SendUpdateObjectRequest({"GlobalSchema", "ProjectFavorite", Utf8String(projectfavoriteId)}, propertiesJson)->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_UpdateProjectFavorite completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_DeleteProjectFavorite
(
CWSCCHANDLE apiHandle,
LPCWSTR projectfavoriteId
)
    {
    VERIFY_API

    if (projectfavoriteId == NULL || wcslen(projectfavoriteId) == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "projectfavoriteId is NULL or empty."};

    auto result = api->m_wsRepositoryClientPtr->SendDeleteObjectRequest({"GlobalSchema", "ProjectFavorite", Utf8String(projectfavoriteId)})->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_DeleteProjectFavorite completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_ReadProjectMRUList
(
CWSCCHANDLE apiHandle,
CWSCCDATABUFHANDLE* projectmruBuffer
)
    {
    VERIFY_API

    if (projectmruBuffer == NULL)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "projectmruBuffer is NULL."};

    auto result = api->m_wsRepositoryClientPtr->SendQueryRequest(WSQuery("GlobalSchema", "ProjectMRU"))->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    int instanceCount = 0;
    for (WSObjectsReader::Instance instance : result.GetValue().GetInstances())
        instanceCount++;
    LPCWSCCPROJECTMRUBUFFER projectmruBuf = (LPCWSCCPROJECTMRUBUFFER) calloc(instanceCount, sizeof(CWSCCPROJECTMRUBUFFER));
    instanceCount = 0;
    for (WSObjectsReader::Instance instance : result.GetValue().GetInstances())
        {
        LPCWSCCPROJECTMRUBUFFER bufToFill = projectmruBuf + instanceCount++;
        ProjectMRUBufferStuffer(bufToFill, instance.GetProperties());
        }

    CWSCCBUFFER* buf = (CWSCCBUFFER*) calloc(1, sizeof(CWSCCBUFFER));
    if (buf == NULL)
        {
        free(projectmruBuf);
        return CALLSTATUS {INTERNAL_MEMORY_ERROR, "Memory failed to initialize interally.", "Failed to calloc memory for CWSCCBUFFER."};
        }

    buf->lCount = instanceCount;
    buf->lType = BUFF_TYPE_PROJECTMRU;
    buf->lpItems = projectmruBuf;

    *projectmruBuffer = (CWSCCDATABUFHANDLE) buf;

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_ReadProjectMRUList completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_CreateProjectMRU
(
CWSCCHANDLE apiHandle,
LPCWSTR ProjectGuid,
LPCWSTR ProjectName,
LPCWSTR LastModified
)
    {
    VERIFY_API

    Json::Value instance;
    instance["schemaName"] = "GlobalSchema";
    instance["className"] = "ProjectMRU";

    Json::Value propertiesJson;
    if (ProjectGuid != NULL) propertiesJson["ProjectGuid"] = Utf8String(ProjectGuid);
    if (ProjectName != NULL) propertiesJson["ProjectName"] = Utf8String(ProjectName);
    if (LastModified != NULL) propertiesJson["LastModified"] = Utf8String(LastModified);
    if (propertiesJson.size() == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "There were not any valid ProjectMRU properties passed in."};
    instance["properties"] = propertiesJson;

    Json::Value objectCreationJson;
    objectCreationJson["instance"] = instance;

    auto result = api->m_wsRepositoryClientPtr->SendCreateObjectRequest(objectCreationJson)->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_CreateProjectMRU completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_ReadProjectMRU
(
CWSCCHANDLE apiHandle,
LPCWSTR projectmruId,
CWSCCDATABUFHANDLE* projectmruBuffer
)
    {
    VERIFY_API

    if (projectmruBuffer == NULL || projectmruId == NULL || wcslen(projectmruId) == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "projectmruBuffer is NULL or projectmruId is NULL or empty."};

    auto result = api->m_wsRepositoryClientPtr->SendGetObjectRequest({"GlobalSchema", "ProjectMRU", Utf8String(projectmruId)})->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    LPCWSCCPROJECTMRUBUFFER projectmruBuf = (LPCWSCCPROJECTMRUBUFFER) calloc(1, sizeof(CWSCCPROJECTMRUBUFFER));
    ProjectMRUBufferStuffer(projectmruBuf, (*result.GetValue().GetInstances().begin()).GetProperties());

    CWSCCBUFFER* buf = (CWSCCBUFFER*) calloc(1, sizeof(CWSCCBUFFER));
    if (buf == NULL)
        {
        free(projectmruBuf);
        return CALLSTATUS {INTERNAL_MEMORY_ERROR, "Memory failed to initialize interally.", "Failed to calloc memory for CWSCCBUFFER."};
        }

    buf->lCount = 1;
    buf->lType = BUFF_TYPE_PROJECTMRU;
    buf->lpItems = projectmruBuf;

    *projectmruBuffer = (CWSCCDATABUFHANDLE) buf;

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_ReadProjectMRU completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_UpdateProjectMRU
(
CWSCCHANDLE apiHandle,
LPCWSTR projectmruId,
LPCWSTR ProjectGuid,
LPCWSTR ProjectName,
LPCWSTR LastModified
)
    {
    VERIFY_API

    Json::Value propertiesJson;
    if (ProjectGuid != NULL) propertiesJson["ProjectGuid"] = Utf8String(ProjectGuid);
    if (ProjectName != NULL) propertiesJson["ProjectName"] = Utf8String(ProjectName);
    if (LastModified != NULL) propertiesJson["LastModified"] = Utf8String(LastModified);
    if (propertiesJson.size() == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "There were not any valid ProjectMRU properties passed in."};

    auto result = api->m_wsRepositoryClientPtr->SendUpdateObjectRequest({"GlobalSchema", "ProjectMRU", Utf8String(projectmruId)}, propertiesJson)->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_UpdateProjectMRU completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_DeleteProjectMRU
(
CWSCCHANDLE apiHandle,
LPCWSTR projectmruId
)
    {
    VERIFY_API

    if (projectmruId == NULL || wcslen(projectmruId) == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "projectmruId is NULL or empty."};

    auto result = api->m_wsRepositoryClientPtr->SendDeleteObjectRequest({"GlobalSchema", "ProjectMRU", Utf8String(projectmruId)})->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_DeleteProjectMRU completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_ReadProjectMRUDetailList
(
CWSCCHANDLE apiHandle,
CWSCCDATABUFHANDLE* projectmrudetailBuffer
)
    {
    VERIFY_API

    if (projectmrudetailBuffer == NULL)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "projectmrudetailBuffer is NULL."};

    auto result = api->m_wsRepositoryClientPtr->SendQueryRequest(WSQuery("GlobalSchema", "ProjectMRUDetail"))->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    int instanceCount = 0;
    for (WSObjectsReader::Instance instance : result.GetValue().GetInstances())
        instanceCount++;
    LPCWSCCPROJECTMRUDETAILBUFFER projectmrudetailBuf = (LPCWSCCPROJECTMRUDETAILBUFFER) calloc(instanceCount, sizeof(CWSCCPROJECTMRUDETAILBUFFER));
    instanceCount = 0;
    for (WSObjectsReader::Instance instance : result.GetValue().GetInstances())
        {
        LPCWSCCPROJECTMRUDETAILBUFFER bufToFill = projectmrudetailBuf + instanceCount++;
        ProjectMRUDetailBufferStuffer(bufToFill, instance.GetProperties());
        }

    CWSCCBUFFER* buf = (CWSCCBUFFER*) calloc(1, sizeof(CWSCCBUFFER));
    if (buf == NULL)
        {
        free(projectmrudetailBuf);
        return CALLSTATUS {INTERNAL_MEMORY_ERROR, "Memory failed to initialize interally.", "Failed to calloc memory for CWSCCBUFFER."};
        }

    buf->lCount = instanceCount;
    buf->lType = BUFF_TYPE_PROJECTMRUDETAIL;
    buf->lpItems = projectmrudetailBuf;

    *projectmrudetailBuffer = (CWSCCDATABUFHANDLE) buf;

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_ReadProjectMRUDetailList completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_CreateProjectMRUDetail
(
CWSCCHANDLE apiHandle,
bool* IsFavorite,
long* LastAccessedByUser,
LPCWSTR Name,
LPCWSTR Number,
LPCWSTR OrganizationId,
bool* Active,
LPCWSTR Industry,
LPCWSTR AssetType,
LPCWSTR LastModified,
LPCWSTR Location,
double* Latitude,
double* Longitude,
bool* LocationIsUsingLatLong,
LPCWSTR RegisteredDate,
LPCWSTR TimeZoneLocation,
int* Status,
LPCWSTR PWDMInvitationId
)
    {
    VERIFY_API

    Json::Value instance;
    instance["schemaName"] = "GlobalSchema";
    instance["className"] = "ProjectMRUDetail";

    Json::Value propertiesJson;
    if (IsFavorite != NULL) propertiesJson["IsFavorite"] = *IsFavorite;
    if (LastAccessedByUser != NULL) propertiesJson["LastAccessedByUser"] = *LastAccessedByUser;
    if (Name != NULL) propertiesJson["Name"] = Utf8String(Name);
    if (Number != NULL) propertiesJson["Number"] = Utf8String(Number);
    if (OrganizationId != NULL) propertiesJson["OrganizationId"] = Utf8String(OrganizationId);
    if (Active != NULL) propertiesJson["Active"] = *Active;
    if (Industry != NULL) propertiesJson["Industry"] = Utf8String(Industry);
    if (AssetType != NULL) propertiesJson["AssetType"] = Utf8String(AssetType);
    if (LastModified != NULL) propertiesJson["LastModified"] = Utf8String(LastModified);
    if (Location != NULL) propertiesJson["Location"] = Utf8String(Location);
    if (Latitude != NULL) propertiesJson["Latitude"] = *Latitude;
    if (Longitude != NULL) propertiesJson["Longitude"] = *Longitude;
    if (LocationIsUsingLatLong != NULL) propertiesJson["LocationIsUsingLatLong"] = *LocationIsUsingLatLong;
    if (RegisteredDate != NULL) propertiesJson["RegisteredDate"] = Utf8String(RegisteredDate);
    if (TimeZoneLocation != NULL) propertiesJson["TimeZoneLocation"] = Utf8String(TimeZoneLocation);
    if (Status != NULL) propertiesJson["Status"] = *Status;
    if (PWDMInvitationId != NULL) propertiesJson["PWDMInvitationId"] = Utf8String(PWDMInvitationId);
    if (propertiesJson.size() == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "There were not any valid ProjectMRUDetail properties passed in."};
    instance["properties"] = propertiesJson;

    Json::Value objectCreationJson;
    objectCreationJson["instance"] = instance;

    auto result = api->m_wsRepositoryClientPtr->SendCreateObjectRequest(objectCreationJson)->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_CreateProjectMRUDetail completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_ReadProjectMRUDetail
(
CWSCCHANDLE apiHandle,
LPCWSTR projectmrudetailId,
CWSCCDATABUFHANDLE* projectmrudetailBuffer
)
    {
    VERIFY_API

    if (projectmrudetailBuffer == NULL || projectmrudetailId == NULL || wcslen(projectmrudetailId) == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "projectmrudetailBuffer is NULL or projectmrudetailId is NULL or empty."};

    auto result = api->m_wsRepositoryClientPtr->SendGetObjectRequest({"GlobalSchema", "ProjectMRUDetail", Utf8String(projectmrudetailId)})->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    LPCWSCCPROJECTMRUDETAILBUFFER projectmrudetailBuf = (LPCWSCCPROJECTMRUDETAILBUFFER) calloc(1, sizeof(CWSCCPROJECTMRUDETAILBUFFER));
    ProjectMRUDetailBufferStuffer(projectmrudetailBuf, (*result.GetValue().GetInstances().begin()).GetProperties());

    CWSCCBUFFER* buf = (CWSCCBUFFER*) calloc(1, sizeof(CWSCCBUFFER));
    if (buf == NULL)
        {
        free(projectmrudetailBuf);
        return CALLSTATUS {INTERNAL_MEMORY_ERROR, "Memory failed to initialize interally.", "Failed to calloc memory for CWSCCBUFFER."};
        }

    buf->lCount = 1;
    buf->lType = BUFF_TYPE_PROJECTMRUDETAIL;
    buf->lpItems = projectmrudetailBuf;

    *projectmrudetailBuffer = (CWSCCDATABUFHANDLE) buf;

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_ReadProjectMRUDetail completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_UpdateProjectMRUDetail
(
CWSCCHANDLE apiHandle,
LPCWSTR projectmrudetailId,
bool* IsFavorite,
long* LastAccessedByUser,
LPCWSTR Name,
LPCWSTR Number,
LPCWSTR OrganizationId,
bool* Active,
LPCWSTR Industry,
LPCWSTR AssetType,
LPCWSTR LastModified,
LPCWSTR Location,
double* Latitude,
double* Longitude,
bool* LocationIsUsingLatLong,
LPCWSTR RegisteredDate,
LPCWSTR TimeZoneLocation,
int* Status,
LPCWSTR PWDMInvitationId
)
    {
    VERIFY_API

    Json::Value propertiesJson;
    if (IsFavorite != NULL) propertiesJson["IsFavorite"] = *IsFavorite;
    if (LastAccessedByUser != NULL) propertiesJson["LastAccessedByUser"] = *LastAccessedByUser;
    if (Name != NULL) propertiesJson["Name"] = Utf8String(Name);
    if (Number != NULL) propertiesJson["Number"] = Utf8String(Number);
    if (OrganizationId != NULL) propertiesJson["OrganizationId"] = Utf8String(OrganizationId);
    if (Active != NULL) propertiesJson["Active"] = *Active;
    if (Industry != NULL) propertiesJson["Industry"] = Utf8String(Industry);
    if (AssetType != NULL) propertiesJson["AssetType"] = Utf8String(AssetType);
    if (LastModified != NULL) propertiesJson["LastModified"] = Utf8String(LastModified);
    if (Location != NULL) propertiesJson["Location"] = Utf8String(Location);
    if (Latitude != NULL) propertiesJson["Latitude"] = *Latitude;
    if (Longitude != NULL) propertiesJson["Longitude"] = *Longitude;
    if (LocationIsUsingLatLong != NULL) propertiesJson["LocationIsUsingLatLong"] = *LocationIsUsingLatLong;
    if (RegisteredDate != NULL) propertiesJson["RegisteredDate"] = Utf8String(RegisteredDate);
    if (TimeZoneLocation != NULL) propertiesJson["TimeZoneLocation"] = Utf8String(TimeZoneLocation);
    if (Status != NULL) propertiesJson["Status"] = *Status;
    if (PWDMInvitationId != NULL) propertiesJson["PWDMInvitationId"] = Utf8String(PWDMInvitationId);
    if (propertiesJson.size() == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "There were not any valid ProjectMRUDetail properties passed in."};

    auto result = api->m_wsRepositoryClientPtr->SendUpdateObjectRequest({"GlobalSchema", "ProjectMRUDetail", Utf8String(projectmrudetailId)}, propertiesJson)->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_UpdateProjectMRUDetail completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_DeleteProjectMRUDetail
(
CWSCCHANDLE apiHandle,
LPCWSTR projectmrudetailId
)
    {
    VERIFY_API

    if (projectmrudetailId == NULL || wcslen(projectmrudetailId) == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "projectmrudetailId is NULL or empty."};

    auto result = api->m_wsRepositoryClientPtr->SendDeleteObjectRequest({"GlobalSchema", "ProjectMRUDetail", Utf8String(projectmrudetailId)})->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_DeleteProjectMRUDetail completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_ReadProjectTemplateList
(
CWSCCHANDLE apiHandle,
CWSCCDATABUFHANDLE* projecttemplateBuffer
)
    {
    VERIFY_API

    if (projecttemplateBuffer == NULL)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "projecttemplateBuffer is NULL."};

    auto result = api->m_wsRepositoryClientPtr->SendQueryRequest(WSQuery("GlobalSchema", "ProjectTemplate"))->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    int instanceCount = 0;
    for (WSObjectsReader::Instance instance : result.GetValue().GetInstances())
        instanceCount++;
    LPCWSCCPROJECTTEMPLATEBUFFER projecttemplateBuf = (LPCWSCCPROJECTTEMPLATEBUFFER) calloc(instanceCount, sizeof(CWSCCPROJECTTEMPLATEBUFFER));
    instanceCount = 0;
    for (WSObjectsReader::Instance instance : result.GetValue().GetInstances())
        {
        LPCWSCCPROJECTTEMPLATEBUFFER bufToFill = projecttemplateBuf + instanceCount++;
        ProjectTemplateBufferStuffer(bufToFill, instance.GetProperties());
        }

    CWSCCBUFFER* buf = (CWSCCBUFFER*) calloc(1, sizeof(CWSCCBUFFER));
    if (buf == NULL)
        {
        free(projecttemplateBuf);
        return CALLSTATUS {INTERNAL_MEMORY_ERROR, "Memory failed to initialize interally.", "Failed to calloc memory for CWSCCBUFFER."};
        }

    buf->lCount = instanceCount;
    buf->lType = BUFF_TYPE_PROJECTTEMPLATE;
    buf->lpItems = projecttemplateBuf;

    *projecttemplateBuffer = (CWSCCDATABUFHANDLE) buf;

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_ReadProjectTemplateList completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_CreateProjectTemplate
(
CWSCCHANDLE apiHandle,
LPCWSTR Name,
LPCWSTR Number,
LPCWSTR OrganizationId,
bool* Active,
LPCWSTR Industry,
LPCWSTR AssetType,
LPCWSTR LastModified,
LPCWSTR Location,
double* Latitude,
double* Longitude,
bool* LocationIsUsingLatLong,
LPCWSTR RegisteredDate,
LPCWSTR TimeZoneLocation,
int* Status
)
    {
    VERIFY_API

    Json::Value instance;
    instance["schemaName"] = "GlobalSchema";
    instance["className"] = "ProjectTemplate";

    Json::Value propertiesJson;
    if (Name != NULL) propertiesJson["Name"] = Utf8String(Name);
    if (Number != NULL) propertiesJson["Number"] = Utf8String(Number);
    if (OrganizationId != NULL) propertiesJson["OrganizationId"] = Utf8String(OrganizationId);
    if (Active != NULL) propertiesJson["Active"] = *Active;
    if (Industry != NULL) propertiesJson["Industry"] = Utf8String(Industry);
    if (AssetType != NULL) propertiesJson["AssetType"] = Utf8String(AssetType);
    if (LastModified != NULL) propertiesJson["LastModified"] = Utf8String(LastModified);
    if (Location != NULL) propertiesJson["Location"] = Utf8String(Location);
    if (Latitude != NULL) propertiesJson["Latitude"] = *Latitude;
    if (Longitude != NULL) propertiesJson["Longitude"] = *Longitude;
    if (LocationIsUsingLatLong != NULL) propertiesJson["LocationIsUsingLatLong"] = *LocationIsUsingLatLong;
    if (RegisteredDate != NULL) propertiesJson["RegisteredDate"] = Utf8String(RegisteredDate);
    if (TimeZoneLocation != NULL) propertiesJson["TimeZoneLocation"] = Utf8String(TimeZoneLocation);
    if (Status != NULL) propertiesJson["Status"] = *Status;
    if (propertiesJson.size() == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "There were not any valid ProjectTemplate properties passed in."};
    instance["properties"] = propertiesJson;

    Json::Value objectCreationJson;
    objectCreationJson["instance"] = instance;

    auto result = api->m_wsRepositoryClientPtr->SendCreateObjectRequest(objectCreationJson)->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_CreateProjectTemplate completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_ReadProjectTemplate
(
CWSCCHANDLE apiHandle,
LPCWSTR projecttemplateId,
CWSCCDATABUFHANDLE* projecttemplateBuffer
)
    {
    VERIFY_API

    if (projecttemplateBuffer == NULL || projecttemplateId == NULL || wcslen(projecttemplateId) == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "projecttemplateBuffer is NULL or projecttemplateId is NULL or empty."};

    auto result = api->m_wsRepositoryClientPtr->SendGetObjectRequest({"GlobalSchema", "ProjectTemplate", Utf8String(projecttemplateId)})->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    LPCWSCCPROJECTTEMPLATEBUFFER projecttemplateBuf = (LPCWSCCPROJECTTEMPLATEBUFFER) calloc(1, sizeof(CWSCCPROJECTTEMPLATEBUFFER));
    ProjectTemplateBufferStuffer(projecttemplateBuf, (*result.GetValue().GetInstances().begin()).GetProperties());

    CWSCCBUFFER* buf = (CWSCCBUFFER*) calloc(1, sizeof(CWSCCBUFFER));
    if (buf == NULL)
        {
        free(projecttemplateBuf);
        return CALLSTATUS {INTERNAL_MEMORY_ERROR, "Memory failed to initialize interally.", "Failed to calloc memory for CWSCCBUFFER."};
        }

    buf->lCount = 1;
    buf->lType = BUFF_TYPE_PROJECTTEMPLATE;
    buf->lpItems = projecttemplateBuf;

    *projecttemplateBuffer = (CWSCCDATABUFHANDLE) buf;

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_ReadProjectTemplate completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_UpdateProjectTemplate
(
CWSCCHANDLE apiHandle,
LPCWSTR projecttemplateId,
LPCWSTR Name,
LPCWSTR Number,
LPCWSTR OrganizationId,
bool* Active,
LPCWSTR Industry,
LPCWSTR AssetType,
LPCWSTR LastModified,
LPCWSTR Location,
double* Latitude,
double* Longitude,
bool* LocationIsUsingLatLong,
LPCWSTR RegisteredDate,
LPCWSTR TimeZoneLocation,
int* Status
)
    {
    VERIFY_API

    Json::Value propertiesJson;
    if (Name != NULL) propertiesJson["Name"] = Utf8String(Name);
    if (Number != NULL) propertiesJson["Number"] = Utf8String(Number);
    if (OrganizationId != NULL) propertiesJson["OrganizationId"] = Utf8String(OrganizationId);
    if (Active != NULL) propertiesJson["Active"] = *Active;
    if (Industry != NULL) propertiesJson["Industry"] = Utf8String(Industry);
    if (AssetType != NULL) propertiesJson["AssetType"] = Utf8String(AssetType);
    if (LastModified != NULL) propertiesJson["LastModified"] = Utf8String(LastModified);
    if (Location != NULL) propertiesJson["Location"] = Utf8String(Location);
    if (Latitude != NULL) propertiesJson["Latitude"] = *Latitude;
    if (Longitude != NULL) propertiesJson["Longitude"] = *Longitude;
    if (LocationIsUsingLatLong != NULL) propertiesJson["LocationIsUsingLatLong"] = *LocationIsUsingLatLong;
    if (RegisteredDate != NULL) propertiesJson["RegisteredDate"] = Utf8String(RegisteredDate);
    if (TimeZoneLocation != NULL) propertiesJson["TimeZoneLocation"] = Utf8String(TimeZoneLocation);
    if (Status != NULL) propertiesJson["Status"] = *Status;
    if (propertiesJson.size() == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "There were not any valid ProjectTemplate properties passed in."};

    auto result = api->m_wsRepositoryClientPtr->SendUpdateObjectRequest({"GlobalSchema", "ProjectTemplate", Utf8String(projecttemplateId)}, propertiesJson)->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_UpdateProjectTemplate completed successfully."};
    }

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                    04/2016
+---------------+---------------+---------------+---------------+---------------+------*/
CWSCC_EXPORT CALLSTATUS ConnectWebServicesClientC_DeleteProjectTemplate
(
CWSCCHANDLE apiHandle,
LPCWSTR projecttemplateId
)
    {
    VERIFY_API

    if (projecttemplateId == NULL || wcslen(projecttemplateId) == 0)
        return CALLSTATUS {INVALID_PARAMETER, "Invalid parameter passed to function", "projecttemplateId is NULL or empty."};

    auto result = api->m_wsRepositoryClientPtr->SendDeleteObjectRequest({"GlobalSchema", "ProjectTemplate", Utf8String(projecttemplateId)})->GetResult();
    if (!result.IsSuccess())
        return wsresultToConnectWebServicesClientCStatus(result.GetError().GetId(), result.GetError().GetDisplayMessage(), result.GetError().GetDisplayDescription());

    return CALLSTATUS {SUCCESS, "Successful operation", "ConnectWebServicesClientC_DeleteProjectTemplate completed successfully."};
    }

