/*---------------------------------------------------------------------------------------------
 * Copyright (c) Bentley Systems, Incorporated. All rights reserved.
 * See LICENSE.md in the repository root for full copyright notice.
 *--------------------------------------------------------------------------------------------*/
#pragma once

#include <Bentley/BeEvent.h>
#include <ECDb/ECDb.h>
#include <ECObjects/IssueReporter.h>

#include "ECDbLogger.h"

BEGIN_BENTLEY_SQLITE_EC_NAMESPACE

using ECN::IssueCategory;
using ECN::IssueSeverity;

struct ECDB_EXPORT IssueType : ECN::IssueType {
    using ECN::IssueType::IssueType;

    static IssueType ECDbIssue;
};

using ECN::IssueId;
struct ECDB_EXPORT ECDbIssueId {
    static ECN::IssueId ECDb_0001;
    static ECN::IssueId ECDb_0002;
    static ECN::IssueId ECDb_0003;
    static ECN::IssueId ECDb_0004;
    static ECN::IssueId ECDb_0005;
    static ECN::IssueId ECDb_0006;
    static ECN::IssueId ECDb_0007;
    static ECN::IssueId ECDb_0008;
    static ECN::IssueId ECDb_0009;
    static ECN::IssueId ECDb_0010;
    static ECN::IssueId ECDb_0011;
    static ECN::IssueId ECDb_0012;
    static ECN::IssueId ECDb_0013;
    static ECN::IssueId ECDb_0014;
    static ECN::IssueId ECDb_0015;
    static ECN::IssueId ECDb_0016;
    static ECN::IssueId ECDb_0017;
    static ECN::IssueId ECDb_0018;
    static ECN::IssueId ECDb_0019;
    static ECN::IssueId ECDb_0020;
    static ECN::IssueId ECDb_0021;
    static ECN::IssueId ECDb_0022;
    static ECN::IssueId ECDb_0023;
    static ECN::IssueId ECDb_0024;
    static ECN::IssueId ECDb_0025;
    static ECN::IssueId ECDb_0026;
    static ECN::IssueId ECDb_0027;
    static ECN::IssueId ECDb_0028;
    static ECN::IssueId ECDb_0029;
    static ECN::IssueId ECDb_0030;
    static ECN::IssueId ECDb_0031;
    static ECN::IssueId ECDb_0032;
    static ECN::IssueId ECDb_0033;
    static ECN::IssueId ECDb_0034;
    static ECN::IssueId ECDb_0035;
    static ECN::IssueId ECDb_0036;
    static ECN::IssueId ECDb_0037;
    static ECN::IssueId ECDb_0038;
    static ECN::IssueId ECDb_0039;
    static ECN::IssueId ECDb_0040;
    static ECN::IssueId ECDb_0041;
    static ECN::IssueId ECDb_0042;
    static ECN::IssueId ECDb_0043;
    static ECN::IssueId ECDb_0044;
    static ECN::IssueId ECDb_0045;
    static ECN::IssueId ECDb_0046;
    static ECN::IssueId ECDb_0047;
    static ECN::IssueId ECDb_0048;
    static ECN::IssueId ECDb_0049;
    static ECN::IssueId ECDb_0050;
    static ECN::IssueId ECDb_0051;
    static ECN::IssueId ECDb_0052;
    static ECN::IssueId ECDb_0053;
    static ECN::IssueId ECDb_0054;
    static ECN::IssueId ECDb_0055;
    static ECN::IssueId ECDb_0056;
    static ECN::IssueId ECDb_0057;
    static ECN::IssueId ECDb_0058;
    static ECN::IssueId ECDb_0059;
    static ECN::IssueId ECDb_0060;
    static ECN::IssueId ECDb_0061;
    static ECN::IssueId ECDb_0062;
    static ECN::IssueId ECDb_0063;
    static ECN::IssueId ECDb_0064;
    static ECN::IssueId ECDb_0065;
    static ECN::IssueId ECDb_0066;
    static ECN::IssueId ECDb_0067;
    static ECN::IssueId ECDb_0068;
    static ECN::IssueId ECDb_0069;
    static ECN::IssueId ECDb_0070;
    static ECN::IssueId ECDb_0071;
    static ECN::IssueId ECDb_0072;
    static ECN::IssueId ECDb_0073;
    static ECN::IssueId ECDb_0074;
    static ECN::IssueId ECDb_0075;
    static ECN::IssueId ECDb_0076;
    static ECN::IssueId ECDb_0077;
    static ECN::IssueId ECDb_0078;
    static ECN::IssueId ECDb_0079;
    static ECN::IssueId ECDb_0080;
    static ECN::IssueId ECDb_0081;
    static ECN::IssueId ECDb_0082;
    static ECN::IssueId ECDb_0083;
    static ECN::IssueId ECDb_0084;
    static ECN::IssueId ECDb_0085;
    static ECN::IssueId ECDb_0086;
    static ECN::IssueId ECDb_0087;
    static ECN::IssueId ECDb_0088;
    static ECN::IssueId ECDb_0089;
    static ECN::IssueId ECDb_0090;
    static ECN::IssueId ECDb_0091;
    static ECN::IssueId ECDb_0092;
    static ECN::IssueId ECDb_0093;
    static ECN::IssueId ECDb_0094;
    static ECN::IssueId ECDb_0095;
    static ECN::IssueId ECDb_0096;
    static ECN::IssueId ECDb_0097;
    static ECN::IssueId ECDb_0098;
    static ECN::IssueId ECDb_0099;

    static ECN::IssueId ECDb_0100;
    static ECN::IssueId ECDb_0101;
    static ECN::IssueId ECDb_0102;
    static ECN::IssueId ECDb_0103;
    static ECN::IssueId ECDb_0104;
    static ECN::IssueId ECDb_0105;
    static ECN::IssueId ECDb_0106;
    static ECN::IssueId ECDb_0107;
    static ECN::IssueId ECDb_0108;
    static ECN::IssueId ECDb_0109;
    static ECN::IssueId ECDb_0110;
    static ECN::IssueId ECDb_0111;
    static ECN::IssueId ECDb_0112;
    static ECN::IssueId ECDb_0113;
    static ECN::IssueId ECDb_0114;
    static ECN::IssueId ECDb_0115;
    static ECN::IssueId ECDb_0116;
    static ECN::IssueId ECDb_0117;
    static ECN::IssueId ECDb_0118;
    static ECN::IssueId ECDb_0119;
    static ECN::IssueId ECDb_0120;
    static ECN::IssueId ECDb_0121;
    static ECN::IssueId ECDb_0122;
    static ECN::IssueId ECDb_0123;
    static ECN::IssueId ECDb_0124;
    static ECN::IssueId ECDb_0125;
    static ECN::IssueId ECDb_0126;
    static ECN::IssueId ECDb_0127;
    static ECN::IssueId ECDb_0128;
    static ECN::IssueId ECDb_0129;
    static ECN::IssueId ECDb_0130;
    static ECN::IssueId ECDb_0131;
    static ECN::IssueId ECDb_0132;
    static ECN::IssueId ECDb_0133;
    static ECN::IssueId ECDb_0134;
    static ECN::IssueId ECDb_0135;
    static ECN::IssueId ECDb_0136;
    static ECN::IssueId ECDb_0137;
    static ECN::IssueId ECDb_0138;
    static ECN::IssueId ECDb_0139;
    static ECN::IssueId ECDb_0140;
    static ECN::IssueId ECDb_0141;
    static ECN::IssueId ECDb_0142;
    static ECN::IssueId ECDb_0143;
    static ECN::IssueId ECDb_0144;
    static ECN::IssueId ECDb_0145;
    static ECN::IssueId ECDb_0146;
    static ECN::IssueId ECDb_0147;
    static ECN::IssueId ECDb_0148;
    static ECN::IssueId ECDb_0149;
    static ECN::IssueId ECDb_0150;
    static ECN::IssueId ECDb_0151;
    static ECN::IssueId ECDb_0152;
    static ECN::IssueId ECDb_0153;
    static ECN::IssueId ECDb_0154;
    static ECN::IssueId ECDb_0155;
    static ECN::IssueId ECDb_0156;
    static ECN::IssueId ECDb_0157;
    static ECN::IssueId ECDb_0158;
    static ECN::IssueId ECDb_0159;
    static ECN::IssueId ECDb_0160;
    static ECN::IssueId ECDb_0161;
    static ECN::IssueId ECDb_0162;
    static ECN::IssueId ECDb_0163;
    static ECN::IssueId ECDb_0164;
    static ECN::IssueId ECDb_0165;
    static ECN::IssueId ECDb_0166;
    static ECN::IssueId ECDb_0167;
    static ECN::IssueId ECDb_0168;
    static ECN::IssueId ECDb_0169;
    static ECN::IssueId ECDb_0170;
    static ECN::IssueId ECDb_0171;
    static ECN::IssueId ECDb_0172;
    static ECN::IssueId ECDb_0173;
    static ECN::IssueId ECDb_0174;
    static ECN::IssueId ECDb_0175;
    static ECN::IssueId ECDb_0176;
    static ECN::IssueId ECDb_0177;
    static ECN::IssueId ECDb_0178;
    static ECN::IssueId ECDb_0179;
    static ECN::IssueId ECDb_0180;
    static ECN::IssueId ECDb_0181;
    static ECN::IssueId ECDb_0182;
    static ECN::IssueId ECDb_0183;
    static ECN::IssueId ECDb_0184;
    static ECN::IssueId ECDb_0185;
    static ECN::IssueId ECDb_0186;
    static ECN::IssueId ECDb_0187;
    static ECN::IssueId ECDb_0188;
    static ECN::IssueId ECDb_0189;
    static ECN::IssueId ECDb_0190;
    static ECN::IssueId ECDb_0191;
    static ECN::IssueId ECDb_0192;
    static ECN::IssueId ECDb_0193;
    static ECN::IssueId ECDb_0194;
    static ECN::IssueId ECDb_0195;
    static ECN::IssueId ECDb_0196;
    static ECN::IssueId ECDb_0197;
    static ECN::IssueId ECDb_0198;
    static ECN::IssueId ECDb_0199;

    static ECN::IssueId ECDb_0200;
    static ECN::IssueId ECDb_0201;
    static ECN::IssueId ECDb_0202;
    static ECN::IssueId ECDb_0203;
    static ECN::IssueId ECDb_0204;
    static ECN::IssueId ECDb_0205;
    static ECN::IssueId ECDb_0206;
    static ECN::IssueId ECDb_0207;
    static ECN::IssueId ECDb_0208;
    static ECN::IssueId ECDb_0209;
    static ECN::IssueId ECDb_0210;
    static ECN::IssueId ECDb_0211;
    static ECN::IssueId ECDb_0212;
    static ECN::IssueId ECDb_0213;
    static ECN::IssueId ECDb_0214;
    static ECN::IssueId ECDb_0215;
    static ECN::IssueId ECDb_0216;
    static ECN::IssueId ECDb_0217;
    static ECN::IssueId ECDb_0218;
    static ECN::IssueId ECDb_0219;
    static ECN::IssueId ECDb_0220;
    static ECN::IssueId ECDb_0221;
    static ECN::IssueId ECDb_0222;
    static ECN::IssueId ECDb_0223;
    static ECN::IssueId ECDb_0224;
    static ECN::IssueId ECDb_0225;
    static ECN::IssueId ECDb_0226;
    static ECN::IssueId ECDb_0227;
    static ECN::IssueId ECDb_0228;
    static ECN::IssueId ECDb_0229;
    static ECN::IssueId ECDb_0230;
    static ECN::IssueId ECDb_0231;
    static ECN::IssueId ECDb_0232;
    static ECN::IssueId ECDb_0233;
    static ECN::IssueId ECDb_0234;
    static ECN::IssueId ECDb_0235;
    static ECN::IssueId ECDb_0236;
    static ECN::IssueId ECDb_0237;
    static ECN::IssueId ECDb_0238;
    static ECN::IssueId ECDb_0239;
    static ECN::IssueId ECDb_0240;
    static ECN::IssueId ECDb_0241;
    static ECN::IssueId ECDb_0242;
    static ECN::IssueId ECDb_0243;
    static ECN::IssueId ECDb_0244;
    static ECN::IssueId ECDb_0245;
    static ECN::IssueId ECDb_0246;
    static ECN::IssueId ECDb_0247;
    static ECN::IssueId ECDb_0248;
    static ECN::IssueId ECDb_0249;
    static ECN::IssueId ECDb_0250;
    static ECN::IssueId ECDb_0251;
    static ECN::IssueId ECDb_0252;
    static ECN::IssueId ECDb_0253;
    static ECN::IssueId ECDb_0254;
    static ECN::IssueId ECDb_0255;
    static ECN::IssueId ECDb_0256;
    static ECN::IssueId ECDb_0257;
    static ECN::IssueId ECDb_0258;
    static ECN::IssueId ECDb_0259;
    static ECN::IssueId ECDb_0260;
    static ECN::IssueId ECDb_0261;
    static ECN::IssueId ECDb_0262;
    static ECN::IssueId ECDb_0263;
    static ECN::IssueId ECDb_0264;
    static ECN::IssueId ECDb_0265;
    static ECN::IssueId ECDb_0266;
    static ECN::IssueId ECDb_0267;
    static ECN::IssueId ECDb_0268;
    static ECN::IssueId ECDb_0269;
    static ECN::IssueId ECDb_0270;
    static ECN::IssueId ECDb_0271;
    static ECN::IssueId ECDb_0272;
    static ECN::IssueId ECDb_0273;
    static ECN::IssueId ECDb_0274;
    static ECN::IssueId ECDb_0275;
    static ECN::IssueId ECDb_0276;
    static ECN::IssueId ECDb_0277;
    static ECN::IssueId ECDb_0278;
    static ECN::IssueId ECDb_0279;
    static ECN::IssueId ECDb_0280;
    static ECN::IssueId ECDb_0281;
    static ECN::IssueId ECDb_0282;
    static ECN::IssueId ECDb_0283;
    static ECN::IssueId ECDb_0284;
    static ECN::IssueId ECDb_0285;
    static ECN::IssueId ECDb_0286;
    static ECN::IssueId ECDb_0287;
    static ECN::IssueId ECDb_0288;
    static ECN::IssueId ECDb_0289;
    static ECN::IssueId ECDb_0290;
    static ECN::IssueId ECDb_0291;
    static ECN::IssueId ECDb_0292;
    static ECN::IssueId ECDb_0293;
    static ECN::IssueId ECDb_0294;
    static ECN::IssueId ECDb_0295;
    static ECN::IssueId ECDb_0296;
    static ECN::IssueId ECDb_0297;
    static ECN::IssueId ECDb_0298;
    static ECN::IssueId ECDb_0299;

    static ECN::IssueId ECDb_0300;
    static ECN::IssueId ECDb_0301;
    static ECN::IssueId ECDb_0302;
    static ECN::IssueId ECDb_0303;
    static ECN::IssueId ECDb_0304;
    static ECN::IssueId ECDb_0305;
    static ECN::IssueId ECDb_0306;
    static ECN::IssueId ECDb_0307;
    static ECN::IssueId ECDb_0308;
    static ECN::IssueId ECDb_0309;
    static ECN::IssueId ECDb_0310;
    static ECN::IssueId ECDb_0311;
    static ECN::IssueId ECDb_0312;
    static ECN::IssueId ECDb_0313;
    static ECN::IssueId ECDb_0314;
    static ECN::IssueId ECDb_0315;
    static ECN::IssueId ECDb_0316;
    static ECN::IssueId ECDb_0317;
    static ECN::IssueId ECDb_0318;
    static ECN::IssueId ECDb_0319;
    static ECN::IssueId ECDb_0320;
    static ECN::IssueId ECDb_0321;
    static ECN::IssueId ECDb_0322;
    static ECN::IssueId ECDb_0323;
    static ECN::IssueId ECDb_0324;
    static ECN::IssueId ECDb_0325;
    static ECN::IssueId ECDb_0326;
    static ECN::IssueId ECDb_0327;
    static ECN::IssueId ECDb_0328;
    static ECN::IssueId ECDb_0329;
    static ECN::IssueId ECDb_0330;
    static ECN::IssueId ECDb_0331;
    static ECN::IssueId ECDb_0332;
    static ECN::IssueId ECDb_0333;
    static ECN::IssueId ECDb_0334;
    static ECN::IssueId ECDb_0335;
    static ECN::IssueId ECDb_0336;
    static ECN::IssueId ECDb_0337;
    static ECN::IssueId ECDb_0338;
    static ECN::IssueId ECDb_0339;
    static ECN::IssueId ECDb_0340;
    static ECN::IssueId ECDb_0341;
    static ECN::IssueId ECDb_0342;
    static ECN::IssueId ECDb_0343;
    static ECN::IssueId ECDb_0344;
    static ECN::IssueId ECDb_0345;
    static ECN::IssueId ECDb_0346;
    static ECN::IssueId ECDb_0347;
    static ECN::IssueId ECDb_0348;
    static ECN::IssueId ECDb_0349;
    static ECN::IssueId ECDb_0350;
    static ECN::IssueId ECDb_0351;
    static ECN::IssueId ECDb_0352;
    static ECN::IssueId ECDb_0353;
    static ECN::IssueId ECDb_0354;
    static ECN::IssueId ECDb_0355;
    static ECN::IssueId ECDb_0356;
    static ECN::IssueId ECDb_0357;
    static ECN::IssueId ECDb_0358;
    static ECN::IssueId ECDb_0359;
    static ECN::IssueId ECDb_0360;
    static ECN::IssueId ECDb_0361;
    static ECN::IssueId ECDb_0362;
    static ECN::IssueId ECDb_0363;
    static ECN::IssueId ECDb_0364;
    static ECN::IssueId ECDb_0365;
    static ECN::IssueId ECDb_0366;
    static ECN::IssueId ECDb_0367;
    static ECN::IssueId ECDb_0368;
    static ECN::IssueId ECDb_0369;
    static ECN::IssueId ECDb_0370;
    static ECN::IssueId ECDb_0371;
    static ECN::IssueId ECDb_0372;
    static ECN::IssueId ECDb_0373;
    static ECN::IssueId ECDb_0374;
    static ECN::IssueId ECDb_0375;
    static ECN::IssueId ECDb_0376;
    static ECN::IssueId ECDb_0377;
    static ECN::IssueId ECDb_0378;
    static ECN::IssueId ECDb_0379;
    static ECN::IssueId ECDb_0380;
    static ECN::IssueId ECDb_0381;
    static ECN::IssueId ECDb_0382;
    static ECN::IssueId ECDb_0383;
    static ECN::IssueId ECDb_0384;
    static ECN::IssueId ECDb_0385;
    static ECN::IssueId ECDb_0386;
    static ECN::IssueId ECDb_0387;
    static ECN::IssueId ECDb_0388;  // This issue id was being used to report unsupported deletion of KoQs. KoQ deletion support is now added and issue id is now unused.
    static ECN::IssueId ECDb_0389;
    static ECN::IssueId ECDb_0390;
    static ECN::IssueId ECDb_0391;
    static ECN::IssueId ECDb_0392;
    static ECN::IssueId ECDb_0393;
    static ECN::IssueId ECDb_0394;
    static ECN::IssueId ECDb_0395;
    static ECN::IssueId ECDb_0396;
    static ECN::IssueId ECDb_0397;
    static ECN::IssueId ECDb_0398;
    static ECN::IssueId ECDb_0399;

    static ECN::IssueId ECDb_0400;
    static ECN::IssueId ECDb_0401;
    static ECN::IssueId ECDb_0402;
    static ECN::IssueId ECDb_0403;
    static ECN::IssueId ECDb_0404;  // This issue id was being used to report unsupported deletion of ECEnumerations. ECEnumerations deletion support is now added and issue id is now unused.
    static ECN::IssueId ECDb_0405;
    static ECN::IssueId ECDb_0406;
    static ECN::IssueId ECDb_0407;
    static ECN::IssueId ECDb_0408;
    static ECN::IssueId ECDb_0409;
    static ECN::IssueId ECDb_0410;
    static ECN::IssueId ECDb_0411;
    static ECN::IssueId ECDb_0412;
    static ECN::IssueId ECDb_0413;
    static ECN::IssueId ECDb_0414;
    static ECN::IssueId ECDb_0415;
    static ECN::IssueId ECDb_0416;
    static ECN::IssueId ECDb_0417;
    static ECN::IssueId ECDb_0418;
    static ECN::IssueId ECDb_0419;
    static ECN::IssueId ECDb_0420;
    static ECN::IssueId ECDb_0421;
    static ECN::IssueId ECDb_0422;
    static ECN::IssueId ECDb_0423;
    static ECN::IssueId ECDb_0424;
    static ECN::IssueId ECDb_0425;
    static ECN::IssueId ECDb_0426;
    static ECN::IssueId ECDb_0427;
    static ECN::IssueId ECDb_0428;
    static ECN::IssueId ECDb_0429;
    static ECN::IssueId ECDb_0430;
    static ECN::IssueId ECDb_0431;
    static ECN::IssueId ECDb_0432;
    static ECN::IssueId ECDb_0433;
    static ECN::IssueId ECDb_0434;
    static ECN::IssueId ECDb_0435;
    static ECN::IssueId ECDb_0436;
    static ECN::IssueId ECDb_0437;
    static ECN::IssueId ECDb_0438;
    static ECN::IssueId ECDb_0439;
    static ECN::IssueId ECDb_0440;
    static ECN::IssueId ECDb_0441;
    static ECN::IssueId ECDb_0442;
    static ECN::IssueId ECDb_0443;
    static ECN::IssueId ECDb_0444;
    static ECN::IssueId ECDb_0445;
    static ECN::IssueId ECDb_0446;
    static ECN::IssueId ECDb_0447;
    static ECN::IssueId ECDb_0448;
    static ECN::IssueId ECDb_0449;
    static ECN::IssueId ECDb_0450;
    static ECN::IssueId ECDb_0451;
    static ECN::IssueId ECDb_0452;
    static ECN::IssueId ECDb_0453;
    static ECN::IssueId ECDb_0454;
    static ECN::IssueId ECDb_0455;
    static ECN::IssueId ECDb_0456;
    static ECN::IssueId ECDb_0457;
    static ECN::IssueId ECDb_0458;
    static ECN::IssueId ECDb_0459;
    static ECN::IssueId ECDb_0460;
    static ECN::IssueId ECDb_0461;
    static ECN::IssueId ECDb_0462;
    static ECN::IssueId ECDb_0463;
    static ECN::IssueId ECDb_0464;
    static ECN::IssueId ECDb_0465;
    static ECN::IssueId ECDb_0466;
    static ECN::IssueId ECDb_0467;
    static ECN::IssueId ECDb_0468;
    static ECN::IssueId ECDb_0469;
    static ECN::IssueId ECDb_0470;
    static ECN::IssueId ECDb_0471;
    static ECN::IssueId ECDb_0472;
    static ECN::IssueId ECDb_0473;
    static ECN::IssueId ECDb_0474;
    static ECN::IssueId ECDb_0475;
    static ECN::IssueId ECDb_0476;
    static ECN::IssueId ECDb_0477;
    static ECN::IssueId ECDb_0478;
    static ECN::IssueId ECDb_0479;
    static ECN::IssueId ECDb_0480;
    static ECN::IssueId ECDb_0481;
    static ECN::IssueId ECDb_0482;
    static ECN::IssueId ECDb_0483;
    static ECN::IssueId ECDb_0484;
    static ECN::IssueId ECDb_0485;
    static ECN::IssueId ECDb_0486;
    static ECN::IssueId ECDb_0487;
    static ECN::IssueId ECDb_0488;
    static ECN::IssueId ECDb_0489;
    static ECN::IssueId ECDb_0490;
    static ECN::IssueId ECDb_0491;
    static ECN::IssueId ECDb_0492;
    static ECN::IssueId ECDb_0493;
    static ECN::IssueId ECDb_0494;
    static ECN::IssueId ECDb_0495;
    static ECN::IssueId ECDb_0496;
    static ECN::IssueId ECDb_0497;
    static ECN::IssueId ECDb_0498;
    static ECN::IssueId ECDb_0499;

    static ECN::IssueId ECDb_0500;
    static ECN::IssueId ECDb_0501;
    static ECN::IssueId ECDb_0502;
    static ECN::IssueId ECDb_0503;
    static ECN::IssueId ECDb_0504;
    static ECN::IssueId ECDb_0505;
    static ECN::IssueId ECDb_0506;
    static ECN::IssueId ECDb_0507;
    static ECN::IssueId ECDb_0508;
    static ECN::IssueId ECDb_0509;
    static ECN::IssueId ECDb_0510;
    static ECN::IssueId ECDb_0511;
    static ECN::IssueId ECDb_0512;
    static ECN::IssueId ECDb_0513;
    static ECN::IssueId ECDb_0514;
    static ECN::IssueId ECDb_0515;
    static ECN::IssueId ECDb_0516;
    static ECN::IssueId ECDb_0517;
    static ECN::IssueId ECDb_0518;
    static ECN::IssueId ECDb_0519;
    static ECN::IssueId ECDb_0520;
    static ECN::IssueId ECDb_0521;
    static ECN::IssueId ECDb_0522;
    static ECN::IssueId ECDb_0523;
    static ECN::IssueId ECDb_0524;
    static ECN::IssueId ECDb_0525;
    static ECN::IssueId ECDb_0526;
    static ECN::IssueId ECDb_0527;
    static ECN::IssueId ECDb_0528;
    static ECN::IssueId ECDb_0529;
    static ECN::IssueId ECDb_0530;
    static ECN::IssueId ECDb_0531;
    static ECN::IssueId ECDb_0532;
    static ECN::IssueId ECDb_0533;
    static ECN::IssueId ECDb_0534;
    static ECN::IssueId ECDb_0535;
    static ECN::IssueId ECDb_0536;
    static ECN::IssueId ECDb_0537;
    static ECN::IssueId ECDb_0538;
    static ECN::IssueId ECDb_0539;
    static ECN::IssueId ECDb_0540;
    static ECN::IssueId ECDb_0541;
    static ECN::IssueId ECDb_0542;
    static ECN::IssueId ECDb_0543;
    static ECN::IssueId ECDb_0544;
    static ECN::IssueId ECDb_0545;
    static ECN::IssueId ECDb_0546;
    static ECN::IssueId ECDb_0547;
    static ECN::IssueId ECDb_0548;
    static ECN::IssueId ECDb_0549;
    static ECN::IssueId ECDb_0550;
    static ECN::IssueId ECDb_0551;
    static ECN::IssueId ECDb_0552;
    static ECN::IssueId ECDb_0553;
    static ECN::IssueId ECDb_0554;
    static ECN::IssueId ECDb_0555;
    static ECN::IssueId ECDb_0556;
    static ECN::IssueId ECDb_0557;
    static ECN::IssueId ECDb_0558;
    static ECN::IssueId ECDb_0559;
    static ECN::IssueId ECDb_0560;
    static ECN::IssueId ECDb_0561;
    static ECN::IssueId ECDb_0562;
    static ECN::IssueId ECDb_0563;
    static ECN::IssueId ECDb_0564;
    static ECN::IssueId ECDb_0565;
    static ECN::IssueId ECDb_0566;
    static ECN::IssueId ECDb_0567;
    static ECN::IssueId ECDb_0568;
    static ECN::IssueId ECDb_0569;
    static ECN::IssueId ECDb_0570;
    static ECN::IssueId ECDb_0571;
    static ECN::IssueId ECDb_0572;
    static ECN::IssueId ECDb_0573;
    static ECN::IssueId ECDb_0574;
    static ECN::IssueId ECDb_0575;
    static ECN::IssueId ECDb_0576;
    static ECN::IssueId ECDb_0577;
    static ECN::IssueId ECDb_0578;
    static ECN::IssueId ECDb_0579;
    static ECN::IssueId ECDb_0580;
    static ECN::IssueId ECDb_0581;
    static ECN::IssueId ECDb_0582;
    static ECN::IssueId ECDb_0583;
    static ECN::IssueId ECDb_0584;
    static ECN::IssueId ECDb_0585;
    static ECN::IssueId ECDb_0586;
    static ECN::IssueId ECDb_0587;
    static ECN::IssueId ECDb_0588;
    static ECN::IssueId ECDb_0589;
    static ECN::IssueId ECDb_0590;
    static ECN::IssueId ECDb_0591;
    static ECN::IssueId ECDb_0592;
    static ECN::IssueId ECDb_0593;
    static ECN::IssueId ECDb_0594;
    static ECN::IssueId ECDb_0595;
    static ECN::IssueId ECDb_0596;
    static ECN::IssueId ECDb_0597;
    static ECN::IssueId ECDb_0598;
    static ECN::IssueId ECDb_0599;

    static ECN::IssueId ECDb_0600;
    static ECN::IssueId ECDb_0601;
    static ECN::IssueId ECDb_0602;
    static ECN::IssueId ECDb_0603;
    static ECN::IssueId ECDb_0604;
    static ECN::IssueId ECDb_0605;
    static ECN::IssueId ECDb_0606;
    static ECN::IssueId ECDb_0607;
    static ECN::IssueId ECDb_0608;
    static ECN::IssueId ECDb_0609;
    static ECN::IssueId ECDb_0610;
    static ECN::IssueId ECDb_0611;
    static ECN::IssueId ECDb_0612;
    static ECN::IssueId ECDb_0613;
    static ECN::IssueId ECDb_0614;
    static ECN::IssueId ECDb_0615;
    static ECN::IssueId ECDb_0616;
    static ECN::IssueId ECDb_0617;
    static ECN::IssueId ECDb_0618;
    static ECN::IssueId ECDb_0619;
    static ECN::IssueId ECDb_0620;
    static ECN::IssueId ECDb_0621;
    static ECN::IssueId ECDb_0622;
    static ECN::IssueId ECDb_0623;
    static ECN::IssueId ECDb_0624;
    static ECN::IssueId ECDb_0625;
    static ECN::IssueId ECDb_0626;
    static ECN::IssueId ECDb_0627;
    static ECN::IssueId ECDb_0628;
    static ECN::IssueId ECDb_0629;
    static ECN::IssueId ECDb_0630;
    static ECN::IssueId ECDb_0631;
    static ECN::IssueId ECDb_0632;
    static ECN::IssueId ECDb_0633;
    static ECN::IssueId ECDb_0634;
    static ECN::IssueId ECDb_0635;
    static ECN::IssueId ECDb_0636;
    static ECN::IssueId ECDb_0637;
    static ECN::IssueId ECDb_0638;
    static ECN::IssueId ECDb_0639;
    static ECN::IssueId ECDb_0640;
    static ECN::IssueId ECDb_0641;
    static ECN::IssueId ECDb_0642;
    static ECN::IssueId ECDb_0643;
    static ECN::IssueId ECDb_0644;
    static ECN::IssueId ECDb_0645;
    static ECN::IssueId ECDb_0646;
    static ECN::IssueId ECDb_0647;
    static ECN::IssueId ECDb_0648;
    static ECN::IssueId ECDb_0649;
    static ECN::IssueId ECDb_0650;
    static ECN::IssueId ECDb_0651;
    static ECN::IssueId ECDb_0652;
    static ECN::IssueId ECDb_0653;
    static ECN::IssueId ECDb_0654;
    static ECN::IssueId ECDb_0655;
    static ECN::IssueId ECDb_0656;
    static ECN::IssueId ECDb_0657;
    static ECN::IssueId ECDb_0658;
    static ECN::IssueId ECDb_0659;
    static ECN::IssueId ECDb_0660;
    static ECN::IssueId ECDb_0661;
    static ECN::IssueId ECDb_0662;
    static ECN::IssueId ECDb_0663;
    static ECN::IssueId ECDb_0664;
    static ECN::IssueId ECDb_0665;
    static ECN::IssueId ECDb_0666;
    static ECN::IssueId ECDb_0667;
    static ECN::IssueId ECDb_0668;
    static ECN::IssueId ECDb_0669;
    static ECN::IssueId ECDb_0670;
    static ECN::IssueId ECDb_0671;
    static ECN::IssueId ECDb_0672;
    static ECN::IssueId ECDb_0673;
    static ECN::IssueId ECDb_0674;
    static ECN::IssueId ECDb_0675;
    static ECN::IssueId ECDb_0676;
    static ECN::IssueId ECDb_0677;
    static ECN::IssueId ECDb_0678;
    static ECN::IssueId ECDb_0679;
    static ECN::IssueId ECDb_0680;
    static ECN::IssueId ECDb_0681;
    static ECN::IssueId ECDb_0682;
    static ECN::IssueId ECDb_0683;
    static ECN::IssueId ECDb_0684;
    static ECN::IssueId ECDb_0685;
    static ECN::IssueId ECDb_0686;

    static ECN::IssueId ECDb_0700;
    static ECN::IssueId ECDb_0701;
    static ECN::IssueId ECDb_0702;
    static ECN::IssueId ECDb_0703;
    static ECN::IssueId ECDb_0704;
    static ECN::IssueId ECDb_0705;
    static ECN::IssueId ECDb_0706;
    static ECN::IssueId ECDb_0707;
    static ECN::IssueId ECDb_0708;
    static ECN::IssueId ECDb_0709;
    static ECN::IssueId ECDb_0710;
    static ECN::IssueId ECDb_0711;
    static ECN::IssueId ECDb_0712;
    static ECN::IssueId ECDb_0713;
    static ECN::IssueId ECDb_0714;
    static ECN::IssueId ECDb_0715;
    static ECN::IssueId ECDb_0716;
    static ECN::IssueId ECDb_0717;
    static ECN::IssueId ECDb_0718;
    static ECN::IssueId ECDb_0719;
    static ECN::IssueId ECDb_0720;
    static ECN::IssueId ECDb_0721;
    static ECN::IssueId ECDb_0722;
    static ECN::IssueId ECDb_0723;
    static ECN::IssueId ECDb_0724;
    static ECN::IssueId ECDb_0725;
    static ECN::IssueId ECDb_0726;
    static ECN::IssueId ECDb_0727;
    static ECN::IssueId ECDb_0728;
    static ECN::IssueId ECDb_0729;
    static ECN::IssueId ECDb_0730;
    static ECN::IssueId ECDb_0731;
    static ECN::IssueId ECDb_0732;
    static ECN::IssueId ECDb_0733;
    static ECN::IssueId ECDb_0734;
    static ECN::IssueId ECDb_0735;
    static ECN::IssueId ECDb_0736;
    static ECN::IssueId ECDb_0737;
    static ECN::IssueId ECDb_0738;
    static ECN::IssueId ECDb_0739;  // this issue id is being used to report instance query related ambiguity
    static ECN::IssueId ECDb_0740;
    static ECN::IssueId ECDb_0741;
};

//---------------------------------------------------------------------------------------
// @bsistruct
//---------------------------------------------------------------------------------------
struct IssueDataSource final {
    enum class FilterAction {
        Ignore,
        Forward,
    };
    typedef BeEvent<ECN::IssueSeverity, ECN::IssueCategory, ECN::IssueType, ECN::IssueId, Utf8CP> listener_t;
    typedef std::function<FilterAction(ECN::IssueSeverity, ECN::IssueCategory, ECN::IssueType, ECN::IssueId, Utf8CP)> filter_callback_t;

    struct FilterScope final {
       private:
        IssueDataSource const& m_source;

       public:
        FilterScope(IssueDataSource const&, filter_callback_t);
        ~FilterScope();
        IssueDataSource const& Source() const { return m_source; }
    };

   private:
    mutable listener_t m_issueEvent;
    mutable filter_callback_t m_filterCallback;
    mutable cancel_callback_type m_sourceCancel;
    mutable cancel_callback_type m_issueListenerCancel;
    static std::map<IssueSeverity, NativeLogging::SEVERITY> s_serverityMap;

   public:
    IssueDataSource() {}
    IssueDataSource(IssueDataSource const&) = delete;
    IssueDataSource& operator=(IssueDataSource const&) = delete;
    // set null to remove last listener
    void SetOldStyleListener(ECN::IIssueListener const* listener) const;
    // Subscribe issue from another source and raise them locally
    void SetIn(IssueDataSource& source) const;
    // Clear the in;
    void ClearIn() const;
    // Allow to subscribe to events
    listener_t& OnIssueReported() const { return m_issueEvent; }
    // Set filter that would can prevent message from getting propagated
    void SetFilter(filter_callback_t filterCallback) const;
    // Clear filter callback
    void ClearFilter() const;
    // Report issue which will be propagated
    void Report(ECN::IssueSeverity severity, ECN::IssueCategory category, ECN::IssueType type, ECN::IssueId id, Utf8CP message) const;
    template <typename... FmtArgs>
    void ReportV(ECN::IssueSeverity severity, ECN::IssueCategory category, ECN::IssueType type, ECN::IssueId id, Utf8CP message, FmtArgs&&... fmtArgs) const {
        Utf8String formattedMessage;
        formattedMessage.Sprintf(message, std::forward<FmtArgs>(fmtArgs)...);
        Report(severity, category, type, id, formattedMessage.c_str());
    }
    ~IssueDataSource() { ClearIn(); }
    // A default implementation of adding native logger sink to a issue data source
    static cancel_callback_type AppendLogSink(IssueDataSource& source, Utf8CP loggerName);
};

END_BENTLEY_SQLITE_EC_NAMESPACE