/*--------------------------------------------------------------------------------------+
|
|     $Source: ECDb/SchemaImportContext.cpp $
|
|  $Copyright: (c) 2015 Bentley Systems, Incorporated. All rights reserved. $
|
+--------------------------------------------------------------------------------------*/
#include "ECDbPch.h"
#include "SchemaImportContext.h"

BEGIN_BENTLEY_SQLITE_EC_NAMESPACE

//*************************************************************************************
// SchemaImportContext
//*************************************************************************************
//---------------------------------------------------------------------------------------
// @bsimethod                                                    Krischan.Eberle   07/2015
//---------------------------------------------------------------------------------------
UserECDbMapStrategy const* SchemaImportContext::GetUserStrategy(ECClassCR ecclass, ECDbClassMap const* classMapCA) const
    {
    return GetUserStrategyP(ecclass, classMapCA);
    }

//---------------------------------------------------------------------------------------
// @bsimethod                                                    Krischan.Eberle   07/2015
//---------------------------------------------------------------------------------------
UserECDbMapStrategy* SchemaImportContext::GetUserStrategyP(ECClassCR ecclass) const
    {
    return GetUserStrategyP(ecclass, nullptr);
    }

//---------------------------------------------------------------------------------------
// @bsimethod                                                    Krischan.Eberle   07/2015
//---------------------------------------------------------------------------------------
UserECDbMapStrategy* SchemaImportContext::GetUserStrategyP(ECClassCR ecclass, ECDbClassMap const* classMapCA) const
    {
    auto it = m_userStrategyCache.find(&ecclass);
    if (it != m_userStrategyCache.end())
        return it->second.get();

    bool hasClassMapCA = true;
    ECDbClassMap classMap;
    if (classMapCA == nullptr)
        {
        hasClassMapCA = ECDbMapCustomAttributeHelper::TryGetClassMap(classMap, ecclass);
        classMapCA = &classMap;
        }

    std::unique_ptr<UserECDbMapStrategy> userStrategy = std::unique_ptr<UserECDbMapStrategy>(new UserECDbMapStrategy());

    if (hasClassMapCA)
        {
        ECDbClassMap::MapStrategy strategy;
        if (ECOBJECTS_STATUS_Success != classMapCA->TryGetMapStrategy(strategy))
            return nullptr; // error

        if (SUCCESS != UserECDbMapStrategy::TryParse(*userStrategy, strategy) || !userStrategy->IsValid())
            return nullptr; // error
        }

    UserECDbMapStrategy* userStrategyP = userStrategy.get();
    m_userStrategyCache[&ecclass] = std::move(userStrategy);
    return userStrategyP;
    }

//---------------------------------------------------------------------------------------
// @bsimethod                                                    Krischan.Eberle   08/2015
//---------------------------------------------------------------------------------------
void SchemaImportContext::CacheClassMapInfo(ClassMap const& classMap, std::unique_ptr<ClassMapInfo>& info)
    {
    m_classMapInfoCache.push_back(std::make_pair(&classMap, std::move(info)));
    }



//****************************************************************************************

//---------------------------------------------------------------------------------------
// @bsimethod                                                    Krischan.Eberle   10/2015
//---------------------------------------------------------------------------------------
BentleyStatus SchemaImportECDbMapDb::Load()
    {
    //first load generic mapping meta data
    ECDbSQLManager& manager = m_coreMapDb.GetManagerR();
    if (!manager.IsLoaded())
        {
        if (SUCCESS != manager.Load())
            return ERROR;
        }
    
    //then load meta data only needed for schema import
    return ReadIndexInfosFromDb(manager.GetECDb());
    }

//---------------------------------------------------------------------------------------
// @bsimethod                                                    Affan.Khan        09/2014
//---------------------------------------------------------------------------------------
ECDbSqlIndex* SchemaImportECDbMapDb::CreateIndex(ECDbCR ecdb, ECDbSqlTable& table, Utf8CP indexName, bool isUnique, std::vector<ECDbSqlColumn const*> const& columns, Utf8CP primaryWhereClause, bool isAutoGenerated, ECN::ECClassId classId, bool applyToSubclassesIfPartial)
    {
    if (columns.empty())
        {
        BeAssert(false && "Index must have at least one column defined.");
        return nullptr;
        }

    Utf8String generatedIndexName;
    if (Utf8String::IsNullOrEmpty(indexName))
        {
        do
            {
            m_coreMapDb.GetNameGenerator().Generate(generatedIndexName);
            } while (IsNameInUse(generatedIndexName.c_str()));

            indexName = generatedIndexName.c_str();
        }

    return CacheIndex(ecdb, m_coreMapDb.GetManagerR().GetIdGenerator().NextIndexId(),
                      table, indexName, isUnique, columns, primaryWhereClause, isAutoGenerated, classId, applyToSubclassesIfPartial);
    }

//---------------------------------------------------------------------------------------
// @bsimethod                                                    Affan.Khan        09/2014
//---------------------------------------------------------------------------------------
ECDbSqlIndex* SchemaImportECDbMapDb::CreateIndex(ECDbCR ecdb, ECDbSqlTable& table, Utf8CP indexName, bool isUnique, std::vector<Utf8CP> const& columnNames, Utf8CP primaryWhereClause, bool isAutoGenerated, ECN::ECClassId classId, bool applyToSubclassesIfPartial)
    {
    if (columnNames.empty())
        return nullptr;

    std::vector<ECDbSqlColumn const*> columns;
    for (Utf8CP colName : columnNames)
        {
        ECDbSqlColumn const* col = table.FindColumnCP(colName);
        if (col == nullptr)
            {
            BeAssert(false && "Failed to find index column");
            return nullptr;
            }

        columns.push_back(col);
        }

    return CreateIndex(ecdb, table, indexName, isUnique, columns, primaryWhereClause, isAutoGenerated, classId, applyToSubclassesIfPartial);
    }

//---------------------------------------------------------------------------------------
// @bsimethod                                                    Affan.Khan        09/2014
//---------------------------------------------------------------------------------------
ECDbSqlIndex* SchemaImportECDbMapDb::CacheIndex(ECDbCR ecdb, ECDbIndexId id, ECDbSqlTable& table, Utf8CP indexName, bool isUnique, std::vector<ECDbSqlColumn const*> const& columns, Utf8CP primaryWhereClause, bool isAutoGenerated, ECN::ECClassId classId, bool applyToSubclassesIfPartial) const
    {
    BeAssert(!columns.empty());

    auto it = m_usedIndexNames.find(indexName);
    if (it != m_usedIndexNames.end())
        {
        ecdb.GetECDbImplR().GetIssueReporter().Report(ECDbIssueSeverity::Error, "Index with name '%s' already defined in the ECDb file.", indexName);
        return nullptr;
        }

    std::unique_ptr<ECDbSqlIndex> index (new ECDbSqlIndex(id, table, indexName, isUnique, columns, primaryWhereClause, isAutoGenerated, classId, applyToSubclassesIfPartial));
    ECDbSqlIndex* indexP = index.get();
    m_indexes.push_back(std::move(index));

    m_usedIndexNames.insert(indexP->GetName().c_str());
    return indexP;
    }



//---------------------------------------------------------------------------------------
// @bsimethod                                                    Affan.Khan        10/2014
//---------------------------------------------------------------------------------------
BentleyStatus SchemaImportECDbMapDb::CreateInDb(ECDbR ecdb, ECDbSqlIndex const& index) const
    {
    if (index.GetColumns().empty())
        {
        BeAssert(false && "Index definition is not valid");
        return ERROR;
        }

    bool exists = false;
        {
        CachedStatementPtr stmt = nullptr;
        if (BE_SQLITE_OK != ecdb.GetCachedStatement(stmt, "select NULL from sqlite_master WHERE type='index' and name=?"))
            {
            BeAssert(false);
            return ERROR;
            }

        stmt->BindText(1, index.GetName().c_str(), Statement::MakeCopy::No);
        exists = BE_SQLITE_ROW == stmt->Step();
        }

    if (exists)
        {
        Utf8String ddl("DROP INDEX [");
        ddl.append(index.GetName()).append("]");

        if (ecdb.ExecuteSql(ddl.c_str()) != BE_SQLITE_OK)
            {
            ecdb.GetECDbImplR().GetIssueReporter().Report(ECDbIssueSeverity::Error, "Failed to drop index %s on table %s. Error: %s", index.GetName().c_str(), index.GetTable().GetName().c_str(),
                                                          ecdb.GetLastError());

            BeAssert(false && "Failed to create index");
            return ERROR;
            }
        }

    NativeSqlBuilder ddl;
    if (SUCCESS != BuildCreateIndexDdl(ddl, ecdb, index))
        return ERROR;

    if (BE_SQLITE_OK != ecdb.ExecuteSql(ddl.ToString()))
        {
        ecdb.GetECDbImplR().GetIssueReporter().Report(ECDbIssueSeverity::Error, "Failed to create index %s on table %s. Error: %s", index.GetName().c_str(), index.GetTable().GetName().c_str(),
                                                      ecdb.GetLastError());
        BeAssert(false && "Failed to create index");
        return ERROR;
        }

    return SUCCESS;
    }

//---------------------------------------------------------------------------------------
// @bsimethod                                                Krischan.Eberle 10/2015
//---------------------------------------------------------------------------------------
BentleyStatus SchemaImportECDbMapDb::BuildCreateIndexDdl(NativeSqlBuilder& ddl, ECDbCR ecdb, ECDbSqlIndex const& index) const
    {
    ddl.Append("CREATE ");
    if (index.GetIsUnique())
        ddl.Append("UNIQUE ");

    Utf8CP indexName = index.GetName().c_str();
    Utf8CP tableName = index.GetTable().GetName().c_str();
    ddl.Append("INDEX ").AppendEscaped(indexName).Append(" ON ").AppendEscaped(tableName).Append(" (");

    bool isFirstCol = true;
    for (ECDbSqlColumn const* col : index.GetColumns())
        {
        if (!isFirstCol)
            ddl.AppendComma(false);

        ddl.AppendEscaped(col->GetName().c_str());
        isFirstCol = false;
        }

    ddl.AppendParenRight();

    NativeSqlBuilder whereClause;
    if (SUCCESS != GenerateIndexWhereClause(whereClause, ecdb, index))
        return ERROR;

    if (!whereClause.IsEmpty())
        ddl.Append(" WHERE ").Append(whereClause.ToString());

    return SUCCESS;
    }

//---------------------------------------------------------------------------------------
// @bsimethod                                                    Krischan.Eberle  10/2015
//---------------------------------------------------------------------------------------
BentleyStatus SchemaImportECDbMapDb::GenerateIndexWhereClause(NativeSqlBuilder& whereClause, ECDbCR ecdb, ECDbSqlIndex const& index) const
    {
    bool hasWhere = !index.GetPrimaryWhereClause().empty();
    if (hasWhere)
        whereClause.AppendParenLeft().Append(index.GetPrimaryWhereClause().c_str()).AppendParenRight();

    ECDbSqlColumn const* classIdCol = nullptr;
    if (!index.HasClassId() || !index.GetTable().TryGetECClassIdColumn(classIdCol))
        return SUCCESS;

    BeAssert(index.HasClassId());

    BeAssert(classIdCol != nullptr);

    ECClassCP ecclass = ecdb.Schemas().GetECClass(index.GetClassId());
    if (ecclass == nullptr)
        {
        BeAssert(false);
        return ERROR;
        }

    ClassMapCP classMap = ecdb.GetECDbImplR().GetECDbMap().GetClassMapCP(*ecclass);
    if (classMap == nullptr)
        {
        BeAssert(false);
        return ERROR;
        }

    StorageDescription const& storageDescription = classMap->GetStorageDescription();
    std::vector<size_t> nonVirtualPartitionIndices = storageDescription.GetNonVirtualHorizontalPartitionIndices();
    HorizontalPartition const* horizPartition = nullptr;
    if (nonVirtualPartitionIndices.empty())
        horizPartition = &storageDescription.GetRootHorizontalPartition();
    else
        {
        BeAssert(nonVirtualPartitionIndices.size() == 1 && "Check that class only maps to a single table should have been done during class name preparation");
        horizPartition = storageDescription.GetHorizontalPartition(nonVirtualPartitionIndices[0]);
        }

    if (!horizPartition->NeedsClassIdFilter())
        return SUCCESS;

    //now we know the index would have to be partial.
    if (!index.GetIsUnique())
        {
        //non-unique indexes will never be made partial as they don't enforce anything and usually
        //are just there for performance - which a partial index will spoil.
        if (ecclass->GetRelationshipClassCP() != nullptr)
            ecdb.GetECDbImplR().GetIssueReporter().Report(ECDbIssueSeverity::Warning,
                                                          "ECDb creates an index for ECRelationshipClass '%s' on the foreign key column which is shared by multiple classes. "
                                                          "For performance reasons ECDb will create a non-partial index which therefore might include unnecessary rows."
                                                          "If you don't need that index, you can disable it in the ECRelationshipClass (via custom attribute).", ecclass->GetFullName());

        else
            ecdb.GetECDbImplR().GetIssueReporter().Report(ECDbIssueSeverity::Warning,
                                                          "Index '%s' defined for ECClass '%s' includes a column shared by multiple ECClasses. "
                                                          "For performance reasons, ECDb will create a non-partial index which therefore includes more rows than needed.",
                                                          index.GetName().c_str(), ecclass->GetFullName());

        return SUCCESS;
        }

    //unique indexes are always created to not lose enforcement of the uniqueness
    if (!index.IsAutoGenerated())
        {
        ecdb.GetECDbImplR().GetIssueReporter().Report(ECDbIssueSeverity::Warning,
                                                      "Index '%s' defined for ECClass '%s' includes a column shared by multiple ECClasses. "
                                                      "This results in a partial index filtered by ECClassId which might impact performance. "
                                                      "Consider changing the ECClass to not share columns.", index.GetName().c_str(), ecclass->GetFullName());
        }
    else
        {
        if (ecclass->GetRelationshipClassCP() != nullptr)
            ecdb.GetECDbImplR().GetIssueReporter().Report(ECDbIssueSeverity::Warning,
                                                      "ECDb has to create a unique index for ECRelationshipClass '%s' to enforce the cardinality. "
                                                      "This results in a partial index filtered by ECClassId which might impact performance. "
                                                      "Consider changing the ECRelationshipClass to not share a table.", ecclass->GetFullName());
        }

    if (hasWhere)
        whereClause.AppendSpace().Append(BooleanSqlOperator::And, true);

    if (!index.AppliesToSubclassesIfPartial())
        {
        whereClause.Append(classIdCol->GetName().c_str()).Append(BooleanSqlOperator::EqualTo).Append(index.GetClassId());
        return SUCCESS;
        }


    if (hasWhere)
        whereClause.AppendParenLeft();

    horizPartition->AppendECClassIdFilterSql(classIdCol->GetName().c_str(), whereClause);
    
    if (hasWhere)
        whereClause.AppendParenRight();

    return SUCCESS;
    }


//---------------------------------------------------------------------------------------
// @bsimethod                                                    Krischan.Eberle  08/2015
//---------------------------------------------------------------------------------------
BentleyStatus SchemaImportECDbMapDb::CreateOrUpdateIndicesInDb(ECDbR ecdb) const
    {
    for (std::unique_ptr<ECDbSqlIndex>& indexPtr : m_indexes)
        {
        ECDbSqlIndex& index = *indexPtr;

        if (SUCCESS != CreateInDb(ecdb, index))
            return ERROR;

        //populates the ec_Index table
        if (SUCCESS != InsertIndexInfoIntoDb(ecdb, index))
            return ERROR;
        }

    return SUCCESS;
    }


//---------------------------------------------------------------------------------------
// @bsimethod                                                    Affan.Khan  08/2015
//---------------------------------------------------------------------------------------
BentleyStatus SchemaImportECDbMapDb::ReadIndexInfosFromDb(ECDbCR ecdb) const
    {
    CachedStatementPtr stmt = nullptr;
    ecdb.GetCachedStatement(stmt, "SELECT I.Id, T.Name, I.Name, I.IsUnique, I.PrimaryWhereClause, I.IsAutoGenerated, I.ClassId, I.AppliesToSubclassesIfPartial FROM ec_Index I INNER JOIN ec_Table T ON T.Id = I.TableId");
    if (stmt == nullptr)
        return ERROR;

    while (stmt->Step() == BE_SQLITE_ROW)
        {
        int64_t id = stmt->GetValueInt64(0);
        Utf8CP tableName = stmt->GetValueText(1);
        Utf8CP name = stmt->GetValueText(2);
        bool isUnique = stmt->GetValueInt(3) == 1;
        Utf8CP primaryWhereClause = !stmt->IsColumnNull(4) ? stmt->GetValueText(4) : nullptr;
        bool isAutoGenerated = stmt->GetValueInt(5) == 1;
        ECClassId classId = !stmt->IsColumnNull(6) ? stmt->GetValueInt64(6) : ECClass::UNSET_ECCLASSID;
        bool appliesToSubclassesIfPartial = stmt->GetValueInt(7) == 1;

        ECDbSqlTable* table = m_coreMapDb.FindTableP(tableName);
        if (table == nullptr)
            {
            BeAssert(false && "Failed to find table");
            return ERROR;
            }

        CachedStatementPtr indexColStmt = nullptr;
        ecdb.GetCachedStatement(indexColStmt, "SELECT C.Name FROM ec_IndexColumn I INNER JOIN ec_Column C ON C.Id = I.ColumnId WHERE I.IndexId = ? ORDER BY I.Ordinal");
        if (indexColStmt == nullptr)
            return ERROR;

        indexColStmt->BindInt64(1, id);
        std::vector<ECDbSqlColumn const*> columns;
        while (indexColStmt->Step() == BE_SQLITE_ROW)
            {
            Utf8CP columnName = indexColStmt->GetValueText(0);
            ECDbSqlColumn const* col = table->FindColumnCP(columnName);
            if (col == nullptr)
                return ERROR;

            columns.push_back(col);
            }

        if (nullptr == CacheIndex(ecdb, id, *table, name, isUnique, columns, primaryWhereClause, isAutoGenerated, classId, appliesToSubclassesIfPartial))
            return ERROR;
        }

    return SUCCESS;
    }

//---------------------------------------------------------------------------------------
// @bsimethod                                                    Affan.Khan        01/2015
//---------------------------------------------------------------------------------------
BentleyStatus SchemaImportECDbMapDb::InsertIndexInfoIntoDb(ECDbCR ecdb, ECDbSqlIndex const& index) const
    {
    CachedStatementPtr stmt = nullptr;
    ecdb.GetCachedStatement(stmt, "INSERT OR REPLACE INTO ec_Index (Id, TableId, Name, IsUnique, PrimaryWhereClause, IsAutoGenerated, ClassId, AppliesToSubclassesIfPartial) VALUES (?,?,?,?,?,?,?,?)");
    if (stmt == nullptr)
        return ERROR;

    stmt->BindInt64(1, index.GetId());
    stmt->BindInt64(2, index.GetTable().GetId());
    stmt->BindText(3, index.GetName().c_str(), Statement::MakeCopy::No);
    stmt->BindInt(4, index.GetIsUnique() ? 1 : 0);

    if (!index.GetPrimaryWhereClause().empty())
        stmt->BindText(5, index.GetPrimaryWhereClause().c_str(), Statement::MakeCopy::No);

    stmt->BindInt(6, index.IsAutoGenerated() ? 1 : 0);
    if (index.HasClassId())
        stmt->BindInt64(7, index.GetClassId());

    stmt->BindInt(8, index.AppliesToSubclassesIfPartial() ? 1 : 0);

    DbResult stat = stmt->Step();
    if (stat != BE_SQLITE_DONE)
        return ERROR;

    CachedStatementPtr indexColStmt = nullptr;
    ecdb.GetCachedStatement(indexColStmt, "INSERT OR REPLACE INTO ec_IndexColumn (IndexId, ColumnId, Ordinal) VALUES (?,?,?)");
    if (indexColStmt == nullptr)
        return ERROR;

    int i = 0;
    for (ECDbSqlColumn const* col : index.GetColumns())
        {
        indexColStmt->BindInt64(1, index.GetId());
        indexColStmt->BindInt64(2, col->GetId());
        indexColStmt->BindInt64(3, i);

        stat = indexColStmt->Step();
        if (stat != BE_SQLITE_DONE)
            return ERROR;

        indexColStmt->Reset();
        indexColStmt->ClearBindings();
        i++;
        }

    return SUCCESS;
    }

//---------------------------------------------------------------------------------------
// @bsimethod                                                    Krischan.Eberle  10/2015
//---------------------------------------------------------------------------------------
bool SchemaImportECDbMapDb::IsNameInUse(Utf8CP name) const
    {
    return m_usedIndexNames.find(name) != m_usedIndexNames.end() || m_coreMapDb.IsNameInUse(name);
    }


END_BENTLEY_SQLITE_EC_NAMESPACE
