/*--------------------------------------------------------------------------------------+
|
|     $Source: PrivateApi/DgnPlatformInternal/DgnCore/MaterialTokens.h $
|
|  $Copyright: (c) 2015 Bentley Systems, Incorporated. All rights reserved. $
|
+--------------------------------------------------------------------------------------*/
#pragma once

#include <DgnPlatform/DgnPlatform.h>

DGNPLATFORM_TYPEDEFS (MaterialTokenManager)

BEGIN_BENTLEY_DGN_NAMESPACE

enum PaletteToken
    {
    PALETTETOKEN_Invalid                            = -1,
    PALETTETOKEN_Material                           = 0,
    PALETTETOKEN_Color                              = 1,
    PALETTETOKEN_SpecularColor                      = 2,
    PALETTETOKEN_Diffuse                            = 3,
    PALETTETOKEN_Reflect                            = 4,
    PALETTETOKEN_Transmit                           = 5,
    PALETTETOKEN_Refract                            = 6,
    PALETTETOKEN_Specular                           = 7,
    PALETTETOKEN_Finish                             = 8,
    PALETTETOKEN_Highlight                          = 9,
    PALETTETOKEN_Pattern                            = 10,
    PALETTETOKEN_PatternOff                         = 11,
    PALETTETOKEN_PatternSize                        = 12,
    PALETTETOKEN_PatternAngle                       = 13,
    PALETTETOKEN_PatternScale                       = 14,
    PALETTETOKEN_PatternOffset                      = 15,
    PALETTETOKEN_PatternFlipV                       = 16,
    PALETTETOKEN_PatternLockSize                    = 17,
    PALETTETOKEN_PatternWeight                      = 18,
    PALETTETOKEN_PatternMapping                     = 19,
    PALETTETOKEN_PatternScaleMode                   = 20,
    PALETTETOKEN_BgTrans                            = 21,
    PALETTETOKEN_Fresnel                            = 22,
    PALETTETOKEN_PixiePattern                       = 23,
    PALETTETOKEN_PixieColor                         = 24,
    PALETTETOKEN_BumpMap                            = 25,
    PALETTETOKEN_BumpMapOff                         = 26,
    PALETTETOKEN_BumpMapScale                       = 27,
    PALETTETOKEN_BumpMapInvert                      = 28,
    PALETTETOKEN_Shadows                            = 29,
    PALETTETOKEN_End                                = 30,
    PALETTETOKEN_Ambient                            = 31,
    PALETTETOKEN_Radiosity                          = 32,
    PALETTETOKEN_LockEfficiency                     = 33,
    PALETTETOKEN_LockSpecularAndReflect             = 34,
    PALETTETOKEN_LockFinishToSpecular               = 35,
    PALETTETOKEN_ActualReflect                      = 36,
    PALETTETOKEN_Translucency                       = 37,
    PALETTETOKEN_Glow                               = 38,
    PALETTETOKEN_Thickness                          = 39,
    PALETTETOKEN_MapState                           = 40,
    PALETTETOKEN_MapLink                            = 41,
    PALETTETOKEN_PatternUnits                       = 42,
    PALETTETOKEN_MaterialVersion                    = 43,
    PALETTETOKEN_LayerType                          = 44,
    PALETTETOKEN_LayerState                         = 45,
    PALETTETOKEN_LayerGamma                         = 46,
    PALETTETOKEN_LayerColor                         = 47,
    PALETTETOKEN_LayerBrightness                    = 48,
    PALETTETOKEN_LayerContrast                      = 49,
    PALETTETOKEN_LayerOpacity                       = 50,
    PALETTETOKEN_LayerBlend                         = 51,
    PALETTETOKEN_LayerTileMode                      = 52,
    PALETTETOKEN_ProjectionOffset                   = 53,
    PALETTETOKEN_ProjectionAngles                   = 54,
    PALETTETOKEN_ProjectionScale                    = 55,
    PALETTETOKEN_PatternFlipU                       = 56,
    PALETTETOKEN_PatternTileDecalU                  = 57,
    PALETTETOKEN_PatternTileDecalV                  = 58,
    PALETTETOKEN_PatternTileMirrorU                 = 59,
    PALETTETOKEN_PatternTileMirrorV                 = 60,
    PALETTETOKEN_PatternLockProjectionScale         = 61,
    PALETTETOKEN_PatternCylCapped                   = 62,
    PALETTETOKEN_SpecularMap                        = 63,
    PALETTETOKEN_SpecularMapOff                     = 64,
    PALETTETOKEN_ReflectMap                         = 65,
    PALETTETOKEN_ReflectMapOff                      = 66,
    PALETTETOKEN_TransparencyMap                    = 67,
    PALETTETOKEN_TransparencyMapOff                 = 68,
    PALETTETOKEN_TranslucencyMap                    = 69,
    PALETTETOKEN_TranslucencyMapOff                 = 70,
    PALETTETOKEN_FinishMap                          = 71,
    PALETTETOKEN_FinishMapOff                       = 72,
    PALETTETOKEN_AssignmentOrAttachmentString       = 73,
    PALETTETOKEN_BlurReflections                    = 74,
    PALETTETOKEN_ReflectionRays                     = 75,
    PALETTETOKEN_DisplacementDistance               = 76,
    PALETTETOKEN_LinkedToLXP                        = 77,
    PALETTETOKEN_InvisibleToEye                     = 78,
    PALETTETOKEN_Dispersion                         = 79,
    PALETTETOKEN_Clearcoat                          = 80,
    PALETTETOKEN_BlurRefractions                    = 81,
    PALETTETOKEN_RefractionRays                     = 82,
    PALETTETOKEN_ShaderType                         = 83,
    PALETTETOKEN_ShaderEffect                       = 84,
    PALETTETOKEN_ShaderFlags                        = 85,
    PALETTETOKEN_ShaderBlend                        = 86,
    PALETTETOKEN_ShaderOpacity                      = 87,
    PALETTETOKEN_ShaderRate                         = 88,
    PALETTETOKEN_ShaderDirectMultiplier             = 89,
    PALETTETOKEN_ShaderIndirectMultiplier           = 90,
    PALETTETOKEN_ShaderSaturation                   = 91,
    PALETTETOKEN_ShaderIndirectIllumType            = 92,
    PALETTETOKEN_ShaderFlagEnabled                  = 93,
    PALETTETOKEN_ShaderFlagInvert                   = 94,
    PALETTETOKEN_ShaderFlagReceiveShadows           = 95,
    PALETTETOKEN_ShaderFlagVisibleToCamera          = 96,
    PALETTETOKEN_ShaderFlagVisibleToIndirectRays    = 97,
    PALETTETOKEN_ShaderFlagVisibleToReflectionRays  = 98,
    PALETTETOKEN_ShaderFlagVisibleToRefractionRays  = 99,
    PALETTETOKEN_DiffuseMap                         = 100,
    PALETTETOKEN_DiffuseMapOff                      = 101,
    PALETTETOKEN_GlowAmountMap                      = 102,
    PALETTETOKEN_GlowAmountMapOff                   = 103,
    PALETTETOKEN_ClearcoatAmountMap                 = 104,
    PALETTETOKEN_ClearcoatAmountMapOff              = 105,
    PALETTETOKEN_AnisotropicDirectionMap            = 106,
    PALETTETOKEN_AnisotropicDirectionMapOff         = 107,
    PALETTETOKEN_SpecularColorMap                   = 108,
    PALETTETOKEN_SpecularColorMapOff                = 109,
    PALETTETOKEN_TransparentColorMap                = 110,
    PALETTETOKEN_TransparentColorMapOff             = 111,
    PALETTETOKEN_TranslucencyColorMap               = 112,
    PALETTETOKEN_TranslucencyColorMapOff            = 113,
    PALETTETOKEN_TransparentColor                   = 114,
    PALETTETOKEN_TranslucencyColor                  = 115,
    PALETTETOKEN_Anisotropy                         = 116,
    PALETTETOKEN_FrontWeighting                     = 117,
    PALETTETOKEN_ScatteringDistance                 = 118,
    PALETTETOKEN_SubsurfaceSamples                  = 119,
    PALETTETOKEN_ValueMapInvert                     = 120,
    PALETTETOKEN_FurSpacing                         = 121,
    PALETTETOKEN_FurLength                          = 122,
    PALETTETOKEN_FurWidth                           = 123,
    PALETTETOKEN_FurTaper                           = 124,
    PALETTETOKEN_FurOffset                          = 125,
    PALETTETOKEN_FurStripRotation                   = 126,
    PALETTETOKEN_FurGrowthJitter                    = 127,
    PALETTETOKEN_FurPositionJitter                  = 128,
    PALETTETOKEN_FurDirectionJitter                 = 129,
    PALETTETOKEN_FurSizeJitter                      = 130,
    PALETTETOKEN_FurFlex                            = 131,
    PALETTETOKEN_FurRootBend                        = 132,
    PALETTETOKEN_FurCurls                           = 133,
    PALETTETOKEN_FurBumpAmplitude                   = 134,
    PALETTETOKEN_FurGuideRange                      = 135,
    PALETTETOKEN_FurGuideLength                     = 136,
    PALETTETOKEN_FurBlendAmount                     = 137,
    PALETTETOKEN_FurBlendAngle                      = 138,
    PALETTETOKEN_FurClumps                          = 139,
    PALETTETOKEN_FurClumpRange                      = 140,
    PALETTETOKEN_FurRate                            = 141,
    PALETTETOKEN_FurType                            = 142,
    PALETTETOKEN_FurGuides                          = 143,
    PALETTETOKEN_FurSegments                        = 144,
    PALETTETOKEN_FurAdaptiveSampling                = 145,
    PALETTETOKEN_FurRemoveBaseSurface               = 146,
    PALETTETOKEN_UseFur                             = 147,
    PALETTETOKEN_DisplacementMap                    = 148,
    PALETTETOKEN_DisplacementMapOff                 = 149,
    PALETTETOKEN_NormalMap                          = 150,
    PALETTETOKEN_NormalMapOff                       = 151,
    PALETTETOKEN_FurLengthMap                       = 152,
    PALETTETOKEN_FurLengthMapOff                    = 153,
    PALETTETOKEN_FurDensityMap                      = 154,
    PALETTETOKEN_FurDensityMapOff                   = 155,
    PALETTETOKEN_FurJitterMap                       = 156,
    PALETTETOKEN_FurJitterMapOff                    = 157,
    PALETTETOKEN_FurFlexMap                         = 158,
    PALETTETOKEN_FurFlexMapOff                      = 159,
    PALETTETOKEN_FurClumpsMap                       = 160,
    PALETTETOKEN_FurClumpsMapOff                    = 161,
    PALETTETOKEN_FurDirectionMap                    = 162,
    PALETTETOKEN_FurDirectionMapOff                 = 163,
    PALETTETOKEN_FurVectorMap                       = 164,
    PALETTETOKEN_FurVectorMapOff                    = 165,
    PALETTETOKEN_FurBumpMap                         = 166,
    PALETTETOKEN_FurBumpMapOff                      = 167,
    PALETTETOKEN_FurCurlsMap                        = 168,
    PALETTETOKEN_FurCurlsMapOff                     = 169,
    PALETTETOKEN_MapLayerType                       = 170,
    PALETTETOKEN_LxoProcType                        = 171,
    PALETTETOKEN_LxoNoiseColor1                     = 172,
    PALETTETOKEN_LxoNoiseAlpha1                     = 173,
    PALETTETOKEN_LxoNoiseColor2                     = 174,
    PALETTETOKEN_LxoNoiseAlpha2                     = 175,
    PALETTETOKEN_LxoNoiseType                       = 176,
    PALETTETOKEN_LxoNoiseFreq                       = 177,
    PALETTETOKEN_LxoNoiseFreqRatio                  = 178,
    PALETTETOKEN_LxoNoiseAmplitudeRatio             = 179,
    PALETTETOKEN_LxoNoiseBias                       = 180,
    PALETTETOKEN_LxoNoiseGain                       = 181,
    PALETTETOKEN_LxoCheckerColor1                   = 182,
    PALETTETOKEN_LxoCheckerAlpha1                   = 183,
    PALETTETOKEN_LxoCheckerColor2                   = 184,
    PALETTETOKEN_LxoCheckerAlpha2                   = 185,
    PALETTETOKEN_LxoCheckerType                     = 186,
    PALETTETOKEN_LxoCheckerTransitionWidth          = 187,
    PALETTETOKEN_LxoCheckerBias                     = 188,
    PALETTETOKEN_LxoCheckerGain                     = 189,
    PALETTETOKEN_LxoGridLineColor                   = 190,
    PALETTETOKEN_LxoGridLineAlpha                   = 191,
    PALETTETOKEN_LxoGridFillerColor                 = 192,
    PALETTETOKEN_LxoGridFillerAlpha                 = 193,
    PALETTETOKEN_LxoGridTransitionWidth             = 194,
    PALETTETOKEN_LxoGridType                        = 195,
    PALETTETOKEN_LxoGridLineWidth                   = 196,
    PALETTETOKEN_LxoGridBias                        = 197,
    PALETTETOKEN_LxoGridGain                        = 198,
    PALETTETOKEN_LxoDotColor                        = 199,
    PALETTETOKEN_LxoDotAlpha                        = 200,
    PALETTETOKEN_LxoDotFillerColor                  = 201,
    PALETTETOKEN_LxoDotFillerAlpha                  = 202,
    PALETTETOKEN_LxoDotTransitionWidth              = 203,
    PALETTETOKEN_LxoDotType                         = 204,
    PALETTETOKEN_LxoDotWidth                        = 205,
    PALETTETOKEN_LxoDotBias                         = 206,
    PALETTETOKEN_LxoDotGain                         = 207,
    PALETTETOKEN_LxoConstantColor                   = 208,
    PALETTETOKEN_LxoCellularColor                   = 209,
    PALETTETOKEN_LxoCellularFillerColor             = 210,
    PALETTETOKEN_LxoCellularAlpha                   = 211,
    PALETTETOKEN_LxoCellularFillerAlpha             = 212,
    PALETTETOKEN_LxoCellularTransitionWidth         = 213,
    PALETTETOKEN_LxoCellularWidth                   = 214,
    PALETTETOKEN_LxoCellularBias                    = 215,
    PALETTETOKEN_LxoCellularGain                    = 216,
    PALETTETOKEN_LxoCellularFreqRatio               = 217,
    PALETTETOKEN_LxoCellularAmplitudeRatio          = 218,
    PALETTETOKEN_LxoCellularValueVariation          = 219,
    PALETTETOKEN_LxoCellularHueVariation            = 220,
    PALETTETOKEN_LxoCellularSaturationVariation     = 221,
    PALETTETOKEN_LxoCellularType                    = 222,
    PALETTETOKEN_LxoCellularFrequencies             = 223,
    PALETTETOKEN_LxoWoodColor                       = 224,
    PALETTETOKEN_LxoWoodAlpha                       = 225,
    PALETTETOKEN_LxoWoodFillerColor                 = 226,
    PALETTETOKEN_LxoWoodFillerAlpha                 = 227,
    PALETTETOKEN_LxoWoodRingScale                   = 228,
    PALETTETOKEN_LxoWoodWaveScale                   = 229,
    PALETTETOKEN_LxoWoodWaviness                    = 230,
    PALETTETOKEN_LxoWoodGraininess                  = 231,
    PALETTETOKEN_LxoWoodGrainScale                  = 232,
    PALETTETOKEN_LxoWoodBias                        = 233,
    PALETTETOKEN_LxoWoodGain                        = 234,
    PALETTETOKEN_LxoWeaveYarnColor                  = 235,
    PALETTETOKEN_LxoWeaveGapColor                   = 236,
    PALETTETOKEN_LxoWeaveYarnAlpha                  = 237,
    PALETTETOKEN_LxoWeaveGapAlpha                   = 238,
    PALETTETOKEN_LxoWeaveYarnWidth                  = 239,
    PALETTETOKEN_LxoWeaveRoundness                  = 240,
    PALETTETOKEN_LxoWeaveBias                       = 241,
    PALETTETOKEN_LxoWeaveGain                       = 242,
    PALETTETOKEN_LxoRipplesCrestColor               = 243,
    PALETTETOKEN_LxoRipplesCrestAlpha               = 244,
    PALETTETOKEN_LxoRipplesTroughColor              = 245,
    PALETTETOKEN_LxoRipplesTroughAlpha              = 246,
    PALETTETOKEN_LxoRipplesWavelength               = 247,
    PALETTETOKEN_LxoRipplesPhase                    = 248,
    PALETTETOKEN_LxoRipplesBias                     = 249,
    PALETTETOKEN_LxoRipplesGain                     = 250,
    PALETTETOKEN_LxoRipplesSources                  = 251,
    PALETTETOKEN_LxoGradientVersion                 = 252,
    PALETTETOKEN_LxoGradientEnvType                 = 253,
    PALETTETOKEN_LxoGradientPre                     = 254,
    PALETTETOKEN_LxoGradientPost                    = 255,
    PALETTETOKEN_LxoGradientKeyX                    = 256,
    PALETTETOKEN_LxoGradientKeyY                    = 257,
    PALETTETOKEN_LxoGradientTANISlopeType           = 258,
    PALETTETOKEN_LxoGradientTANIWeightType          = 259,
    PALETTETOKEN_LxoGradientTANISlope               = 260,
    PALETTETOKEN_LxoGradientTANIWeight              = 261,
    PALETTETOKEN_LxoGradientTANIValue               = 262,
    PALETTETOKEN_LxoGradientTANOBreaks              = 263,
    PALETTETOKEN_LxoGradientTANOSlopeType           = 264,
    PALETTETOKEN_LxoGradientTANOWeightType          = 265,
    PALETTETOKEN_LxoGradientTANOSlope               = 266,
    PALETTETOKEN_LxoGradientTANOWeight              = 267,
    PALETTETOKEN_LxoGradientTANOValue               = 268,
    PALETTETOKEN_LxoGradientFlag                    = 269,
    PALETTETOKEN_LxoGradientInput                   = 270,
    PALETTETOKEN_OffsetZ                            = 271,
    PALETTETOKEN_ScaleZ                             = 272,
    PALETTETOKEN_LxoNoiseValue1                     = 273,
    PALETTETOKEN_LxoNoiseValue2                     = 274,
    PALETTETOKEN_LxoCheckerValue1                   = 275,
    PALETTETOKEN_LxoCheckerValue2                   = 276,
    PALETTETOKEN_LxoGridLineValue                   = 277,
    PALETTETOKEN_LxoGridFillerValue                 = 278,
    PALETTETOKEN_LxoDotValue                        = 279,
    PALETTETOKEN_LxoDotFillerValue                  = 280,
    PALETTETOKEN_LxoConstantValue                   = 281,
    PALETTETOKEN_LxoCellularCellValue               = 282,
    PALETTETOKEN_LxoCellularFillerValue             = 283,
    PALETTETOKEN_LxoWoodRingValue                   = 284,
    PALETTETOKEN_LxoWoodFillerValue                 = 285,
    PALETTETOKEN_LxoWeaveYarnValue                  = 286,
    PALETTETOKEN_LxoWeaveGapValue                   = 287,
    PALETTETOKEN_LxoRipplesCrestValue               = 288,
    PALETTETOKEN_LxoRipplesTroughValue              = 289,
    PALETTETOKEN_MapEnd                             = 290,
    PALETTETOKEN_Invisible                          = 291, // redundant with InvisibleToEye, but older palettes wrote out incorrect keyword.
    PALETTETOKEN_ReflectFresnel                     = 292,
    PALETTETOKEN_Dissolve                           = 293,
    PALETTETOKEN_AbsorptionDistance                 = 294,
    PALETTETOKEN_RefractionRoughness                = 295,
    PALETTETOKEN_GlowColor                          = 296,
    PALETTETOKEN_GlowColorMap                       = 297,
    PALETTETOKEN_GlowColorMapOff                    = 298,
    PALETTETOKEN_FurAutoFading                      = 299,
    PALETTETOKEN_FurHairShader                      = 300,
    PALETTETOKEN_UseFurMaterial                     = 301,
    PALETTETOKEN_FurMaterialName                    = 302,
    PALETTETOKEN_FurPaletteName                     = 303,
    PALETTETOKEN_LockFresnelToReflect               = 304,
    PALETTETOKEN_LockRefractionRoughnessToFinish    = 305,
    PALETTETOKEN_ImageGamma                         = 306,
    PALETTETOKEN_ReflectColor                       = 307,
    PALETTETOKEN_ReflectColorMap                    = 308,
    PALETTETOKEN_ReflectColorMapOff                 = 309,
    PALETTETOKEN_RefractionRoughnessMap             = 310,
    PALETTETOKEN_RefractionRoughnessMapOff          = 311,
    PALETTETOKEN_SpecularFresnelMap                 = 312,
    PALETTETOKEN_SpecularFresnelMapOff              = 313,
    PALETTETOKEN_GeometryMap                        = 314,
    PALETTETOKEN_GeometryMapOff                     = 315,
    PALETTETOKEN_CutSectionUseMaterial              = 316,
    PALETTETOKEN_CutSectionMaterialName             = 317,
    PALETTETOKEN_CutSectionMaterialPalette          = 318,
    PALETTETOKEN_CutSectionMaterialID               = 319,
    PALETTETOKEN_FurBillboard                       = 320,
    PALETTETOKEN_FurFrustumCulling                  = 321,
    PALETTETOKEN_LxoOcclusionDistance               = 322,
    PALETTETOKEN_LxoOcclusionVariance               = 323,
    PALETTETOKEN_LxoOcclusionVarianceScale          = 324,
    PALETTETOKEN_LxoOcclusionSpreadAngle            = 325,
    PALETTETOKEN_LxoOcclusionMaxCavityAngle         = 326,
    PALETTETOKEN_LxoOcclusionType                   = 327,
    PALETTETOKEN_LxoOcclusionRays                   = 328,
    PALETTETOKEN_LxoOcclusionColor1                 = 329,
    PALETTETOKEN_LxoOcclusionColor2                 = 330,
    PALETTETOKEN_LxoOcclusionAlpha1                 = 331,
    PALETTETOKEN_LxoOcclusionAlpha2                 = 332,
    PALETTETOKEN_LxoOcclusionBias                   = 333,
    PALETTETOKEN_LxoOcclusionGain                   = 334,
    PALETTETOKEN_LxoOcclusionValue1                 = 335,
    PALETTETOKEN_LxoOcclusionValue2                 = 336,
    PALETTETOKEN_LxoOcclusionSameSurface            = 337,
    PALETTETOKEN_ExitColor                          = 338,
    PALETTETOKEN_BackFaceCulling                    = 339,
    PALETTETOKEN_Antialiasing                       = 340,
    PALETTETOKEN_TextureFilterType                  = 341,
    PALETTETOKEN_LowValue                           = 342,
    PALETTETOKEN_HighValue                          = 343,
    PALETTETOKEN_AntialiasStrength                  = 344,
    PALETTETOKEN_MinimumSpot                        = 345,
    PALETTETOKEN_UseCellColors                      = 346,
    PALETTETOKEN_Snappable                          = 347,
    PALETTETOKEN_BrickPrimaryColor                  = 348,
    PALETTETOKEN_BrickSecondaryColor                = 349,	
    PALETTETOKEN_BrickPatternId                     = 350,	
    PALETTETOKEN_BrickHeaderCourseInterval          = 351,
    PALETTETOKEN_BrickBondType                      = 352,	
    PALETTETOKEN_BrickFlemishHeaders                = 353,	
    PALETTETOKEN_BrickMortarWidth                   = 354,
    PALETTETOKEN_BrickBrightnessVariation           = 355,
    PALETTETOKEN_BrickHorizontalVariation           = 356,
    PALETTETOKEN_BrickNoisiness                     = 357,	
    PALETTETOKEN_BrickAspectRatio		    = 358,	
    PALETTETOKEN_CheckerPrimaryColor		    = 359,
    PALETTETOKEN_CheckerSecondaryColor	            = 360,
    PALETTETOKEN_CheckerScaleFactor		    = 361,
    PALETTETOKEN_Checker3dPrimaryColor	            = 362,
    PALETTETOKEN_Checker3dSecondaryColor	    = 363,	
    PALETTETOKEN_Checker3dScaleFactor	            = 364,
    PALETTETOKEN_CloudsPrimaryColor	            = 365,
    PALETTETOKEN_CloudsSecondaryColor	            = 366,
    PALETTETOKEN_CloudsThickness		    = 367,
    PALETTETOKEN_CloudsLOD			    = 368,
    PALETTETOKEN_CloudsStepSize			    = 369,
    PALETTETOKEN_CloudsOnly		            = 370,
    PALETTETOKEN_FlamePrimaryColor	            = 371,
    PALETTETOKEN_FlameHeight	                    = 372,
    PALETTETOKEN_FlameWidth		            = 373,
    PALETTETOKEN_FlameFlickerSpeed		    = 374,
    PALETTETOKEN_FlameTurbulenceScale		    = 375,
    PALETTETOKEN_FlameLOD			    = 376,
    PALETTETOKEN_FogPrimaryColor		    = 377,	
    PALETTETOKEN_FogMinimumDensity		    = 378,
    PALETTETOKEN_FogMaximumDensity		    = 379,
    PALETTETOKEN_FogDriftSpeed			    = 380,
    PALETTETOKEN_FogSwirlSpeed			    = 381,
    PALETTETOKEN_FogThickness			    = 382,
    PALETTETOKEN_FogContrast			    = 383,
    PALETTETOKEN_FogLOD				    = 384,
    PALETTETOKEN_MarblePrimaryColor		    = 385,
    PALETTETOKEN_MarbleSecondaryColor		    = 386,	
    PALETTETOKEN_MarbleLOD			    = 387,
    PALETTETOKEN_MarbleVeinTightness		    = 388,
    PALETTETOKEN_SandPrimaryColor		    = 389,
    PALETTETOKEN_SandSecondaryColor		    = 390,
    PALETTETOKEN_SandLOD		            = 391,	    
    PALETTETOKEN_StonePrimaryColor		    = 392,
    PALETTETOKEN_StoneSecondaryColor		    = 393,
    PALETTETOKEN_StoneColors		            = 394,
    PALETTETOKEN_StoneColorTableOffset		    = 395,
    PALETTETOKEN_StoneMortarThickness		    = 396,
    PALETTETOKEN_StoneNoisiness		            = 397,
    PALETTETOKEN_TurbulenceLOD		            = 398,
    PALETTETOKEN_TurfPrimaryColor		    = 399,
    PALETTETOKEN_TurfSecondaryColor		    = 400,
    PALETTETOKEN_WaterPrimaryColor		    = 401,
    PALETTETOKEN_WaterRippleScale		    = 402,
    PALETTETOKEN_WaterRippleLOD		            = 403,
    PALETTETOKEN_WaterWaveScale		            = 404,
    PALETTETOKEN_WaterWaveLOD		            = 405,
    PALETTETOKEN_WaterWaveMinimum		    = 406,
    PALETTETOKEN_WaterRipplesPerWave		    = 407,
    PALETTETOKEN_WaterStepSize	                    = 408,
    PALETTETOKEN_WavesPrimaryColor		    = 409,
    PALETTETOKEN_WavesSecondaryColor		    = 410,
    PALETTETOKEN_WoodPrimaryColor		    = 411,
    PALETTETOKEN_WoodSecondaryColor		    = 412,
    PALETTETOKEN_AdvancedWoodPrimaryColor	    = 413,
    PALETTETOKEN_AdvancedWoodSecondaryColor	    = 414,
    PALETTETOKEN_BoardsPrimaryColor                 = 415,
    PALETTETOKEN_BoardsSecondaryColor	            = 416,
    PALETTETOKEN_BoardsPatternId	            = 417,
    PALETTETOKEN_BoardsPerColumn	            = 418,
    PALETTETOKEN_BoardsPerRow	                    = 419,
    PALETTETOKEN_BoardsCrackWidth	            = 420,
    PALETTETOKEN_BoardsBrightnessVariation          = 421,
    PALETTETOKEN_BoardsHorizontalVariation          = 422,
    PALETTETOKEN_BoardsWoodGrainScaleFactor         = 423,
    PALETTETOKEN_GradientInput	                    = 424,
    PALETTETOKEN_GradientType	                    = 425,
    PALETTETOKEN_GradientRelativeCoords             = 426,
    PALETTETOKEN_GradientPatternScaleZ	            = 427,
    PALETTETOKEN_GradientPatternOffsetZ	            = 428,
    PALETTETOKEN_GradientOffsets	            = 429,
    PALETTETOKEN_GradientColors	                    = 430,
                                                    
    PALETTETOKEN_TokenCount, // Always add above this entry and add corresponding keyword to s_paletteKeywords in MaterialTokens.cpp.
    };

enum TableToken
    {
    TABLETOKEN_Invalid              = -1,
    TABLETOKEN_RenderingParameters  = 0,
    TABLETOKEN_Palette              = 1,
    TABLETOKEN_Assign               = 2,
    TABLETOKEN_End                  = 3,
    TABLETOKEN_TokenCount, // Always add above this entry and add corresponding keyword to s_tableKeywords in MaterialTokens.cpp.
    };

enum HighlightToken
    {
    HIGHLIGHTTOKEN_Invalid      = -1,
    HIGHLIGHTTOKEN_Plastic      = 0,
    HIGHLIGHTTOKEN_Metallic     = 1,
    HIGHLIGHTTOKEN_UseElement   = 2,
    HIGHLIGHTTOKEN_Custom       = 3,
    HIGHLIGHTTOKEN_TokenCount, // Always add above this entry and add corresponding keyword to s_highlightKeywords in MaterialTokens.cpp.
    };

enum MapLinkToken
    {
    MAPLINKTOKEN_Invalid                = -1,
    MAPLINKTOKEN_Pattern                = 0,
    MAPLINKTOKEN_Bump                   = 1,
    MAPLINKTOKEN_Specular               = 2,
    MAPLINKTOKEN_Reflect                = 3,
    MAPLINKTOKEN_Transparency           = 4,
    MAPLINKTOKEN_Translucency           = 5,
    MAPLINKTOKEN_Finish                 = 6,
    MAPLINKTOKEN_Diffuse                = 7,
    MAPLINKTOKEN_GlowAmount             = 8,
    MAPLINKTOKEN_ClearcoatAmount        = 9,
    MAPLINKTOKEN_AnisotropicDirection   = 10,
    MAPLINKTOKEN_SpecularColor          = 11,
    MAPLINKTOKEN_TransparentColor       = 12,
    MAPLINKTOKEN_TranslucencyColor      = 13,
    MAPLINKTOKEN_Displacement           = 14,
    MAPLINKTOKEN_Normal                 = 15,
    MAPLINKTOKEN_FurLength              = 16,
    MAPLINKTOKEN_FurDensity             = 17,
    MAPLINKTOKEN_FurJitter              = 18,
    MAPLINKTOKEN_FurFlex                = 19,
    MAPLINKTOKEN_FurClumps              = 20,
    MAPLINKTOKEN_FurDirection           = 21,
    MAPLINKTOKEN_FurVector              = 22,
    MAPLINKTOKEN_FurBump                = 23,
    MAPLINKTOKEN_FurCurls               = 24,
    MAPLINKTOKEN_GlowColor              = 25,
    MAPLINKTOKEN_ReflectColor           = 26,
    MAPLINKTOKEN_RefractionRoughness    = 27,
    MAPLINKTOKEN_SpecularFresnel        = 28,
    MAPLINKTOKEN_Geometry               = 29,
    MAPLINKTOKEN_TokenCount, // Always add above this entry and add corresponding keyword to s_mapLinkKeywords in MaterialTokens.cpp.
    };

enum LayerTypeToken
    {
    LAYERTYPETOKEN_Invalid              = -1,
    LAYERTYPETOKEN_Image                = 0,
    LAYERTYPETOKEN_Procedure            = 1,
    LAYERTYPETOKEN_Gradient             = 2,
    LAYERTYPETOKEN_Normal               = 3,
    LAYERTYPETOKEN_Add                  = 4,
    LAYERTYPETOKEN_Subtract             = 5,
    LAYERTYPETOKEN_Alpha                = 6,
    LAYERTYPETOKEN_Dissolve             = 7,
    LAYERTYPETOKEN_Atop                 = 8,
    LAYERTYPETOKEN_In                   = 9,
    LAYERTYPETOKEN_Out                  = 10,
    LAYERTYPETOKEN_Gamma                = 11,
    LAYERTYPETOKEN_Tint                 = 12,
    LAYERTYPETOKEN_Brightness           = 13,
    LAYERTYPETOKEN_Contrast             = 14,
    LAYERTYPETOKEN_GroupStart           = 15,
    LAYERTYPETOKEN_GroupEnd             = 16,
    LAYERTYPETOKEN_AlphaBackgroundStart = 17,
    LAYERTYPETOKEN_AlphaBackgroundEnd   = 18,
    LAYERTYPETOKEN_LxoProcedure         = 19,
    LAYERTYPETOKEN_Difference           = 20,
    LAYERTYPETOKEN_NormalMultiply       = 21,
    LAYERTYPETOKEN_Divide               = 22,
    LAYERTYPETOKEN_Multiply             = 23,
    LAYERTYPETOKEN_Screen               = 24,
    LAYERTYPETOKEN_Overlay              = 25,
    LAYERTYPETOKEN_SoftLight            = 26,
    LAYERTYPETOKEN_HardLight            = 27,
    LAYERTYPETOKEN_Darken               = 28,
    LAYERTYPETOKEN_Lighten              = 29,
    LAYERTYPETOKEN_ColorDodge           = 30,
    LAYERTYPETOKEN_ColorBurn            = 31,
    LAYERTYPETOKEN_8119LxoProcedure     = 32,
    LAYERTYPETOKEN_Cell                 = 33,
    LAYERTYPETOKEN_TokenCount, // Always add above this entry and add corresponding keyword to s_layerTypeKeywords in MaterialTokens.cpp.
    };

enum LxoProcTypeToken
    {
    LXOPROCTYPETOKEN_Invalid    = -1,
    LXOPROCTYPETOKEN_None       = 0,
    LXOPROCTYPETOKEN_Noise      = 1,
    LXOPROCTYPETOKEN_Checker    = 2,
    LXOPROCTYPETOKEN_Grid       = 3,
    LXOPROCTYPETOKEN_Dot        = 4,
    LXOPROCTYPETOKEN_Constant   = 5,
    LXOPROCTYPETOKEN_Cellular   = 6,
    LXOPROCTYPETOKEN_Wood       = 7,
    LXOPROCTYPETOKEN_Weave      = 8,
    LXOPROCTYPETOKEN_Ripples    = 9,
    LXOPROCTYPETOKEN_Gradient   = 10,
    LXOPROCTYPETOKEN_Occlusion  = 11,
    LXOPROCTYPETOKEN_TokenCount, // Always add above this entry and add corresponding keyword to s_lxoProcTypeKeywords in MaterialTokens.cpp.
    };

enum TileToken
    {
    TILETOKEN_Invalid   = -1,
    TILETOKEN_Repeat    = 0,
    TILETOKEN_Mirror    = 1,
    TILETOKEN_Decal     = 2,
    TILETOKEN_TokenCount, // Always add above this entry and add corresponding keyword to s_tileKeywords in MaterialTokens.cpp.
    };

typedef std::map <WString, int32_t>           KeywordTokenMap;
typedef std::pair <WString, int32_t>          KeywordTokenPair;

//=======================================================================================
// @bsiclass                                                    MattGooding     01/10
//=======================================================================================
struct MaterialTokenManager
{
private:
    KeywordTokenMap                 m_paletteMap;
    KeywordTokenMap                 m_tableMap;
    KeywordTokenMap                 m_highlightMap;
    KeywordTokenMap                 m_mapLinkMap;
    KeywordTokenMap                 m_layerTypeMap;
    KeywordTokenMap                 m_lxoProcTypeMap;
    KeywordTokenMap                 m_tileMap;

    MaterialTokenManager ();

    int32_t ResolveToken (WStringR arg, WCharCP keyword, KeywordTokenMap const& map);

public:
    PaletteToken ResolvePaletteToken (WStringR arg, WCharCP input);
    TableToken ResolveTableToken (WStringR arg, WCharCP input);
    HighlightToken ResolveHighlightToken (WStringR arg, WCharCP input);
    MapLinkToken ResolveMapLinkToken (WStringR arg, WCharCP input);
    LayerTypeToken ResolveLayerTypeToken (WStringR arg, WCharCP input);
    LxoProcTypeToken ResolveLxoProcTypeToken (WStringR arg, WCharCP input);
    TileToken ResolveTileToken (WStringR arg, WCharCP input);

    void ResolvePaletteKeyword (Utf8StringR keyword, PaletteToken token, MaterialVersion version);
    void ResolvePaletteKeyword (WStringR keyword, PaletteToken token, MaterialVersion version);
    void ResolveTableKeyword (WStringR keyword, TableToken token);
    void ResolveHighlightKeyword (WStringR keyword, HighlightToken token);
    void ResolveMapLinkKeyword (WStringR keyword, MapLinkToken token);
    void ResolveLayerTypeKeyword (WStringR keyword, LayerTypeToken token);
    void ResolveLxoProcTypeKeyword (WStringR keyword, LxoProcTypeToken token);
    void ResolveTileKeyword (WStringR keyword, TileToken token);

    MaterialMapLayer::LayerType ResolveLayerTypeFromToken (LayerTypeToken token);
    LayerTypeToken ResolveLayerTokenFromType (MaterialMapLayer::LayerType type);
    MaterialMap::MapType ResolveMapTypeFromToken (MapLinkToken token);
    MapLinkToken ResolveMapTokenFromType (MaterialMap::MapType type);

    static MaterialTokenManagerR GetManagerR ();
};

END_BENTLEY_DGN_NAMESPACE
