/*--------------------------------------------------------------------------------------+
|
|  $Source: Domain/GeneratedInserts/GeneratedOmniClass41Inserts.cpp $
|
|  $Copyright: (c) 2018 Bentley Systems, Incorporated. All rights reserved. $
|
+--------------------------------------------------------------------------------------*/
//===========================================================================================
// WARNING: This is an automatically generated code for building classification inserts 
// WARNING: To generate, call "bb -r BuildingShared -f BuildingShared -p CodeGenerators b -c"
//===========================================================================================


#include <ClassificationSystems/ClassificationSystemsApi.h>
#include <DgnClientFx/DgnClientApp.h>
#include <BuildingShared\BuildingSharedApi.h>


namespace BS = BENTLEY_BUILDING_SHARED_NAMESPACE_NAME;

BEGIN_CLASSIFICATIONSYSTEMS_NAMESPACE
void ClassificationSystemsDomain::InsertOmniClass41Definitions(Dgn::DgnDbR db) const
    {
    ClassificationSystemCPtr omniClassSystem = TryAndGetSystem(db, "OmniClass");
    OmniClassClassDefinitionPtr subsection0OmniClass;
    subsection0OmniClass = InsertOmniClass(*omniClassSystem, "41-10 00 00", "Chemical Elements", nullptr);
    OmniClassClassDefinitionPtr subsection1OmniClass;
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-10 10 00", "Non-Metallic Solid Elements", subsection0OmniClass.get());
    OmniClassClassDefinitionPtr subsection2OmniClass;
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 10 06", "Carbon ", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 10 14", "Silicon", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 10 15", "Phosphorus", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 10 16", "Sulfur", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 10 20", "Calcium", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 10 53", "Iodine", subsection1OmniClass.get());
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 00", "Metallic Elements", subsection0OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 05", "Boron", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 12", "Magnesium", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 13", "Aluminum", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 19", "Potassium", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 22", "Titanium", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 23", "Vanadium", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 24", "Chromium", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 25", "Manganese", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 26", "Iron", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 27", "Cobalt", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 28", "Nickel", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 29", "Copper", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 30", "Zinc", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 33", "Arsenic", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 42", "Molybdenum", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 47", "Silver", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 48", "Cadmium", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 50", "Tin", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 51", "Antimony", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 74", "Tungsten", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 79", "Gold", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 82", "Lead", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 20 83", "Bismuth", subsection1OmniClass.get());
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-10 50 00", "Liquid Elements", subsection0OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 50 80", "Mercury", subsection1OmniClass.get());
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-10 70 00", "Gaseous Elements", subsection0OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 70 01", "Hydrogen", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 70 02", "Helium", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 70 07", "Nitrogen", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 70 08", "Oxygen", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 70 09", "Fluorine", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 70 10", "Neon", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 70 17", "Chlorine", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 70 18", "Argon", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 70 36", "Krypton", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 70 54", "Xenon", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-10 70 86", "Radon", subsection1OmniClass.get());
    subsection0OmniClass = InsertOmniClass(*omniClassSystem, "41-30 00 00", "Solid Compounds", nullptr);
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 00", "Mineral Compounds", subsection0OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11", "Rocks", subsection1OmniClass.get());
    OmniClassClassDefinitionPtr subsection3OmniClass;
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 11", "Granites", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 14", "Limestones", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 17", "Marbles", subsection2OmniClass.get());
    OmniClassClassDefinitionPtr subsection4OmniClass;
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 17 11", "Marble Stone", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 17 14", "Travertine", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 17 17", "Limestone Marble", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 17 21", "Onyx", subsection3OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 21", "Quartz-Based Rocks", subsection2OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 21 11", "Quartz", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 21 14", "Quartzitic-Sandstone", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 21 17", "Sandstone", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 21 21", "Sand", subsection3OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 24", "Slates", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 27", "Rock Fibers", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 31", "Other Rocks", subsection2OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 31 11", "Barite", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 31 14", "Chalk", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 31 17", "Tufa", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 31 21", "Perlite", subsection3OmniClass.get());
    OmniClassClassDefinitionPtr subsection5OmniClass;
                        subsection5OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 31 21 11", "Expanded Perlite", subsection4OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 31 24", "Shale", subsection3OmniClass.get());
                        subsection5OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 31 24 11", "Expanded Shale", subsection4OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 31 27", "Mica", subsection3OmniClass.get());
                        subsection5OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 31 27 11", "Expanded Mica", subsection4OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 11 31 31", "Expanded Vermiculite", subsection3OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 14", "Clays", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 14 11", "Clay", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 14 14", "Fire Clay", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 14 17", "Bentonite", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 14 21", "Expanded Clay", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 14 24", "Ceramics", subsection2OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 14 24 11", "Brick", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 14 24 14", "Earthenware", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 14 24 17", "Terracotta ", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 14 24 21", "Fired Shale", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 14 24 24", "Porcelain", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 14 24 27", "Vitreous China", subsection3OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 17", "Other Cementitious Materials", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 17 11", "Soils", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 17 14", "Cements", subsection2OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 17 14 11", "Portland Cement", subsection3OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 17 17", "Limes", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 17 17 11", "Hydrated Lime", subsection2OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 17 17 14", "Quicklime", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 17 17 17", "Slaked Lime", subsection3OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 17 21", "Gypsums", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 17 24", "Calcium Silicate", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 17 27", "Magnesia", subsection2OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 21", "Bituminous and Petrochemical Minerals", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 21 11", "Asphalts", subsection2OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 21 11 11", "Asphalt", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 21 11 14", "Polymer Modified Asphalt", subsection3OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 21 14", "Coal Tars", subsection2OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 21 14 11", "Coal Tar Pitch", subsection3OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 21 17", "Paraffins", subsection2OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 24", "Other Non-Metallic Natural Minerals", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 24 11", "Asbestos", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 24 14", "Graphite", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 24 17", "Carbon Black", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 24 21", "Salt (Sodium Chloride)", subsection2OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 27", "Other Minerals Not Occurring Naturally", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 27 11", "Glasses and Glass-Like Materials", subsection2OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 27 11 11", "Glass", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 27 11 14", "Porcelain Enamel", subsection3OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 27 14", "Other Minerals", subsection2OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 27 14 11", "Fly Ash", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 27 14 14", "Carbon Fiber", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 27 14 17", "Silicon Carbide", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 10 27 14 21", "Cermet", subsection3OmniClass.get());
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 00", "Metallic Compounds", subsection0OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 11", "Iron Alloys", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 11 11", "Carbon Steels", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 11 14", "Stainless Steels", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 11 21", "Other Steels", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 11 99", "Other Iron Alloys", subsection2OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 11 99 11", "Cast Iron", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 11 99 14", "Wrought Iron", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 11 99 17", "Ductile Iron", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 11 99 21", "Malleable Iron", subsection3OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 14", "Aluminum Alloys", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 14 11", "Aluminum-Zinc Alloys", subsection2OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 17", "Copper Alloys", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 17 11", "Brasses", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 17 14", "Bronzes", subsection2OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 21", "Zinc Alloys", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 21 11", "Zinc-Lead Alloys", subsection2OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 21 11 11", "Zamac", subsection3OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 21 14", "Other Zinc Alloys", subsection2OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 21 14 11", "Mazac", subsection3OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 24", "Lead Alloys", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 24 11", "Lead and Tin Alloys", subsection2OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 24 11 11", "Terne", subsection3OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 20 27", "Other Alloys", subsection1OmniClass.get());
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 00", "Plant Materials", subsection0OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 21", "Materials from Other Plants", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 34 11", "Natural Rubber", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 34 12", "Cotton", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 34 13", "Jute", subsection2OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 11", "Materials from Plants in General", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 11 11", "Cellulose", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 11 14", "Paper", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 11 17", "Textiles", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 11 21", "Combustion Residues", subsection2OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 14", "Materials from Trees", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 14 11", "Timber", subsection2OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 14 11 11", "Softwood Timber", subsection3OmniClass.get());
                        subsection5OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 14 11 11 11", "Southern Pine", subsection4OmniClass.get());
                        subsection5OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 14 11 11 14", "Douglas Fir-Larch", subsection4OmniClass.get());
                        subsection5OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 14 11 11 17", "Spruce-Pine-Fir", subsection4OmniClass.get());
                        subsection5OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 14 11 11 21", "Redwood", subsection4OmniClass.get());
                        subsection5OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 14 11 11 24", "Western Red Cedar", subsection4OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 14 11 14", "Hardwood Timber", subsection3OmniClass.get());
                        subsection5OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 14 11 14 11", "White Oak", subsection4OmniClass.get());
                        subsection5OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 14 11 14 14", "Red Oak", subsection4OmniClass.get());
                        subsection5OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 14 11 14 17", "Maple", subsection4OmniClass.get());
                        subsection5OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 14 11 14 21", "Cherry", subsection4OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 14 14", "Other Tree Parts", subsection2OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 14 14 11", "Tree Bark", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 14 14 14", "Coir", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 14 14 17", "Cork", subsection3OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 17", "Materials from Grasses", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 17 11", "Bamboo", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 17 14", "Grass", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 17 17", "Linen", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 17 21", "Reeds", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 30 17 24", "Straw", subsection2OmniClass.get());
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-30 40 00", "Other Organic Materials", subsection0OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 40 11", "Materials from Animals", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 40 11 11", "Animal Hair Materials", subsection2OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 40 11 11 11", "Wool", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 40 11 11 14", "Horsehair", subsection3OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 40 11 14", "Other Animal-Based Materials", subsection2OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 40 11 14 11", "Leather", subsection3OmniClass.get());
                    subsection4OmniClass = InsertOmniClass(*omniClassSystem, "41-30 40 11 14 14", "Tallow", subsection3OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 40 14", "Materials from Insects", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 40 14 11", "Silk", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 40 14 14", "Beeswax", subsection2OmniClass.get());
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 00", "Synthetic Solid Compounds", subsection0OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 11", "Acids", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 14", "Bases (Alkalis)", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 17", "Salts", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21", "Plastics", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21 11", "Acrylonitrile-Butadiene-Styrene (ABS)", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21 14", "Acrylic, Polymethyl Methacrylate", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21 17", "Epoxy", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21 21", "Polyamide", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21 24", "Polybutylene (PB)", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21 27", "Phenolic", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21 31", "Polycarbonate", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21 34", "Polyester", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21 37", "Polyethylene, Polythene (PE)", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21 41", "Polyisocyanurate", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21 51", "Polypropylene", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21 54", "Polystyrene", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21 61", "Polyurethane", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21 64", "Polyvinyl Chloride, Plasticised (PVC)", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21 71", "Polyvinyl Chloride, Unplasticised (PVC-U)", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21 74", "Polyvinylidene Fluoride", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21 81", "Urea Formaldehyde", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 21 84", "Vinyl", subsection2OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 24", "Rubbers", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 24 11", "Butyl Rubber", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 24 14", "Neoprene", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 24 17", "Silicone", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 24 21", "Polysulfide", subsection2OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 27", "Other Petrochemical Compounds", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 27 11", "Paraffin", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 27 14", "Waxes", subsection2OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-30 50 99", "Other Synthetic Solid Compounds", subsection1OmniClass.get());
    subsection0OmniClass = InsertOmniClass(*omniClassSystem, "41-50 00 00", "Liquids", nullptr);
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-50 10 00", "Water", subsection0OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-50 10 11", "Fresh Waters", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-50 10 11 11", "Rain Water", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-50 10 11 14", "Ground Water", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-50 10 11 17", "Distilled Water", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-50 10 11 21", "Deionized Water", subsection2OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-50 10 14", "Salt Waters", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-50 10 14 11", "Sea Water", subsection2OmniClass.get());
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-50 20 00", "Water-Based Solutions", subsection0OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-50 20 11", "Water-Based Acid Solutions", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-50 20 14", "Water-Based Base (Alkali) Solutions", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-50 20 99", "Other Water-Based Solutions", subsection1OmniClass.get());
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-50 30 00", "Mineral Liquids", subsection0OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-50 30 11", "Petroleum Products", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-50 30 11 11", "Gasoline", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-50 30 11 14", "Diesel Oils", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-50 30 11 17", "Fuel Oils", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-50 30 11 21", "Kerosene", subsection2OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-50 30 14", "Mineral Oils", subsection1OmniClass.get());
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-50 40 00", "Plant Derived Liquids", subsection0OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-50 40 11", "Vegetable Oils", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-50 40 99", "Other Plant-Derived Liquids", subsection1OmniClass.get());
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-50 50 00", "Animal-Derived Liquids", subsection0OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-50 50 11", "Fish Oils", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-50 50 99", "Other Animal-Derived Liquids", subsection1OmniClass.get());
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-50 60 00", "Synthetic Liquids", subsection0OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-50 60 11", "Alcohols", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-50 60 14", "Lubricants", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-50 60 17", "Ammonia", subsection1OmniClass.get());
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-50 99 00", "Other Liquids", subsection0OmniClass.get());
    subsection0OmniClass = InsertOmniClass(*omniClassSystem, "41-70 00 00", "Gases", nullptr);
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-70 10 00", "Natural Gases", subsection0OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-70 10 11", "Natural Air", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-70 10 14", "Carbon Dioxide", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-70 10 17", "Carbon Monoxide", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-70 10 21", "Water Vapor", subsection1OmniClass.get());
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-70 20 00", "Hydrocarbon Gases", subsection0OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-70 20 11", "Propane", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-70 20 14", "Butane", subsection1OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-70 20 17", "LPG", subsection1OmniClass.get());
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-70 30 00", "Refrigerants", subsection0OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-70 30 11", "Fluorocarbons", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-70 30 11 11", "Trichlorofluoromethane (CFC-11)", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-70 30 11 12", "Dichlorodifluoromethane (CFC-12)", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-70 30 11 13", "Chlorotrifluoromethane (CFC-13)", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-70 30 11 14", "Chlorodifluoromethane (HCFC-22)", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-70 30 11 15", "Trifluoromethane (HFC-23)", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-70 30 11 16", "Trichlorotrifluoroethane (CFC-113)", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-70 30 11 17", "Dichloro-Tetrafluoroethane (CFC-114)", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-70 30 11 18", "Chloro-Pentafluoroethane (CFC-115)", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-70 30 11 19", "Hexachloroethane (CFC-116)", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-70 30 11 20", "Tetrafluoroethane (HFC-134a)", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-70 30 11 21", "Heptafluoropropane (HFC-227ea)", subsection2OmniClass.get());
        subsection1OmniClass = InsertOmniClass(*omniClassSystem, "41-70 99 00", "Other Gases", subsection0OmniClass.get());
            subsection2OmniClass = InsertOmniClass(*omniClassSystem, "41-70 99 11", "Halon", subsection1OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-70 99 11 11", "Bromochlorodifluoromethane (Halon 1211)", subsection2OmniClass.get());
                subsection3OmniClass = InsertOmniClass(*omniClassSystem, "41-70 99 11 12", "Bromotrifluoromethane (Halon 1301)", subsection2OmniClass.get());
    }

END_CLASSIFICATIONSYSTEMS_NAMESPACE
