/*--------------------------------------------------------------------------------------+
|
|  $Source: Domain/GeneratedInserts/GeneratedOmniClass41Inserts.cpp $
|
|  $Copyright: (c) 2019 Bentley Systems, Incorporated. All rights reserved. $
|
+--------------------------------------------------------------------------------------*/
//===========================================================================================
// WARNING: This is an automatically generated code for building classification inserts 
// WARNING: To generate, call "bb -r BuildingShared -f BuildingShared -p CodeGenerators b -c"
//===========================================================================================


#include <ClassificationSystems/ClassificationSystemsApi.h>
#include <BuildingShared/DgnUtils/BuildingDgnUtilsApi.h>


namespace BS = BENTLEY_BUILDING_SHARED_NAMESPACE_NAME;

BEGIN_CLASSIFICATIONSYSTEMS_NAMESPACE

void ClassificationSystemsDomain::InsertOmniClass41Definitions(Dgn::DgnDbR db) const
    {
    ClassificationSystemCPtr omniClassSystem = TryAndGetSystem(db, "OmniClass", "2006-03-28");
    ClassificationTableCPtr omniClassTable = TryAndGetTable(*omniClassSystem , "Table 41 - Materials");

    ClassificationPtr subsection0OmniClass;
    subsection0OmniClass = InsertClassification(*omniClassTable, "Chemical Elements", "41-10 00 00", "", nullptr, nullptr);
    ClassificationPtr subsection1OmniClass;
        subsection1OmniClass = InsertClassification(*omniClassTable, "Non-Metallic Solid Elements", "41-10 10 00", "", nullptr, subsection0OmniClass.get());
    ClassificationPtr subsection2OmniClass;
            subsection2OmniClass = InsertClassification(*omniClassTable, "Carbon ", "41-10 10 06", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Silicon", "41-10 10 14", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Phosphorus", "41-10 10 15", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Sulfur", "41-10 10 16", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Calcium", "41-10 10 20", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Iodine", "41-10 10 53", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassTable, "Metallic Elements", "41-10 20 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Boron", "41-10 20 05", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Magnesium", "41-10 20 12", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Aluminum", "41-10 20 13", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Potassium", "41-10 20 19", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Titanium", "41-10 20 22", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Vanadium", "41-10 20 23", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Chromium", "41-10 20 24", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Manganese", "41-10 20 25", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Iron", "41-10 20 26", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Cobalt", "41-10 20 27", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Nickel", "41-10 20 28", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Copper", "41-10 20 29", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Zinc", "41-10 20 30", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Arsenic", "41-10 20 33", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Molybdenum", "41-10 20 42", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Silver", "41-10 20 47", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Cadmium", "41-10 20 48", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Tin", "41-10 20 50", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Antimony", "41-10 20 51", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Tungsten", "41-10 20 74", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Gold", "41-10 20 79", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Lead", "41-10 20 82", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Bismuth", "41-10 20 83", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassTable, "Liquid Elements", "41-10 50 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Mercury", "41-10 50 80", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassTable, "Gaseous Elements", "41-10 70 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Hydrogen", "41-10 70 01", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Helium", "41-10 70 02", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Nitrogen", "41-10 70 07", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Oxygen", "41-10 70 08", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Fluorine", "41-10 70 09", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Neon", "41-10 70 10", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Chlorine", "41-10 70 17", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Argon", "41-10 70 18", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Krypton", "41-10 70 36", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Xenon", "41-10 70 54", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Radon", "41-10 70 86", "", nullptr, subsection1OmniClass.get());
    subsection0OmniClass = InsertClassification(*omniClassTable, "Solid Compounds", "41-30 00 00", "", nullptr, nullptr);
        subsection1OmniClass = InsertClassification(*omniClassTable, "Mineral Compounds", "41-30 10 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Rocks", "41-30 10 11", "", nullptr, subsection1OmniClass.get());
    ClassificationPtr subsection3OmniClass;
                subsection3OmniClass = InsertClassification(*omniClassTable, "Granites", "41-30 10 11 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Limestones", "41-30 10 11 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Marbles", "41-30 10 11 17", "", nullptr, subsection2OmniClass.get());
    ClassificationPtr subsection4OmniClass;
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Marble Stone", "41-30 10 11 17 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Travertine", "41-30 10 11 17 14", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Limestone Marble", "41-30 10 11 17 17", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Onyx", "41-30 10 11 17 21", "", nullptr, subsection3OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Quartz-Based Rocks", "41-30 10 11 21", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Quartz", "41-30 10 11 21 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Quartzitic-Sandstone", "41-30 10 11 21 14", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Sandstone", "41-30 10 11 21 17", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Sand", "41-30 10 11 21 21", "", nullptr, subsection3OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Slates", "41-30 10 11 24", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Rock Fibers", "41-30 10 11 27", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Other Rocks", "41-30 10 11 31", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Barite", "41-30 10 11 31 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Chalk", "41-30 10 11 31 14", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Tufa", "41-30 10 11 31 17", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Perlite", "41-30 10 11 31 21", "", nullptr, subsection3OmniClass.get());
    ClassificationPtr subsection5OmniClass;
                        subsection5OmniClass = InsertClassification(*omniClassTable, "Expanded Perlite", "41-30 10 11 31 21 11", "", nullptr, subsection4OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Shale", "41-30 10 11 31 24", "", nullptr, subsection3OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassTable, "Expanded Shale", "41-30 10 11 31 24 11", "", nullptr, subsection4OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Mica", "41-30 10 11 31 27", "", nullptr, subsection3OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassTable, "Expanded Mica", "41-30 10 11 31 27 11", "", nullptr, subsection4OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Expanded Vermiculite", "41-30 10 11 31 31", "", nullptr, subsection3OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Clays", "41-30 10 14", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Clay", "41-30 10 14 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Fire Clay", "41-30 10 14 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Bentonite", "41-30 10 14 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Expanded Clay", "41-30 10 14 21", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Ceramics", "41-30 10 14 24", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Brick", "41-30 10 14 24 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Earthenware", "41-30 10 14 24 14", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Terracotta ", "41-30 10 14 24 17", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Fired Shale", "41-30 10 14 24 21", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Porcelain", "41-30 10 14 24 24", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Vitreous China", "41-30 10 14 24 27", "", nullptr, subsection3OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Other Cementitious Materials", "41-30 10 17", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Soils", "41-30 10 17 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Cements", "41-30 10 17 14", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Portland Cement", "41-30 10 17 14 11", "", nullptr, subsection3OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Limes", "41-30 10 17 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Hydrated Lime", "41-30 10 17 17 11", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Quicklime", "41-30 10 17 17 14", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Slaked Lime", "41-30 10 17 17 17", "", nullptr, subsection3OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Gypsums", "41-30 10 17 21", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Calcium Silicate", "41-30 10 17 24", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Magnesia", "41-30 10 17 27", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Bituminous and Petrochemical Minerals", "41-30 10 21", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Asphalts", "41-30 10 21 11", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Asphalt", "41-30 10 21 11 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Polymer Modified Asphalt", "41-30 10 21 11 14", "", nullptr, subsection3OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Coal Tars", "41-30 10 21 14", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Coal Tar Pitch", "41-30 10 21 14 11", "", nullptr, subsection3OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Paraffins", "41-30 10 21 17", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Other Non-Metallic Natural Minerals", "41-30 10 24", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Asbestos", "41-30 10 24 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Graphite", "41-30 10 24 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Carbon Black", "41-30 10 24 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Salt (Sodium Chloride)", "41-30 10 24 21", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Other Minerals Not Occurring Naturally", "41-30 10 27", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Glasses and Glass-Like Materials", "41-30 10 27 11", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Glass", "41-30 10 27 11 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Porcelain Enamel", "41-30 10 27 11 14", "", nullptr, subsection3OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Other Minerals", "41-30 10 27 14", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Fly Ash", "41-30 10 27 14 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Carbon Fiber", "41-30 10 27 14 14", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Silicon Carbide", "41-30 10 27 14 17", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Cermet", "41-30 10 27 14 21", "", nullptr, subsection3OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassTable, "Metallic Compounds", "41-30 20 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Iron Alloys", "41-30 20 11", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Carbon Steels", "41-30 20 11 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Stainless Steels", "41-30 20 11 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Other Steels", "41-30 20 11 21", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Other Iron Alloys", "41-30 20 11 99", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Cast Iron", "41-30 20 11 99 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Wrought Iron", "41-30 20 11 99 14", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Ductile Iron", "41-30 20 11 99 17", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Malleable Iron", "41-30 20 11 99 21", "", nullptr, subsection3OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Aluminum Alloys", "41-30 20 14", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Aluminum-Zinc Alloys", "41-30 20 14 11", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Copper Alloys", "41-30 20 17", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Brasses", "41-30 20 17 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Bronzes", "41-30 20 17 14", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Zinc Alloys", "41-30 20 21", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Zinc-Lead Alloys", "41-30 20 21 11", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Zamac", "41-30 20 21 11 11", "", nullptr, subsection3OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Other Zinc Alloys", "41-30 20 21 14", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Mazac", "41-30 20 21 14 11", "", nullptr, subsection3OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Lead Alloys", "41-30 20 24", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Lead and Tin Alloys", "41-30 20 24 11", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Terne", "41-30 20 24 11 11", "", nullptr, subsection3OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Other Alloys", "41-30 20 27", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassTable, "Plant Materials", "41-30 30 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Materials from Other Plants", "41-30 30 21", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Natural Rubber", "41-30 34 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Cotton", "41-30 34 12", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Jute", "41-30 34 13", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Materials from Plants in General", "41-30 30 11", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Cellulose", "41-30 30 11 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Paper", "41-30 30 11 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Textiles", "41-30 30 11 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Combustion Residues", "41-30 30 11 21", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Materials from Trees", "41-30 30 14", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Timber", "41-30 30 14 11", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Softwood Timber", "41-30 30 14 11 11", "", nullptr, subsection3OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassTable, "Southern Pine", "41-30 30 14 11 11 11", "", nullptr, subsection4OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassTable, "Douglas Fir-Larch", "41-30 30 14 11 11 14", "", nullptr, subsection4OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassTable, "Spruce-Pine-Fir", "41-30 30 14 11 11 17", "", nullptr, subsection4OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassTable, "Redwood", "41-30 30 14 11 11 21", "", nullptr, subsection4OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassTable, "Western Red Cedar", "41-30 30 14 11 11 24", "", nullptr, subsection4OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Hardwood Timber", "41-30 30 14 11 14", "", nullptr, subsection3OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassTable, "White Oak", "41-30 30 14 11 14 11", "", nullptr, subsection4OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassTable, "Red Oak", "41-30 30 14 11 14 14", "", nullptr, subsection4OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassTable, "Maple", "41-30 30 14 11 14 17", "", nullptr, subsection4OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassTable, "Cherry", "41-30 30 14 11 14 21", "", nullptr, subsection4OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Other Tree Parts", "41-30 30 14 14", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Tree Bark", "41-30 30 14 14 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Coir", "41-30 30 14 14 14", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Cork", "41-30 30 14 14 17", "", nullptr, subsection3OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Materials from Grasses", "41-30 30 17", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Bamboo", "41-30 30 17 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Grass", "41-30 30 17 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Linen", "41-30 30 17 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Reeds", "41-30 30 17 21", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Straw", "41-30 30 17 24", "", nullptr, subsection2OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassTable, "Other Organic Materials", "41-30 40 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Materials from Animals", "41-30 40 11", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Animal Hair Materials", "41-30 40 11 11", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Wool", "41-30 40 11 11 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Horsehair", "41-30 40 11 11 14", "", nullptr, subsection3OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Other Animal-Based Materials", "41-30 40 11 14", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Leather", "41-30 40 11 14 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassTable, "Tallow", "41-30 40 11 14 14", "", nullptr, subsection3OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Materials from Insects", "41-30 40 14", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Silk", "41-30 40 14 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Beeswax", "41-30 40 14 14", "", nullptr, subsection2OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassTable, "Synthetic Solid Compounds", "41-30 50 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Acids", "41-30 50 11", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Bases (Alkalis)", "41-30 50 14", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Salts", "41-30 50 17", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Plastics", "41-30 50 21", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Acrylonitrile-Butadiene-Styrene (ABS)", "41-30 50 21 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Acrylic, Polymethyl Methacrylate", "41-30 50 21 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Epoxy", "41-30 50 21 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Polyamide", "41-30 50 21 21", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Polybutylene (PB)", "41-30 50 21 24", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Phenolic", "41-30 50 21 27", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Polycarbonate", "41-30 50 21 31", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Polyester", "41-30 50 21 34", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Polyethylene, Polythene (PE)", "41-30 50 21 37", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Polyisocyanurate", "41-30 50 21 41", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Polypropylene", "41-30 50 21 51", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Polystyrene", "41-30 50 21 54", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Polyurethane", "41-30 50 21 61", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Polyvinyl Chloride, Plasticised (PVC)", "41-30 50 21 64", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Polyvinyl Chloride, Unplasticised (PVC-U)", "41-30 50 21 71", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Polyvinylidene Fluoride", "41-30 50 21 74", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Urea Formaldehyde", "41-30 50 21 81", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Vinyl", "41-30 50 21 84", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Rubbers", "41-30 50 24", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Butyl Rubber", "41-30 50 24 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Neoprene", "41-30 50 24 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Silicone", "41-30 50 24 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Polysulfide", "41-30 50 24 21", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Other Petrochemical Compounds", "41-30 50 27", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Paraffin", "41-30 50 27 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Waxes", "41-30 50 27 14", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Other Synthetic Solid Compounds", "41-30 50 99", "", nullptr, subsection1OmniClass.get());
    subsection0OmniClass = InsertClassification(*omniClassTable, "Liquids", "41-50 00 00", "", nullptr, nullptr);
        subsection1OmniClass = InsertClassification(*omniClassTable, "Water", "41-50 10 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Fresh Waters", "41-50 10 11", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Rain Water", "41-50 10 11 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Ground Water", "41-50 10 11 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Distilled Water", "41-50 10 11 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Deionized Water", "41-50 10 11 21", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Salt Waters", "41-50 10 14", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Sea Water", "41-50 10 14 11", "", nullptr, subsection2OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassTable, "Water-Based Solutions", "41-50 20 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Water-Based Acid Solutions", "41-50 20 11", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Water-Based Base (Alkali) Solutions", "41-50 20 14", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Other Water-Based Solutions", "41-50 20 99", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassTable, "Mineral Liquids", "41-50 30 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Petroleum Products", "41-50 30 11", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Gasoline", "41-50 30 11 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Diesel Oils", "41-50 30 11 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Fuel Oils", "41-50 30 11 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Kerosene", "41-50 30 11 21", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Mineral Oils", "41-50 30 14", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassTable, "Plant Derived Liquids", "41-50 40 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Vegetable Oils", "41-50 40 11", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Other Plant-Derived Liquids", "41-50 40 99", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassTable, "Animal-Derived Liquids", "41-50 50 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Fish Oils", "41-50 50 11", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Other Animal-Derived Liquids", "41-50 50 99", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassTable, "Synthetic Liquids", "41-50 60 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Alcohols", "41-50 60 11", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Lubricants", "41-50 60 14", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Ammonia", "41-50 60 17", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassTable, "Other Liquids", "41-50 99 00", "", nullptr, subsection0OmniClass.get());
    subsection0OmniClass = InsertClassification(*omniClassTable, "Gases", "41-70 00 00", "", nullptr, nullptr);
        subsection1OmniClass = InsertClassification(*omniClassTable, "Natural Gases", "41-70 10 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Natural Air", "41-70 10 11", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Carbon Dioxide", "41-70 10 14", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Carbon Monoxide", "41-70 10 17", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Water Vapor", "41-70 10 21", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassTable, "Hydrocarbon Gases", "41-70 20 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Propane", "41-70 20 11", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Butane", "41-70 20 14", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "LPG", "41-70 20 17", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassTable, "Refrigerants", "41-70 30 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Fluorocarbons", "41-70 30 11", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Trichlorofluoromethane (CFC-11)", "41-70 30 11 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Dichlorodifluoromethane (CFC-12)", "41-70 30 11 12", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Chlorotrifluoromethane (CFC-13)", "41-70 30 11 13", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Chlorodifluoromethane (HCFC-22)", "41-70 30 11 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Trifluoromethane (HFC-23)", "41-70 30 11 15", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Trichlorotrifluoroethane (CFC-113)", "41-70 30 11 16", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Dichloro-Tetrafluoroethane (CFC-114)", "41-70 30 11 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Chloro-Pentafluoroethane (CFC-115)", "41-70 30 11 18", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Hexachloroethane (CFC-116)", "41-70 30 11 19", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Tetrafluoroethane (HFC-134a)", "41-70 30 11 20", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Heptafluoropropane (HFC-227ea)", "41-70 30 11 21", "", nullptr, subsection2OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassTable, "Other Gases", "41-70 99 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassTable, "Halon", "41-70 99 11", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Bromochlorodifluoromethane (Halon 1211)", "41-70 99 11 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassTable, "Bromotrifluoromethane (Halon 1301)", "41-70 99 11 12", "", nullptr, subsection2OmniClass.get());

    }

END_CLASSIFICATIONSYSTEMS_NAMESPACE
