/*--------------------------------------------------------------------------------------+
|
|  $Source: Domain/GeneratedInserts/GeneratedOmniClass41Inserts.cpp $
|
|  $Copyright: (c) 2019 Bentley Systems, Incorporated. All rights reserved. $
|
+--------------------------------------------------------------------------------------*/
//===========================================================================================
// WARNING: This is an automatically generated code for building classification inserts 
// WARNING: To generate, call "bb -r BuildingShared -f BuildingShared -p CodeGenerators b -c"
//===========================================================================================


#include <ClassificationSystems/ClassificationSystemsApi.h>

#include <BuildingShared/DgnUtils/BuildingDgnUtilsApi.h>


namespace BS = BENTLEY_BUILDING_SHARED_NAMESPACE_NAME;

BEGIN_CLASSIFICATIONSYSTEMS_NAMESPACE
void ClassificationSystemsDomain::InsertOmniClass41Definitions(Dgn::DgnDbR db) const
    {
    ClassificationSystemCPtr omniClassSystem = TryAndGetSystem(db, "OmniClass");
    ClassificationPtr subsection0OmniClass;
    subsection0OmniClass = InsertClassification(*omniClassSystem, "Chemical Elements", "41-10 00 00", "", nullptr, nullptr);
    ClassificationPtr subsection1OmniClass;
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Non-Metallic Solid Elements", "41-10 10 00", "", nullptr, subsection0OmniClass.get());
    ClassificationPtr subsection2OmniClass;
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Carbon ", "41-10 10 06", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Silicon", "41-10 10 14", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Phosphorus", "41-10 10 15", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Sulfur", "41-10 10 16", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Calcium", "41-10 10 20", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Iodine", "41-10 10 53", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Metallic Elements", "41-10 20 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Boron", "41-10 20 05", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Magnesium", "41-10 20 12", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Aluminum", "41-10 20 13", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Potassium", "41-10 20 19", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Titanium", "41-10 20 22", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Vanadium", "41-10 20 23", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Chromium", "41-10 20 24", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Manganese", "41-10 20 25", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Iron", "41-10 20 26", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Cobalt", "41-10 20 27", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Nickel", "41-10 20 28", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Copper", "41-10 20 29", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Zinc", "41-10 20 30", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Arsenic", "41-10 20 33", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Molybdenum", "41-10 20 42", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Silver", "41-10 20 47", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Cadmium", "41-10 20 48", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Tin", "41-10 20 50", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Antimony", "41-10 20 51", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Tungsten", "41-10 20 74", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Gold", "41-10 20 79", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Lead", "41-10 20 82", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Bismuth", "41-10 20 83", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Liquid Elements", "41-10 50 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Mercury", "41-10 50 80", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Gaseous Elements", "41-10 70 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Hydrogen", "41-10 70 01", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Helium", "41-10 70 02", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Nitrogen", "41-10 70 07", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Oxygen", "41-10 70 08", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Fluorine", "41-10 70 09", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Neon", "41-10 70 10", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Chlorine", "41-10 70 17", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Argon", "41-10 70 18", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Krypton", "41-10 70 36", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Xenon", "41-10 70 54", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Radon", "41-10 70 86", "", nullptr, subsection1OmniClass.get());
    subsection0OmniClass = InsertClassification(*omniClassSystem, "Solid Compounds", "41-30 00 00", "", nullptr, nullptr);
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Mineral Compounds", "41-30 10 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Rocks", "41-30 10 11", "", nullptr, subsection1OmniClass.get());
    ClassificationPtr subsection3OmniClass;
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Granites", "41-30 10 11 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Limestones", "41-30 10 11 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Marbles", "41-30 10 11 17", "", nullptr, subsection2OmniClass.get());
    ClassificationPtr subsection4OmniClass;
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Marble Stone", "41-30 10 11 17 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Travertine", "41-30 10 11 17 14", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Limestone Marble", "41-30 10 11 17 17", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Onyx", "41-30 10 11 17 21", "", nullptr, subsection3OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Quartz-Based Rocks", "41-30 10 11 21", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Quartz", "41-30 10 11 21 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Quartzitic-Sandstone", "41-30 10 11 21 14", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Sandstone", "41-30 10 11 21 17", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Sand", "41-30 10 11 21 21", "", nullptr, subsection3OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Slates", "41-30 10 11 24", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Rock Fibers", "41-30 10 11 27", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Other Rocks", "41-30 10 11 31", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Barite", "41-30 10 11 31 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Chalk", "41-30 10 11 31 14", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Tufa", "41-30 10 11 31 17", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Perlite", "41-30 10 11 31 21", "", nullptr, subsection3OmniClass.get());
    ClassificationPtr subsection5OmniClass;
                        subsection5OmniClass = InsertClassification(*omniClassSystem, "Expanded Perlite", "41-30 10 11 31 21 11", "", nullptr, subsection4OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Shale", "41-30 10 11 31 24", "", nullptr, subsection3OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassSystem, "Expanded Shale", "41-30 10 11 31 24 11", "", nullptr, subsection4OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Mica", "41-30 10 11 31 27", "", nullptr, subsection3OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassSystem, "Expanded Mica", "41-30 10 11 31 27 11", "", nullptr, subsection4OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Expanded Vermiculite", "41-30 10 11 31 31", "", nullptr, subsection3OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Clays", "41-30 10 14", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Clay", "41-30 10 14 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Fire Clay", "41-30 10 14 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Bentonite", "41-30 10 14 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Expanded Clay", "41-30 10 14 21", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Ceramics", "41-30 10 14 24", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Brick", "41-30 10 14 24 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Earthenware", "41-30 10 14 24 14", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Terracotta ", "41-30 10 14 24 17", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Fired Shale", "41-30 10 14 24 21", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Porcelain", "41-30 10 14 24 24", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Vitreous China", "41-30 10 14 24 27", "", nullptr, subsection3OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Other Cementitious Materials", "41-30 10 17", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Soils", "41-30 10 17 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Cements", "41-30 10 17 14", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Portland Cement", "41-30 10 17 14 11", "", nullptr, subsection3OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Limes", "41-30 10 17 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Hydrated Lime", "41-30 10 17 17 11", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Quicklime", "41-30 10 17 17 14", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Slaked Lime", "41-30 10 17 17 17", "", nullptr, subsection3OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Gypsums", "41-30 10 17 21", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Calcium Silicate", "41-30 10 17 24", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Magnesia", "41-30 10 17 27", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Bituminous and Petrochemical Minerals", "41-30 10 21", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Asphalts", "41-30 10 21 11", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Asphalt", "41-30 10 21 11 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Polymer Modified Asphalt", "41-30 10 21 11 14", "", nullptr, subsection3OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Coal Tars", "41-30 10 21 14", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Coal Tar Pitch", "41-30 10 21 14 11", "", nullptr, subsection3OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Paraffins", "41-30 10 21 17", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Other Non-Metallic Natural Minerals", "41-30 10 24", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Asbestos", "41-30 10 24 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Graphite", "41-30 10 24 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Carbon Black", "41-30 10 24 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Salt (Sodium Chloride)", "41-30 10 24 21", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Other Minerals Not Occurring Naturally", "41-30 10 27", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Glasses and Glass-Like Materials", "41-30 10 27 11", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Glass", "41-30 10 27 11 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Porcelain Enamel", "41-30 10 27 11 14", "", nullptr, subsection3OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Other Minerals", "41-30 10 27 14", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Fly Ash", "41-30 10 27 14 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Carbon Fiber", "41-30 10 27 14 14", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Silicon Carbide", "41-30 10 27 14 17", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Cermet", "41-30 10 27 14 21", "", nullptr, subsection3OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Metallic Compounds", "41-30 20 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Iron Alloys", "41-30 20 11", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Carbon Steels", "41-30 20 11 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Stainless Steels", "41-30 20 11 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Other Steels", "41-30 20 11 21", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Other Iron Alloys", "41-30 20 11 99", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Cast Iron", "41-30 20 11 99 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Wrought Iron", "41-30 20 11 99 14", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Ductile Iron", "41-30 20 11 99 17", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Malleable Iron", "41-30 20 11 99 21", "", nullptr, subsection3OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Aluminum Alloys", "41-30 20 14", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Aluminum-Zinc Alloys", "41-30 20 14 11", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Copper Alloys", "41-30 20 17", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Brasses", "41-30 20 17 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Bronzes", "41-30 20 17 14", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Zinc Alloys", "41-30 20 21", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Zinc-Lead Alloys", "41-30 20 21 11", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Zamac", "41-30 20 21 11 11", "", nullptr, subsection3OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Other Zinc Alloys", "41-30 20 21 14", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Mazac", "41-30 20 21 14 11", "", nullptr, subsection3OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Lead Alloys", "41-30 20 24", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Lead and Tin Alloys", "41-30 20 24 11", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Terne", "41-30 20 24 11 11", "", nullptr, subsection3OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Other Alloys", "41-30 20 27", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Plant Materials", "41-30 30 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Materials from Other Plants", "41-30 30 21", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Natural Rubber", "41-30 34 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Cotton", "41-30 34 12", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Jute", "41-30 34 13", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Materials from Plants in General", "41-30 30 11", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Cellulose", "41-30 30 11 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Paper", "41-30 30 11 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Textiles", "41-30 30 11 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Combustion Residues", "41-30 30 11 21", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Materials from Trees", "41-30 30 14", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Timber", "41-30 30 14 11", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Softwood Timber", "41-30 30 14 11 11", "", nullptr, subsection3OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassSystem, "Southern Pine", "41-30 30 14 11 11 11", "", nullptr, subsection4OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassSystem, "Douglas Fir-Larch", "41-30 30 14 11 11 14", "", nullptr, subsection4OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassSystem, "Spruce-Pine-Fir", "41-30 30 14 11 11 17", "", nullptr, subsection4OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassSystem, "Redwood", "41-30 30 14 11 11 21", "", nullptr, subsection4OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassSystem, "Western Red Cedar", "41-30 30 14 11 11 24", "", nullptr, subsection4OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Hardwood Timber", "41-30 30 14 11 14", "", nullptr, subsection3OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassSystem, "White Oak", "41-30 30 14 11 14 11", "", nullptr, subsection4OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassSystem, "Red Oak", "41-30 30 14 11 14 14", "", nullptr, subsection4OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassSystem, "Maple", "41-30 30 14 11 14 17", "", nullptr, subsection4OmniClass.get());
                        subsection5OmniClass = InsertClassification(*omniClassSystem, "Cherry", "41-30 30 14 11 14 21", "", nullptr, subsection4OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Other Tree Parts", "41-30 30 14 14", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Tree Bark", "41-30 30 14 14 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Coir", "41-30 30 14 14 14", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Cork", "41-30 30 14 14 17", "", nullptr, subsection3OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Materials from Grasses", "41-30 30 17", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Bamboo", "41-30 30 17 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Grass", "41-30 30 17 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Linen", "41-30 30 17 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Reeds", "41-30 30 17 21", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Straw", "41-30 30 17 24", "", nullptr, subsection2OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Other Organic Materials", "41-30 40 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Materials from Animals", "41-30 40 11", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Animal Hair Materials", "41-30 40 11 11", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Wool", "41-30 40 11 11 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Horsehair", "41-30 40 11 11 14", "", nullptr, subsection3OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Other Animal-Based Materials", "41-30 40 11 14", "", nullptr, subsection2OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Leather", "41-30 40 11 14 11", "", nullptr, subsection3OmniClass.get());
                    subsection4OmniClass = InsertClassification(*omniClassSystem, "Tallow", "41-30 40 11 14 14", "", nullptr, subsection3OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Materials from Insects", "41-30 40 14", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Silk", "41-30 40 14 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Beeswax", "41-30 40 14 14", "", nullptr, subsection2OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Synthetic Solid Compounds", "41-30 50 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Acids", "41-30 50 11", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Bases (Alkalis)", "41-30 50 14", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Salts", "41-30 50 17", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Plastics", "41-30 50 21", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Acrylonitrile-Butadiene-Styrene (ABS)", "41-30 50 21 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Acrylic, Polymethyl Methacrylate", "41-30 50 21 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Epoxy", "41-30 50 21 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Polyamide", "41-30 50 21 21", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Polybutylene (PB)", "41-30 50 21 24", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Phenolic", "41-30 50 21 27", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Polycarbonate", "41-30 50 21 31", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Polyester", "41-30 50 21 34", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Polyethylene, Polythene (PE)", "41-30 50 21 37", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Polyisocyanurate", "41-30 50 21 41", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Polypropylene", "41-30 50 21 51", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Polystyrene", "41-30 50 21 54", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Polyurethane", "41-30 50 21 61", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Polyvinyl Chloride, Plasticised (PVC)", "41-30 50 21 64", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Polyvinyl Chloride, Unplasticised (PVC-U)", "41-30 50 21 71", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Polyvinylidene Fluoride", "41-30 50 21 74", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Urea Formaldehyde", "41-30 50 21 81", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Vinyl", "41-30 50 21 84", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Rubbers", "41-30 50 24", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Butyl Rubber", "41-30 50 24 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Neoprene", "41-30 50 24 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Silicone", "41-30 50 24 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Polysulfide", "41-30 50 24 21", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Other Petrochemical Compounds", "41-30 50 27", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Paraffin", "41-30 50 27 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Waxes", "41-30 50 27 14", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Other Synthetic Solid Compounds", "41-30 50 99", "", nullptr, subsection1OmniClass.get());
    subsection0OmniClass = InsertClassification(*omniClassSystem, "Liquids", "41-50 00 00", "", nullptr, nullptr);
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Water", "41-50 10 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Fresh Waters", "41-50 10 11", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Rain Water", "41-50 10 11 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Ground Water", "41-50 10 11 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Distilled Water", "41-50 10 11 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Deionized Water", "41-50 10 11 21", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Salt Waters", "41-50 10 14", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Sea Water", "41-50 10 14 11", "", nullptr, subsection2OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Water-Based Solutions", "41-50 20 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Water-Based Acid Solutions", "41-50 20 11", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Water-Based Base (Alkali) Solutions", "41-50 20 14", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Other Water-Based Solutions", "41-50 20 99", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Mineral Liquids", "41-50 30 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Petroleum Products", "41-50 30 11", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Gasoline", "41-50 30 11 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Diesel Oils", "41-50 30 11 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Fuel Oils", "41-50 30 11 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Kerosene", "41-50 30 11 21", "", nullptr, subsection2OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Mineral Oils", "41-50 30 14", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Plant Derived Liquids", "41-50 40 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Vegetable Oils", "41-50 40 11", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Other Plant-Derived Liquids", "41-50 40 99", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Animal-Derived Liquids", "41-50 50 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Fish Oils", "41-50 50 11", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Other Animal-Derived Liquids", "41-50 50 99", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Synthetic Liquids", "41-50 60 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Alcohols", "41-50 60 11", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Lubricants", "41-50 60 14", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Ammonia", "41-50 60 17", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Other Liquids", "41-50 99 00", "", nullptr, subsection0OmniClass.get());
    subsection0OmniClass = InsertClassification(*omniClassSystem, "Gases", "41-70 00 00", "", nullptr, nullptr);
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Natural Gases", "41-70 10 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Natural Air", "41-70 10 11", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Carbon Dioxide", "41-70 10 14", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Carbon Monoxide", "41-70 10 17", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Water Vapor", "41-70 10 21", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Hydrocarbon Gases", "41-70 20 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Propane", "41-70 20 11", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Butane", "41-70 20 14", "", nullptr, subsection1OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "LPG", "41-70 20 17", "", nullptr, subsection1OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Refrigerants", "41-70 30 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Fluorocarbons", "41-70 30 11", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Trichlorofluoromethane (CFC-11)", "41-70 30 11 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Dichlorodifluoromethane (CFC-12)", "41-70 30 11 12", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Chlorotrifluoromethane (CFC-13)", "41-70 30 11 13", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Chlorodifluoromethane (HCFC-22)", "41-70 30 11 14", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Trifluoromethane (HFC-23)", "41-70 30 11 15", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Trichlorotrifluoroethane (CFC-113)", "41-70 30 11 16", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Dichloro-Tetrafluoroethane (CFC-114)", "41-70 30 11 17", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Chloro-Pentafluoroethane (CFC-115)", "41-70 30 11 18", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Hexachloroethane (CFC-116)", "41-70 30 11 19", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Tetrafluoroethane (HFC-134a)", "41-70 30 11 20", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Heptafluoropropane (HFC-227ea)", "41-70 30 11 21", "", nullptr, subsection2OmniClass.get());
        subsection1OmniClass = InsertClassification(*omniClassSystem, "Other Gases", "41-70 99 00", "", nullptr, subsection0OmniClass.get());
            subsection2OmniClass = InsertClassification(*omniClassSystem, "Halon", "41-70 99 11", "", nullptr, subsection1OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Bromochlorodifluoromethane (Halon 1211)", "41-70 99 11 11", "", nullptr, subsection2OmniClass.get());
                subsection3OmniClass = InsertClassification(*omniClassSystem, "Bromotrifluoromethane (Halon 1301)", "41-70 99 11 12", "", nullptr, subsection2OmniClass.get());
    }

END_CLASSIFICATIONSYSTEMS_NAMESPACE
