//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ActiveImage.rc
//
#define ID_SELECTIN                     3
#define ID_SELECTOUT                    4
#define IDD_ABOUTBOX                    100
#define IDD_MASTERDLG                   102
#define IDB_SPLASH                      105
#define IDR_MAINFRAME                   126
#define IDR_FILE_TOOLBAR                127
#define IDR_ACTIVETYPE                  128
#define IDS_MSGERR_FILENOTSUPPORTED     129
#define IDD_OBJECT_TOOLBAR              130
#define IDD_DLG_EXPORT_DIALOG           131
#define IDR_NAV_TOOLBAR                 132
#define IDD_DLG_COMPRESSION             132
#define IDD_DLG_PIXEL_TYPE              133
#define IDD_DLG_ENCODING                134
#define IDD_DLG_IMG_SIZE                135
#define IDD_DLG_BLOCK                   136
#define IDD_DLG_SMALL_COMPRESSION       140
#define IDD_DLG_GEO_REF_FORMAT          141
#define IDB_TREELISTICONS               142
#define IDD_DLG_PROGRESS                142
#define IDD_ROTATION                    143
#define IDD_INSERT_OBJECT               144
#define IDD_DLG_CONVERT_TO              150
#define IDD_DLG_DESTINATION             151
#define IDD_DLG_EXPORT_INTEGRITY        152
#define IDD_DLG_SUBRES_PIXEL_TYPE       160
#define IDR_SELECTMOVE_TOOLBAR          161
#define IDD_RECENTER                    164
#define IDD_EXPORT                      174
#define IDC_ZOOM_OUT                    175
#define IDD_INTENSITY                   176
#define IDC_ZOOM_IN                     177
#define IDD_DSTRESS                     179
#define IDD_EXPORT_TO_ORACLE            180
#define IDI_DIR                         182
#define IDD_DFILE_OPEN                  184
#define IDI_LOGICAL                     185
#define IDI_FILE                        186
#define IDB_PIN                         188
#define IDR_HMR_BMP                     190
#define IDB_HMR                         191
#define IDD_HISTOGRAM_SCALING           192
#define IDD_DIALOG_CACHE                196
#define IDD_OPEN_RAWFILE                198
#define IDD_DLG_COLOR_REPLACEMENT       200
#define IDD_DISPLAY_EXTENT              203
#define IDD_DLG_GEOCODING_INFO          204
#define IDD_DIALOG1                     205
#define IDD_DLG_COLORSPACE_TEST         206
#define IDD_INTERNET_FILE_OPEN          207
#define IDD_DLG_AUTHENTIFICATION        208
#define IDD_DLG_AUTHENTICATION          208
#define IDD_LAYERS_DIALOG               209
#define IDD_TEXTLOG                     212
#define IDD_DIALOG2                     213
#define IDD_DLG_TINT                    213
#define IDD_SCALE                       214
#define IDD_IMAGE_INFO                  215
#define IDD_REPROJECT                   216
#define IDD_DLG_INFO_REPROJECTION       218
#define IDC_FULLRES                     1000
#define IDC_OBJECT_TREE                 1001
#define IDC_DISPLAYRES                  1002
#define IDC_COMPRESSION_QUALITY_SLIDER  1002
#define IDC_ANGLE                       1003
#define IDC_SPIN_SET_QUALITY            1003
#define IDC_LIST_FILE                   1004
#define IDC_EDIT_QUALITY                1004
#define IDC_CUSTOMRES                   1005
#define IDC_CMB_COMPRESSION             1005
#define IDC_EDIT_FILENAME               1006
#define IDC_EDIT_WIDTH                  1006
#define IDC_COMPRESSION_L               1007
#define IDC_EDIT_HEIGHT                 1007
#define IDC_OBJECT_LIST                 1008
#define IDC_SPIN_WIDTH                  1008
#define IDC_INTERLEAVE_L                1009
#define IDC_SPIN_HEIGHT                 1009
#define IDC_LINK                        1010
#define IDC_COMBO_BLOCK_TYPE            1010
#define IDC_CMB_FILETYPE                1011
#define IDC_CMB_ENCODING                1011
#define IDC_IMAGEWIDTH_L                1012
#define IDC_CHK_RESAMPLE                1012
#define IDC_IMAGEHEIGHT_L               1013
#define IDC_CMB_PIXEL_TYPE              1013
#define IDC_BUTTON_UP                   1014
#define IDC_CMB_RESAMPLING              1014
#define IDC_RESOLUTION_B                1015
#define IDC_CMB_GEO_REF_FORMAT          1015
#define IDC_BUILD                       1016
#define IDC_EDIT_PATH                   1017
#define IDC_INFORMATION_B               1018
#define IDC_X                           1019
#define IDC_ADVANCE                     1020
#define IDC_PROGRESS_BAR                1020
#define IDC_Y                           1021
#define IDC_STOP_PROGRESSION            1021
#define IDC_INTERLACED                  1022
#define IDC_DURATION                    1022
#define IDC_MULTIRES                    1023
#define IDC_TITLE                       1024
#define IDC_TILEWIDTH                   1025
#define IDC_IMAGE                       1026
#define IDC_TILED                       1027
#define IDC_HTTP                        1028
#define IDC_TILEHEIGHT                  1029
#define IDC_SOCKET                      1030
#define IDC_BT_OK                       1030
#define IDC_TileWidthL                  1031
#define IDC_BT_CANCEL                   1031
#define IDC_IMAGE_NAME                  1032
#define IDC_COMPRESSION                 1033
#define IDC_SERVER_NAME                 1034
#define IDC_INTERLEAVE                  1035
#define IDC_HTTP_EXT_TEXT               1036
#define IDC_TileHeightL                 1037
#define IDC_HTTP_EXT                    1038
#define IDC_FileSizeL                   1039
#define IDC_IMAGEHEIGHT                 1040
#define IDC_IMAGEWIDTH                  1041
#define IDC_CMB_FILE_FORMAT             1041
#define IDC_SOCKET_PORT_TEXT            1042
#define IDC_CHK_BEST_OPTION             1042
#define IDC_FILENAME                    1043
#define IDC_CHK_KEEP_SRCPATH            1043
#define IDC_SOCKET_PORT                 1044
#define IDC_RD_RETAIN_EXT               1044
#define IDC_SELECTFINENAME              1045
#define IDC_RD_REPLACE_EXTENSION        1045
#define IDC_SLIDER1                     1046
#define IDC_FILETYPE                    1047
#define IDC_FILEIN                      1048
#define IDC_FILEOUT                     1049
#define IDC_RD_INPUT_RANGE_CLIPPING     1049
#define IDC_FILESIZE                    1050
#define IDC_RD_OUTPUT_RANGE_COMPRESSION 1050
#define IDC_DRAWSIGNAL                  1050
#define IDC_PIXELTYPE                   1051
#define IDC_ED_MAX_VALUE                1051
#define IDC_BT_BROWSE                   1051
#define ID_BT_STOP                      1052
#define IDC_ED_MIN_VALUE                1052
#define IDC_EDIT_NEW_PATH               1052
#define IDC_EXMULTIRES                  1053
#define IDC_CHECK1                      1053
#define IDC_CHECK_AUTODESTROY           1053
#define IDC_USE_SISTER_FILE             1053
#define IDC_ED_START_COLOR_R            1053
#define IDC_USERNAME                    1054
#define IDC_ED_START_COLOR_G            1054
#define IDC_ED_START_COLOR_B            1055
#define IDC_LAYERNAME                   1056
#define IDC_COMBO_PIXELTYPE             1056
#define IDC_CHK_RESUME_IN_FILENAME      1056
#define IDC_ED_END_COLOR_R              1056
#define IDC_PASSWORD                    1057
#define IDC_COMBO_CODEC                 1057
#define IDC_CHK_ALL_POSSIBILITY         1057
#define IDC_ED_END_COLOR_G              1057
#define IDC_SERVICE                     1058
#define IDC_COMBO_CACHEFORMAT           1058
#define IDC_CHK_GEOREF_COMP             1058
#define IDC_ED_END_COLOR_G2             1058
#define IDC_ED_END_COLOR_B              1058
#define IDC_SELECTSRCFILE               1059
#define IDC_CHK_IMAGE_COMP              1059
#define IDC_ASYNC                       1060
#define IDC_COMBO_IMAGE_COMP_METHOD     1060
#define IDC_BUTTON_BROWSE               1061
#define IDC_FILE_B                      1062
#define IDC_QUERY                       1063
#define IDC_GID                         1064
#define IDC_WIDTH                       1064
#define IDC_AFFINITY                    1064
#define IDC_SUGGEST                     1065
#define IDC_HEIGHT                      1065
#define IDC_SRCFILENAME                 1066
#define IDC_BT_CLOSE                    1066
#define IDC_SRCPIXELTYPE                1067
#define IDC_SWAP                        1067
#define IDC_BT_CUBE_SELECT              1067
#define IDC_SRCIMAGEWIDTH               1068
#define IDC_OFFSET                      1068
#define IDC_CHK_TRESHOLD                1068
#define IDC_BT_NEW_COLOR                1068
#define IDC_SRCIMAGEHEIGHT              1069
#define IDC_FOOTER                      1069
#define IDC_EDIT_ERROR_TOLERENCE        1069
#define IDC_BT_CUBE_REMOVE              1069
#define IDC_DISPLAY_EXTENT_MIN_X        1069
#define IDC_SRCTILEWIDTH                1070
#define IDC_EDIT_THRESHLOD_MIN          1070
#define IDC_DISPLAY_EXTENT_MIN_Y        1070
#define IDC_GEOCODING_INFO_LIST         1070
#define IDC_SRCTILEHEIGHT               1071
#define IDC_AUTODETECT                  1071
#define IDC_EDIT_THRESHLOD_MAX          1071
#define IDC_DISPLAY_EXTENT_MAX_X        1071
#define IDC_BT_REMOVE                   1071
#define IDC_SRCSELECTFILE               1072
#define IDC_SPIN_ERROR_TOLERENCE        1072
#define IDC_DISPLAY_EXTENT_MAX_Y        1072
#define IDC_BT_ADD                      1072
#define IDC_EXFILETYPE                  1073
#define IDC_SPINIDC_THRESHLOD_MIN       1073
#define IDC_CMB_TAG_LIST                1073
#define IDC_EXPIXELTYPE                 1074
#define IDC_SPINIDC_THRESHLOD_MAX       1074
#define IDC_EDIT_TAG_VALUE              1074
#define IDC_EXTILED                     1075
#define IDC_STATIC_TAG_TYPE             1075
#define IDC_EXTILEWIDTH                 1076
#define IDC_CHK_EXPORT_INTEGRITY        1076
#define IDC_HISTOGRAM_DISPLAY           1076
#define IDC_EXTILEHEIGHT                1077
#define IDC_CMB_CHANNEL                 1077
#define IDC_EXINTERLEAVE                1078
#define IDC_CHK_SAVE_IMAGE_RESULT       1078
#define IDC_BT_SAVE                     1078
#define IDC_BUTTON1                     1078
#define IDC_EXINTERLACED                1079
#define IDC_EDIT_IMAGE_RESULT_PATH      1079
#define IDC_EDIT_GEOKEYS                1079
#define IDC_SLIDER_OPACITY              1079
#define IDC_BT_DEST_COLOR               1079
#define IDC_EXFILENAME                  1080
#define IDC_STATIC_ERROR_TOLERENCE      1080
#define IDC_SLIDER_DESATURATION         1080
#define IDC_BT_DEST_COLOR2              1080
#define IDC_EXSELECTFILE                1081
#define IDC_STATIC_THRESHOLD_MIN        1081
#define IDC_BT_DEST_COLOR3              1081
#define IDC_HMRFILEOPENCTRLCTRL         1082
#define IDC_STATIC_THRESHOLD_MAX        1082
#define IDC_EDIT_OPACITY                1082
#define IDC_VERSION_INFO                1083
#define IDC_EDIT_SRC_RED                1083
#define IDC_EDIT_OPACITY2               1084
#define IDC_EDIT_SRC_GREEN              1084
#define IDC_EDIT_SRC_BLUE               1085
#define IDC_EDIT_SRC_L                  1086
#define IDC_EDIT_SRC_U                  1087
#define IDC_EDIT_SRC_V                  1088
#define IDC_EDIT_SCALE_X                1090
#define IDC_EDIT_NEW_L                  1090
#define IDC_EDIT_SCALE_Y                1091
#define IDC_EDIT_DEST_RED               1091
#define IDC_CHK_FIX_IMAGE_SIZE          1092
#define IDC_EDIT_DEST_GREEN             1092
#define IDC_CHK_FIX_IMAGE_SCALE         1093
#define IDC_EDIT_DEST_BLUE              1093
#define IDC_CHK_ASPECT_RATIO            1094
#define IDC_EDIT_DEST_L                 1094
#define IDC_RESET                       1095
#define IDC_EDIT_DEST_U                 1095
#define IDC_EDIT_DEST_V                 1096
#define IDC_EDIT_DEST_RED2              1097
#define IDC_BT_SRC_COLOR                1098
#define IDC_EDIT_DEST_GREEN2            1099
#define IDC_EDIT_DEST_BLUE2             1100
#define IDC_EDIT_DEST_L2                1101
#define IDC_EDIT_DEST_U2                1102
#define IDC_EDIT_DEST_V2                1103
#define IDC_BT_COMPUTE2                 1104
#define IDC_SLIDER_L_ADJUST             1105
#define IDC_EDIT_DEST_RED3              1106
#define IDC_EDIT_DEST_GREEN3            1107
#define IDOPEN                          1107
#define IDC_EDIT_DEST_BLUE3             1108
#define IDC_EDIT_DEST_L3                1109
#define IDC_EDIT_DEST_U3                1110
#define IDC_EDIT_DEST_V3                1111
#define IDC_BT_COMPUTE3                 1112
#define IDC_INTERNET_URL                1113
#define IDC_LIST1                       1117
#define IDAPPLY                         1118
#define IDC_AUTHENTICATIONSTRING        1119
#define IDC_AuthenticationFormat        1120
#define IDC_URL_EXAMPLES                1121
#define IDTEXTLOG_CLOSE                 1123
#define IDC_TEXTLOG                     1124
#define IDC_ADD_ITEM                    1125
#define IDC_ADD_ITEM2                   1126
#define IDC_CLEAR                       1127
#define IDC_MFCLINK1                    1127
#define IDC_EDIT1                       1128
#define IDC_ED_INTERVAL_MIN             1128
#define IDC_ED_INTERVAL_MIN0            1128
#define IDC_EDIT2                       1129
#define IDC_ED_INTERVAL_MAX             1129
#define IDC_ED_INTERVAL_MAX0            1129
#define IDC_SCALE                       1129
#define IDC_EDIT3                       1130
#define IDC_ED_CONTRAST_MIN             1130
#define IDC_ED_CONTRAST_MIN0            1130
#define IDC_EDIT_TEXT_REPROJECT         1130
#define IDC_EDIT4                       1131
#define IDC_ED_CONTRAST_MAX             1131
#define IDC_ED_CONTRAST_MAX0            1131
#define IDC_EDIT5                       1132
#define IDC_ED_GAMMA_FACTOR0            1132
#define IDC_STATIC_GROUP_CONTRAST_STRETCH 1133
#define IDC_STATIC_INTERVAL_MIN         1134
#define IDC_STATIC_INTERVAL             1134
#define IDC_STATIC_INTERVAL_MAX         1135
#define IDC_STATIC_MAX_CHANNEL0         1135
#define IDC_STATIC_CONTRAST_MIN         1136
#define IDC_STATIC_CONTRAST             1136
#define IDC_STATIC_CONTRAST_MAX         1137
#define IDC_STATIC_TEXT_REPRO_INFO_DLG  1137
#define IDC_STATIC_GAMMA_FACTOR         1138
#define IDC_STATIC_MIN_CHANNEL0         1139
#define IDC_STATIC_CHANNEL0             1141
#define IDC_BUTTON_START_COLOR          1142
#define IDC_BUTTON_START_COLOR2         1143
#define IDC_BUTTON_END_COLOR            1143
#define IDC_STATIC_START_COLOR          1144
#define IDC_STATIC_END_COLOR            1145
#define IDC_STATIC_GROUP_DENSITY_SLICING 1146
#define IDC_STATIC_START_INDEX          1147
#define IDC_STATIC_END_INDEX            1148
#define IDC_STATIC_OPACITY              1149
#define IDC_STATIC_DESATURATION         1150
#define IDC_STATIC_TINT_COLOR           1151
#define IDC_ED_TINT_COLOR_R             1152
#define IDC_ED_TINT_COLOR_G             1153
#define IDC_ED_TINT_COLOR_B             1154
#define IDC_BUTTON_TINT_COLOR           1155
#define IDC_BUTTON_TINT_COLOR2          1156
#define IDC_BUTTON_TINT_COL             1156
#define IDC_INFO_TYPE                   1156
#define IDC_ED_INTERVAL_MIN1            1157
#define IDC_INFO_LOCATION               1157
#define IDC_ED_INTERVAL_MAX1            1158
#define IDC_STATIC_MAX_CHANNEL1         1159
#define IDC_INFO_SIZE                   1159
#define IDC_ED_CONTRAST_MIN1            1160
#define IDC_INFO_SIZE_UNCOMP            1160
#define IDC_ED_CONTRAST_MAX1            1161
#define IDC_INFO_DIMENSIONS             1161
#define IDC_STATIC_MIN_CHANNEL1         1162
#define IDC_INFO_TYPE_COMP              1162
#define IDC_STATIC_CHANNEL1             1163
#define IDC_INFO_COLOR_SPACE            1163
#define IDC_ED_INTERVAL_MIN3            1164
#define IDC_ED_INTERVAL_MIN2            1164
#define IDC_INFO_BLOCK_NBR              1164
#define IDC_INFO_BLOCK_COUNT            1164
#define IDC_ED_INTERVAL_MAX3            1165
#define IDC_ED_INTERVAL_MAX2            1165
#define IDC_INFO_BLOCK_SIZE             1165
#define IDC_STATIC_MAX_CHANNEL2         1166
#define IDC_INFO_BLOCK_COUNT2           1166
#define IDC_INFO_SCANLINE               1166
#define IDC_ED_CONTRAST_MIN3            1167
#define IDC_ED_CONTRAST_MIN2            1167
#define IDC_INFO_GCS_NAME               1167
#define IDC_ED_CONTRAST_MAX3            1168
#define IDC_ED_CONTRAST_MAX2            1168
#define IDC_INFO_GCS_UNITS              1168
#define IDC_STATIC_MIN_CHANNEL2         1169
#define IDC_INFO_GCS_UNITS2             1169
#define IDC_INFO_DATUM_NAME             1169
#define IDC_STATIC_CHANNEL2             1170
#define IDC_ED_GAMMA_FACTOR1            1171
#define IDC_ED_GAMMA_FACTOR3            1172
#define IDC_ED_GAMMA_FACTOR2            1172
#define IDC_REPROJECT_TEXT_LABEL        1174
#define IDC_REPROJECT_WKT               1175
#define IDC_REPROJECT_TEXT_EXAMPLE      1176
#define IDC_CLEAR_WKT                   1177
#define IDC_REPROJECT_USE_POLY          1178
#define ID_OK_BUTTON                    1179
#define IDOK1                           1181
#define IDC_EXPORTAS_SELECT             2000
#define IDC_EXPORTAS_FOLDER             2001
#define IDC_EXPORTAS_FORMAT             2002
#define IDC_EXPORTAS_BESTOPTION         2003
#define IDC_EXPORTAS_EXPORT             2004
#define ID_EDIT_CLEAR_MODE              30000
#define ID_EDIT_COPY_MODE               30001
#define ID_EDIT_PASTE_MODE              30002
#define ID_EDIT_ADD_RECT_SHAPE          30003
#define ID_EDIT_ADD_RECT_HOLED_SHAPE    30004
#define ID_EDIT_CHANGESUBSAMPLING_NEAREST 30005
#define ID_EDIT_CHANGESUBSAMPLING_AVERAGE 30006
#define ID_MENU_EDIT_UNDO               30007
#define ID_MENU_EDIT_REDO               30008
#define ID_MENU_EDIT_ADDREFERENCETORASTER 30009
#define ID_MENU_EDIT_MOVEREFERENCETORASTER 30010
#define ID_VIEW_NAVIGATIONTOOLBAR       30019
#define ID_VIEW_ZOOMAREA                30020
#define ID_VIEW_RECENTERXY              30022
#define ID_VIEW_ZOOMIN                  30023
#define ID_VIEW_ZOOMOUT                 30024
#define ID_VIEW_ZOOM11                  30026
#define ID_VIEW_FIT                     30027
#define ID_VIEW_REDRAW                  30028
#define ID_EDIT_ADD_CIRC_SHAPE          30029
#define ID_EDIT_ADD_CIRC_HOLED_SHAPE    30030
#define ID_EDIT_ADD_POLY_SHAPE          30031
#define ID_EDIT_ADD_POLY_HOLED_SHAPE    30032
#define ID_EDIT_REMOVE_CLIPPING         30033
#define ID_VIEW_MAGNIFIER               30034
#define ID_EDIT_REMOVE                  32771
#define ID_EDIT_DEPTH_BRINGTOFRONT      32772
#define ID_ORDER_DEPTH_BRINGTOFRONT     32773
#define ID_EDIT_DEPTH_BRINGTOBACK       32774
#define ID_ORDER_DEPTH_SENDTOBACK       32775
#define ID_EDIT_DEPTH_MOVEUP            32776
#define ID_ORDER_DEPTH_MOVEUP           32777
#define ID_EDIT_DEPTH_MOVEDOWN          32778
#define ID_ORDER_DEPTH_MOVEDOWN         32779
#define ID_EDIT_TRANSFORM_MOVE          32780
#define ID_EDIT_TRANSFORM_ROTATE        32781
#define ID_EDIT_PROPERTIES              32782
#define ID_INSERT_SELECT                32783
#define ID_EDIT_SELECT                  32784
#define ID_EDIT_SELECTALL               32785
#define ID_VIEW_REPAINT                 32786
#define ID_INSERT_FROMTHISDOCUMENT      32798
#define ID_INSERT_FROMEXTERNALDOCUMENT  32799
#define ID_INSERT_NEWOBJECT             32800
#define ID_OBJECT_CHOOSE                32801
#define ID_OBJECT_EXPORT                32802
#define ID_OBJECT_PROPERTIES            32803
#define ID_OBJECT_FILTER                32804
#define ID_EDIT_UNSELECT                32806
#define ID_VIEW_FILETOOLBAR             32808
#define ID_VIEW_OBJECTTOOLBAR           32810
#define ID_VIEW_8BITS                   32845
#define ID_VIEW_TILESIZE_32             32850
#define ID_VIEW_TILESIZE_64             32851
#define ID_VIEW_TILESIZE_128            32852
#define ID_VIEW_TILESIZE_256            32853
#define ID_VIEW_TILESIZE_1024           32854
#define ID_VIEW_TILESIZE_2048           32855
#define ID_VIEW_TILESIZE_4096           32856
#define ID_VIEW_TILESIZE_CUSTOM         32857
#define ID_VIEW_FITTOSCREEN             32861
#define ID_VIEW_GRAYSCALE               32865
#define ID_VIEW_24BITS                  32866
#define ID_VIEW_DEFAULTBACKGROUNDCOLOR  32867
#define ID_VIEW_BACKGROUND              32868
#define ID_INTERNET_ADD                 32870
#define ID_VIEW_VIEWORIGIN_TOPLEFT      32877
#define ID_VIEW_VIEWORIGIN_BOTTOMLEFT   32878
#define ID_FILE_EXPORT_HMR              32879
#define ID_VIEW_AUTOBITS                32881
#define ID_HELP_TESTDISPLAY             32887
#define IDM_STRESS                      32888
#define ID_BUTTON32901                  32901
#define ID_FILE_EXPORT_REGION           32903
#define ID_VIEW_REMOVETRANSPARENCY      32904
#define ID_PRECALCULATE_DISPLAY         32905
#define ID_FILE_READONLY                32906
#define ID_FILE_PREFERENCES             32908
#define ID_FILE_CACHE                   32909
#define ID_FILE_TRANSPARENCY            32910
#define ID_FILE_PREFERENCES_CACHECOMPRESSIONS 32911
#define ID_FILE_EXPORT                  32914
#define ID_FILE_PREFERENCES_USE_REPROJECTION 32916
#define ID_FILE_OVERWRITEHGRTWF         32917
#define ID_FILE_INFO_TIME               32918
#define ID_VIEW_RESAMPLING_NEAREST      32919
#define ID_VIEW_RESAMPLING_AVERAGE      32920
#define ID_VIEW_RESAMPLING_BILINEAR     32921
#define ID_VIEW_RESAMPLING_CONVOLUTION  32922
#define ID_EDIT_COMPUTE_HISTOGRAM       32923
#define ID_FILE_EXPORT_CHANNELS         32924
#define ID_INFO_DISPLAY_EXTENT          32929
#define ID_GEOCODING_INFO               32930
#define ID_PREFERENCES_FITIMAGEONVIEW   32933
#define ID_FILE_PREFERENCES_FITIMAGEONVIEW 32934
#define ID_OPTIONS_LOADINMEMORY         32935
#define ID_OPTIONS_BESTCONTRAST         32936
#define ID_OPTIONS_DISABLECACHE         32937
#define ID_OPTIONS_CACHEDRESOLUTIONS    32938
#define ID_CACHEDRESOLUTIONS_16384      32939
#define ID_CACHEDRESOLUTIONS_8192       32940
#define ID_CACHEDRESOLUTIONS_4096       32941
#define ID_CACHEDRESOLUTIONS_2048       32942
#define ID_CACHEDRESOLUTIONS_1024       32943
#define ID_CACHEDRESOLUTIONS_512        32944
#define ID_CACHEDRESOLUTIONS_256        32945
#define ID_CACHEDRESOLUTIONS_128        32946
#define ID_CACHEDRESOLUTIONS_NORMALCACHE 32947
#define ID_OPTIONS_TIFF64ENABLE         32948
#define ID_Menu                         32949
#define ID_FILE_OPENINTERNETFILE        32950
#define ID_VIEWRESAMPLING_CONVOLUTION   32951
#define ID_VIEW_LAYERS                  32952
#define ID_DISPLAY_ANNOTATION_ICONS     32953
#define ID_MENU_EDIT_SUBSAMPLING_NEAREST 32954
#define ID_MENU_EDIT_SUBSAMPLING_AVERAGE 32955
#define ID_MENU_EDIT_SUBSAMPLING_BILINEAR 32956
#define ID_MENU_EDIT_SUBSAMPLING_BICUBIC 32957
#define ID_INFO_TEXTLOG                 32958
#define ID_EDIT_ADDSHAPE                32959
#define ID_VIEW_SCALE                   32960
#define ID_CHANGECOLORSPACE_ORIGINAL    32961
#define ID_CHANGECOLORSPACE_RLE         32962
#define ID_CHANGECOLORSPACE_RLELINE     32963
#define ID_CHANGECOLORSPACE_GRAY1       32964
#define ID_CHANGECOLORSPACE_GRAY8       32965
#define ID_CHANGECOLORSPACE_RGB         32966
#define ID_CHANGECOLORSPACE_RGBA        32967
#define ID_CHANGECOLORSPACE_YCC         32968
#define ID_CHANGECOLORSPACE_YCCA8       32969
#define ID_CHANGECOLORSPACE_AUTO        32975
#define ID_INFO_IMAGEINFO               32978
#define ID_OPTIONS_LOADINMEMORY_DISABLED 32980
#define ID_OPTIONS_LOADINMEMORY_IMAGE   32981
#define ID_OPTIONS_LOADINMEMORY_STRIP   32982
#define ID_VIEW_1BIT_EQUALWEIGHT        32985
#define ID_VIEW_1BIT_FOREGROUND         32986
#define ID_VIEW_1BIT_BACKGROUND         32987
#define ID_EDIT_REPROJECT               32988
#define ID_EDIT_REPROJECTIONMODEL       32989
#define ID_REPROJECTIONMODEL_EXACTREPROJECTION 32990
#define ID_REPROJECTIONMODEL_POLYNOMIALREPROJECTION 32991
#define ID_REPROJECTIONMODEL_AFFINE     32992
#define ID_REPROJECTIONMODEL_BESTMODEL  32993
#define ID_EDIT_REPROJECTIONINFORMATION 32994
#define ID_INFO_REPROJECTIONINFORMATION 32995
#define ID_Menu32996                    32996
#define ID_OPTIONS_3BAND16BITTORGB      32997
#define ID_3BAND16BITTORGB_NATIVESCAN   32998
#define ID_3BAND16BITTORGB_0            32999
#define ID_3BAND16BITTORGB_1            33000
#define ID_3BAND16BITTORGB_2            33001
#define ID_3BAND16BITTORGB_NONE         33002
#define ID_3BAND16BITTORGB_USEDSAMEVALUE 33003
#define ID_INDICATOR_MOUSEPOSITION      59142
#define ID_INDICATOR_READ               59143
#define ID_INDICATOR_PROGRESSION        59144
#define ID_INDICATOR_DRAWTIME           59145
#define ID_INDICATOR_EXPORTSIZE         59147
#define ID_REDESIGN_MENU_BAR            60000
#define ID_REDESIGN_DRAW_ORIGINAL_COPYFROM 60002
#define ID_REDESIGN_DRAW_10_TIMES       60004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        221
#define _APS_NEXT_COMMAND_VALUE         33004
#define _APS_NEXT_CONTROL_VALUE         1182
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
