@echo off
setLocal EnableDelayedExpansion


set version=%1
set versionlast=%1

set installation_directory=C:\PROGRA~1\

set Server_Projectnumber=Hkbridges12345

set staging_directory=C:\bridge\staging_qa

set user_name=Junaid.Khan@bentley.com

set user_password=%2

set OBDDIR="C:\Program Files\Bentley\OpenBuildings Designer CONNECT Edition\OpenBuildingsDesigner"

set LOGFILE="C:\bridge\"

call :LOG>%LOGFILE%

:LOG

for /d %%a in (MS VM HYB IFC BB24 FNT PRN OFF 2D LVL SAV 3SM CS Multi) do (  
if "%%a" == "MS"  "%installation_directory%Bentley\iModelBridgeMstn\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\MetroStation\DGN\3DModel\MasterMS.dgn" --DGN_CFGFILE="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\MetroStation.cfg" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="%installation_directory%Bentley\iModelBridgeMstn\DgnV8BridgeB02.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir=%installation_directory%Bentley\iModelBridgeMstn\Assets --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password% --DGN_DEBUGCFG=1

if "%%a" == "VM" "%installation_directory%Bentley\iModelBridgeMstn\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\MetroStation\DGN\3DModel\Visualization_Master.dgn" --DGN_CFGFILE="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\MetroStation.cfg" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="%installation_directory%Bentley\iModelBridgeMstn\DgnV8BridgeB02.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir=%installation_directory%Bentley\iModelBridgeMstn\Assets --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password% --DGN_DEBUGCFG=1

if "%%a" == "HYB" "%installation_directory%Bentley\iModelBridgeMstn\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\DGN\Hybrid_ORG_Dataset\Main.dgn" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="%installation_directory%Bentley\iModelBridgeMstn\DgnV8BridgeB02.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir=%installation_directory%Bentley\iModelBridgeMstn\Assets --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password%

if "%%a" == "IFC" "%installation_directory%Bentley\iModelBridgeMstn\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\DGN\BingMaps_IFC\D12_ifc.dgn" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="%installation_directory%Bentley\iModelBridgeMstn\DgnV8BridgeB02.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir=%installation_directory%Bentley\iModelBridgeMstn\Assets --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password%

if "%%a" ==  "BB24" "%installation_directory%Bentley\iModelBridgeMstn\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\DGN\BB24\BB24_All_Haz.i.dgn" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="%installation_directory%Bentley\iModelBridgeMstn\DgnV8BridgeB02.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir=%installation_directory%Bentley\iModelBridgeMstn\Assets --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password%
if "%%a" ==  "BB24" "%installation_directory%Bentley\iModelBridgeMstn\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\DGN\BB24\BB24_All_Viz.i.dgn" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="%installation_directory%Bentley\iModelBridgeMstn\DgnV8BridgeB02.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir=%installation_directory%Bentley\iModelBridgeMstn\Assets --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password%

if "%%a" ==  "FNT" "%installation_directory%Bentley\iModelBridgeMstn\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\DGN\LineStyles\A0.dgn" --DGN_CFGFILE="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN.cfg" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="%installation_directory%Bentley\iModelBridgeMstn\DgnV8BridgeB02.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir=%installation_directory%Bentley\iModelBridgeMstn\Assets --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password% --DGN_DEBUGCFG=1

if "%%a" ==  "PRN" "%installation_directory%Bentley\iModelBridgeMstn\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\DGN\PointCloud_Rasters\PointClouds_RastersNew.dgn" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="%installation_directory%Bentley\iModelBridgeMstn\DgnV8BridgeB02.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir=%installation_directory%Bentley\iModelBridgeMstn\Assets --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password%

if "%%a" ==  "OFF" "%installation_directory%Bentley\iModelBridgeMstn\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\DGN\DGN Links\EQPM01_821.dgn" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="%installation_directory%Bentley\iModelBridgeMstn\DgnV8BridgeB02.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir=%installation_directory%Bentley\iModelBridgeMstn\Assets --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password%

if "%%a" ==  "2D" "%installation_directory%Bentley\iModelBridgeMstn\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\DGN\Corridor_2Dto3D\NB_Corridor.dgn" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="%installation_directory%Bentley\iModelBridgeMstn\DgnV8BridgeB02.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir=%installation_directory%Bentley\iModelBridgeMstn\Assets --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password%

if "%%a" ==  "LVL" "%installation_directory%Bentley\iModelBridgeMstn\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\DGN\Levels\EWR_OSGB_Master.dgn" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="%installation_directory%Bentley\iModelBridgeMstn\DgnV8BridgeB02.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir=%installation_directory%Bentley\iModelBridgeMstn\Assets --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password%

if "%%a" ==  "SAV" "%installation_directory%Bentley\iModelBridgeMstn\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\dgn\View Groups\Master_ViewGroup.dgn" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="%installation_directory%Bentley\iModelBridgeMstn\DgnV8BridgeB02.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir=%installation_directory%Bentley\iModelBridgeMstn\Assets --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password%
if "%%a" ==  "SAV" "%installation_directory%Bentley\iModelBridgeMstn\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\DGN\SavedViews\Master_SavedView.dgn" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="%installation_directory%Bentley\iModelBridgeMstn\DgnV8BridgeB02.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir=%installation_directory%Bentley\iModelBridgeMstn\Assets --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password%

if "%%a" ==  "3SM" "%installation_directory%Bentley\iModelBridgeMstn\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\Reality\DGN\Reality.dgn" --DGN_CFGFILE="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\Reality.cfg" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="%installation_directory%Bentley\iModelBridgeMstn\DgnV8BridgeB02.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir=%installation_directory%Bentley\iModelBridgeMstn\Assets --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password% --DGN_DEBUGCFG=1

if "%%a" ==  "CS" copy /y "C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\DGN\Updates\scenario01_00.dgn" "C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\DGN\Updates\Scenario.dgn" 
if "%%a" ==  "CS" "%installation_directory%Bentley\iModelBridgeMstn\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\DGN\Updates\Scenario.dgn" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="%installation_directory%Bentley\iModelBridgeMstn\DgnV8BridgeB02.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir=%installation_directory%Bentley\iModelBridgeMstn\Assets --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password%
if "%%a" ==  "CS" copy /y "C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\DGN\Updates\scenario01_01.dgn" "C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\DGN\Updates\Scenario.dgn"
if "%%a" ==  "CS" "%installation_directory%Bentley\iModelBridgeMstn\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\DGN\Updates\Scenario.dgn" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="%installation_directory%Bentley\iModelBridgeMstn\DgnV8BridgeB02.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir=%installation_directory%Bentley\iModelBridgeMstn\Assets --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password%

if "%%a" == "Multi"  "%installation_directory%Bentley\iModelBridgeMstn\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\dgn\Building Model\MS_Terrain.dgn" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="%installation_directory%Bentley\iModelBridgeMstn\DgnV8BridgeB02.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir=%installation_directory%Bentley\iModelBridgeMstn\Assets --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password%
if "%%a" == "Multi" c:\Python27\python.exe %OBDDIR%Mdlapps\tfbridgeatp.py "C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\dgn\Building Model\ABD_Structural_00.dgn" --iModelName=%%a_%version% --BB_FLOORMASTER_DGN=BB_FloorMaster.dgnlib --hubUserName=%user_name% --hubEnvironment=QA --hubPassWord=%user_password% --hubProject=%Server_Projectnumber%
if "%%a" == "Multi" "C:\Program Files\Bentley\DwgBridge\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\dgn\Building Model\AutoCAD_Road.dwg" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="C:\Program Files\Bentley\DwgBridge\DwgBridge.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir="C:\Program Files\Bentley\DwgBridge\Assets" --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password%
if "%%a" == "Multi" "C:\Program Files\Bentley\RevitBridge\iModelBridgeFwk.exe" --server-repository=%%a_%version% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\SmokeTestMSTN\dgn\Building Model\REVIT_Architecture.rvt" --fwk-staging-dir=%staging_directory% --fwk-logging-config-file="C:\Program Files\Bentley\RevitBridge\Assets\iModelBridgeFwk.logging.config.xml" --fwk-bridge-library="C:\Program Files\Bentley\RevitBridge\RevitBridge.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir="C:\Program Files\Bentley\RevitBridge\Assets" --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password%

if "%%a" == "VM" "%installation_directory%Bentley\iModelBridgeMstn\iModelBridgeFwk.exe" --server-repository=%%a_%versionlast% --server-project=%Server_Projectnumber% --fwk-input="C:\ProgramData\Bentley\MicroStation CONNECT Edition\Configuration\WorkSpaces\Example\WorkSets\MetroStation\DGN\3DModel\Master.dgn" --fwk-staging-dir=%staging_directory% --fwk-bridge-library="%installation_directory%Bentley\iModelBridgeMstn\DgnV8BridgeB02.dll" --fwk-create-repository-if-necessary --server-environment=QA --fwk-assetsDir=%installation_directory%Bentley\iModelBridgeMstn\Assets --fwk-skip-assignment-check --server-user=%user_name% --server-password=%user_password%
)